/* ============================================================
   Canada Quiz — visitor tracking (one file for the whole site)
   ------------------------------------------------------------
   This file is loaded by all 218 pages, English and French.
   Nothing else anywhere on the site needs to change.

   TO TURN IT ON, fill in one or both lines below, then push.

   1) CLOUDFLARE  — easiest, you already own the domain there.
      Cloudflare dashboard -> Analytics & Logs -> Web Analytics
      -> Add a site -> canada-quiz.com. It shows you a snippet
      containing  "token":"abc123..."  — paste ONLY that token.
      Free, unlimited, no cookies, so no cookie banner needed.

   2) GOOGLE ANALYTICS 4 — deeper: which quizzes get finished,
      pass rates, English vs French, where people come from.
      analytics.google.com -> Admin -> Create property ->
      Web data stream for canada-quiz.com -> copy the
      Measurement ID, which looks like  G-ABCD1234XY.

   Using both is fine, and is what I would do.
   ============================================================ */
var GA4_ID = "G-8XMJNC7TQ5";              // <-- paste your G-XXXXXXXXXX here
var CF_BEACON_TOKEN = "";     // <-- paste your Cloudflare token here

/* ---- KIND MAP: generated by tools/newq/analytics_kinds.py ---- */
var CQ_KIND = {
  "10-tips-to-pass-your-citizenship-test":"article",
  "20-fun-facts-about-canada-for-kids":"article",
  "a-canadian-invented-basketball-for-kids":"article",
  "a-short-history-of-canada":"article",
  "about":"hub",
  "ai-quiz":"quiz",
  "alberta-class-7-mock-test":"driving",
  "alberta-class-7-practice-test":"driving",
  "alberta-road-signs":"driving",
  "alberta-rules-of-the-road":"driving",
  "all-pages":"hub",
  "animals-on-canadian-money-for-kids":"article",
  "bc-class-7l-mock-test":"driving",
  "bc-class-7l-practice-test":"driving",
  "bc-road-signs":"driving",
  "bc-rules-of-the-road":"driving",
  "beginner-driver-education-ontario":"driving",
  "block-builder":"game",
  "blog":"hub",
  "body-quiz":"quiz",
  "brain-trainer":"game",
  "can-canada-feed-itself":"article",
  "canada-diary":"article",
  "canada-driving-test-by-province":"hub",
  "canada-geography-coast-to-coast":"article",
  "canada-major-projects-office-explained":"article",
  "canada-map":"game",
  "canada-population-timeline":"article",
  "canada-provinces-and-territories-explained":"article",
  "canada-quiz":"quiz",
  "canada-usa-trade-history":"article",
  "canadarm-canadas-robot-arm-in-space-for-kids":"article",
  "canadas-animals-and-wildlife":"article",
  "canadas-biggest-cities":"article",
  "canadas-national-parks":"article",
  "canadas-two-official-languages":"article",
  "canadian-citizenship-test-what-to-expect":"article",
  "canadian-food-poutine-maple-syrup":"article",
  "canadian-holidays-explained":"article",
  "canadian-inventions":"article",
  "canadian-money-explained":"article",
  "canadian-personal-tax-basics":"article",
  "canadian-slang-words":"article",
  "canadian-symbols-explained":"article",
  "carrom":"game",
  "categories-game":"game",
  "charades":"game",
  "checkers":"game",
  "chess":"game",
  "churchill-falls-gull-island-explained":"article",
  "churchill-polar-bear-capital-for-kids":"article",
  "citizenship":"hub",
  "color-match":"game",
  "connect4":"game",
  "contact":"hub",
  "crossword":"game",
  "cube-twist":"game",
  "daily":"hub",
  "did-us-tariffs-on-canada-work":"article",
  "draw-it":"game",
  "driving-test":"hub",
  "earth-quiz":"quiz",
  "entertainment-quiz":"quiz",
  "exchange-foreign-drivers-licence-canada":"article",
  "famous-canadians-in-history":"article",
  "farming-in-canada-the-real-picture":"article",
  "first-nations-inuit-and-metis-for-kids":"article",
  "flags-game":"game",
  "for-kids":"hub",
  "fun-quiz":"quiz",
  "game-2048":"game",
  "games":"hub",
  "gk-quiz":"quiz",
  "hide-and-find":"game",
  "hockey-in-canada":"article",
  "hold-to-head":"game",
  "how-canada-chose-its-flag-for-kids":"article",
  "how-canada-rebuilds-its-economy":"article",
  "how-canada-was-built":"article",
  "how-canadas-government-works":"article",
  "how-to-get-a-drivers-licence-in-canada":"article",
  "how-to-incorporate-a-business-in-canada":"article",
  "how-to-prepare-for-the-canadian-citizenship-test":"article",
  "imposter":"game",
  "incorporation-vs-sole-proprietor-canada":"article",
  "index":"hub",
  "indigenous-peoples-of-canada":"article",
  "insulin-discovered-in-canada-for-kids":"article",
  "inukshuk":"game",
  "lights-out":"game",
  "manitoba-class-5-mock-test":"driving",
  "manitoba-class-5-practice-test":"driving",
  "manitoba-road-signs":"driving",
  "manitoba-rules-of-the-road":"driving",
  "maple-says":"game",
  "maple-syrup-and-the-great-robbery-for-kids":"article",
  "math-race":"game",
  "memory":"game",
  "minesweeper":"game",
  "money-quiz":"quiz",
  "new-brunswick-class-7-mock-test":"driving",
  "new-brunswick-class-7-practice-test":"driving",
  "new-brunswick-road-signs":"driving",
  "new-brunswick-rules-of-the-road":"driving",
  "newcomer-first-year-in-canada-checklist":"article",
  "newfoundland-class-5-mock-test":"driving",
  "newfoundland-class-5-practice-test":"driving",
  "newfoundland-road-signs":"driving",
  "newfoundland-rules-of-the-road":"driving",
  "nova-scotia-class-7-mock-test":"driving",
  "nova-scotia-class-7-practice-test":"driving",
  "nova-scotia-road-signs":"driving",
  "nova-scotia-rules-of-the-road":"driving",
  "nunavut-class-7-mock-test":"driving",
  "nunavut-class-7-practice-test":"driving",
  "nunavut-road-signs":"driving",
  "nunavut-rules-of-the-road":"driving",
  "nwt-class-7-mock-test":"driving",
  "nwt-class-7-practice-test":"driving",
  "nwt-road-signs":"driving",
  "nwt-rules-of-the-road":"driving",
  "offline":"hub",
  "ontario-g1-mock-test":"driving",
  "ontario-g1-practice-test":"driving",
  "ontario-g1-road-signs":"driving",
  "ontario-g1-rules-of-the-road":"driving",
  "ontario-g1-study-guide":"driving",
  "pei-class-7-mock-test":"driving",
  "pei-class-7-practice-test":"driving",
  "pei-road-signs":"driving",
  "pei-rules-of-the-road":"driving",
  "prime-ministers-of-canada":"article",
  "privacy":"hub",
  "province-quiz":"quiz",
  "quebec-class-5-mock-test":"driving",
  "quebec-class-5-practice-test":"driving",
  "quebec-road-signs":"driving",
  "quebec-rules-of-the-road":"driving",
  "quizzes":"hub",
  "rare-canadian-history-stories":"article",
  "reversi":"game",
  "rights-and-responsibilities-of-canadian-citizens":"article",
  "saskatchewan-class-7-mock-test":"driving",
  "saskatchewan-class-7-practice-test":"driving",
  "saskatchewan-road-signs":"driving",
  "saskatchewan-rules-of-the-road":"driving",
  "science-quiz":"quiz",
  "scramble":"game",
  "sliding-puzzle":"game",
  "snake":"game",
  "sources":"hub",
  "spin-wheel":"game",
  "story-maker":"game",
  "sudoku":"game",
  "tag":"game",
  "terms":"hub",
  "terry-fox-marathon-of-hope-for-kids":"article",
  "the-bluenose-ship-on-the-dime-for-kids":"article",
  "the-dinosaurs-of-alberta-for-kids":"article",
  "the-history-of-canada-day":"article",
  "the-narwhal-and-the-frozen-north-for-kids":"article",
  "the-northern-lights-for-kids":"article",
  "the-railway-across-canada-for-kids":"article",
  "the-stanley-cup-story-for-kids":"article",
  "the-story-of-the-canadian-flag":"article",
  "the-wild-horses-of-sable-island-for-kids":"article",
  "tictactoe":"game",
  "tile-tap":"game",
  "times-tables":"game",
  "top-answers":"game",
  "trivia-showdown":"game",
  "typing-test":"game",
  "ufo-landing-pad-st-paul-alberta-for-kids":"article",
  "us-tariffs-and-canada-explained":"article",
  "voyageurs-and-the-fur-trade-for-kids":"article",
  "whack-a-beaver":"game",
  "what-canada-and-the-usa-sell-each-other":"article",
  "what-canada-day-really-is-for-kids":"article",
  "what-is-confederation":"article",
  "which-canadian-animal-quiz":"quiz",
  "which-canadian-city-quiz":"quiz",
  "which-canadian-food-quiz":"quiz",
  "which-national-park-quiz":"quiz",
  "which-winter-sport-quiz":"quiz",
  "who-gets-the-tariff-money-back":"article",
  "winnie-the-bear-from-winnipeg-for-kids":"article",
  "winter-in-canada":"article",
  "winter-tires-canada-law-by-province":"article",
  "word-groups":"game",
  "word-guess":"game",
  "word-hive":"game",
  "word-illusions":"game",
  "word-master":"game",
  "word-search":"game",
  "world-quiz":"quiz",
  "worlds-longest-beaver-dam-for-kids":"article",
  "would-you-rather":"game",
  "young-canadians-and-farming":"article",
  "yukon-class-7-mock-test":"driving",
  "yukon-class-7-practice-test":"driving",
  "yukon-road-signs":"driving",
  "yukon-rules-of-the-road":"driving"
};
/* ---- end KIND MAP ---- */

(function () {
  "use strict";

  /* ---------- 1. Google Analytics 4 ---------- */
  /* The queue (dataLayer / gtag) is set up straight away, so anything the page
     reports in its first second is remembered and nothing is lost. Google's own
     script — about 130 KB that costs a slow phone roughly 125 ms of thinking —
     is fetched only once the browser is idle. The numbers arrive the same; they
     just stop competing with the page the visitor is waiting for. */
  if (GA4_ID && GA4_ID.indexOf("G-") === 0) {
    window.dataLayer = window.dataLayer || [];
    window.gtag = function () { window.dataLayer.push(arguments); };
    gtag("js", new Date());
    gtag("config", GA4_ID, { anonymize_ip: true });

    var loadGA = function () {
      var s = document.createElement("script");
      s.async = true;
      s.src = "https://www.googletagmanager.com/gtag/js?id=" + GA4_ID;
      document.head.appendChild(s);
    };
    var idleGA = function () {
      if (window.requestIdleCallback) window.requestIdleCallback(loadGA, { timeout: 4000 });
      else setTimeout(loadGA, 2500);
    };
    if (document.readyState === "complete") idleGA();
    else window.addEventListener("load", idleGA);
  }

  /* ---------- 2. Cloudflare Web Analytics (optional) ---------- */
  if (CF_BEACON_TOKEN) {
    var c = document.createElement("script");
    c.defer = true;
    c.src = "https://static.cloudflareinsights.com/beacon.min.js";
    c.setAttribute("data-cf-beacon", '{"token":"' + CF_BEACON_TOKEN + '"}');
    document.head.appendChild(c);
  }

  /* ---------- 3. What did people actually DO? ---------- */
  function track(name, params) {
    if (typeof window.gtag === "function") window.gtag("event", name, params || {});
  }
  /* Any other script on the site can report something: CQ_TRACK("name", {..}) */
  window.CQ_TRACK = track;

  var page = (location.pathname.split("/").pop() || "index.html").replace(".html", "");
  var lang = /\/fr\//.test(location.pathname) ? "fr" : "en";
  /* What kind of page is this? Look it up first; guess only as a last resort.
     CQ_KIND at the top of this file is generated by
     tools/newq/analytics_kinds.py from the card grids on games.html,
     quizzes.html, blog.html and for-kids.html, and from the driving group in
     tools/site_map.json. That is the site describing itself, rather than a
     pattern trying to describe the site.

     The regular expression below is what this file used on its own until
     24 August 2026, when it was measured against every page and found to be
     reporting thirteen games — block-builder, carrom, connect4, reversi and the
     rest — plus most of the kids' stories and two new articles as "other". The
     per-page numbers were never affected; every grouped total was. It is kept
     only so a page added between builds still gets a sensible answer. If it is
     ever doing real work, run analytics_kinds.py instead. */
  var kind = (typeof CQ_KIND === "object" && CQ_KIND[page]) || "";
  if (kind) { /* looked up — no guessing needed */ }
  else if (/-g1-|class-5|class-7|road-signs|rules-of-the-road|driving|licence/.test(page)) kind = "driving";
  else if (/quiz|citizenship/.test(page)) kind = "quiz";
  else if (/game|puzzle|snake|memory|charades|imposter|chess|checkers|sudoku|crossword|scramble|bee|tiles|wheel|draw|answers|categories|story|head|rather|showdown|tictactoe|beaver|inukshuk|word|typing|colour|color|minesweeper|rubik|2048|connections/.test(page)) kind = "game";
  else if (/blog|canada|history|citizen|tips|facts|flag|symbol|language|holiday|animal|geography|government|indigenous|confederation|rights|province/.test(page)) kind = "article";
  else kind = "other";

  /* Did they stay long enough to really use it? */
  var stayed = false;
  setTimeout(function () {
    stayed = true;
    track("engaged_15s", { page_name: page, content_kind: kind });
  }, 15000);

  /* Clicks on quiz answers, game buttons and category cards */
  var started = false;
  document.addEventListener("click", function (e) {
    var t = e.target;
    if (!t || !t.className || typeof t.className !== "string") return;
    if (/\boption\b/.test(t.className)) {
      if (!started) {
        started = true;
        track("quiz_start", { page_name: page, content_kind: kind, language: lang });
      }
      track("quiz_answer", { page_name: page });
    } else if (/\bbtn\b/.test(t.className)) {
      var label = (t.textContent || "").trim().slice(0, 40);
      track("button_click", { page_name: page, button_label: label, content_kind: kind });
    }
  }, true);

  /* ---------- 3b. Who FINISHED, and did they pass? ----------
     This is the number that actually matters on a quiz site: not how many
     people opened a page, but how many played it to the end.

     Every quiz and every driving test — all 218 pages, both languages —
     ends by putting a .result-big element on the screen. So instead of
     editing every quiz one by one, we simply watch for that element to
     appear. New quizzes are covered automatically, with nothing to add. */
  function readResult(box) {
    var txt = (box.textContent || "").replace(/\s+/g, " ");
    /* the score line is the reliable place to read from; the whole panel is
       only a fallback, because it also contains the missed-question review */
    var scoreEl = box.querySelector(".score");
    var scoreTxt = scoreEl ? scoreEl.textContent : txt;
    var got = null, outOf = null;
    /* "You scored 17 out of 20" · "17 / 20" · "Vous avez obtenu 17 sur 20" */
    var m = scoreTxt.match(/(\d+)\s*(?:\/|out of|sur)\s*(\d+)/i);
    if (m) { got = parseInt(m[1], 10); outOf = parseInt(m[2], 10); }

    var passed = null;
    if (box.querySelector(".result-big.pass")) passed = true;
    else if (box.querySelector(".result-big.fail")) passed = false;
    else if (/\bPASS\b|RÉUSSI|REUSSI/i.test(txt)) passed = true;
    else if (/TRY AGAIN|\bFAIL\b|ÉCHEC|ECHEC/i.test(txt)) passed = false;

    var out = { page_name: page, content_kind: kind, language: lang };
    if (got !== null && outOf) {
      out.score = got;
      out.out_of = outOf;
      out.percent = Math.round((got / outOf) * 100);
    }
    if (passed !== null) out.passed = passed ? "yes" : "no";
    return out;
  }

  /* Careful: on some pages the result screen already sits in the HTML from the
     start, hidden with display:none. So "does it exist?" would fire the moment
     the page opened. What we look for is the result screen becoming VISIBLE. */
  function visibleResult() {
    var all = document.querySelectorAll(".result-big");
    for (var i = 0; i < all.length; i++) {
      if (all[i].offsetParent !== null) return all[i];
    }
    return null;
  }

  var reported = false;
  function checkForResult() {
    var box = visibleResult();
    if (!box) { reported = false; return; }  /* hidden again — next play counts */
    if (reported) return;
    reported = true;
    var panel = (box.closest && box.closest("section")) || box.parentElement || document.body;
    /* let the rest of the result screen finish drawing before reading it */
    setTimeout(function () { track("quiz_complete", readResult(panel)); }, 150);
  }

  if (window.MutationObserver) {
    var pending = null;
    new MutationObserver(function () {
      if (pending) return;
      pending = setTimeout(function () { pending = null; checkForResult(); }, 200);
    }).observe(document.documentElement, {
      childList: true, subtree: true,
      attributes: true, attributeFilter: ["style", "class", "hidden"]
    });
  }

  /* ---------- 4. A counter that never leaves this browser ----------
     Stored in localStorage only. Add  ?mystats  to any address on your own
     phone or computer to see your own play history.
     No personal data, nothing sent anywhere.                     */
  try {
    var K = "cq_local_stats";
    var d = JSON.parse(localStorage.getItem(K) || "{}");
    d[page] = (d[page] || 0) + 1;
    d._total = (d._total || 0) + 1;
    d._first = d._first || new Date().toISOString().slice(0, 10);
    localStorage.setItem(K, JSON.stringify(d));

    if (location.search.indexOf("mystats") > -1) {
      var rows = Object.keys(d).filter(function (k) { return k[0] !== "_"; })
        .sort(function (a, b) { return d[b] - d[a]; })
        .map(function (k) { return "<tr><td style='padding:4px 12px'>" + k + "</td><td style='padding:4px 12px;text-align:right'><b>" + d[k] + "</b></td></tr>"; })
        .join("");
      var box = document.createElement("div");
      box.style.cssText = "position:fixed;inset:auto 10px 10px 10px;max-height:60vh;overflow:auto;background:#fff;border:3px solid #111;border-radius:14px;padding:14px;z-index:99999;font:14px system-ui";
      box.innerHTML = "<b>Your own visits on this device</b> (since " + d._first + ")<br>Total: <b>" + d._total +
        "</b><table style='margin-top:8px;width:100%'>" + rows + "</table>" +
        "<button style='margin-top:10px;padding:6px 14px;border-radius:8px;border:2px solid #111;background:#fff;font-weight:800' onclick='this.parentNode.remove()'>Close</button>";
      document.body.appendChild(box);
    }
  } catch (err) { /* private mode — ignore */ }
})();
