/* canada-quiz.com — MANITOBA Class 5 Learner (5L) practice data
   Test format, and 60 original bilingual questions (30 road signs + 30 rules).
   Written in our own words from the free public information published by
   Manitoba Public Insurance. Not affiliated with MPI or the Province of Manitoba.

   The quiz code lives in js/driving-engine.js and never changes per province. */
window.CQ_DRIVE_Q = [];

/* ---------- road signs ---------- */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"mbs1", sec:"signs", sign:"stop",
  en:{ q:"Where exactly must you stop at this sign?",
       a:["At the stop line, or before the crosswalk if there is no line","Anywhere in the intersection","Level with the sign post","Past the crosswalk"],
       e:"Stop at the line first. If your view is blocked from there, creep forward slowly and stop a second time once you can see." },
  fr:{ q:"Où exactement devez-vous vous arrêter à ce panneau ?",
       a:["À la ligne d'arrêt, ou avant le passage pour piétons s'il n'y a pas de ligne","N'importe où dans l'intersection","À la hauteur du poteau","Après le passage pour piétons"],
       e:"Arrêtez-vous d'abord à la ligne. Si la vue est bloquée, avancez lentement et arrêtez-vous une deuxième fois une fois que vous voyez." },
  c:0 },

{ id:"mbs2", sec:"signs", sign:"yield",
  en:{ q:"What is the difference between this sign and a stop sign?",
       a:["It means the same thing","You must stop only if there is no safe gap","You never have to slow down","It applies only to trucks"],
       e:"A yield lets you keep rolling when the way is clear. A stop sign requires a full stop every time, clear road or not." },
  fr:{ q:"Quelle est la différence entre ce panneau et un panneau d'arrêt ?",
       a:["Il signifie la même chose","Vous ne devez arrêter que s'il n'y a pas d'espace sécuritaire","Vous n'avez jamais à ralentir","Il ne vise que les camions"],
       e:"Céder le passage permet de continuer si la voie est libre. Un panneau d'arrêt exige un arrêt complet chaque fois, route dégagée ou non." },
  c:1 },

{ id:"mbs3", sec:"signs", sign:"speed-limit-begins",
  en:{ q:"What should you do when you see this sign?",
       a:["Ignore it until the next sign","Speed up","Begin adjusting your speed now so you are at the new limit when you reach it","Brake hard immediately"],
       e:"It warns that the limit changes just ahead. Adjusting early is smoother and safer than braking at the sign itself." },
  fr:{ q:"Que devez-vous faire en voyant ce panneau ?",
       a:["L'ignorer jusqu'au prochain panneau","Accélérer","Commencer à ajuster votre vitesse pour être à la nouvelle limite en y arrivant","Freiner brusquement tout de suite"],
       e:"Il annonce un changement de limite juste devant. Ajuster tôt est plus doux et plus sécuritaire que freiner au panneau même." },
  c:2 },

{ id:"mbs4", sec:"signs", sign:"warn-stop-ahead",
  en:{ q:"Why is this sign placed well before the stop sign itself?",
       a:["To mark a parking area","To show a detour","To allow faster driving","Because the stop sign is hidden by a hill or trees"],
       e:"Start braking here so you arrive at the stop line already slow. It appears where the stop sign cannot be seen from far away." },
  fr:{ q:"Pourquoi ce panneau est-il placé bien avant le panneau d'arrêt lui-même ?",
       a:["Pour indiquer une aire de stationnement","Pour indiquer un détour","Pour permettre de rouler plus vite","Parce que le panneau d'arrêt est caché par une côte ou des arbres"],
       e:"Commencez à freiner ici pour arriver à la ligne d'arrêt déjà lent. Il apparaît là où le panneau d'arrêt ne se voit pas de loin." },
  c:3 },

{ id:"mbs5", sec:"signs", sign:"no-entry",
  en:{ q:"You are facing this sign at the end of a ramp. What has happened?",
       a:["You are about to drive against traffic and must not enter","The ramp is closed for repairs","Trucks are banned","Parking is banned"],
       e:"This is the sign drivers see when about to enter an off-ramp the wrong way. Stop, and find the correct entrance." },
  fr:{ q:"Vous faites face à ce panneau au bout d'une bretelle. Que s'est-il passé ?",
       a:["Vous êtes sur le point de rouler à contresens et ne devez pas vous engager","La bretelle est fermée pour travaux","Les camions sont interdits","Le stationnement est interdit"],
       e:"C'est le panneau que voient les conducteurs sur le point d'emprunter une bretelle de sortie à l'envers. Arrêtez et trouvez la bonne entrée." },
  c:0 },

{ id:"mbs6", sec:"signs", sign:"no-right-turn",
  en:{ q:"What is banned where this sign stands?",
       a:["Passing","Turning right","Turning left","Parking"],
       e:"Carry on to the next intersection instead. The ban usually exists because of a one-way street or a blind corner." },
  fr:{ q:"Qu'est-ce qui est interdit là où se trouve ce panneau ?",
       a:["Le dépassement","Le virage à droite","Le virage à gauche","Le stationnement"],
       e:"Continuez jusqu'à la prochaine intersection. L'interdiction existe généralement à cause d'un sens unique ou d'un angle sans visibilité." },
  c:1 },

{ id:"mbs7", sec:"signs", sign:"hov-lane",
  en:{ q:"When may you use a lane marked with this diamond?",
       a:["Only on weekends","Only if you drive a taxi","When you carry at least the number of people shown","Any time you are late"],
       e:"High occupancy vehicle lanes reward carpooling. Driving alone in one is a ticket, even when the lane is empty." },
  fr:{ q:"Quand pouvez-vous utiliser une voie marquée de ce losange ?",
       a:["Seulement la fin de semaine","Seulement si vous conduisez un taxi","Lorsque vous transportez au moins le nombre de personnes indiqué","Chaque fois que vous êtes en retard"],
       e:"Les voies réservées aux véhicules multioccupants récompensent le covoiturage. Y rouler seul vaut une contravention, même si la voie est vide." },
  c:2 },

{ id:"mbs8", sec:"signs", sign:"stop-school-bus",
  en:{ q:"How far back must you stop behind a Manitoba school bus with red lights flashing?",
       a:["At least 1 metre","At least 20 metres","Any distance","At least 5 metres"],
       e:"Leave at least five metres so children have room to walk around the bus. Wait until the lights stop and the bus moves off." },
  fr:{ q:"À quelle distance devez-vous vous arrêter derrière un autobus scolaire manitobain aux feux rouges clignotants ?",
       a:["À au moins 1 mètre","À au moins 20 mètres","N'importe quelle distance","À au moins 5 mètres"],
       e:"Laissez au moins cinq mètres pour que les enfants puissent contourner l'autobus. Attendez que les feux cessent et que l'autobus reparte." },
  c:3 },

{ id:"mbs9", sec:"signs", sign:"warn-school-zone",
  en:{ q:"What is the reduced speed limit in a Manitoba school zone during posted hours?",
       a:["30 km/h","50 km/h","40 km/h","20 km/h"],
       e:"Thirty in a marked school zone during the hours on the sign. Fines in these zones are increased." },
  fr:{ q:"Quelle est la limite de vitesse réduite dans une zone scolaire au Manitoba pendant les heures affichées ?",
       a:["30 km/h","50 km/h","40 km/h","20 km/h"],
       e:"Trente dans une zone scolaire signalée pendant les heures indiquées. Les amendes y sont majorées." },
  c:0 },

{ id:"mbs10", sec:"signs", sign:"warn-playground",
  en:{ q:"Why does this sign matter even when no children are visible?",
       a:["It only applies on weekends","A child can appear from behind a hedge or parked car at any moment","It only applies in summer","It marks a parking lot"],
       e:"Playground signs mark places where a child can run into the road with no warning, chasing a ball. Stay ready either way." },
  fr:{ q:"Pourquoi ce panneau compte-t-il même si aucun enfant n'est visible ?",
       a:["Il ne s'applique que la fin de semaine","Un enfant peut surgir d'une haie ou d'une voiture stationnée à tout moment","Il ne s'applique qu'en été","Il indique un stationnement"],
       e:"Les panneaux de terrain de jeu signalent les endroits où un enfant peut surgir sans avertissement en courant après un ballon. Restez prêt." },
  c:1 },

{ id:"mbs11", sec:"signs", sign:"warn-railway",
  en:{ q:"How close to the nearest rail may you stop at a railway crossing?",
       a:["10 centimetres","There is no rule","No closer than 5 metres","Right at the rail"],
       e:"Five metres minimum. Never start across until you can see the far side is clear, and remember one train can hide another." },
  fr:{ q:"À quelle distance du rail le plus proche pouvez-vous vous arrêter à un passage à niveau ?",
       a:["À 10 centimètres","Il n'y a aucune règle","À au moins 5 mètres","Juste contre le rail"],
       e:"Cinq mètres minimum. Ne vous engagez jamais avant de voir que l'autre côté est dégagé, et rappelez-vous qu'un train peut en cacher un autre." },
  c:2 },

{ id:"mbs12", sec:"signs", sign:"warn-crossbuck",
  en:{ q:"What does this X-shaped sign mark?",
       a:["A hospital","A crossroads","A construction zone","A railway crossing"],
       e:"The crossbuck marks the crossing itself. Slow, look and listen — many Manitoba crossings have no gates or lights." },
  fr:{ q:"Que signale ce panneau en forme de X ?",
       a:["Un hôpital","Un carrefour","Une zone de travaux","Un passage à niveau"],
       e:"La croix de Saint-André signale le passage lui-même. Ralentissez, regardez et écoutez : beaucoup de passages manitobains n'ont ni barrière ni feux." },
  c:3 },

{ id:"mbs13", sec:"signs", sign:"warn-farm-machinery",
  en:{ q:"What is the main risk on the rural road this sign marks?",
       a:["Wide, slow machines that may turn into a field with little warning","Machines that travel very fast",
          "Machines that are banned from the road","Machines that always have right of way"],
       e:"Tractors and combines are wide and slow and block your view ahead. Hold back until you can see far, and watch for a left turn." },
  fr:{ q:"Quel est le principal risque sur la route rurale indiquée par ce panneau ?",
       a:["Des machines larges et lentes qui peuvent tourner vers un champ sans grand préavis","Des machines qui roulent très vite",
          "Des machines interdites sur la route","Des machines qui ont toujours la priorité"],
       e:"Les tracteurs et moissonneuses sont larges, lents et masquent la vue. Restez en retrait jusqu'à voir loin, et surveillez un virage à gauche." },
  c:0 },

{ id:"mbs14", sec:"signs", sign:"slow-vehicle",
  en:{ q:"A vehicle ahead displays this orange triangle. What does it mean?",
       a:["It is a student driver","It travels at 40 km/h or less","It is broken down","It carries dangerous goods"],
       e:"The slow-moving vehicle sign marks tractors, buggies and similar. Slow early — you close on them much faster than you expect." },
  fr:{ q:"Un véhicule devant affiche ce triangle orange. Que signifie-t-il ?",
       a:["Il est conduit par un apprenti","Il roule à 40 km/h ou moins","Il est en panne","Il transporte des matières dangereuses"],
       e:"Le panneau de véhicule lent signale les tracteurs, les voitures à cheval et autres. Ralentissez tôt : vous les rattrapez bien plus vite que prévu." },
  c:1 },

{ id:"mbs15", sec:"signs", sign:"warn-deer",
  en:{ q:"You hit the brakes for the animal on this sign and it runs off. What should you do next?",
       a:["Turn off your lights","Sound your horn continuously","Stay alert — deer travel in groups","Speed up to make up time"],
       e:"Where there is one deer there are usually more. Keep your speed down for the next stretch and scan the ditches." },
  fr:{ q:"Vous freinez pour l'animal de ce panneau et il s'enfuit. Que devriez-vous faire ensuite ?",
       a:["Éteindre vos phares","Klaxonner sans arrêt","Rester vigilant — les chevreuils se déplacent en groupe","Accélérer pour rattraper le temps perdu"],
       e:"Là où il y a un chevreuil, il y en a habituellement d'autres. Gardez une vitesse réduite sur le tronçon suivant et surveillez les fossés." },
  c:2 },

{ id:"mbs16", sec:"signs", sign:"warn-two-way",
  en:{ q:"What changes after this sign?",
       a:["The road becomes one way","A passing lane opens","The limit doubles","Traffic will come toward you in the next lane"],
       e:"The road stops being divided. Keep right and do not pass without a clear view of the whole road ahead." },
  fr:{ q:"Qu'est-ce qui change après ce panneau ?",
       a:["La route devient à sens unique","Une voie de dépassement s'ouvre","La limite double","La circulation viendra vers vous dans la voie voisine"],
       e:"La route cesse d'être séparée. Tenez votre droite et ne dépassez pas sans une vue dégagée sur toute la route devant." },
  c:3 },

{ id:"mbs17", sec:"signs", sign:"warn-slippery",
  en:{ q:"How should you drive on the section this sign warns about?",
       a:["Smoothly — no sudden braking, steering or acceleration","Brake hard before every curve","Accelerate through it","Change lanes often"],
       e:"Low grip punishes sudden inputs. Gentle steering and braking keep the tires working instead of sliding." },
  fr:{ q:"Comment conduire sur la section annoncée par ce panneau ?",
       a:["En douceur — sans freinage, braquage ni accélération brusques","Freiner fort avant chaque courbe","Accélérer pour la traverser","Changer souvent de voie"],
       e:"Une faible adhérence punit les gestes brusques. Un braquage et un freinage doux gardent les pneus en prise plutôt qu'en glissade." },
  c:0 },

{ id:"mbs18", sec:"signs", sign:"warn-bump",
  en:{ q:"Why slow down for the hazard on this sign?",
       a:["It is only a suggestion","A bump unloads the tires for a moment, reducing grip and steering","It damages your paint","It uses fuel"],
       e:"Crossing a bump at speed lifts weight off the tires exactly when you may need them. Slow before it, not on it." },
  fr:{ q:"Pourquoi ralentir pour le danger indiqué par ce panneau ?",
       a:["Ce n'est qu'une suggestion","Une bosse allège les pneus un instant, réduisant l'adhérence et la direction","Elle abîme la peinture","Elle consomme du carburant"],
       e:"Franchir une bosse à vitesse allège les pneus juste au moment où vous pourriez en avoir besoin. Ralentissez avant, pas dessus." },
  c:1 },

{ id:"mbs19", sec:"signs", sign:"warn-t-intersection",
  en:{ q:"What does this sign tell you about the road you are on?",
       a:["It becomes one way","A signal is coming","It ends ahead and you must turn left or right","It narrows"],
       e:"Slow early. Arriving at a T intersection too fast is a common single-vehicle crash on rural roads." },
  fr:{ q:"Que vous indique ce panneau au sujet de la route où vous êtes ?",
       a:["Elle devient à sens unique","Un feu approche","Elle se termine devant et vous devrez tourner à gauche ou à droite","Elle se rétrécit"],
       e:"Ralentissez tôt. Arriver trop vite à une intersection en T est une cause fréquente de sortie de route en campagne." },
  c:2 },

{ id:"mbs20", sec:"signs", sign:"warn-chevron",
  en:{ q:"A row of these markers lines a bend. What do they tell you?",
       a:["Where to park","The distance to town","A cycling route","Which way the road curves, and how sharply"],
       e:"Chevrons follow the outside of the curve. Closely spaced chevrons mean a sharper bend than widely spaced ones." },
  fr:{ q:"Une rangée de ces marqueurs borde un virage. Que vous indiquent-ils ?",
       a:["Où stationner","La distance jusqu'au village","Un itinéraire cyclable","De quel côté la route tourne, et à quel point"],
       e:"Les chevrons suivent l'extérieur de la courbe. Rapprochés, ils annoncent un virage plus serré." },
  c:3 },

{ id:"mbs21", sec:"signs", sign:"temp-lane-closed",
  en:{ q:"When should you move over after seeing this sign?",
       a:["Early, while a safe gap still exists","At the final cone","After the lane ends","Only if waved in"],
       e:"Merging early and smoothly keeps traffic flowing. Racing to the front and squeezing in is what creates the jam." },
  fr:{ q:"Quand devriez-vous changer de voie après avoir vu ce panneau ?",
       a:["Tôt, pendant qu'il reste un espace sécuritaire","Au dernier cône","Après la fin de la voie","Seulement si on vous fait signe"],
       e:"Se rabattre tôt et en douceur garde la circulation fluide. Foncer jusqu'au bout pour s'imposer crée le bouchon." },
  c:0 },

{ id:"mbs22", sec:"signs", sign:"temp-detour",
  en:{ q:"How do detour signs work?",
       a:["They are advisory only","They form a chain — follow each one to the next","They mark the end of a road","They show where to park"],
       e:"Follow the marked route rather than inventing a shortcut, which often ends at another closed road." },
  fr:{ q:"Comment fonctionnent les panneaux de détour ?",
       a:["Ils ne sont qu'indicatifs","Ils forment une chaîne — suivez-les l'un après l'autre","Ils marquent la fin d'une route","Ils indiquent où stationner"],
       e:"Suivez l'itinéraire indiqué plutôt que d'inventer un raccourci, qui se termine souvent devant une autre route fermée." },
  c:1 },

{ id:"mbs23", sec:"signs", sign:"light-flashing-red",
  en:{ q:"How do you treat a flashing red light in Manitoba?",
       a:["Drive through without slowing","Wait for green","Exactly like a stop sign","Exactly like a yield sign"],
       e:"Full stop, then go when the way is clear. It will not turn green, so waiting for green would leave you there all day." },
  fr:{ q:"Comment traiter un feu rouge clignotant au Manitoba ?",
       a:["Passer sans ralentir","Attendre le vert","Exactement comme un panneau d'arrêt","Exactement comme un panneau de cession de passage"],
       e:"Arrêt complet, puis repartez quand la voie est libre. Il ne passera pas au vert : attendre le vert vous y laisserait toute la journée." },
  c:2 },

{ id:"mbs24", sec:"signs", sign:"light-green-arrow",
  en:{ q:"A green arrow points left while the round light beside it is red. What may you do?",
       a:["Go straight","Turn left only after yielding","Nothing","Turn left — oncoming traffic is being held"],
       e:"The advance green arrow protects your turn. The red still blocks going straight until it changes." },
  fr:{ q:"Une flèche verte pointe à gauche alors que le feu rond à côté est rouge. Que pouvez-vous faire ?",
       a:["Aller tout droit","Tourner à gauche après avoir cédé le passage","Rien","Tourner à gauche — la circulation en sens inverse est retenue"],
       e:"La flèche verte protège votre virage. Le rouge interdit toujours d'aller tout droit jusqu'à ce qu'il change." },
  c:3 },

{ id:"mbs25", sec:"signs", sign:"mark-white-lane",
  en:{ q:"What do broken white lines between lanes mean?",
       a:["Traffic beside you goes the same way and you may change lanes","Traffic comes toward you",
          "You may not change lanes","The road is one way"],
       e:"White separates lanes going the same direction. Solid white asks you to stay put; broken white allows a lane change when safe." },
  fr:{ q:"Que signifient des lignes blanches discontinues entre les voies ?",
       a:["La circulation à côté va dans le même sens et vous pouvez changer de voie","La circulation vient vers vous",
          "Vous ne pouvez pas changer de voie","La route est à sens unique"],
       e:"Le blanc sépare des voies de même sens. Continue, elle demande de rester en place ; discontinue, elle permet un changement de voie sécuritaire." },
  c:0 },

{ id:"mbs26", sec:"signs", sign:"mark-broken-yellow",
  en:{ q:"What does a broken yellow line beside your lane allow?",
       a:["Nothing","Passing when the road ahead is clear","Parking","Driving in either direction"],
       e:"Yellow separates opposite directions. Broken means you may pass when you can see far enough to finish safely." },
  fr:{ q:"Qu'autorise une ligne jaune discontinue à côté de votre voie ?",
       a:["Rien","Le dépassement lorsque la voie devant est libre","Le stationnement","La circulation dans les deux sens"],
       e:"Le jaune sépare les sens opposés. Discontinue, elle permet de dépasser quand vous voyez assez loin pour terminer en sécurité." },
  c:1 },

{ id:"mbs27", sec:"signs", sign:"info-trans-canada",
  en:{ q:"Which route does this maple-leaf marker identify?",
       a:["A toll road","A city ring road","The Trans-Canada Highway","A provincial park road"],
       e:"The Trans-Canada crosses Manitoba from east to west and passes through Winnipeg on its way across the country." },
  fr:{ q:"Quelle route ce marqueur à la feuille d'érable identifie-t-il ?",
       a:["Une route à péage","Un périphérique urbain","La route Transcanadienne","Une route de parc provincial"],
       e:"La Transcanadienne traverse le Manitoba d'est en ouest et passe par Winnipeg." },
  c:2 },

{ id:"mbs28", sec:"signs", sign:"info-accessible",
  en:{ q:"Who may park in a space marked with this sign?",
       a:["Anyone for a short stop","Anyone after 6 p.m.","Delivery vehicles","Only a vehicle displaying a valid accessible parking permit"],
       e:"Only a permit holder, at any hour. Parking there without one carries a heavy fine in every Manitoba municipality." },
  fr:{ q:"Qui peut stationner dans une place marquée de ce panneau ?",
       a:["N'importe qui pour un court arrêt","N'importe qui après 18 h","Les véhicules de livraison","Seulement un véhicule affichant un permis de stationnement accessible valide"],
       e:"Seul un titulaire de permis, à toute heure. S'y stationner sans permis entraîne une lourde amende dans toutes les municipalités manitobaines." },
  c:3 },

{ id:"mbs29", sec:"signs", sign:"warn-low-clearance",
  en:{ q:"Who most needs to read this sign?",
       a:["Anyone driving a tall vehicle or carrying a roof load","Motorcyclists only","Cyclists only","Nobody"],
       e:"The number is the height of the opening ahead. If your vehicle or load is taller, you must take another route." },
  fr:{ q:"Qui doit surtout lire ce panneau ?",
       a:["Toute personne conduisant un véhicule haut ou transportant une charge sur le toit","Seulement les motocyclistes","Seulement les cyclistes","Personne"],
       e:"Le chiffre indique la hauteur du passage devant. Si votre véhicule ou votre chargement dépasse, prenez un autre chemin." },
  c:0 },

{ id:"mbs30", sec:"signs", sign:"warn-narrow-bridge",
  en:{ q:"What is ahead when you see this sign?",
       a:["A truck-only bridge","A bridge narrower than the road you are on","A closed bridge","A toll bridge"],
       e:"Slow down, stay well to your side of the centre line, and do not try to pass on the bridge." },
  fr:{ q:"Qu'y a-t-il devant lorsque vous voyez ce panneau ?",
       a:["Un pont réservé aux camions","Un pont plus étroit que la route où vous êtes","Un pont fermé","Un pont à péage"],
       e:"Ralentissez, restez bien de votre côté de la ligne centrale et ne tentez pas de dépasser sur le pont." },
  c:1 }

);

/* ---------- rules of the road ---------- */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"mbr1", sec:"rules", topic:"licensing",
  en:{ q:"What is the minimum age for a Manitoba Class 5 Learner licence?",
       a:["17","15","16, or 15 and a half if enrolled in a high school driver education course","18"],
       e:"Sixteen normally, or fifteen and a half while taking a high school driver education course." },
  fr:{ q:"Quel est l'âge minimal pour un permis d'apprenti classe 5 au Manitoba ?",
       a:["17 ans","15 ans","16 ans, ou 15 ans et demi si inscrit à un cours de conduite au secondaire","18 ans"],
       e:"Seize ans normalement, ou quinze ans et demi pendant un cours de conduite au secondaire." },
  c:2 },

{ id:"mbr2", sec:"rules", topic:"licensing",
  en:{ q:"How long must a Manitoba learner stay in the learner stage?",
       a:["Three months","Twelve months","There is no minimum","At least nine months"],
       e:"A minimum of nine months, not counting any interruption to the licence, before moving to the intermediate stage." },
  fr:{ q:"Combien de temps un apprenti manitobain doit-il rester à l'étape apprenti ?",
       a:["Trois mois","Douze mois","Il n'y a pas de minimum","Au moins neuf mois"],
       e:"Un minimum de neuf mois, sans compter les interruptions du permis, avant de passer à l'étape intermédiaire." },
  c:3 },

{ id:"mbr3", sec:"rules", topic:"licensing",
  en:{ q:"How much driving experience must a Manitoba learner's supervising driver have?",
       a:["A full licence for at least 36 months","One year","Six months","No requirement"],
       e:"At least thirty-six months fully licensed. They must also be under .05 blood alcohol and must not fail a drug screening test." },
  fr:{ q:"Quelle expérience de conduite le superviseur d'un apprenti manitobain doit-il avoir ?",
       a:["Un permis complet depuis au moins 36 mois","Un an","Six mois","Aucune exigence"],
       e:"Au moins trente-six mois de permis complet. Il doit aussi être sous 0,05 d'alcoolémie et ne pas échouer un test de dépistage de drogue." },
  c:0 },

{ id:"mbr4", sec:"rules", topic:"licensing",
  en:{ q:"Where must a Manitoba learner's supervising driver sit?",
       a:["In the back seat","In the front passenger seat","Anywhere in the vehicle","Directly behind the driver"],
       e:"Front passenger seat only, so they can see what you see and reach the controls if needed." },
  fr:{ q:"Où doit s'asseoir le superviseur d'un apprenti manitobain ?",
       a:["Sur la banquette arrière","Sur le siège du passager avant","N'importe où dans le véhicule","Juste derrière le conducteur"],
       e:"Sur le siège du passager avant seulement, pour voir ce que vous voyez et atteindre les commandes au besoin." },
  c:1 },

{ id:"mbr5", sec:"rules", topic:"licensing",
  en:{ q:"Where may passengers sit in a Manitoba learner's vehicle?",
       a:["Only in the front","No passengers at all","In the rear, up to the number of working seatbelts","Anywhere, with no limit"],
       e:"The front passenger seat belongs to the supervising driver. Other passengers ride in the rear, one per working seatbelt." },
  fr:{ q:"Où les passagers peuvent-ils s'asseoir dans le véhicule d'un apprenti manitobain ?",
       a:["Seulement à l'avant","Aucun passager","À l'arrière, jusqu'au nombre de ceintures fonctionnelles","N'importe où, sans limite"],
       e:"Le siège du passager avant revient au superviseur. Les autres passagers prennent place à l'arrière, un par ceinture fonctionnelle." },
  c:2 },

{ id:"mbr6", sec:"rules", topic:"licensing",
  en:{ q:"How much alcohol or drugs may a Manitoba learner have in their system?",
       a:["Under .05","Under .08","No rule applies to learners","None at all"],
       e:"Zero for the whole graduated licensing programme. The supervising driver has a separate limit of under .05." },
  fr:{ q:"Quelle quantité d'alcool ou de drogue un apprenti manitobain peut-il avoir dans l'organisme ?",
       a:["Moins de 0,05","Moins de 0,08","Aucune règle pour les apprentis","Aucune"],
       e:"Zéro pendant tout le programme de permis par étapes. Le superviseur a une limite distincte, sous 0,05." },
  c:3 },

{ id:"mbr7", sec:"rules", topic:"licensing",
  en:{ q:"Which of these may a Manitoba learner NOT do?",
       a:["Tow another vehicle","Drive on a city street","Carry a rear-seat passenger","Drive in daylight"],
       e:"Learners may not tow, may not drive a Class 3 farm truck, and may not operate off-road vehicles on a highway." },
  fr:{ q:"Que ne peut PAS faire un apprenti conducteur manitobain ?",
       a:["Remorquer un autre véhicule","Conduire dans une rue de ville","Transporter un passager à l'arrière","Conduire le jour"],
       e:"Les apprentis ne peuvent pas remorquer, ni conduire un camion agricole de classe 3, ni utiliser un véhicule hors route sur une voie publique." },
  c:0 },

{ id:"mbr8", sec:"rules", topic:"licence",
  en:{ q:"How long do you have to complete the Manitoba knowledge test?",
       a:["No time limit","30 minutes","15 minutes","60 minutes"],
       e:"Thirty minutes. The test is done on a computer, it is not open book, and phones and other devices are not allowed." },
  fr:{ q:"Combien de temps avez-vous pour terminer l'examen théorique manitobain ?",
       a:["Aucune limite de temps","30 minutes","15 minutes","60 minutes"],
       e:"Trente minutes. L'examen se fait à l'ordinateur, à livre fermé, et les téléphones et autres appareils sont interdits." },
  c:1 },

{ id:"mbr9", sec:"rules", topic:"licence",
  en:{ q:"Which three areas does the Manitoba knowledge test cover?",
       a:["Geography, weather and maps","Only road signs","Traffic laws, safe driving practices and road sign recognition","Mechanics, first aid and insurance"],
       e:"Study all three in the Driver's Handbook. Sign recognition is the part most people underestimate." },
  fr:{ q:"Quels trois domaines l'examen théorique manitobain couvre-t-il ?",
       a:["La géographie, la météo et les cartes","Seulement les panneaux","Les lois de la circulation, les pratiques de conduite sécuritaire et la reconnaissance des panneaux","La mécanique, les premiers soins et l'assurance"],
       e:"Étudiez les trois dans le guide du conducteur. La reconnaissance des panneaux est la partie que l'on sous-estime le plus." },
  c:2 },

{ id:"mbr10", sec:"rules", topic:"licence",
  en:{ q:"What must you carry whenever you drive in Manitoba?",
       a:["Only your licence","Only insurance","Nothing","Your licence, registration and proof of insurance"],
       e:"All three. An officer may ask for each one at any stop, and driving without them can bring a fine." },
  fr:{ q:"Que devez-vous avoir avec vous chaque fois que vous conduisez au Manitoba ?",
       a:["Seulement votre permis","Seulement l'assurance","Rien","Votre permis, l'immatriculation et la preuve d'assurance"],
       e:"Les trois. Un agent peut exiger chacun d'eux, et conduire sans eux peut valoir une amende." },
  c:3 },

{ id:"mbr11", sec:"rules", topic:"safe",
  en:{ q:"What is the default speed limit in a Manitoba city or town with no posted sign?",
       a:["50 km/h","30 km/h","60 km/h","80 km/h"],
       e:"Fifty inside a built-up area. On a provincial highway with no sign the default rises to 90 km/h." },
  fr:{ q:"Quelle est la limite de vitesse par défaut dans une ville manitobaine sans panneau ?",
       a:["50 km/h","30 km/h","60 km/h","80 km/h"],
       e:"Cinquante en zone bâtie. Sur une route provinciale sans panneau, la limite par défaut passe à 90 km/h." },
  c:0 },

{ id:"mbr12", sec:"rules", topic:"safe",
  en:{ q:"What is the two-second rule?",
       a:["How long a turn should take","A minimum following distance measured in time, not metres","A rule about signalling","How long to wait at a stop sign"],
       e:"Time works at any speed, unlike a fixed distance. Double it to four seconds or more in rain, snow or fog." },
  fr:{ q:"Qu'est-ce que la règle des deux secondes ?",
       a:["La durée d'un virage","Une distance de suivi minimale mesurée en temps, pas en mètres","Une règle sur le clignotant","Le temps d'attente à un arrêt"],
       e:"Le temps fonctionne à toute vitesse, contrairement à une distance fixe. Doublez à quatre secondes ou plus sous la pluie, la neige ou le brouillard." },
  c:1 },

{ id:"mbr13", sec:"rules", topic:"safe",
  en:{ q:"How far ahead should you signal a turn in town?",
       a:["After starting the turn","Signalling is optional","At least 30 metres","Right as you turn"],
       e:"Signal early enough for drivers behind to react, then cancel it after the turn so nobody is misled." },
  fr:{ q:"Combien de temps avant un virage devez-vous signaler en ville ?",
       a:["Après avoir commencé à tourner","Le clignotant est facultatif","Au moins 30 mètres avant","Juste au moment de tourner"],
       e:"Signalez assez tôt pour que les conducteurs derrière réagissent, puis annulez le clignotant après le virage pour ne pas induire les autres en erreur." },
  c:2 },

{ id:"mbr14", sec:"rules", topic:"safe",
  en:{ q:"Which lane should you normally use on a Manitoba divided highway?",
       a:["The left lane","The middle","Any lane","The right lane, keeping left for passing"],
       e:"Keep right except to pass. Sitting in the left lane forces others to pass on your right, where their blind spot is worst." },
  fr:{ q:"Quelle voie devez-vous normalement utiliser sur une route à chaussées séparées au Manitoba ?",
       a:["La voie de gauche","Celle du milieu","N'importe laquelle","La voie de droite, en gardant la gauche pour dépasser"],
       e:"Tenez la droite sauf pour dépasser. Rester à gauche force les autres à vous dépasser par la droite, là où leur angle mort est le pire." },
  c:3 },

{ id:"mbr15", sec:"rules", topic:"sharing",
  en:{ q:"A school bus on an undivided Manitoba road stops with red lights flashing. Who must stop?",
       a:["Traffic in both directions","Only traffic behind the bus","Only traffic coming toward it","Nobody"],
       e:"Both directions stop unless a median divides the road. Children may cross in front of the bus without looking." },
  fr:{ q:"Un autobus scolaire s'arrête avec feux rouges clignotants sur une route manitobaine sans terre-plein. Qui doit s'arrêter ?",
       a:["La circulation dans les deux sens","Seulement celle derrière l'autobus","Seulement celle en sens inverse","Personne"],
       e:"Les deux sens s'arrêtent, sauf si un terre-plein sépare la route. Des enfants peuvent traverser devant l'autobus sans regarder." },
  c:0 },

{ id:"mbr16", sec:"rules", topic:"sharing",
  en:{ q:"What must you do when passing a stopped emergency vehicle with flashing lights?",
       a:["Stop completely","Slow down, and move over a lane where the road allows","Keep your speed","Sound your horn"],
       e:"Manitoba's slow-down-and-move-over rule protects roadside workers. Give them a full lane whenever a second lane exists." },
  fr:{ q:"Que devez-vous faire en dépassant un véhicule d'urgence arrêté avec gyrophares ?",
       a:["Vous arrêter complètement","Ralentir et changer de voie là où la route le permet","Garder votre vitesse","Klaxonner"],
       e:"La règle manitobaine du ralentissement et du changement de voie protège les travailleurs en bordure de route. Laissez-leur une voie entière lorsqu'une deuxième existe." },
  c:1 },

{ id:"mbr17", sec:"rules", topic:"sharing",
  en:{ q:"How should you pass a cyclist on a Manitoba road?",
       a:["Sound your horn to move them over","Drive alongside them","Leave plenty of room, changing lanes if the lane is narrow","Pass close and quickly"],
       e:"Treat a bike as a vehicle entitled to the lane. Wait for a clear stretch rather than squeezing past." },
  fr:{ q:"Comment dépasser un cycliste sur une route manitobaine ?",
       a:["Klaxonner pour qu'il se tasse","Rouler à côté de lui","Laisser beaucoup d'espace, en changeant de voie si la voie est étroite","Passer de près et vite"],
       e:"Traitez un vélo comme un véhicule qui a droit à la voie. Attendez une portion dégagée plutôt que de vous faufiler." },
  c:2 },

{ id:"mbr18", sec:"rules", topic:"conditions",
  en:{ q:"Manitoba highways get ground blizzards. What is the safest response when visibility drops to nothing?",
       a:["Stop in your lane","Speed up to get through","Follow the car ahead closely","Slow down and, if you must stop, get well off the road with lights on"],
       e:"Stopping in a travel lane invites a rear-end collision from someone who cannot see either. Get right off, keep lights on and stay belted." },
  fr:{ q:"Les routes manitobaines connaissent des poudreries. Quelle est la réaction la plus sûre quand la visibilité tombe à zéro ?",
       a:["Vous arrêter dans votre voie","Accélérer pour traverser","Suivre de près la voiture devant","Ralentir et, s'il faut arrêter, quitter complètement la route avec les feux allumés"],
       e:"S'arrêter dans une voie invite une collision arrière par quelqu'un qui ne voit pas non plus. Dégagez complètement, gardez les feux allumés et restez attaché." },
  c:3 },

{ id:"mbr19", sec:"rules", topic:"conditions",
  en:{ q:"Where does ice form first on a Manitoba road in autumn?",
       a:["On bridges and overpasses","In the middle of a sunny street","Only in parking lots","Only on gravel"],
       e:"Bridges lose heat from above and below, so they freeze while the rest of the road is only wet." },
  fr:{ q:"Où la glace se forme-t-elle d'abord sur une route manitobaine à l'automne ?",
       a:["Sur les ponts et les viaducs","Au milieu d'une rue ensoleillée","Seulement dans les stationnements","Seulement sur le gravier"],
       e:"Les ponts perdent leur chaleur par le dessus et le dessous : ils gèlent alors que le reste de la route n'est que mouillé." },
  c:0 },

{ id:"mbr20", sec:"rules", topic:"conditions",
  en:{ q:"Why do winter tires help even on a dry, very cold Manitoba day?",
       a:["They make the car quieter","Their rubber stays soft below about 7 °C so they keep grip","They are wider","They only help in deep snow"],
       e:"Grip comes from rubber that can flex. Below roughly 7 °C an all-season tire stiffens and its braking distance grows." },
  fr:{ q:"Pourquoi les pneus d'hiver aident-ils même par une journée manitobaine sèche et très froide ?",
       a:["Ils rendent la voiture plus silencieuse","Leur gomme reste souple sous environ 7 °C et garde l'adhérence","Ils sont plus larges","Ils n'aident que dans la neige épaisse"],
       e:"L'adhérence vient d'une gomme capable de se déformer. Sous environ 7 °C, un pneu quatre saisons durcit et sa distance de freinage augmente." },
  c:1 },

{ id:"mbr21", sec:"rules", topic:"conditions",
  en:{ q:"Your car starts to skid on a Manitoba winter road. Where should you look?",
       a:["Straight down","At the vehicle you might hit","Where you want the car to go","At the ditch"],
       e:"Your hands follow your eyes. Ease off the gas, look at your escape path and steer gently toward it." },
  fr:{ q:"Votre voiture commence à déraper sur une route d'hiver au Manitoba. Où devez-vous regarder ?",
       a:["Droit vers le sol","Vers le véhicule que vous risquez de heurter","Là où vous voulez que la voiture aille","Vers le fossé"],
       e:"Vos mains suivent votre regard. Levez le pied, regardez votre trajectoire de sortie et braquez doucement vers elle." },
  c:2 },

{ id:"mbr22", sec:"rules", topic:"impaired",
  en:{ q:"Is holding a phone allowed while driving in Manitoba?",
       a:["Yes, for calls only","Yes, at red lights","Yes, if you are stopped in traffic","No — hand-held use is prohibited, hands-free is permitted"],
       e:"Hand-held use is prohibited whenever you are in control of the vehicle, including stopped at a light." },
  fr:{ q:"Est-il permis de tenir un téléphone en conduisant au Manitoba ?",
       a:["Oui, pour les appels seulement","Oui, aux feux rouges","Oui, si vous êtes immobilisé dans la circulation","Non — l'usage à main est interdit, le mains libres est permis"],
       e:"L'usage à main est interdit dès que vous avez la maîtrise du véhicule, y compris à l'arrêt à un feu." },
  c:3 },

{ id:"mbr23", sec:"rules", topic:"impaired",
  en:{ q:"Why can prescription medicine be a problem for driving?",
       a:["Some medicines cause drowsiness or slow reactions, which is still impaired driving",
          "It cannot, if a doctor prescribed it","Only illegal drugs count","It only matters over 65"],
       e:"Read the label and ask your pharmacist. Allergy pills, cold medicine and some painkillers can make you drowsy enough to be charged." },
  fr:{ q:"Pourquoi un médicament sur ordonnance peut-il poser problème au volant ?",
       a:["Certains médicaments causent de la somnolence ou ralentissent les réflexes, ce qui reste de la conduite avec facultés affaiblies",
          "Il ne peut pas, si un médecin l'a prescrit","Seules les drogues illégales comptent","Cela ne compte qu'après 65 ans"],
       e:"Lisez l'étiquette et demandez à votre pharmacien. Antihistaminiques, médicaments contre le rhume et certains analgésiques peuvent causer assez de somnolence pour mener à une accusation." },
  c:0 },

{ id:"mbr24", sec:"rules", topic:"impaired",
  en:{ q:"A friend who has been drinking wants to drive home. What should you do?",
       a:["Give them coffee","Take the keys and arrange another ride","Let them drive slowly","Follow behind them"],
       e:"Only time clears alcohol. Arranging a ride is a small inconvenience next to a collision or a criminal record." },
  fr:{ q:"Un ami qui a bu veut rentrer en voiture. Que devriez-vous faire ?",
       a:["Lui donner un café","Prendre ses clés et organiser un autre transport","Le laisser conduire lentement","Le suivre"],
       e:"Seul le temps élimine l'alcool. Organiser un transport est un petit inconvénient comparé à une collision ou à un casier judiciaire." },
  c:1 },

{ id:"mbr25", sec:"rules", topic:"vehicle",
  en:{ q:"Who is responsible for seatbelts for passengers under 18 in Manitoba?",
       a:["The vehicle owner","Nobody","The driver","Each passenger"],
       e:"The driver answers for younger passengers, including the correct child seat or booster for their age and size." },
  fr:{ q:"Qui est responsable des ceintures des passagers de moins de 18 ans au Manitoba ?",
       a:["Le propriétaire du véhicule","Personne","Le conducteur","Chaque passager"],
       e:"Le conducteur répond des passagers plus jeunes, y compris du siège d'auto ou du siège d'appoint adapté à leur âge et à leur taille." },
  c:2 },

{ id:"mbr26", sec:"rules", topic:"vehicle",
  en:{ q:"Why should you carry a winter emergency kit in Manitoba?",
       a:["It improves fuel economy","Insurance requires it","It reduces tire wear","Help can be far away and the cold is dangerous"],
       e:"On a rural highway you may wait a long time. A blanket, warm clothes, a shovel, food, water and a charged phone are the basics." },
  fr:{ q:"Pourquoi transporter une trousse d'urgence hivernale au Manitoba ?",
       a:["Cela améliore la consommation","L'assurance l'exige","Cela réduit l'usure des pneus","Les secours peuvent être loin et le froid est dangereux"],
       e:"Sur une route rurale, l'attente peut être longue. Couverture, vêtements chauds, pelle, nourriture, eau et téléphone chargé sont l'essentiel." },
  c:3 },

{ id:"mbr27", sec:"rules", topic:"vehicle",
  en:{ q:"What does it mean if the ABS light stays on after you start the engine?",
       a:["The anti-lock system has a fault and needs service","The parking brake is on",
          "You are low on fuel","The headlights are on"],
       e:"Your brakes still work, but the anti-lock function may not. Leave extra following distance until it is repaired." },
  fr:{ q:"Que signifie un témoin ABS qui reste allumé après le démarrage ?",
       a:["Le système antiblocage présente une défaillance et doit être vérifié","Le frein de stationnement est serré",
          "Le niveau de carburant est bas","Les phares sont allumés"],
       e:"Vos freins fonctionnent encore, mais la fonction antiblocage peut être hors service. Gardez plus de distance jusqu'à la réparation." },
  c:0 },

{ id:"mbr28", sec:"rules", topic:"collisions",
  en:{ q:"You are first at a collision scene in Manitoba. What comes first?",
       a:["Move the vehicles","Make the scene safe and call 911","Move the injured","Take photographs"],
       e:"Protect the scene and call for help. Do not move an injured person unless there is immediate danger such as fire." },
  fr:{ q:"Vous arrivez le premier sur les lieux d'une collision au Manitoba. Que faites-vous d'abord ?",
       a:["Déplacer les véhicules","Sécuriser les lieux et appeler le 911","Déplacer les blessés","Prendre des photos"],
       e:"Protégez les lieux et appelez à l'aide. Ne déplacez pas une personne blessée sauf danger immédiat, comme un incendie." },
  c:1 },

{ id:"mbr29", sec:"rules", topic:"collisions",
  en:{ q:"How should you use anti-lock brakes in an emergency stop?",
       a:["Press lightly","Use the parking brake","Press hard and hold, steering around the hazard","Pump the pedal"],
       e:"ABS pumps for you. The vibration under your foot is normal — keep firm pressure and steer, because ABS lets you brake and steer at once." },
  fr:{ q:"Comment utiliser des freins antiblocage lors d'un arrêt d'urgence ?",
       a:["Appuyer légèrement","Utiliser le frein de stationnement","Appuyer fermement et maintenir, en contournant l'obstacle","Pomper la pédale"],
       e:"L'ABS pompe à votre place. La vibration sous le pied est normale : maintenez une pression ferme et braquez, car l'ABS permet de freiner et de diriger en même temps." },
  c:2 },

{ id:"mbr30", sec:"rules", topic:"collisions",
  en:{ q:"Your vehicle breaks down on a Manitoba highway in winter. What is usually safest?",
       a:["Walk to the nearest town","Stand beside the road","Leave the car in a driving lane","Stay in the vehicle with hazards on unless help is very close"],
       e:"Your car is shelter and it is visible. Walking in a Manitoba winter is how people get into serious trouble." },
  fr:{ q:"Votre véhicule tombe en panne sur une route manitobaine en hiver. Qu'est-ce qui est habituellement le plus sûr ?",
       a:["Marcher jusqu'au village le plus proche","Vous tenir au bord de la route","Laisser la voiture dans une voie de circulation","Rester dans le véhicule avec les feux de détresse, sauf si l'aide est tout près"],
       e:"Votre voiture est un abri et elle est visible. Marcher pendant un hiver manitobain est la façon dont les gens se mettent en danger." },
  c:3 }

);

/* ---------------------------------------------------------------------------
   THE PROVINCE. Everything the engine needs to run the Manitoba practice test.
   --------------------------------------------------------------------------- */
window.CQ_PROVINCE = {
  code: "MB",
  name: { en: "Manitoba", fr: "Manitoba" },
  licence: "Class 5L",
  minutes: 30,
  /* MPI publishes the 30-minute limit and the three subject areas, but not the
     exact number of questions or the pass mark. Our mock test uses a fair,
     clearly-stated approximation: 30 questions in 30 minutes, pass at 24. */
  sections: [
    { id: "signs", ask: 15, pass: 12,
      name: { en: "Road Signs", fr: "Panneaux routiers" } },
    { id: "rules", ask: 15, pass: 12,
      name: { en: "Traffic Laws and Safe Driving", fr: "Lois de la circulation et conduite sécuritaire" } }
  ],
  handbook: { en: "Manitoba Driver's Handbook (MPI)",
              fr: "Guide du conducteur du Manitoba (MPI)" },
  handbookUrl: "https://apps.mpi.mb.ca/comms/drivershandbook/",
  bookingUrl: "https://www.mpi.mb.ca/testing-for-your-class-5-licence/",
  topics: [
    { id:"licensing",  en:"Graduated Licensing",         fr:"Permis par étapes" },
    { id:"safe",       en:"Safe and Responsible Driving", fr:"Conduite sécuritaire et responsable" },
    { id:"sharing",    en:"Sharing the Road",             fr:"Partager la route" },
    { id:"conditions", en:"Driving Conditions",           fr:"Conditions de conduite" },
    { id:"licence",    en:"Your Licence and the Test",    fr:"Votre permis et l'examen" },
    { id:"impaired",   en:"Impaired and Distracted Driving", fr:"Facultés affaiblies et distraction" },
    { id:"vehicle",    en:"Your Vehicle",                 fr:"Votre véhicule" },
    { id:"collisions", en:"Emergencies and Collisions",   fr:"Urgences et collisions" }
  ],
  questions: window.CQ_DRIVE_Q
};


/* Ten more rules questions, added 3 September 2026.
   Written from this jurisdiction's own official handbook, and
   chosen for what makes its rules different from its neighbours'.
   The French is written beside the English on purpose: see the
   note at the top of tools/newq/fr_qbank.py. */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"mbx1", sec:"rules",
  en:{ q:"What are the three stages of Manitoba's graduated licensing programme?",
       a:["L, N and full","Class 5L, Class 5I and Class 5F","G1, G2 and G","Learner, probationary and regular"],
       e:"Manitoba uses Class 5L (learner), Class 5I (intermediate) and Class 5F (full). Ontario uses G1, G2 and G; British Columbia uses L and N." },
  fr:{ q:"Quelles sont les trois étapes du programme d'accès graduel à la conduite du Manitoba ?",
       a:["L, N et complet","Classe 5L, classe 5I et classe 5F","G1, G2 et G","Apprenti, probatoire et régulier"],
       e:"Le Manitoba utilise la classe 5L (apprenti), la classe 5I (intermédiaire) et la classe 5F (complète). L'Ontario emploie G1, G2 et G ; la Colombie-Britannique, L et N." },
  c:1 },

{ id:"mbx2", sec:"rules",
  en:{ q:"How long must a Manitoba driver stay at zero alcohol?",
       a:["Only while a learner","Until the intermediate stage ends","Until age 21","Through both new stages and the first 36 months of the full licence"],
       e:"Manitoba is unusual: zero alcohol does not stop when you get your full Class 5F licence. It continues for the first 36 months of that stage, roughly five years from the day you start." },
  fr:{ q:"Combien de temps un conducteur manitobain doit-il demeurer à zéro alcool ?",
       a:["Seulement pendant le stade d'apprenti","Jusqu'à la fin du stade intermédiaire","Jusqu'à 21 ans","Pendant les deux stades de nouveau conducteur et les 36 premiers mois du permis complet"],
       e:"Le Manitoba se distingue : le zéro alcool ne cesse pas à l'obtention du permis complet de classe 5F. Il se poursuit pendant les 36 premiers mois de ce stade, soit environ cinq ans depuis le début." },
  c:3 },

{ id:"mbx3", sec:"rules",
  en:{ q:"How long must a Manitoba learner's supervising driver have held a full licence?",
       a:["6 months","1 year","3 years","10 years"],
       e:"The supervising driver must have held a full Class 5F for at least three years, must be the only front-seat passenger, and must be under .05." },
  fr:{ q:"Depuis combien de temps l'accompagnateur d'un apprenti manitobain doit-il détenir un permis complet ?",
       a:["6 mois","1 an","3 ans","10 ans"],
       e:"L'accompagnateur doit détenir une classe 5F complète depuis au moins trois ans, être le seul passager avant et avoir un taux d'alcoolémie inférieur à 0,05." },
  c:2 },

{ id:"mbx4", sec:"rules",
  en:{ q:"Between midnight and 5 a.m., how many passengers may a Manitoba intermediate driver carry alone?",
       a:["None","One","Three","As many as there are seat belts"],
       e:"Between midnight and 5 a.m. a Class 5I driver may carry only one passenger, unless a qualified supervising driver is in the front seat." },
  fr:{ q:"Entre minuit et 5 h, combien de passagers un conducteur intermédiaire manitobain peut-il transporter seul ?",
       a:["Aucun","Un","Trois","Autant qu'il y a de ceintures"],
       e:"Entre minuit et 5 h, un conducteur de classe 5I ne peut transporter qu'un seul passager, sauf si un accompagnateur qualifié occupe le siège avant." },
  c:1 },

{ id:"mbx5", sec:"rules",
  en:{ q:"What does Manitoba use instead of demerit points?",
       a:["A warning letter system","A points bank","The Driver Safety Rating scale","Nothing at all"],
       e:"Manitoba runs a Driver Safety Rating scale from +20 down to −20. Good driving moves you up and cuts your premium; convictions move you down." },
  fr:{ q:"Qu'utilise le Manitoba à la place des points d'inaptitude ?",
       a:["Un système de lettres d'avertissement","Une banque de points","L'échelle de la cote de sécurité du conducteur","Rien du tout"],
       e:"Le Manitoba applique une cote de sécurité du conducteur allant de +20 à −20. Une bonne conduite vous fait monter et réduit votre prime ; les condamnations vous font descendre." },
  c:2 },

{ id:"mbx6", sec:"rules",
  en:{ q:"What happens to a Manitoba driver caught using a hand-held phone?",
       a:["A warning","A $200 fine only","3 demerit points only","A $672 fine and a 3-day licence suspension"],
       e:"A first offence is $672 and an immediate three-day suspension, rising to seven days next time, plus a drop of five levels on the Driver Safety Rating." },
  fr:{ q:"Qu'arrive-t-il à un conducteur manitobain surpris à utiliser un téléphone à main ?",
       a:["Un avertissement","Une amende de 200 $ seulement","3 points d'inaptitude seulement","Une amende de 672 $ et une suspension de permis de 3 jours"],
       e:"Une première infraction entraîne 672 $ et une suspension immédiate de trois jours, portée à sept jours la fois suivante, plus une baisse de cinq échelons de la cote de sécurité du conducteur." },
  c:3 },

{ id:"mbx7", sec:"rules",
  en:{ q:"What is the default speed limit on a Manitoba rural highway with no sign?",
       a:["90 km/h","80 km/h","100 km/h","110 km/h"],
       e:"Manitoba's rural default is 90 km/h, and 50 km/h in a city or town. Saskatchewan's rural default next door is 80 km/h." },
  fr:{ q:"Quelle est la limite de vitesse par défaut sur une route rurale manitobaine sans panneau ?",
       a:["90 km/h","80 km/h","100 km/h","110 km/h"],
       e:"La limite rurale par défaut au Manitoba est de 90 km/h, et de 50 km/h en ville ou en village. Chez sa voisine la Saskatchewan, la limite rurale par défaut est de 80 km/h." },
  c:0 },

{ id:"mbx8", sec:"rules",
  en:{ q:"When are studded tires illegal in Manitoba?",
       a:["All year","Between 30 April and 1 October","Only in Winnipeg","They are never illegal"],
       e:"Studded tires may not be used between 30 April and 1 October. Winter tires themselves are not required by law in Manitoba." },
  fr:{ q:"Quand les pneus cloutés sont-ils interdits au Manitoba ?",
       a:["Toute l'année","Entre le 30 avril et le 1er octobre","Seulement à Winnipeg","Ils ne sont jamais interdits"],
       e:"Les pneus cloutés ne peuvent être utilisés entre le 30 avril et le 1er octobre. Les pneus d'hiver eux-mêmes ne sont pas obligatoires par la loi au Manitoba." },
  c:1 },

{ id:"mbx9", sec:"rules",
  en:{ q:"When may a child stop using a booster seat in Manitoba?",
       a:["At age 5","At 18 kg","At 145 cm, 80 lb or age 9 — whichever comes first","At age 12"],
       e:"A child may leave the booster on reaching 145 cm, or 80 lb, or age 9 — whichever happens first." },
  fr:{ q:"Quand un enfant peut-il cesser d'utiliser un siège d'appoint au Manitoba ?",
       a:["À 5 ans","À 18 kg","À 145 cm, 80 lb ou 9 ans, selon la première éventualité","À 12 ans"],
       e:"Un enfant peut quitter le siège d'appoint dès qu'il atteint 145 cm, 80 lb ou 9 ans, selon la première éventualité." },
  c:2 },

{ id:"mbx10", sec:"rules",
  en:{ q:"What is the speed limit in a Manitoba school zone where the regular limit is under 80 km/h?",
       a:["30 km/h","40 km/h","50 km/h","60 km/h"],
       e:"Where the regular limit is under 80 km/h a school zone is 30 km/h. Where it is 80 or more the school zone is 50 km/h. The hours are set by each municipality, so read the sign." },
  fr:{ q:"Quelle est la limite de vitesse dans une zone scolaire manitobaine où la limite habituelle est inférieure à 80 km/h ?",
       a:["30 km/h","40 km/h","50 km/h","60 km/h"],
       e:"Là où la limite habituelle est inférieure à 80 km/h, la zone scolaire est à 30 km/h. Là où elle est de 80 km/h ou plus, la zone scolaire est à 50 km/h. Les heures sont fixées par chaque municipalité : lisez le panneau." },
  c:0 }
);
