/* canada-quiz.com — NEW BRUNSWICK Class 7 Level 1 practice data
   67 original bilingual questions (34 road signs + 33 rules of the road).
   Written in our own words from the free New Brunswick Driver's Handbook, the
   driver licensing pages on gnb.ca, Service New Brunswick's driving-test pages
   and the province's own highway-wildlife page.
   Not affiliated with Service New Brunswick or the Government of New Brunswick.

   The quiz code lives in js/driving-engine.js and never changes per province. */
window.CQ_DRIVE_Q = [];

/* ---------- road signs ---------- */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"nbs1", sec:"signs", sign:"stop",
  en:{ q:"What must you do at this sign?",
       a:["Come to a complete stop, then go when it is safe","Slow down and keep rolling","Stop only if you see another vehicle","Sound your horn and continue"],
       e:"A complete stop means the wheels stop turning. Stop at the line, or before the crosswalk if there is no line, then move off once the way is clear." },
  fr:{ q:"Que devez-vous faire à ce panneau ?",
       a:["Faire un arrêt complet, puis avancer quand c'est sécuritaire","Ralentir et continuer à rouler","Vous arrêter seulement si vous voyez un autre véhicule","Klaxonner et continuer"],
       e:"Un arrêt complet signifie que les roues cessent de tourner. Arrêtez-vous à la ligne, ou avant le passage pour piétons s'il n'y en a pas, puis repartez une fois la voie libre." },
  c:0 },
{ id:"nbs2", sec:"signs", sign:"yield",
  en:{ q:"What does this sign ask of you?",
       a:["Let traffic and pedestrians already there go first","Stop every time","Speed up to merge","Turn right only"],
       e:"Yield means give way. Slow down, be ready to stop, and go only when you will not force anybody else to brake or swerve." },
  fr:{ q:"Que vous demande ce panneau ?",
       a:["Laisser passer d'abord la circulation et les piétons déjà là","Vous arrêter chaque fois","Accélérer pour vous insérer","Tourner à droite seulement"],
       e:"Céder le passage veut dire laisser passer. Ralentissez, soyez prêt à arrêter, et n'avancez que si personne n'est forcé de freiner ou de faire un écart." },
  c:0 },
{ id:"nbs3", sec:"signs", sign:"no-entry",
  en:{ q:"You see this sign at the mouth of a street. What does it mean?",
       a:["Do not enter, traffic comes the other way","Entry allowed after 6 p.m.","Trucks only","Parking area ahead"],
       e:"The street faces you the wrong way. Driving in puts you head-on against traffic, which is one of the most dangerous mistakes a new driver can make." },
  fr:{ q:"Vous voyez ce panneau à l'entrée d'une rue. Que signifie-t-il ?",
       a:["Entrée interdite, la circulation vient en sens inverse","Entrée permise après 18 h","Camions seulement","Aire de stationnement devant"],
       e:"La rue est à sens unique face à vous. Y entrer vous met de front contre la circulation, l'une des erreurs les plus dangereuses pour un nouveau conducteur." },
  c:0 },
{ id:"nbs4", sec:"signs", sign:"one-way",
  en:{ q:"What is this sign telling you?",
       a:["All traffic on this street moves in the direction of the arrow","The road bends in that direction","Turn here for parking","Two-way traffic starts here"],
       e:"A one-way street. Every lane runs the same way, so watch for the sign before turning into any street you do not know." },
  fr:{ q:"Que vous indique ce panneau ?",
       a:["Toute la circulation de cette rue va dans le sens de la flèche","La route tourne dans cette direction","Tournez ici pour le stationnement","La circulation à double sens commence ici"],
       e:"Une rue à sens unique. Toutes les voies vont dans le même sens : cherchez le panneau avant de tourner dans une rue que vous ne connaissez pas." },
  c:0 },
{ id:"nbs5", sec:"signs", sign:"no-left-turn",
  en:{ q:"What does this sign prohibit?",
       a:["Turning left at this place","Turning right at this place","Going straight through","Stopping at any time"],
       e:"A red circle with a slash always means you must not do the thing shown. Here the thing shown is a left turn." },
  fr:{ q:"Qu'interdit ce panneau ?",
       a:["Tourner à gauche à cet endroit","Tourner à droite à cet endroit","Continuer tout droit","Vous arrêter en tout temps"],
       e:"Un cercle rouge barré signifie toujours que ce qui est illustré est interdit. Ici, il s'agit d'un virage à gauche." },
  c:0 },
{ id:"nbs6", sec:"signs", sign:"no-u-turn",
  en:{ q:"What may you not do where this sign is posted?",
       a:["Turn around to go back the way you came","Park on the left side","Change lanes","Turn right on a red light"],
       e:"No U-turn. Drive on and turn around somewhere it is allowed and you can see well in both directions." },
  fr:{ q:"Que ne pouvez-vous pas faire là où ce panneau est affiché ?",
       a:["Faire demi-tour pour revenir d'où vous venez","Stationner du côté gauche","Changer de voie","Tourner à droite au feu rouge"],
       e:"Demi-tour interdit. Continuez et faites demi-tour là où c'est permis et où vous voyez bien dans les deux sens." },
  c:0 },
{ id:"nbs7", sec:"signs", sign:"no-parking",
  en:{ q:"What does this sign mean?",
       a:["You may not park here, but you may stop briefly to let someone out","You may not stop here for any reason","Parking is free here","Parking for delivery vehicles only"],
       e:"No parking is not the same as no stopping. You may pause to let a passenger in or out, but you may not leave the vehicle parked." },
  fr:{ q:"Que signifie ce panneau ?",
       a:["Vous ne pouvez pas stationner ici, mais vous pouvez arrêter brièvement pour laisser descendre quelqu'un","Vous ne pouvez vous arrêter ici pour aucune raison","Le stationnement est gratuit ici","Stationnement réservé aux véhicules de livraison"],
       e:"Stationnement interdit n'est pas la même chose qu'arrêt interdit. Vous pouvez vous immobiliser pour faire monter ou descendre un passager, mais non laisser le véhicule stationné." },
  c:0 },
{ id:"nbs8", sec:"signs", sign:"no-stopping",
  en:{ q:"How is this sign stricter than a no parking sign?",
       a:["You may not stop at all, even to drop someone off","It only applies at night","It applies to trucks only","It allows fifteen minutes of parking"],
       e:"No stopping means exactly that. Do not stop the vehicle here at all unless traffic or a police officer makes you." },
  fr:{ q:"En quoi ce panneau est-il plus strict qu'un panneau de stationnement interdit ?",
       a:["Vous ne pouvez pas vous arrêter du tout, même pour laisser descendre quelqu'un","Il ne s'applique que la nuit","Il s'applique seulement aux camions","Il permet quinze minutes de stationnement"],
       e:"Arrêt interdit veut dire exactement cela. Ne vous immobilisez pas ici, sauf si la circulation ou un policier vous y oblige." },
  c:0 },
{ id:"nbs9", sec:"signs", sign:"no-passing",
  en:{ q:"What are you being told here?",
       a:["Do not pass another vehicle along this stretch of road","Do not change lanes in town","Passing lane ahead","Trucks may not use this road"],
       e:"No passing. It is posted where you cannot see far enough ahead to overtake safely, such as a hill or a bend." },
  fr:{ q:"Que vous dit-on ici ?",
       a:["Ne dépassez aucun véhicule sur ce tronçon de route","Ne changez pas de voie en ville","Voie de dépassement devant","Les camions ne peuvent pas emprunter cette route"],
       e:"Dépassement interdit. Il est affiché là où vous ne voyez pas assez loin pour dépasser en sécurité, comme une côte ou une courbe." },
  c:0 },
{ id:"nbs10", sec:"signs", sign:"keep-right",
  en:{ q:"What does this sign instruct?",
       a:["Pass to the right of the island or obstacle ahead","Right turn only","Merge right in 100 metres","Right lane closed"],
       e:"Keep right. There is something in the road ahead — an island, a divider or a work area — and you go around it on the right." },
  fr:{ q:"Qu'ordonne ce panneau ?",
       a:["Passer à droite de l'îlot ou de l'obstacle devant","Virage à droite seulement","Insertion à droite dans 100 mètres","Voie de droite fermée"],
       e:"Tenez la droite. Il y a quelque chose sur la route devant — un îlot, un séparateur ou une zone de travaux — et vous le contournez par la droite." },
  c:0 },
{ id:"nbs11", sec:"signs", sign:"ped-crossover",
  en:{ q:"You approach this sign and a person steps onto the crossing. What do you do?",
       a:["Stop and let them cross the whole way before moving off","Drive around behind them","Sound your horn","Speed up to clear the crossing first"],
       e:"The whole point of a marked crossing is that people on foot go first. Wait until they are safely across before you move." },
  fr:{ q:"Vous approchez de ce panneau et une personne s'engage sur le passage. Que faites-vous ?",
       a:["Vous arrêter et la laisser traverser complètement avant de repartir","La contourner par l'arrière","Klaxonner","Accélérer pour franchir le passage avant elle"],
       e:"Tout l'intérêt d'un passage marqué est que les piétons passent en premier. Attendez qu'ils aient traversé en sécurité avant d'avancer." },
  c:0 },
{ id:"nbs12", sec:"signs", sign:"stop-school-bus",
  en:{ q:"A school bus ahead has its red lights flashing. What must you do?",
       a:["Stop and wait until the lights go out and the bus moves off","Pass slowly on the left","Pass on the right","Sound your horn and go by"],
       e:"Flashing red lights on a school bus mean children are getting on or off. Stop, and stay stopped until the lights stop flashing." },
  fr:{ q:"Un autobus scolaire devant vous fait clignoter ses feux rouges. Que devez-vous faire ?",
       a:["Vous arrêter et attendre que les feux s'éteignent et que l'autobus reparte","Dépasser lentement par la gauche","Dépasser par la droite","Klaxonner et passer"],
       e:"Des feux rouges clignotants sur un autobus scolaire signifient que des enfants montent ou descendent. Arrêtez-vous et restez arrêté jusqu'à ce que les feux cessent de clignoter." },
  c:0 },
{ id:"nbs13", sec:"signs", sign:"warn-school-bus",
  en:{ q:"What is this yellow sign warning you about?",
       a:["A school bus stop is ahead","A bus terminal is ahead","School buses are banned here","A bus lane begins"],
       e:"A warning, not an order. Expect a school bus to be stopping ahead, and be ready for its red lights." },
  fr:{ q:"De quoi ce panneau jaune vous avertit-il ?",
       a:["Un arrêt d'autobus scolaire se trouve devant","Un terminus d'autobus se trouve devant","Les autobus scolaires sont interdits ici","Une voie réservée aux autobus commence"],
       e:"Un avertissement, pas un ordre. Attendez-vous à ce qu'un autobus scolaire s'arrête devant, et soyez prêt pour ses feux rouges." },
  c:0 },
{ id:"nbs14", sec:"signs", sign:"warn-moose",
  en:{ q:"You see this sign on a New Brunswick highway at dusk. What should you do?",
       a:["Slow down and scan both shoulders, because a moose may step out","Speed up to pass the area quickly","Turn on your high beams and keep your speed","Nothing, the sign is only for trucks"],
       e:"New Brunswick publishes that more than 400 people here are involved in a moose-vehicle collision every year, and most happen between dusk and dawn. Slowing down is what buys you the time to stop." },
  fr:{ q:"Vous voyez ce panneau sur une route du Nouveau-Brunswick au crépuscule. Que devriez-vous faire ?",
       a:["Ralentir et surveiller les deux accotements, car un orignal peut surgir","Accélérer pour traverser la zone rapidement","Allumer vos feux de route et garder votre vitesse","Rien, ce panneau ne vise que les camions"],
       e:"Le Nouveau-Brunswick publie que plus de 400 personnes y sont impliquées dans une collision avec un orignal chaque année, et la plupart surviennent entre le crépuscule et l'aube. Ralentir est ce qui vous donne le temps de vous arrêter." },
  c:0 },
{ id:"nbs15", sec:"signs", sign:"warn-deer",
  en:{ q:"What does this sign mean?",
       a:["Deer often cross here, so watch the shoulders","A deer farm is ahead","Hunting is permitted here","A wildlife park entrance"],
       e:"Where one animal crosses, another usually follows. If one runs across in front of you, slow down and expect a second." },
  fr:{ q:"Que signifie ce panneau ?",
       a:["Des chevreuils traversent souvent ici, surveillez les accotements","Une ferme d'élevage de cerfs se trouve devant","La chasse est permise ici","Entrée d'un parc animalier"],
       e:"Là où un animal traverse, un autre suit généralement. Si l'un court devant vous, ralentissez et attendez-vous à un deuxième." },
  c:0 },
{ id:"nbs16", sec:"signs", sign:"warn-curve-right",
  en:{ q:"What is ahead when you see this sign?",
       a:["A curve to the right — slow down before you reach it","A right turn you must take","A right lane ending","A rest area on the right"],
       e:"Slow down before the curve, not in it. Braking in the middle of a bend is how a car leaves the road." },
  fr:{ q:"Qu'y a-t-il devant quand vous voyez ce panneau ?",
       a:["Une courbe vers la droite — ralentissez avant d'y arriver","Un virage à droite obligatoire","Une voie de droite qui se termine","Une halte routière à droite"],
       e:"Ralentissez avant la courbe, pas dedans. Freiner au milieu d'un virage est la façon dont une voiture quitte la route." },
  c:0 },
{ id:"nbs17", sec:"signs", sign:"warn-winding",
  en:{ q:"This sign warns of what?",
       a:["A series of curves, one after another","A single sharp turn","A winding river beside the road","A detour"],
       e:"More than one bend ahead. Pick a speed you can hold through all of them rather than braking and accelerating between each." },
  fr:{ q:"Ce panneau avertit de quoi ?",
       a:["Une série de courbes, l'une après l'autre","Un seul virage serré","Une rivière sinueuse le long de la route","Un détour"],
       e:"Plus d'une courbe devant. Choisissez une vitesse que vous pouvez tenir dans toutes plutôt que de freiner et d'accélérer entre chacune." },
  c:0 },
{ id:"nbs18", sec:"signs", sign:"warn-slippery",
  en:{ q:"What does this sign warn about?",
       a:["The road may be slippery, especially when wet","Loose gravel ahead","A car wash ahead","Skidding is prohibited"],
       e:"The surface can lose grip. Slow down, leave more room, and steer and brake gently." },
  fr:{ q:"De quoi ce panneau avertit-il ?",
       a:["La chaussée peut être glissante, surtout quand elle est mouillée","Gravier meuble devant","Un lave-auto devant","Le dérapage est interdit"],
       e:"La surface peut perdre son adhérence. Ralentissez, laissez plus d'espace, et braquez et freinez en douceur." },
  c:0 },
{ id:"nbs19", sec:"signs", sign:"warn-narrow-bridge",
  en:{ q:"What is ahead?",
       a:["A bridge narrower than the road you are on","A bridge that is closed","A weight limit","A ferry crossing"],
       e:"The road pinches in. Check for oncoming traffic before you commit, because there may not be room for two vehicles side by side." },
  fr:{ q:"Qu'y a-t-il devant ?",
       a:["Un pont plus étroit que la route où vous êtes","Un pont fermé","Une limite de poids","Une traverse de traversier"],
       e:"La route se rétrécit. Vérifiez la circulation en sens inverse avant de vous engager, car il n'y a peut-être pas la place pour deux véhicules côte à côte." },
  c:0 },
{ id:"nbs20", sec:"signs", sign:"warn-steep-hill",
  en:{ q:"You see this sign. What is the safest thing to do?",
       a:["Shift to a lower gear and let the engine help slow you","Put the car in neutral to save fuel","Hold the brake down the whole way","Speed up so the hill does not slow you"],
       e:"A lower gear does the braking for you. Riding the brake all the way down heats it until it fades, which is exactly when you need it." },
  fr:{ q:"Vous voyez ce panneau. Quelle est la chose la plus sécuritaire à faire ?",
       a:["Passer à un rapport inférieur et laisser le moteur vous ralentir","Mettre au point mort pour économiser du carburant","Garder le frein enfoncé tout le long","Accélérer pour que la côte ne vous ralentisse pas"],
       e:"Un rapport inférieur freine à votre place. Garder le frein enfoncé jusqu'en bas le chauffe jusqu'à ce qu'il s'affaiblisse, précisément au moment où vous en avez besoin." },
  c:0 },
{ id:"nbs21", sec:"signs", sign:"warn-two-way",
  en:{ q:"What does this sign tell you?",
       a:["Traffic ahead comes both ways — stay right of the centre line","The road is closed ahead","A passing lane begins","Two lanes merge into one"],
       e:"You are leaving a divided road for one where oncoming traffic shares the same surface. Keep right and do not drift." },
  fr:{ q:"Que vous dit ce panneau ?",
       a:["La circulation devant va dans les deux sens — restez à droite de la ligne médiane","La route est fermée devant","Une voie de dépassement commence","Deux voies se fondent en une"],
       e:"Vous quittez une route divisée pour une route où la circulation en sens inverse partage la même chaussée. Tenez la droite et ne déviez pas." },
  c:0 },
{ id:"nbs22", sec:"signs", sign:"warn-merge",
  en:{ q:"Traffic is joining from a ramp ahead. What is the courteous and safe response?",
       a:["Adjust your speed or move over to leave them room","Hold your speed and your lane no matter what","Speed up so they cannot get in","Stop at the end of the merge lane"],
       e:"Merging works when both drivers give a little. Adjusting early is easier and safer than braking hard at the last second." },
  fr:{ q:"De la circulation s'insère depuis une bretelle devant. Quelle est la réaction courtoise et sécuritaire ?",
       a:["Ajuster votre vitesse ou changer de voie pour leur laisser de la place","Garder votre vitesse et votre voie quoi qu'il arrive","Accélérer pour les empêcher d'entrer","Vous arrêter au bout de la voie d'insertion"],
       e:"L'insertion fonctionne quand les deux conducteurs cèdent un peu. Ajuster tôt est plus facile et plus sûr que freiner brusquement à la dernière seconde." },
  c:0 },
{ id:"nbs23", sec:"signs", sign:"warn-signal-ahead",
  en:{ q:"What is this sign preparing you for?",
       a:["A set of traffic lights you may not be able to see yet","A police checkpoint","A level crossing","A flashing beacon only"],
       e:"It is posted where a hill, a bend or trees hide the lights. Cover the brake and be ready to stop." },
  fr:{ q:"À quoi ce panneau vous prépare-t-il ?",
       a:["Des feux de circulation que vous ne voyez peut-être pas encore","Un contrôle policier","Un passage à niveau","Un simple feu clignotant"],
       e:"Il est affiché là où une côte, une courbe ou des arbres cachent les feux. Gardez le pied près du frein et soyez prêt à arrêter." },
  c:0 },
{ id:"nbs24", sec:"signs", sign:"warn-stop-ahead",
  en:{ q:"You see this sign. What should you do?",
       a:["Start slowing now, because a stop sign is coming that you cannot see yet","Stop right where the sign is","Stop only if traffic is coming","Nothing, it is for trucks"],
       e:"It gives you the warning a hidden stop sign cannot. By the time you can see the stop sign, you should already be slow." },
  fr:{ q:"Vous voyez ce panneau. Que devriez-vous faire ?",
       a:["Commencer à ralentir maintenant, car un arrêt que vous ne voyez pas encore approche","Vous arrêter à la hauteur du panneau","Vous arrêter seulement si de la circulation arrive","Rien, il est destiné aux camions"],
       e:"Il vous donne l'avertissement qu'un arrêt caché ne peut pas donner. Quand vous verrez le panneau d'arrêt, vous devriez déjà rouler lentement." },
  c:0 },
{ id:"nbs25", sec:"signs", sign:"warn-pedestrian",
  en:{ q:"What should this sign make you do?",
       a:["Watch for people walking and be ready to stop","Sound your horn to warn them","Move to the left lane and keep your speed","Nothing unless it is a school day"],
       e:"People on foot have no bumper. Cover the brake, look well ahead, and expect somebody to step out." },
  fr:{ q:"Que devrait vous faire faire ce panneau ?",
       a:["Surveiller les piétons et être prêt à vous arrêter","Klaxonner pour les avertir","Passer dans la voie de gauche et garder votre vitesse","Rien, sauf un jour d'école"],
       e:"Un piéton n'a pas de pare-chocs. Gardez le pied près du frein, regardez loin devant et attendez-vous à ce que quelqu'un s'engage." },
  c:0 },
{ id:"nbs26", sec:"signs", sign:"warn-school-zone",
  en:{ q:"What does this sign mark?",
       a:["A school zone, where children may be crossing","A library","A bus depot","A playground with no road access"],
       e:"Children do not judge speed and distance the way adults do. Slow right down and watch both sides of the road." },
  fr:{ q:"Que signale ce panneau ?",
       a:["Une zone scolaire, où des enfants peuvent traverser","Une bibliothèque","Un dépôt d'autobus","Un terrain de jeu sans accès routier"],
       e:"Les enfants n'évaluent pas la vitesse et la distance comme les adultes. Ralentissez beaucoup et surveillez les deux côtés de la route." },
  c:0 },
{ id:"nbs27", sec:"signs", sign:"warn-playground",
  en:{ q:"What does this sign warn about?",
       a:["Children may run into the road from a play area","A parking lot entrance","A sports stadium ahead","A picnic area"],
       e:"A ball rolling into the road is usually followed by a child. Slow down and be ready." },
  fr:{ q:"De quoi ce panneau avertit-il ?",
       a:["Des enfants peuvent surgir sur la route depuis une aire de jeu","Une entrée de stationnement","Un stade sportif devant","Une aire de pique-nique"],
       e:"Un ballon qui roule sur la route est généralement suivi d'un enfant. Ralentissez et soyez prêt." },
  c:0 },
{ id:"nbs28", sec:"signs", sign:"warn-railway",
  en:{ q:"What is ahead when you see this round yellow sign?",
       a:["A railway crossing","A roundabout","A tunnel","A bridge under repair"],
       e:"A train needs a long way to stop and cannot steer around you. Slow, look both ways, and listen with the window down if your view is poor." },
  fr:{ q:"Qu'y a-t-il devant quand vous voyez ce panneau jaune rond ?",
       a:["Un passage à niveau","Un carrefour giratoire","Un tunnel","Un pont en réparation"],
       e:"Un train met très longtemps à s'arrêter et ne peut pas vous contourner. Ralentissez, regardez des deux côtés et écoutez, la vitre baissée, si votre visibilité est mauvaise." },
  c:0 },
{ id:"nbs29", sec:"signs", sign:"warn-crossbuck",
  en:{ q:"You are stopped at this sign and a train has just passed. What do you do?",
       a:["Check that a second train is not coming on another track before you cross","Cross immediately","Reverse away from the tracks","Wait exactly two minutes"],
       e:"One train can hide another going the other way on a second track. Look again both ways before you move." },
  fr:{ q:"Vous êtes arrêté à ce panneau et un train vient de passer. Que faites-vous ?",
       a:["Vérifier qu'un deuxième train n'arrive pas sur une autre voie avant de traverser","Traverser immédiatement","Reculer loin des rails","Attendre exactement deux minutes"],
       e:"Un train peut en cacher un autre venant en sens inverse sur une deuxième voie. Regardez de nouveau des deux côtés avant d'avancer." },
  c:0 },
{ id:"nbs30", sec:"signs", sign:"warn-roundabout",
  en:{ q:"What is ahead, and who has the right of way there?",
       a:["A roundabout — traffic already going round it goes first","A roundabout — you go first","A detour — follow the arrows","A dead end — turn back"],
       e:"Yield to the traffic already circulating, enter when there is a gap, and signal before you leave." },
  fr:{ q:"Qu'y a-t-il devant, et qui a la priorité ?",
       a:["Un carrefour giratoire — la circulation qui y tourne déjà passe en premier","Un carrefour giratoire — vous passez en premier","Un détour — suivez les flèches","Un cul-de-sac — faites demi-tour"],
       e:"Cédez le passage à la circulation qui tourne déjà, engagez-vous dans un intervalle, et signalez avant de sortir." },
  c:0 },
{ id:"nbs31", sec:"signs", sign:"temp-construction",
  en:{ q:"An orange diamond sign appears. What does the colour tell you?",
       a:["Road work is ahead","A permanent hazard is ahead","A tourist attraction is ahead","A parking area is ahead"],
       e:"Orange means temporary road work. Expect workers, equipment, changed lanes and a lower posted limit." },
  fr:{ q:"Un panneau losange orange apparaît. Que vous dit la couleur ?",
       a:["Des travaux routiers se trouvent devant","Un danger permanent se trouve devant","Une attraction touristique se trouve devant","Une aire de stationnement se trouve devant"],
       e:"L'orange signale des travaux temporaires. Attendez-vous à des travailleurs, de l'équipement, des voies modifiées et une limite affichée plus basse." },
  c:0 },
{ id:"nbs32", sec:"signs", sign:"temp-flagger",
  en:{ q:"This sign is posted before a work zone. What does it mean?",
       a:["A person will be directing traffic ahead — obey their signals","The road is closed","A speed camera is ahead","A survey crew is measuring"],
       e:"A flagperson's directions come before signs and lights. Slow right down and watch for the signal paddle." },
  fr:{ q:"Ce panneau est affiché avant une zone de travaux. Que signifie-t-il ?",
       a:["Une personne dirigera la circulation devant — obéissez à ses signaux","La route est fermée","Un radar photo se trouve devant","Une équipe d'arpentage prend des mesures"],
       e:"Les directives d'un signaleur priment sur les panneaux et les feux. Ralentissez beaucoup et surveillez la palette de signalisation." },
  c:0 },
{ id:"nbs33", sec:"signs", sign:"light-flashing-red",
  en:{ q:"A traffic light is flashing red. What must you do?",
       a:["Treat it exactly like a stop sign","Treat it like a yield sign","Drive through without slowing","Wait for it to turn green"],
       e:"A flashing red is a stop sign made of light. Come to a full stop, then go when the way is clear." },
  fr:{ q:"Un feu de circulation clignote en rouge. Que devez-vous faire ?",
       a:["Le traiter exactement comme un panneau d'arrêt","Le traiter comme un panneau de cession de passage","Passer sans ralentir","Attendre qu'il passe au vert"],
       e:"Un feu rouge clignotant est un panneau d'arrêt fait de lumière. Faites un arrêt complet, puis avancez quand la voie est libre." },
  c:0 },
{ id:"nbs34", sec:"signs", sign:"mark-solid-yellow",
  en:{ q:"There is a solid yellow line on your side of the centre. What does it mean?",
       a:["Do not cross it to pass","Passing is allowed if you are quick","It marks the edge of the road","It marks a bicycle lane"],
       e:"A solid line on your side means no passing. It is painted where you cannot see far enough ahead to overtake safely." },
  fr:{ q:"Il y a une ligne jaune continue de votre côté du centre. Que signifie-t-elle ?",
       a:["Ne la franchissez pas pour dépasser","Le dépassement est permis si vous êtes rapide","Elle marque le bord de la chaussée","Elle marque une voie cyclable"],
       e:"Une ligne continue de votre côté signifie qu'il est interdit de dépasser. Elle est tracée là où vous ne voyez pas assez loin pour dépasser en sécurité." },
  c:0 }
);

/* ---------- rules of the road ---------- */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"nbr1", sec:"rules", topic:"licensing",
  en:{ q:"What is the beginner licence called in New Brunswick?",
       a:["Class 7 Level 1","Class G1","Class 5 Learner","Class L1"],
       e:"New Brunswick uses Class 7 Level 1, marked with an L on the front of the card. It is not called G1 — that is another province." },
  fr:{ q:"Comment s'appelle le permis débutant au Nouveau-Brunswick ?",
       a:["Classe 7 niveau 1","Classe G1","Classe 5 apprenti","Classe L1"],
       e:"Le Nouveau-Brunswick utilise la classe 7 niveau 1, indiquée par un L à l'avant de la carte. On ne l'appelle pas G1 : c'est une autre province." },
  c:0 },
{ id:"nbr2", sec:"rules", topic:"licensing",
  en:{ q:"What is the minimum age to get a Class 7 Level 1 licence?",
       a:["16","14","18","21"],
       e:"Sixteen. If you are under 18 a parent or guardian must consent, and that consent has to be witnessed by somebody who is not a relative." },
  fr:{ q:"Quel est l'âge minimal pour obtenir un permis de classe 7 niveau 1 ?",
       a:["16 ans","14 ans","18 ans","21 ans"],
       e:"Seize ans. Si vous avez moins de 18 ans, un parent ou tuteur doit consentir, et ce consentement doit être attesté par une personne qui n'est pas un membre de la famille." },
  c:0 },
{ id:"nbr3", sec:"rules", topic:"licensing",
  en:{ q:"How long must you normally hold Level 1 before moving to Level 2?",
       a:["12 months, or 8 months with a recognized driving school","3 months, always","24 months, always","There is no minimum"],
       e:"Twelve months, reduced to eight if you graduate from a recognized licensed driving school. That four-month saving is the main reason people take the course." },
  fr:{ q:"Combien de temps devez-vous normalement détenir le niveau 1 avant de passer au niveau 2 ?",
       a:["12 mois, ou 8 mois avec une école de conduite reconnue","3 mois, toujours","24 mois, toujours","Il n'y a pas de minimum"],
       e:"Douze mois, réduits à huit si vous êtes diplômé d'une école de conduite reconnue. Cette économie de quatre mois est la principale raison de suivre le cours." },
  c:0 },
{ id:"nbr4", sec:"rules", topic:"licensing",
  en:{ q:"How long does the whole graduated programme take, at a minimum?",
       a:["24 months","6 months","12 months","5 years"],
       e:"At least 24 months in total: a minimum of 12 months at Level 1 and 12 more at Level 2. New Brunswick's programme is based on experience, not on your age." },
  fr:{ q:"Combien de temps dure au minimum tout le programme progressif ?",
       a:["24 mois","6 mois","12 mois","5 ans"],
       e:"Au moins 24 mois au total : un minimum de 12 mois au niveau 1 et 12 autres au niveau 2. Le programme du Nouveau-Brunswick est fondé sur l'expérience, pas sur votre âge." },
  c:0 },
{ id:"nbr5", sec:"rules", topic:"licensing",
  en:{ q:"Who may sit beside a Level 1 driver?",
       a:["Someone with a Class 5 or better licence and at least 3 years of driving experience","Anybody over 16 with a licence","Any adult, licensed or not","Another Level 1 driver"],
       e:"Class 5 or better, and at least three years of experience. They must sit in the front passenger seat, where they can see what you see." },
  fr:{ q:"Qui peut s'asseoir à côté d'un conducteur de niveau 1 ?",
       a:["Une personne détenant un permis de classe 5 ou mieux et au moins 3 ans d'expérience","N'importe qui de plus de 16 ans avec un permis","N'importe quel adulte, avec ou sans permis","Un autre conducteur de niveau 1"],
       e:"Classe 5 ou mieux, et au moins trois ans d'expérience. Cette personne doit s'asseoir à la place du passager avant, d'où elle voit ce que vous voyez." },
  c:0 },
{ id:"nbr6", sec:"rules", topic:"licensing",
  en:{ q:"Where must the supervising driver sit?",
       a:["In the front passenger seat","Anywhere in the vehicle","In the back seat","In a following vehicle"],
       e:"The front passenger seat. From there they can see the road, the mirrors and the instruments, and reach the wheel if they truly must." },
  fr:{ q:"Où doit s'asseoir le conducteur accompagnateur ?",
       a:["À la place du passager avant","N'importe où dans le véhicule","Sur la banquette arrière","Dans un véhicule qui suit"],
       e:"À la place du passager avant. De là, il voit la route, les rétroviseurs et les cadrans, et peut atteindre le volant s'il le faut vraiment." },
  c:0 },
{ id:"nbr7", sec:"rules", topic:"licensing",
  en:{ q:"May a Level 1 driver carry friends in the car?",
       a:["No — nobody may travel with them except the supervising driver","Yes, up to three","Yes, if they all wear seatbelts","Yes, during daylight only"],
       e:"No. A Level 1 driver cannot drive alone and cannot carry any passenger other than the supervising driver. Level 2 is where passengers are allowed." },
  fr:{ q:"Un conducteur de niveau 1 peut-il transporter des amis ?",
       a:["Non — personne ne peut l'accompagner sauf le conducteur accompagnateur","Oui, jusqu'à trois","Oui, s'ils portent tous la ceinture","Oui, de jour seulement"],
       e:"Non. Un conducteur de niveau 1 ne peut pas conduire seul ni transporter de passager autre que le conducteur accompagnateur. C'est au niveau 2 que les passagers sont permis." },
  c:0 },
{ id:"nbr8", sec:"rules", topic:"licensing",
  en:{ q:"Between which hours may a Level 1 driver not drive?",
       a:["Midnight and 5 a.m.","10 p.m. and 6 a.m.","9 p.m. and 7 a.m.","There is no time restriction"],
       e:"Midnight to 5 a.m. Those are the hours when tiredness, poor light and impaired drivers all peak at once." },
  fr:{ q:"Entre quelles heures un conducteur de niveau 1 ne peut-il pas conduire ?",
       a:["Minuit et 5 h","22 h et 6 h","21 h et 7 h","Il n'y a aucune restriction horaire"],
       e:"De minuit à 5 h. Ce sont les heures où la fatigue, le manque de lumière et les conducteurs facultés affaiblies culminent en même temps." },
  c:0 },
{ id:"nbr9", sec:"rules", topic:"licensing",
  en:{ q:"How much alcohol may be in a Level 1 driver's blood?",
       a:["None at all","The same as any adult driver","A small amount with a meal","Any amount below the legal adult limit"],
       e:"Zero. New Brunswick has zero tolerance for drugs and alcohol in the graduated programme, and breaking it brings a one-year suspension." },
  fr:{ q:"Quelle quantité d'alcool peut se trouver dans le sang d'un conducteur de niveau 1 ?",
       a:["Aucune","La même que pour tout conducteur adulte","Une petite quantité avec un repas","Toute quantité sous la limite légale des adultes"],
       e:"Zéro. Le Nouveau-Brunswick applique la tolérance zéro pour les drogues et l'alcool dans le programme progressif, et une infraction entraîne une suspension d'un an." },
  c:0 },
{ id:"nbr10", sec:"rules", topic:"licensing",
  en:{ q:"How many passengers may a Level 2 driver carry?",
       a:["Up to three, with only one in the front seat","As many as there are seatbelts","None","Only family members"],
       e:"Up to three passengers, and only one of them in the front seat. That is a Level 2 rule; at Level 1 nobody but the supervising driver may ride with you." },
  fr:{ q:"Combien de passagers un conducteur de niveau 2 peut-il transporter ?",
       a:["Jusqu'à trois, avec un seul à l'avant","Autant qu'il y a de ceintures","Aucun","Seulement des membres de sa famille"],
       e:"Jusqu'à trois passagers, dont un seul à l'avant. C'est une règle du niveau 2 ; au niveau 1, personne d'autre que le conducteur accompagnateur ne peut vous accompagner." },
  c:0 },
{ id:"nbr11", sec:"rules", topic:"licence",
  en:{ q:"Which two written exams must a new car driver pass in New Brunswick?",
       a:["A road sign recognition exam and a rules of the road exam","One combined exam only","A rules exam and a first-aid exam","A sign exam and a mechanical exam"],
       e:"Two separate exams: the Road Sign Recognition Exam and the Rules of the Road Non-Commercial Knowledge Exam. That is why this site keeps signs and rules as two study pages." },
  fr:{ q:"Quels deux examens écrits un nouveau conducteur automobile doit-il réussir au Nouveau-Brunswick ?",
       a:["Un examen de reconnaissance des panneaux et un examen sur le code de la route","Un seul examen combiné","Un examen sur le code et un examen de secourisme","Un examen sur les panneaux et un examen mécanique"],
       e:"Deux examens distincts : l'examen de reconnaissance des panneaux et l'examen théorique non commercial sur le code de la route. C'est pourquoi ce site garde les panneaux et le code sur deux pages d'étude." },
  c:0 },
{ id:"nbr12", sec:"rules", topic:"licence",
  en:{ q:"How long are your written test results valid?",
       a:["Six months","One month","Two years","For life"],
       e:"Six months. If you leave it longer than that before finishing the rest of the process, you have to sit the exams again." },
  fr:{ q:"Combien de temps vos résultats d'examens écrits sont-ils valides ?",
       a:["Six mois","Un mois","Deux ans","À vie"],
       e:"Six mois. Si vous attendez plus longtemps avant de terminer le reste des démarches, vous devez repasser les examens." },
  c:0 },
{ id:"nbr13", sec:"rules", topic:"licence",
  en:{ q:"New Brunswick was the first province in Canada to do what with its written driver's test?",
       a:["Offer it online, taken at home with a webcam","Make it free","Remove it entirely","Offer it only by telephone"],
       e:"New Brunswick was first in Canada to put the written test online, in 2020. It is taken on a desktop or laptop with a camera, and a proctoring system takes random snapshots." },
  fr:{ q:"Le Nouveau-Brunswick a été la première province canadienne à faire quoi avec son examen écrit ?",
       a:["L'offrir en ligne, passé à la maison avec une caméra","Le rendre gratuit","L'abolir complètement","L'offrir seulement par téléphone"],
       e:"Le Nouveau-Brunswick a été le premier au Canada à mettre l'examen écrit en ligne, en 2020. Il se passe sur un ordinateur de bureau ou portable muni d'une caméra, et un système de surveillance prend des photos au hasard." },
  c:0 },
{ id:"nbr14", sec:"rules", topic:"licence",
  en:{ q:"You want to sit the written test online. What do you need?",
       a:["A desktop or laptop with a working camera","A smartphone","A tablet with no camera","Nothing but an internet connection"],
       e:"A desktop or a laptop with a camera. During the test you cannot use a phone, wear earbuds, leave your seat or look anything up." },
  fr:{ q:"Vous voulez passer l'examen écrit en ligne. De quoi avez-vous besoin ?",
       a:["D'un ordinateur de bureau ou portable avec une caméra fonctionnelle","D'un téléphone intelligent","D'une tablette sans caméra","De rien d'autre qu'une connexion Internet"],
       e:"D'un ordinateur de bureau ou portable avec une caméra. Pendant l'examen, vous ne pouvez pas utiliser de téléphone, porter des écouteurs, quitter votre siège ni consulter quoi que ce soit." },
  c:0 },
{ id:"nbr15", sec:"rules", topic:"licence",
  en:{ q:"In which languages can you take the New Brunswick written test?",
       a:["Both English and French","English only","French only","English, with an interpreter for French"],
       e:"Both. New Brunswick is Canada's only officially bilingual province, and testing is available in both official languages." },
  fr:{ q:"Dans quelles langues pouvez-vous passer l'examen écrit du Nouveau-Brunswick ?",
       a:["En anglais et en français","En anglais seulement","En français seulement","En anglais, avec un interprète pour le français"],
       e:"Les deux. Le Nouveau-Brunswick est la seule province officiellement bilingue du Canada, et les examens sont offerts dans les deux langues officielles." },
  c:0 },
{ id:"nbr16", sec:"rules", topic:"licence",
  en:{ q:"After you pass the written exams, what happens before you get the licence?",
       a:["You wait at least four business days, then do a vision test at an SNB centre","The licence is mailed the same day","You take the road test immediately","Nothing else is required"],
       e:"New Brunswick asks you to wait a minimum of four business days after passing, then go to a Service New Brunswick office for the vision screening. It catches a lot of people out." },
  fr:{ q:"Après avoir réussi les examens écrits, que se passe-t-il avant d'obtenir le permis ?",
       a:["Vous attendez au moins quatre jours ouvrables, puis passez un examen de la vue dans un centre SNB","Le permis est posté le jour même","Vous passez l'examen pratique immédiatement","Rien d'autre n'est exigé"],
       e:"Le Nouveau-Brunswick demande d'attendre au minimum quatre jours ouvrables après la réussite, puis de se rendre dans un bureau de Services Nouveau-Brunswick pour l'examen de la vue. Beaucoup de gens l'ignorent." },
  c:0 },
{ id:"nbr17", sec:"rules", topic:"licence",
  en:{ q:"What eyesight standard must you meet?",
       a:["20/40 in your better eye","20/20 in both eyes","20/100 in one eye","There is no vision requirement"],
       e:"20/40 in the best eye. Glasses or contact lenses count, and if you need them to reach that standard, the licence says so." },
  fr:{ q:"Quelle norme de vision devez-vous atteindre ?",
       a:["20/40 du meilleur œil","20/20 des deux yeux","20/100 d'un œil","Il n'y a aucune exigence de vision"],
       e:"20/40 du meilleur œil. Les lunettes ou les lentilles comptent, et si vous en avez besoin pour atteindre cette norme, le permis l'indique." },
  c:0 },
{ id:"nbr18", sec:"rules", topic:"licence",
  en:{ q:"Going from Level 2 to a full Class 5 licence in New Brunswick requires what?",
       a:["Applying for it after the required time — the province states no further road test is needed","A second road test","A written test","An eye test only"],
       e:"New Brunswick states that no further road test is required for the Class 5 upgrade, but you must apply. Not applying can bring sanctions, so do not simply let it sit." },
  fr:{ q:"Passer du niveau 2 au permis complet de classe 5 au Nouveau-Brunswick exige quoi ?",
       a:["En faire la demande après le délai requis — la province indique qu'aucun autre examen pratique n'est exigé","Un deuxième examen pratique","Un examen écrit","Un examen de la vue seulement"],
       e:"Le Nouveau-Brunswick indique qu'aucun autre examen pratique n'est exigé pour l'obtention de la classe 5, mais vous devez en faire la demande. Ne pas le faire peut entraîner des sanctions ; ne laissez donc pas traîner." },
  c:0 },
{ id:"nbr19", sec:"rules", topic:"sharing",
  en:{ q:"A school bus ahead is showing amber lights. What does that mean?",
       a:["It is about to stop — be ready for the red lights","It has broken down","You must stop immediately","It is turning left"],
       e:"Amber is the warning. Red is the order. When the reds come on, everyone stops." },
  fr:{ q:"Un autobus scolaire devant vous montre des feux ambres. Que cela signifie-t-il ?",
       a:["Il est sur le point de s'arrêter — soyez prêt pour les feux rouges","Il est en panne","Vous devez vous arrêter immédiatement","Il tourne à gauche"],
       e:"L'ambre est l'avertissement. Le rouge est l'ordre. Quand les feux rouges s'allument, tout le monde s'arrête." },
  c:0 },
{ id:"nbr20", sec:"rules", topic:"sharing",
  en:{ q:"You are following a cyclist on a narrow road. What is the safe thing to do?",
       a:["Stay back until there is room to pass with plenty of space","Pass close so you clear the lane quickly","Sound your horn to move them over","Drive alongside them"],
       e:"A bicycle can wobble, hit a pothole or swerve around a grate. Wait for room, then give them a wide berth." },
  fr:{ q:"Vous suivez un cycliste sur une route étroite. Quelle est la chose sécuritaire à faire ?",
       a:["Rester derrière jusqu'à ce qu'il y ait de la place pour dépasser largement","Dépasser de près pour libérer la voie rapidement","Klaxonner pour le faire tasser","Rouler à sa hauteur"],
       e:"Un vélo peut vaciller, heurter un nid-de-poule ou éviter une grille. Attendez d'avoir la place, puis laissez-lui une bonne marge." },
  c:0 },
{ id:"nbr21", sec:"rules", topic:"sharing",
  en:{ q:"An emergency vehicle behind you has its lights and siren on. What do you do?",
       a:["Pull over to the right when it is safe and stop until it passes","Speed up to get out of the way","Stop where you are immediately","Move left and slow down"],
       e:"Signal, move right, and stop clear of the lane. Stopping in the middle of the road or braking suddenly makes it harder, not easier." },
  fr:{ q:"Un véhicule d'urgence derrière vous a ses gyrophares et sa sirène en marche. Que faites-vous ?",
       a:["Vous ranger à droite quand c'est sécuritaire et arrêter jusqu'à son passage","Accélérer pour vous écarter","Vous arrêter sur place immédiatement","Vous déplacer à gauche et ralentir"],
       e:"Signalez, tassez-vous à droite et arrêtez hors de la voie. S'arrêter au milieu de la route ou freiner brusquement complique les choses au lieu de les simplifier." },
  c:0 },
{ id:"nbr22", sec:"rules", topic:"sharing",
  en:{ q:"Why are large trucks harder to share the road with?",
       a:["They have big blind spots and need much longer to stop","They are always speeding","They cannot use their mirrors","They are not allowed to brake"],
       e:"If you cannot see the driver's face in their mirror, they cannot see you. Never sit alongside a truck, and never cut in front of one." },
  fr:{ q:"Pourquoi est-il plus difficile de partager la route avec les gros camions ?",
       a:["Ils ont de grands angles morts et mettent beaucoup plus de temps à s'arrêter","Ils roulent toujours trop vite","Ils ne peuvent pas utiliser leurs rétroviseurs","Ils n'ont pas le droit de freiner"],
       e:"Si vous ne voyez pas le visage du conducteur dans son rétroviseur, il ne vous voit pas. Ne restez jamais à côté d'un camion et ne lui coupez jamais la route." },
  c:0 },
{ id:"nbr23", sec:"rules", topic:"conditions",
  en:{ q:"In New Brunswick, when do most moose-vehicle collisions happen?",
       a:["Between dusk and dawn","At midday","Only in winter","Only during a snowstorm"],
       e:"The province publishes that most happen between dusk and dawn, and that the majority fall between May and October. A moose is dark and its eyes do not reflect your headlights the way a deer's do." },
  fr:{ q:"Au Nouveau-Brunswick, quand surviennent la plupart des collisions avec un orignal ?",
       a:["Entre le crépuscule et l'aube","À midi","Seulement en hiver","Seulement pendant une tempête de neige"],
       e:"La province publie que la plupart surviennent entre le crépuscule et l'aube, et que la majorité se produit de mai à octobre. Un orignal est sombre et ses yeux ne réfléchissent pas vos phares comme ceux d'un chevreuil." },
  c:0 },
{ id:"nbr24", sec:"rules", topic:"conditions",
  en:{ q:"Why is hitting a moose more dangerous than hitting a smaller animal?",
       a:["It can weigh up to 450 kg and its long legs put the body into the windshield","It is more likely to run away","It always steps aside at the last moment","It weighs less than a deer"],
       e:"New Brunswick publishes that a moose can weigh up to 450 kg. Because the legs are long, a car goes under the body and the body comes through the glass." },
  fr:{ q:"Pourquoi heurter un orignal est-il plus dangereux que heurter un plus petit animal ?",
       a:["Il peut peser jusqu'à 450 kg et ses longues pattes projettent le corps dans le pare-brise","Il est plus susceptible de s'enfuir","Il s'écarte toujours à la dernière seconde","Il pèse moins qu'un chevreuil"],
       e:"Le Nouveau-Brunswick publie qu'un orignal peut peser jusqu'à 450 kg. Comme ses pattes sont longues, la voiture passe sous le corps et le corps traverse la vitre." },
  c:0 },
{ id:"nbr25", sec:"rules", topic:"conditions",
  en:{ q:"An animal runs across the road in front of you. What is the safest response?",
       a:["Brake firmly in a straight line rather than swerving","Swerve hard around it","Accelerate past it","Close your eyes and brake"],
       e:"Swerving is how a survivable collision becomes a rollover or a head-on. Brake hard, stay in your lane, and keep looking where you want to go." },
  fr:{ q:"Un animal traverse la route devant vous. Quelle est la réaction la plus sécuritaire ?",
       a:["Freiner fermement en ligne droite plutôt que de faire un écart","Faire un écart brusque pour l'éviter","Accélérer pour le dépasser","Fermer les yeux et freiner"],
       e:"L'écart transforme une collision survivable en tonneau ou en choc frontal. Freinez fort, restez dans votre voie et gardez les yeux là où vous voulez aller." },
  c:0 },
{ id:"nbr26", sec:"rules", topic:"conditions",
  en:{ q:"Fog has closed in. What should you use?",
       a:["Low beams","High beams","Hazard lights while moving","No lights at all"],
       e:"High beams bounce off fog and blind you. Low beams throw the light under it. Slow down and increase your following distance." },
  fr:{ q:"Le brouillard s'est installé. Que devriez-vous utiliser ?",
       a:["Les feux de croisement","Les feux de route","Les feux de détresse en roulant","Aucun feu"],
       e:"Les feux de route se réfléchissent sur le brouillard et vous aveuglent. Les feux de croisement éclairent en dessous. Ralentissez et augmentez votre distance de suivi." },
  c:0 },
{ id:"nbr27", sec:"rules", topic:"safe",
  en:{ q:"What is the safest way to deal with a text message while driving?",
       a:["Do not read or send it until you have parked","Read it at a red light","Reply using one hand","Dictate it while driving"],
       e:"Anything that takes your eyes off the road takes them off it for longer than you think. A car covers a great deal of ground in the seconds you are looking down." },
  fr:{ q:"Quelle est la façon la plus sécuritaire de gérer un message texte au volant ?",
       a:["Ne pas le lire ni y répondre avant d'être stationné","Le lire à un feu rouge","Répondre d'une seule main","Le dicter en conduisant"],
       e:"Tout ce qui détourne vos yeux de la route les en détourne plus longtemps que vous ne le croyez. Une voiture parcourt beaucoup de chemin pendant que vous regardez ailleurs." },
  c:0 },
{ id:"nbr28", sec:"rules", topic:"safe",
  en:{ q:"You are getting drowsy on a long drive. What actually works?",
       a:["Stop somewhere safe and rest","Open the window and turn up the radio","Drink coffee and keep going","Drive faster to arrive sooner"],
       e:"Nothing but sleep fixes sleepiness. Cold air and loud music postpone it by a few minutes, which is not long enough to matter." },
  fr:{ q:"Vous avez sommeil lors d'un long trajet. Qu'est-ce qui fonctionne vraiment ?",
       a:["Vous arrêter dans un endroit sécuritaire et vous reposer","Ouvrir la fenêtre et monter la radio","Boire du café et continuer","Rouler plus vite pour arriver plus tôt"],
       e:"Rien d'autre que le sommeil ne corrige la somnolence. L'air froid et la musique forte ne la repoussent que de quelques minutes, ce qui est trop court pour compter." },
  c:0 },
{ id:"nbr29", sec:"rules", topic:"safe",
  en:{ q:"What is the point of checking your mirrors every few seconds?",
       a:["So you already know what is around you before you need to act","To check your appearance","It is only needed before turning","To watch for police"],
       e:"A driver who knows what is beside and behind them can react at once. A driver who has to look first has already lost the time they needed." },
  fr:{ q:"À quoi sert de vérifier vos rétroviseurs toutes les quelques secondes ?",
       a:["À savoir déjà ce qui vous entoure avant d'avoir à réagir","À vérifier votre apparence","Ce n'est nécessaire qu'avant de tourner","À surveiller la police"],
       e:"Un conducteur qui sait ce qui se trouve à côté et derrière lui peut réagir tout de suite. Celui qui doit d'abord regarder a déjà perdu le temps qu'il lui fallait." },
  c:0 },
{ id:"nbr30", sec:"rules", topic:"vehicle",
  en:{ q:"Your windshield washer bottle is empty in winter. Why does it matter?",
       a:["Salt spray blinds the windshield and you cannot clear it","The engine will overheat","The wipers will not turn on","It does not matter"],
       e:"One truck passing on a slushy road can coat the glass in seconds. With no washer fluid there is nothing you can do but pull over." },
  fr:{ q:"Votre réservoir de lave-glace est vide en hiver. Pourquoi est-ce important ?",
       a:["Les projections salines aveuglent le pare-brise et vous ne pouvez pas le nettoyer","Le moteur va surchauffer","Les essuie-glaces ne fonctionneront pas","Cela n'a pas d'importance"],
       e:"Un seul camion qui vous croise sur une route enneigée peut couvrir la vitre en quelques secondes. Sans lave-glace, il ne vous reste qu'à vous ranger." },
  c:0 },
{ id:"nbr31", sec:"rules", topic:"vehicle",
  en:{ q:"Why check tire pressure regularly?",
       a:["Under-inflated tires grip and stop worse and wear out faster","It makes the car quieter","It improves the radio reception","Only new drivers need to"],
       e:"Tires are the only part of the car touching the road. A soft tire changes how the car steers and how far it takes to stop." },
  fr:{ q:"Pourquoi vérifier régulièrement la pression des pneus ?",
       a:["Des pneus sous-gonflés adhèrent et freinent moins bien et s'usent plus vite","Cela rend la voiture plus silencieuse","Cela améliore la réception radio","Seuls les nouveaux conducteurs doivent le faire"],
       e:"Les pneus sont la seule partie de la voiture qui touche la route. Un pneu mou change la direction et la distance de freinage." },
  c:0 },
{ id:"nbr32", sec:"rules", topic:"collisions",
  en:{ q:"You are in a collision with injuries. What is the first thing to do?",
       a:["Make sure the scene is safe and call for help","Move all vehicles immediately","Take photographs first","Drive to the nearest garage"],
       e:"Safety first, then help. Turn on your hazard lights, do not stand in traffic, and call emergency services before anything else." },
  fr:{ q:"Vous êtes impliqué dans une collision avec des blessés. Quelle est la première chose à faire ?",
       a:["Vous assurer que les lieux sont sécuritaires et appeler à l'aide","Déplacer immédiatement tous les véhicules","Prendre des photos d'abord","Vous rendre au garage le plus proche"],
       e:"La sécurité d'abord, puis les secours. Allumez vos feux de détresse, ne restez pas dans la circulation, et appelez les services d'urgence avant tout." },
  c:0 },
{ id:"nbr33", sec:"rules", topic:"collisions",
  en:{ q:"Your vehicle breaks down on a highway shoulder at night. What is safest?",
       a:["Stay belted inside with the hazard lights on and call for help","Stand behind the car to warn traffic","Walk along the lane to the next exit","Sit on the guardrail facing away from traffic"],
       e:"Standing near fast-moving traffic in the dark is far more dangerous than the breakdown. Stay inside, belted, with the hazards on." },
  fr:{ q:"Votre véhicule tombe en panne sur l'accotement d'une route la nuit. Qu'est-ce qui est le plus sécuritaire ?",
       a:["Rester à l'intérieur, ceinture bouclée, feux de détresse allumés, et appeler à l'aide","Vous tenir derrière la voiture pour avertir la circulation","Marcher dans la voie jusqu'à la prochaine sortie","Vous asseoir sur la glissière, dos à la circulation"],
       e:"Se tenir près d'une circulation rapide dans le noir est bien plus dangereux que la panne elle-même. Restez à l'intérieur, ceinture bouclée, feux de détresse allumés." },
  c:0 }
);


/* ---------------------------------------------------------------------------
   OUR standard, not New Brunswick's. The province publishes two written exams
   and 30 minutes for the online version, and that is all: no question count
   and no pass mark appear on any government page. So the two sections below
   mirror the province's two real exams, and the numbers on them are ours — a
   sensible study target, stated as ours on every page that shows them.
   --------------------------------------------------------------------------- */
window.CQ_PROVINCE = {
  code: "NB",
  name: { en: "New Brunswick", fr: "Nouveau-Brunswick" },
  licence: "Class 7 Level 1",
  minutes: 30,
  sections: [
    { id: "signs", ask: 20, pass: 16,
      name: { en: "Road Sign Recognition Exam",
              fr: "Examen de reconnaissance des panneaux" } },
    { id: "rules", ask: 20, pass: 16,
      name: { en: "Rules of the Road Knowledge Exam",
              fr: "Examen th\u00e9orique sur le code de la route" } }
  ],
  handbook: { en: "New Brunswick Driver's Handbook",
              fr: "Manuel du conducteur pour le Nouveau-Brunswick" },
  handbookUrl: "https://www.gnb.ca/en/topic/driving-transportation/driving-licensing/driver-handbook.html",
  bookingUrl: "https://www.gnb.ca/en/topic/driving-transportation/driving-licensing/written-road-tests.html",
  topics: [
    { id:"licensing",  en:"Graduated Licensing",          fr:"Permis par \u00e9tapes" },
    { id:"licence",    en:"Your Licence and the Exams",   fr:"Votre permis et les examens" },
    { id:"sharing",    en:"Sharing the Road",             fr:"Partager la route" },
    { id:"conditions", en:"Wildlife and Weather",         fr:"Faune et m\u00e9t\u00e9o" },
    { id:"safe",       en:"Safe and Responsible Driving", fr:"Conduite s\u00e9curitaire et responsable" },
    { id:"vehicle",    en:"Your Vehicle",                 fr:"Votre v\u00e9hicule" },
    { id:"collisions", en:"Emergencies and Collisions",   fr:"Urgences et collisions" }
  ],
  questions: window.CQ_DRIVE_Q
};
