/* canada-quiz.com — NEWFOUNDLAND AND LABRADOR Class 5 Level I practice data
   60 original bilingual questions (30 road signs + 30 rules of the road).
   Written in our own words from the free Driver's Handbook, the Motor
   Registration Division pages on gov.nl.ca, and the province's own moose
   safety, winter maintenance and off-road vehicle advisories.
   Not affiliated with the Motor Registration Division or the Government of
   Newfoundland and Labrador.

   The quiz code lives in js/driving-engine.js and never changes per province. */
window.CQ_DRIVE_Q = [];

/* ---------- road signs ---------- */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"nls1", sec:"signs", sign:"stop",
  en:{ q:"You reach this sign on an empty street early in the morning. What does the law require?",
       a:["A complete stop, even when you can see the way is clear","A rolling stop if nothing is coming","A stop only when a pedestrian is waiting","A tap on the brakes to show you saw it"],
       e:"The sign means stop every time. Stop at the stop line, or before the crosswalk if there is no line, and move off only when the way is clear." },
  fr:{ q:"Vous arrivez à ce panneau dans une rue déserte tôt le matin. Qu'exige la loi ?",
       a:["Un arrêt complet, même si la voie est visiblement libre","Un arrêt roulant si personne ne vient","Un arrêt seulement si un piéton attend","Un coup de frein pour montrer que vous l'avez vu"],
       e:"Le panneau signifie s'arrêter chaque fois. Arrêtez-vous à la ligne d'arrêt, ou avant le passage pour piétons s'il n'y a pas de ligne, et repartez seulement quand la voie est libre." },
  c:0 },
{ id:"nls2", sec:"signs", sign:"yield",
  en:{ q:"You are joining a highway on a ramp posted with this sign. What does it require?",
       a:["Come to a full stop at the end of the ramp","Give way to traffic already on the highway, stopping if you have to","Keep your speed and expect drivers to open a gap","Use the shoulder until a gap appears"],
       e:"Yield means the other traffic has the right of way. Match your speed to the traffic, look for a real gap, and stop if one does not come." },
  fr:{ q:"Vous vous engagez sur une route par une bretelle où ce panneau est affiché. Qu'exige-t-il ?",
       a:["Faire un arrêt complet au bout de la bretelle","Céder le passage à la circulation déjà sur la route, en vous arrêtant s'il le faut","Garder votre vitesse et compter sur les autres pour vous laisser entrer","Rouler sur l'accotement jusqu'à ce qu'un espace se libère"],
       e:"Céder le passage veut dire que l'autre circulation a la priorité. Ajustez votre vitesse à la sienne, cherchez un vrai espace et arrêtez-vous s'il ne vient pas." },
  c:1 },
{ id:"nls3", sec:"signs", sign:"speed-50",
  en:{ q:"What is this black and white sign telling you?",
       a:["The speed most drivers here choose","The lowest speed allowed","The highest speed allowed here in good conditions","A speed suggested for trucks only"],
       e:"A posted limit is a maximum for a clear, dry day. In rain, snow or fog the safe speed is lower, and driving too fast for the conditions is still an offence." },
  fr:{ q:"Que vous indique ce panneau noir et blanc ?",
       a:["La vitesse que la plupart des conducteurs adoptent ici","La vitesse minimale permise","La vitesse maximale permise ici par bonnes conditions","Une vitesse suggérée aux camions seulement"],
       e:"Une limite affichée est un maximum pour une journée claire et sèche. Sous la pluie, la neige ou le brouillard, la vitesse sécuritaire est plus basse, et rouler trop vite pour les conditions demeure une infraction." },
  c:2 },
{ id:"nls4", sec:"signs", sign:"no-entry",
  en:{ q:"This sign faces you at the entrance to a street. What should you do?",
       a:["Enter slowly with your headlights on","Enter only to make a delivery","Enter and keep well to the right","Do not enter, and look for another way round"],
       e:"The street runs the other way. Driving past this sign puts you head-on into traffic that has no reason to expect you." },
  fr:{ q:"Ce panneau vous fait face à l'entrée d'une rue. Que devez-vous faire ?",
       a:["Entrer lentement avec les phares allumés","Entrer seulement pour une livraison","Entrer en tenant bien la droite","Ne pas entrer et chercher un autre chemin"],
       e:"La rue circule en sens inverse. Franchir ce panneau vous place face à des conducteurs qui n'ont aucune raison de vous attendre." },
  c:3 },
{ id:"nls5", sec:"signs", sign:"no-passing",
  en:{ q:"You are behind a slow truck and you see this sign. What does it tell you?",
       a:["You must stay behind until the restriction ends","You may pass if the truck driver waves you by","You may pass if you can do it in under ten seconds","You may pass by using the shoulder"],
       e:"The restriction is posted where you cannot see far enough ahead to pull back in safely. Staying behind costs you a minute; being wrong costs far more." },
  fr:{ q:"Vous suivez un camion lent et vous voyez ce panneau. Que vous indique-t-il ?",
       a:["Vous devez rester derrière jusqu'à la fin de l'interdiction","Vous pouvez dépasser si le camionneur vous fait signe","Vous pouvez dépasser si cela prend moins de dix secondes","Vous pouvez dépasser en utilisant l'accotement"],
       e:"L'interdiction est affichée là où vous ne voyez pas assez loin devant pour vous rabattre en sécurité. Rester derrière coûte une minute ; se tromper coûte bien plus cher." },
  c:0 },
{ id:"nls6", sec:"signs", sign:"no-parking",
  en:{ q:"You want to leave your car here for ten minutes while you run into a shop. This sign is posted. May you?",
       a:["Yes, if you stay under fifteen minutes","No, leaving the car standing is exactly what this sign forbids","Yes, if you leave the engine running","Yes, if your hazard lights are on"],
       e:"Parking means leaving the vehicle standing, with or without a driver in it. Hazard lights and a running engine change nothing." },
  fr:{ q:"Vous voulez laisser votre voiture ici dix minutes pour entrer dans un magasin. Ce panneau est affiché. Le pouvez-vous ?",
       a:["Oui, si vous restez moins de quinze minutes","Non, laisser la voiture immobilisée est exactement ce que ce panneau interdit","Oui, si vous laissez le moteur en marche","Oui, si vos feux de détresse sont allumés"],
       e:"Stationner, c'est laisser le véhicule immobilisé, avec ou sans conducteur à bord. Les feux de détresse et le moteur en marche n'y changent rien." },
  c:1 },
{ id:"nls7", sec:"signs", sign:"no-stopping",
  en:{ q:"Your phone rings and you look for somewhere to pull over. You see this sign. What does it mean for you?",
       a:["You may stop as long as you stay in the vehicle","You may stop for up to five minutes","You may not stop here at all, so carry on until the restriction ends","You may stop if you switch the engine off"],
       e:"This is the strictest of the three, and it means no stopping for any reason, even briefly. Carry on to a safe spot beyond the sign before you touch the phone." },
  fr:{ q:"Votre téléphone sonne et vous cherchez où vous ranger. Vous voyez ce panneau. Que signifie-t-il pour vous ?",
       a:["Vous pouvez vous arrêter tant que vous restez dans le véhicule","Vous pouvez vous arrêter jusqu'à cinq minutes","Vous ne pouvez pas vous arrêter ici du tout : continuez jusqu'à la fin de l'interdiction","Vous pouvez vous arrêter si vous coupez le moteur"],
       e:"C'est le plus strict des trois, et il interdit tout arrêt, pour quelque raison que ce soit, même bref. Continuez jusqu'à un endroit sûr au-delà du panneau avant de toucher au téléphone." },
  c:2 },
{ id:"nls8", sec:"signs", sign:"stop-school-bus",
  en:{ q:"This sign is mounted on the side of a school bus and swings out when the bus stops. What does it require of you?",
       a:["Pass slowly on the left","Pass on the right if the shoulder is wide","Sound your horn and continue","Stop and wait until the arm folds back and the lights stop flashing"],
       e:"Wait until the arm folds back and the red lights stop flashing. Children may still be crossing in front of the bus, where you cannot see them." },
  fr:{ q:"Ce panneau est monté sur le côté d'un autobus scolaire et se déploie quand l'autobus s'arrête. Qu'exige-t-il de vous ?",
       a:["Dépasser lentement par la gauche","Dépasser par la droite si l'accotement est large","Klaxonner et continuer","Vous arrêter et attendre que le bras se replie et que les feux cessent de clignoter"],
       e:"Attendez que le bras se replie et que les feux rouges cessent de clignoter. Des enfants peuvent encore traverser devant l'autobus, là où vous ne les voyez pas." },
  c:3 },
{ id:"nls9", sec:"signs", sign:"keep-right",
  en:{ q:"A concrete island splits the road ahead and this sign stands on it. What does it tell you?",
       a:["Go by on the right-hand side of the island","Go by on whichever side is clear","Stop before the island and wait","The road ahead is closed"],
       e:"Keep right of the island. Choosing the wrong side puts you into traffic coming the other way, which is why the sign is planted on the island itself." },
  fr:{ q:"Un îlot de béton sépare la route devant et ce panneau y est planté. Que vous indique-t-il ?",
       a:["Passer du côté droit de l'îlot","Passer du côté qui est libre","Vous arrêter avant l'îlot et attendre","La route devant est fermée"],
       e:"Tenez la droite de l'îlot. Choisir le mauvais côté vous place face à la circulation inverse, et c'est pourquoi le panneau est planté sur l'îlot même." },
  c:0 },
{ id:"nls10", sec:"signs", sign:"warn-moose",
  en:{ q:"You see this yellow sign on a Newfoundland highway. What is it telling you?",
       a:["A farm keeps animals beside the road","You are entering a stretch where moose are often on the road","Hunting is allowed beyond this point","A wildlife park entrance is ahead"],
       e:"The province posts these where moose collisions keep happening. Cut your speed, scan both shoulders far ahead, and be ready for an animal that will not move out of your way." },
  fr:{ q:"Vous voyez ce panneau jaune sur une route de Terre-Neuve. Que vous indique-t-il ?",
       a:["Une ferme garde des animaux au bord de la route","Vous entrez dans un secteur où des orignaux se trouvent souvent sur la chaussée","La chasse est permise au-delà de ce point","L'entrée d'un parc animalier est devant"],
       e:"La province installe ces panneaux là où les collisions avec des orignaux se répètent. Réduisez votre vitesse, balayez les deux accotements loin devant et attendez-vous à un animal qui ne s'écartera pas." },
  c:1 },
{ id:"nls11", sec:"signs", sign:"warn-pavement-ends",
  en:{ q:"What is coming up when you pass this warning sign?",
       a:["A bridge deck","A weigh station","The pavement runs out and the surface becomes gravel","A tunnel"],
       e:"Slow down well before the change. Loose gravel gives far less grip than pavement, and where a gravel road in this province carries no speed sign the limit is 60 km/h." },
  fr:{ q:"Qu'est-ce qui vous attend lorsque vous franchissez ce panneau d'avertissement ?",
       a:["Un tablier de pont","Une station de pesée","Le revêtement se termine et la surface devient du gravier","Un tunnel"],
       e:"Ralentissez bien avant le changement. Le gravier meuble offre beaucoup moins d'adhérence que l'asphalte, et sur un chemin de gravier sans panneau de vitesse dans la province la limite est de 60 km/h." },
  c:2 },
{ id:"nls12", sec:"signs", sign:"warn-slippery",
  en:{ q:"Rain has just started and you pass this sign. What extra care does it call for?",
       a:["Turn on your hazard lights","Move over to the shoulder","Change to a lower gear and hold the brake down","Ease off the accelerator and avoid sudden steering or braking"],
       e:"The road loses grip as soon as it is wet, and the first few minutes of rain are the worst as oil lifts off the surface. Smooth inputs and a bigger gap keep you out of a skid." },
  fr:{ q:"La pluie vient de commencer et vous passez ce panneau. Quelle prudence supplémentaire demande-t-il ?",
       a:["Allumer vos feux de détresse","Vous ranger sur l'accotement","Rétrograder et garder le pied sur le frein","Relâcher l'accélérateur et éviter les coups de volant et de frein"],
       e:"La chaussée perd son adhérence dès qu'elle est mouillée, et les premières minutes de pluie sont les pires parce que l'huile remonte à la surface. Des gestes doux et une plus grande distance vous évitent le dérapage." },
  c:3 },
{ id:"nls13", sec:"signs", sign:"warn-steep-hill",
  en:{ q:"You meet this sign at the top of a long descent. What is the safest way down?",
       a:["Slow down before the hill and use a lower gear so the engine helps hold you back","Coast down in neutral to save fuel","Keep steady pressure on the brake all the way down","Speed up so you can climb the next hill"],
       e:"Riding the brakes the whole way heats them until they fade. A lower gear does most of the work and leaves the brakes fresh for the moment you really need them." },
  fr:{ q:"Vous rencontrez ce panneau au sommet d'une longue descente. Quelle est la façon la plus sûre de descendre ?",
       a:["Ralentir avant la pente et utiliser un rapport inférieur pour que le moteur vous retienne","Descendre au point mort pour économiser du carburant","Garder une pression constante sur le frein jusqu'en bas","Accélérer pour mieux monter la côte suivante"],
       e:"Freiner sans arrêt échauffe les freins jusqu'à ce qu'ils perdent leur efficacité. Un rapport inférieur fait le gros du travail et garde les freins disponibles au moment critique." },
  c:0 },
{ id:"nls14", sec:"signs", sign:"warn-winding",
  en:{ q:"What is the road like on the stretch where this sign is posted?",
       a:["There is one sharp curve, then the road is straight","There is a series of curves in both directions","The road ends shortly","The road is closed in winter"],
       e:"A winding road means several bends one after another. Set your speed before the first one and stay off the brakes in the middle of each curve." },
  fr:{ q:"Que vous dit ce panneau sur la route qui suit ?",
       a:["Il y a un seul virage serré, puis la route est droite","Il y a une suite de virages dans les deux sens","La route se termine bientôt","La route est fermée l'hiver"],
       e:"Une route sinueuse enchaîne plusieurs courbes. Choisissez votre vitesse avant la première et évitez de freiner au milieu d'un virage." },
  c:1 },
{ id:"nls15", sec:"signs", sign:"warn-narrow-bridge",
  en:{ q:"This sign appears before a bridge. What should you expect?",
       a:["The bridge carries one direction only","The bridge has a weight limit","The bridge is narrower than the road, so the lanes tighten","The bridge deck is gravel"],
       e:"The lanes squeeze together on the structure. Slow down, place your vehicle in the middle of your lane, and never try to pass on the bridge." },
  fr:{ q:"Ce panneau apparaît avant un pont. À quoi devez-vous vous attendre ?",
       a:["Le pont ne sert qu'à un seul sens","Le pont a une limite de poids","Le pont est plus étroit que la route et les voies se resserrent","Le tablier du pont est en gravier"],
       e:"Les voies se resserrent sur l'ouvrage. Ralentissez, placez votre véhicule au milieu de votre voie et ne tentez jamais un dépassement sur le pont." },
  c:2 },
{ id:"nls16", sec:"signs", sign:"warn-school-zone",
  en:{ q:"What does this sign mean for the way you drive on the stretch ahead?",
       a:["Children are only present in September","You may park on both sides","Buses have priority over you","Children may be near or on the road, so slow down and be ready to stop"],
       e:"School zones are where children step out without checking. Where a school zone in this province carries no speed sign of its own the limit is 50 km/h, and posted school zones run lower, from 30 to 50." },
  fr:{ q:"Que signifie ce panneau pour votre conduite sur le tronçon qui suit ?",
       a:["Des enfants ne sont présents qu'en septembre","Vous pouvez stationner des deux côtés","Les autobus ont priorité sur vous","Des enfants peuvent être près de la chaussée ou dessus : ralentissez et soyez prêt à arrêter"],
       e:"Les zones scolaires sont des endroits où les enfants s'engagent sans regarder. Quand une zone scolaire de la province ne porte aucun panneau de vitesse, la limite est de 50 km/h, et les zones affichées vont de 30 à 50 km/h." },
  c:3 },
{ id:"nls17", sec:"signs", sign:"warn-chevron",
  en:{ q:"A row of these markers is lined up on the outside of a bend. What are they for?",
       a:["They show which way the road turns and how sharply","They mark a pedestrian crossing","They mark the edge of a parking area","They show where snowploughs turn round"],
       e:"Chevrons point the way through the curve. If you can see several of them stacked close together, the bend is tighter than it looks from the approach." },
  fr:{ q:"Une rangée de ces marqueurs est alignée à l'extérieur d'une courbe. À quoi servent-ils ?",
       a:["Ils indiquent le sens du virage et sa sévérité","Ils marquent un passage pour piétons","Ils marquent la limite d'une aire de stationnement","Ils indiquent où les chasse-neige font demi-tour"],
       e:"Les chevrons montrent la trajectoire dans la courbe. Si vous en voyez plusieurs très rapprochés, le virage est plus serré qu'il n'y paraît à l'approche." },
  c:0 },
{ id:"nls18", sec:"signs", sign:"warn-fallen-rock",
  en:{ q:"You pass this sign on a road cut into a hillside. What are you being warned about?",
       a:["Loose gravel spread by a truck","Rock may have fallen onto the road from the slope above","Blasting is going on nearby","The road is unpaved beyond this point"],
       e:"Rock comes down after rain and after a freeze and thaw. Scan the surface far enough ahead that you can steer around a boulder instead of meeting it." },
  fr:{ q:"Vous passez ce panneau sur une route taillée dans une colline. De quoi vous avertit-il ?",
       a:["Du gravier meuble répandu par un camion","Des pierres peuvent être tombées sur la chaussée depuis la pente au-dessus","Un dynamitage a lieu à proximité","La route n'est plus revêtue au-delà de ce point"],
       e:"Les pierres se détachent après la pluie et après un cycle de gel et de dégel. Balayez la chaussée assez loin devant pour contourner un bloc au lieu de le percuter." },
  c:1 },
{ id:"nls19", sec:"signs", sign:"warn-crossbuck",
  en:{ q:"You reach this white X-shaped sign at a railway line that has no gates and no lights. What is your duty?",
       a:["Cross without slowing, since there are no gates","Stop every time, as you would at a stop sign","Slow down, look and listen both ways, and cross only when it is clearly safe","Sound your horn and cross"],
       e:"The crossbuck marks the crossing itself and gives you no protection at all. A train needs far more distance to stop than you do, so the looking is yours to do." },
  fr:{ q:"Vous arrivez à ce panneau blanc en forme de X à une voie ferrée sans barrière ni feux. Quel est votre devoir ?",
       a:["Traverser sans ralentir, puisqu'il n'y a pas de barrière","Vous arrêter chaque fois, comme à un panneau d'arrêt","Ralentir, regarder et écouter des deux côtés, puis traverser seulement si c'est clairement sécuritaire","Klaxonner et traverser"],
       e:"La croix de Saint-André marque le passage à niveau sans vous protéger. Un train met bien plus de distance que vous à s'arrêter : c'est à vous de regarder." },
  c:2 },
{ id:"nls20", sec:"signs", sign:"temp-construction",
  en:{ q:"Orange signs like this one appear beside the road. What do they mean?",
       a:["A permanent change to the road layout","A route set aside for large trucks","A tourist route","Roadwork is going on, so expect workers, equipment and changed conditions"],
       e:"Orange always means temporary. Slow to the posted work-zone speed, watch for people on foot, and expect the lane to shift without much notice." },
  fr:{ q:"Des panneaux orange comme celui-ci apparaissent au bord de la route. Que signifient-ils ?",
       a:["Un changement permanent de l'aménagement routier","Un itinéraire réservé aux gros camions","Une route touristique","Des travaux sont en cours : attendez-vous à des travailleurs, à de la machinerie et à des conditions modifiées"],
       e:"L'orange signifie toujours temporaire. Ralentissez à la vitesse affichée dans la zone de travaux, surveillez les personnes à pied et attendez-vous à un déplacement de voie sans grand préavis." },
  c:3 },
{ id:"nls21", sec:"signs", sign:"temp-flagger",
  en:{ q:"This orange sign warns that somebody will be directing traffic ahead. How much authority do their signals carry?",
       a:["You must obey them, even where they contradict the usual rules","They are advice you may take or leave","They apply to trucks only","They apply only when no police officer is present"],
       e:"A traffic control person guides you through the work zone and their instructions come first. Watch the paddle, and do not move until you are waved on." },
  fr:{ q:"Ce panneau orange annonce que quelqu'un dirigera la circulation devant. Quelle autorité ont ses signaux ?",
       a:["Vous devez leur obéir, même s'ils vont à l'encontre des règles habituelles","Ce sont des conseils que vous suivez ou non","Ils ne visent que les camions","Ils ne s'appliquent qu'en l'absence d'un policier"],
       e:"Le signaleur vous guide dans la zone de travaux et ses instructions priment. Surveillez sa palette et n'avancez pas avant qu'il vous fasse signe." },
  c:0 },
{ id:"nls22", sec:"signs", sign:"temp-detour",
  en:{ q:"What does this orange sign ask you to do?",
       a:["Leave the highway for good at the next exit","Leave the usual route and follow the marked way around the closure","Stop and wait for a pilot vehicle","Turn back the way you came"],
       e:"A detour routes you around a closed section and back onto your road. Follow the whole run of detour markers instead of guessing your own way through side streets." },
  fr:{ q:"Que vous demande ce panneau orange ?",
       a:["Quitter la route définitivement à la prochaine sortie","Quitter l'itinéraire habituel et suivre le chemin balisé qui contourne la fermeture","Vous arrêter et attendre un véhicule d'escorte","Rebrousser chemin"],
       e:"Un détour vous fait contourner un tronçon fermé puis vous ramène sur votre route. Suivez toute la série de panneaux de détour au lieu d'improviser par les rues secondaires." },
  c:1 },
{ id:"nls23", sec:"signs", sign:"info-trans-canada",
  en:{ q:"What does this route marker identify?",
       a:["A city bypass","A scenic coastal loop","The Trans-Canada Highway, the route that crosses the province and the country","A road that is closed in winter"],
       e:"The marker keeps you on the Trans-Canada. Where the paved Trans-Canada in this province carries no speed sign, the limit is 100 km/h." },
  fr:{ q:"Qu'identifie cet écusson de route ?",
       a:["Une voie de contournement urbaine","Une boucle panoramique côtière","La route Transcanadienne, celle qui traverse la province et le pays","Une route fermée l'hiver"],
       e:"L'écusson vous garde sur la Transcanadienne. Là où la Transcanadienne revêtue de la province ne porte aucun panneau de vitesse, la limite est de 100 km/h." },
  c:2 },
{ id:"nls24", sec:"signs", sign:"info-hospital",
  en:{ q:"What does this blue sign point you to?",
       a:["A pharmacy","A rest area","A police station","A hospital"],
       e:"Blue signs point to services rather than telling you what to do. Knowing this one matters more on a long highway drive than anywhere else." },
  fr:{ q:"Vers quoi vous dirige ce panneau bleu ?",
       a:["Une pharmacie","Une halte routière","Un poste de police","Un hôpital"],
       e:"Les panneaux bleus indiquent des services plutôt que des obligations. Savoir reconnaître celui-ci compte encore plus sur un long trajet en route." },
  c:3 },
{ id:"nls25", sec:"signs", sign:"info-gas",
  en:{ q:"You are running low and you see this blue sign. What is it telling you?",
       a:["Fuel is available at the next exit or turning","A weigh station is ahead","A vehicle inspection station is ahead","Parking is available"],
       e:"Blue service signs are worth watching on long stretches with few communities, because the next chance to fill up can be a very long way further on." },
  fr:{ q:"Vous manquez de carburant et vous voyez ce panneau bleu. Que vous indique-t-il ?",
       a:["Du carburant est offert à la prochaine sortie ou au prochain embranchement","Une station de pesée est devant","Un centre d'inspection des véhicules est devant","Du stationnement est offert"],
       e:"Les panneaux bleus de services méritent votre attention sur les longs tronçons peu habités, car la prochaine occasion de faire le plein peut être très loin." },
  c:0 },
{ id:"nls26", sec:"signs", sign:"info-accessible",
  en:{ q:"Who may use a parking space marked with this sign?",
       a:["Anyone, once the lot is full","Only a vehicle displaying a valid accessible parking permit","Anyone stopping for under ten minutes","Delivery vehicles"],
       e:"The space exists because somebody needs the extra room and the short distance. Using it without a permit is an offence, however briefly you are there." },
  fr:{ q:"Qui peut utiliser une place de stationnement marquée de ce panneau ?",
       a:["N'importe qui, une fois le terrain plein","Seulement un véhicule affichant une vignette de stationnement accessible valide","N'importe qui s'arrêtant moins de dix minutes","Les véhicules de livraison"],
       e:"Cette place existe parce que quelqu'un a besoin de l'espace supplémentaire et de la courte distance. L'utiliser sans vignette est une infraction, si bref que soit l'arrêt." },
  c:1 },
{ id:"nls27", sec:"signs", sign:"light-amber",
  en:{ q:"The light turns amber as you approach and you are still some distance back. What is required?",
       a:["Speed up to clear the intersection","Cover the brake but carry on through","Stop, unless you are so close that stopping would be unsafe","Stop only if a vehicle is waiting on the cross street"],
       e:"Amber means the red is coming, not that you have a few seconds in hand. Stop if you can do it safely, and go through only where braking would put you or the driver behind you at risk." },
  fr:{ q:"Le feu passe au jaune à votre approche et vous êtes encore assez loin. Qu'est-ce qui est exigé ?",
       a:["Accélérer pour dégager l'intersection","Couvrir le frein mais continuer","Vous arrêter, sauf si vous êtes si près que l'arrêt serait dangereux","Vous arrêter seulement si un véhicule attend sur la rue transversale"],
       e:"Le jaune annonce le rouge, il ne vous accorde pas quelques secondes de plus. Arrêtez-vous si vous le pouvez en sécurité, et ne passez que si freiner mettait en danger vous ou le conducteur derrière." },
  c:2 },
{ id:"nls28", sec:"signs", sign:"light-flashing-red",
  en:{ q:"You reach an intersection where the light is flashing red. What must you do?",
       a:["Slow down and go through if nothing is coming","Treat it as a green light","Wait for the light to become steady","Stop completely, then go when the way is clear"],
       e:"A flashing red works exactly like a stop sign. Every driver arriving at it must stop, so take your turn rather than assume the right of way is yours." },
  fr:{ q:"Vous arrivez à une intersection où le feu clignote au rouge. Que devez-vous faire ?",
       a:["Ralentir et passer si rien ne vient","Le traiter comme un feu vert","Attendre que le feu devienne fixe","Vous arrêter complètement, puis repartir quand la voie est libre"],
       e:"Un feu rouge clignotant fonctionne exactement comme un panneau d'arrêt. Tout conducteur qui s'y présente doit s'arrêter : attendez votre tour au lieu de présumer de la priorité." },
  c:3 },
{ id:"nls29", sec:"signs", sign:"mark-solid-yellow",
  en:{ q:"Two solid yellow lines separate you from oncoming traffic. What are you not allowed to do?",
       a:["Cross them to pass the vehicle ahead","Drive at the posted speed limit","Change lanes on your own side of the road","Follow the road around a curve"],
       e:"Yellow separates traffic moving in opposite directions, and a solid line on your side means passing is not permitted along that stretch." },
  fr:{ q:"Deux lignes jaunes continues vous séparent de la circulation en sens inverse. Qu'est-ce qui vous est interdit ?",
       a:["Les franchir pour dépasser le véhicule devant","Rouler à la vitesse affichée","Changer de voie de votre côté de la chaussée","Suivre la route dans une courbe"],
       e:"Le jaune sépare les circulations de sens opposés, et une ligne continue de votre côté interdit le dépassement sur ce tronçon." },
  c:0 },
{ id:"nls30", sec:"signs", sign:"mark-stop-line",
  en:{ q:"A wide white line is painted across your lane at an intersection. What is it for?",
       a:["It marks where pedestrians walk","It shows where the front of your vehicle must stop","It separates two lanes going the same way","It marks a bus stop"],
       e:"Stop with your bumper behind the line rather than on it. Stopping past it blocks the crosswalk and hides you from traffic on the cross street." },
  fr:{ q:"Une large ligne blanche est peinte en travers de votre voie à une intersection. À quoi sert-elle ?",
       a:["Elle indique où les piétons marchent","Elle montre où l'avant de votre véhicule doit s'arrêter","Elle sépare deux voies allant dans le même sens","Elle marque un arrêt d'autobus"],
       e:"Arrêtez-vous avec le pare-chocs derrière la ligne, pas dessus. S'arrêter au-delà bloque le passage pour piétons et vous cache de la circulation transversale." },
  c:1 }
);

/* ---------- rules of the road ---------- */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"nlr1", sec:"rules", topic:"licensing",
  en:{ q:"How long must a Class 5 Level I licence be held in Newfoundland and Labrador before the road test?",
       a:["Three months, or one month with driver education","Six months, or three months with driver education","Twelve months, or eight months with an approved driver education program","Twenty-four months, with no reduction available"],
       e:"The province cuts the wait from twelve months to eight for a driver who completes an approved driver education program. That eight-month figure belongs to this province, so do not carry a number over from somewhere else." },
  fr:{ q:"Combien de temps faut-il détenir un permis de classe 5, niveau I, à Terre-Neuve-et-Labrador avant l'examen sur route ?",
       a:["Trois mois, ou un mois avec un cours de conduite","Six mois, ou trois mois avec un cours de conduite","Douze mois, ou huit mois avec un programme d'éducation à la conduite approuvé","Vingt-quatre mois, sans réduction possible"],
       e:"La province réduit l'attente de douze à huit mois pour la personne qui termine un programme d'éducation à la conduite approuvé. Ce chiffre de huit mois est propre à la province : ne reprenez pas un nombre venu d'ailleurs." },
  c:2 },
{ id:"nlr2", sec:"rules", topic:"licensing",
  en:{ q:"Who may ride in the vehicle with a Level I driver?",
       a:["As many people as there are seat belts","Family members only","One friend, plus the accompanying driver","Nobody except the accompanying driver"],
       e:"At Level I the vehicle holds you and your supervisor and no one else. The limit loosens at Level II, where it becomes the number of working seat belts." },
  fr:{ q:"Qui peut prendre place dans le véhicule avec un conducteur de niveau I ?",
       a:["Autant de personnes qu'il y a de ceintures de sécurité","Les membres de la famille seulement","Un ami, en plus du conducteur accompagnateur","Personne, sauf le conducteur accompagnateur"],
       e:"Au niveau I, le véhicule ne transporte que vous et votre accompagnateur. La limite s'assouplit au niveau II, où elle devient le nombre de ceintures de sécurité en état de servir." },
  c:3 },
{ id:"nlr3", sec:"rules", topic:"licensing",
  en:{ q:"At what hours is a Level I driver forbidden to drive?",
       a:["Between midnight and 5 a.m.","Between 11 p.m. and 6 a.m.","Between 1 a.m. and 4 a.m.","There is no restriction on hours"],
       e:"The curfew runs from midnight to five in the morning, and it does not simply vanish at Level II: at that stage those hours are allowed only with a qualified accompanying driver, or under a work exemption." },
  fr:{ q:"À quelles heures un conducteur de niveau I n'a-t-il pas le droit de conduire ?",
       a:["Entre minuit et 5 h","Entre 23 h et 6 h","Entre 1 h et 4 h","Il n'y a aucune restriction d'heures"],
       e:"Le couvre-feu va de minuit à cinq heures du matin, et il ne disparaît pas au niveau II : à cette étape, ces heures ne sont permises qu'avec un accompagnateur qualifié ou grâce à une exemption pour le travail." },
  c:0 },
{ id:"nlr4", sec:"rules", topic:"licensing",
  en:{ q:"What must the driver who accompanies a learner in this province meet?",
       a:["Two years of driving experience and a blood alcohol level under 0.05","At least four years of driving experience and no alcohol at all in their blood","Any full licence, with no experience requirement","Ten years of driving experience and a clean record"],
       e:"The province asks for four years behind the wheel and zero blood alcohol from the supervisor. That person is there to do the thinking when something goes wrong, which is impossible after a drink." },
  fr:{ q:"Quelles conditions le conducteur qui accompagne un apprenti doit-il remplir dans la province ?",
       a:["Deux ans d'expérience de conduite et une alcoolémie inférieure à 0,05","Au moins quatre ans d'expérience de conduite et aucune trace d'alcool dans le sang","N'importe quel permis complet, sans exigence d'expérience","Dix ans d'expérience de conduite et un dossier sans tache"],
       e:"La province exige quatre ans d'expérience au volant et une alcoolémie de zéro de l'accompagnateur. Cette personne est là pour réfléchir à votre place quand la situation dérape, ce qui est impossible après un verre." },
  c:1 },
{ id:"nlr5", sec:"rules", topic:"licensing",
  en:{ q:"How many demerit points may a novice driver collect within one year before the licence is suspended?",
       a:["Three","Four","Six","Twelve"],
       e:"A novice driver is suspended at six points in a single year, with a written warning at three. The figure of twelve that people quote belongs to full licence holders and is counted over two years." },
  fr:{ q:"Combien de points d'inaptitude un conducteur novice peut-il accumuler en un an avant la suspension de son permis ?",
       a:["Trois","Quatre","Six","Douze"],
       e:"Le conducteur novice est suspendu à six points en une seule année, avec un avertissement écrit à trois. Le chiffre de douze que l'on cite souvent vise le titulaire d'un permis complet et se compte sur deux ans." },
  c:2 },
{ id:"nlr6", sec:"rules", topic:"licence",
  en:{ q:"What mark does Newfoundland and Labrador require on the written knowledge test?",
       a:["70 per cent","75 per cent","80 per cent","85 per cent"],
       e:"The province states 85 per cent on its licensing pages and in the Driver's Handbook. Some practice sites publish 80 per cent, which is not the province's figure, so study to the higher one." },
  fr:{ q:"Quelle note Terre-Neuve-et-Labrador exige-t-elle à l'examen théorique ?",
       a:["70 pour cent","75 pour cent","80 pour cent","85 pour cent"],
       e:"La province indique 85 pour cent sur ses pages de permis et dans le Manuel du conducteur. Certains sites de pratique publient 80 pour cent, ce qui n'est pas le chiffre de la province : étudiez pour la note la plus élevée." },
  c:3 },
{ id:"nlr7", sec:"rules", topic:"licence",
  en:{ q:"How must the NOVICE DRIVER sign be displayed on a learner's vehicle?",
       a:["On the rear, in black letters at least 5 cm high on a white background","On the windscreen, in any colour","On both front doors, at least 10 cm high","Anywhere on the vehicle, as long as it can be read"],
       e:"The sign goes on the back, where the drivers behind you can see it, and its size and colours are set out in law. Bring it to the road test as well, because it is on the list of things you must have with you." },
  fr:{ q:"Comment le panneau NOVICE DRIVER doit-il être affiché sur le véhicule d'un apprenti ?",
       a:["À l'arrière, en lettres noires d'au moins 5 cm de hauteur sur fond blanc","Sur le pare-brise, dans n'importe quelle couleur","Sur les deux portières avant, en lettres d'au moins 10 cm","N'importe où sur le véhicule, pourvu qu'il soit lisible"],
       e:"Le panneau se place à l'arrière, là où les conducteurs derrière vous le voient, et sa taille comme ses couleurs sont fixées par la loi. Apportez-le aussi à l'examen sur route : il figure parmi les articles à avoir avec vous." },
  c:0 },
{ id:"nlr8", sec:"rules", topic:"licence",
  en:{ q:"What is the minimum age to enter the graduated licensing program here, and what else does a seventeen-year-old need?",
       a:["Fifteen, with a letter from the school","Sixteen, and anyone under nineteen needs consent from a parent or guardian","Seventeen, with no further condition","Eighteen, and nobody younger may apply"],
       e:"You may begin at sixteen, and an applicant under nineteen needs a parent or guardian to consent. That consent is about the application itself, not about who sits beside you afterwards." },
  fr:{ q:"Quel est l'âge minimal pour entrer dans le programme de permis par étapes ici, et de quoi une personne de dix-sept ans a-t-elle aussi besoin ?",
       a:["Quinze ans, avec une lettre de l'école","Seize ans, et toute personne de moins de dix-neuf ans a besoin du consentement d'un parent ou tuteur","Dix-sept ans, sans autre condition","Dix-huit ans, et personne de plus jeune ne peut faire une demande"],
       e:"Vous pouvez commencer à seize ans, et le demandeur de moins de dix-neuf ans a besoin du consentement d'un parent ou tuteur. Ce consentement porte sur la demande elle-même, non sur la personne qui vous accompagnera ensuite." },
  c:1 },
{ id:"nlr9", sec:"rules", topic:"licence",
  en:{ q:"You pass the knowledge test online through MyGovNL. May you start driving with a supervisor that afternoon?",
       a:["Yes, the online pass is all that is needed","Yes, as long as you print the result","No, you must first attend an appointment for the vision test and to have your documents checked","No, you must wait thirty days"],
       e:"The online pass is only the first step. Until you attend the appointment, have your vision tested and your documents verified, you are not allowed to drive." },
  fr:{ q:"Vous réussissez l'examen théorique en ligne au moyen de MyGovNL. Pouvez-vous commencer à conduire avec un accompagnateur l'après-midi même ?",
       a:["Oui, la réussite en ligne suffit","Oui, à condition d'imprimer le résultat","Non, vous devez d'abord vous présenter à un rendez-vous pour l'examen de la vue et la vérification de vos documents","Non, vous devez attendre trente jours"],
       e:"La réussite en ligne n'est que la première étape. Tant que vous ne vous êtes pas présenté au rendez-vous pour l'examen de la vue et la vérification des documents, vous n'avez pas le droit de conduire." },
  c:2 },
{ id:"nlr10", sec:"rules", topic:"licence",
  en:{ q:"In which languages may the written test be taken in this province?",
       a:["English only, in every case","English and French online","English online, and English or Spanish in person","English online, and English, French or Ukrainian in person by appointment"],
       e:"The online version runs in English. If you would rather sit the test in French or in Ukrainian, book an appointment and take it in person at a Motor Registration Division office." },
  fr:{ q:"Dans quelles langues peut-on passer l'examen théorique dans la province ?",
       a:["En anglais seulement, dans tous les cas","En anglais et en français en ligne","En anglais en ligne, et en anglais ou en espagnol en personne","En anglais en ligne, et en anglais, en français ou en ukrainien en personne sur rendez-vous"],
       e:"La version en ligne se fait en anglais. Si vous préférez passer l'examen en français ou en ukrainien, prenez rendez-vous et présentez-vous à un bureau de la Division de l'immatriculation des véhicules." },
  c:3 },
{ id:"nlr11", sec:"rules", topic:"orv",
  en:{ q:"Where may an off-road vehicle cross a highway in this province?",
       a:["Only where there is at least 150 metres of visibility in both directions","Anywhere, as long as the rider wears a helmet","Only at an intersection controlled by traffic lights","Anywhere between sunrise and sunset"],
       e:"The crossing rule is built around what can be seen: 150 metres each way, so a driver has time to react to you and you to them. Cross straight across and do not linger on the road." },
  fr:{ q:"Où un véhicule hors route peut-il traverser une route dans la province ?",
       a:["Seulement là où la visibilité atteint au moins 150 mètres dans les deux directions","N'importe où, pourvu que le conducteur porte un casque","Seulement à une intersection munie de feux de circulation","N'importe où, entre le lever et le coucher du soleil"],
       e:"La règle repose sur ce que l'on voit : 150 mètres de chaque côté, pour qu'un conducteur ait le temps de réagir et vous aussi. Traversez tout droit et ne vous attardez pas sur la chaussée." },
  c:0 },
{ id:"nlr12", sec:"rules", topic:"orv",
  en:{ q:"An off-road vehicle needs to use the shoulder of a highway to reach a trail. What are the limits?",
       a:["Up to 5 km, at no more than 50 km/h","No more than 1 km, at no more than 20 km/h","No limit on distance, at no more than 30 km/h","The shoulder may never be used for any distance"],
       e:"The shoulder is a way of reaching the trail, not a route in its own right: one kilometre at a maximum of 20 km/h." },
  fr:{ q:"Un véhicule hors route doit emprunter l'accotement d'une route pour rejoindre un sentier. Quelles sont les limites ?",
       a:["Jusqu'à 5 km, à 50 km/h au maximum","Au plus 1 km, à 20 km/h au maximum","Aucune limite de distance, à 30 km/h au maximum","L'accotement ne peut jamais être emprunté"],
       e:"L'accotement sert à rejoindre le sentier, non à voyager : un kilomètre, à 20 km/h au maximum." },
  c:1 },
{ id:"nlr13", sec:"rules", topic:"orv",
  en:{ q:"An off-road vehicle is crossing a highway or running along the shoulder. Who has the right of way?",
       a:["The off-road vehicle, because it is the more vulnerable","Whoever arrives first","Highway traffic, at all times","It depends on the posted speed limit"],
       e:"The rule gives highway traffic the right of way in every case. An off-road vehicle on or beside a road is a guest there and has to wait." },
  fr:{ q:"Un véhicule hors route traverse une route ou circule sur l'accotement. Qui a la priorité ?",
       a:["Le véhicule hors route, parce qu'il est le plus vulnérable","Celui qui arrive le premier","La circulation de la route, en tout temps","Cela dépend de la limite de vitesse affichée"],
       e:"La règle accorde la priorité à la circulation routière dans tous les cas. Un véhicule hors route sur la chaussée ou à côté y est un invité et doit attendre." },
  c:2 },
{ id:"nlr14", sec:"rules", topic:"orv",
  en:{ q:"A fourteen-year-old wants to ride an off-road vehicle. What does the law require?",
       a:["Nothing, a rider of any age may ride alone away from the highway","A learner's permit","A helmet and nothing further","Supervision by a licensed driver who is at least eighteen"],
       e:"Under sixteen means supervised, and the supervisor must be a licensed driver of eighteen or older. The engine size must also suit the rider's age and weight, as the manufacturer recommends." },
  fr:{ q:"Une personne de quatorze ans veut conduire un véhicule hors route. Qu'exige la loi ?",
       a:["Rien, on peut conduire seul à tout âge à l'écart des routes","Un permis d'apprenti","Un casque, rien de plus","La surveillance d'un conducteur titulaire d'un permis et âgé d'au moins dix-huit ans"],
       e:"Moins de seize ans signifie sous surveillance, et le surveillant doit être un conducteur titulaire d'un permis âgé d'au moins dix-huit ans. La cylindrée doit aussi convenir à l'âge et au poids du conducteur, selon la recommandation du fabricant." },
  c:3 },
{ id:"nlr15", sec:"rules", topic:"wildlife",
  en:{ q:"In which part of the year do more than 70 per cent of this province's moose collisions happen?",
       a:["Between May and October","Between November and February","Between January and April","They are spread evenly through the year"],
       e:"More than seven in ten fall in the warmer half of the year, with June to August the worst months. A quiet summer evening on a highway is exactly when a driver relaxes." },
  fr:{ q:"À quelle période de l'année plus de 70 pour cent des collisions avec des orignaux surviennent-elles dans la province ?",
       a:["Entre mai et octobre","Entre novembre et février","Entre janvier et avril","Elles sont réparties également sur l'année"],
       e:"Plus de sept sur dix surviennent durant la moitié chaude de l'année, et juin à août sont les pires mois. Un soir d'été tranquille sur une route est précisément le moment où l'on baisse la garde." },
  c:0 },
{ id:"nlr16", sec:"rules", topic:"wildlife",
  en:{ q:"At what time of day do most moose collisions occur?",
       a:["Around the middle of the day","Between dusk and dawn","During the morning rush","The time of day makes no difference"],
       e:"Most happen between dusk and dawn, and the risk of injury then is about twice what it is in daylight. A moose stands tall and dark, and your headlights find almost nothing to catch." },
  fr:{ q:"À quel moment de la journée la plupart des collisions avec des orignaux surviennent-elles ?",
       a:["Vers le milieu du jour","Entre le crépuscule et l'aube","Pendant l'heure de pointe du matin","Le moment de la journée n'y change rien"],
       e:"La plupart surviennent entre le crépuscule et l'aube, et le risque de blessure y est environ deux fois plus élevé qu'en plein jour. L'orignal est haut et sombre, et vos phares n'accrochent presque rien." },
  c:1 },
{ id:"nlr17", sec:"rules", topic:"wildlife",
  en:{ q:"What kind of night carries the greatest risk of a moose collision here?",
       a:["A foggy night","A rainy night","A clear night","A snowy night"],
       e:"Most of these collisions happen on clear nights, when a driver feels comfortable and holds the speed up. Good weather is not the same thing as being able to see an animal standing in an unlit lane." },
  fr:{ q:"Quel type de nuit présente le plus grand risque de collision avec un orignal ici ?",
       a:["Une nuit de brouillard","Une nuit de pluie","Une nuit claire","Une nuit de neige"],
       e:"La plupart de ces collisions surviennent par nuit claire, quand le conducteur se sent à l'aise et maintient sa vitesse. Le beau temps ne veut pas dire que l'on voit un animal debout dans une voie sans éclairage." },
  c:2 },
{ id:"nlr18", sec:"rules", topic:"wildlife",
  en:{ q:"You are driving a dark highway in an area posted with moose warning signs. What does the province advise?",
       a:["Follow the vehicle ahead closely so its lights help you","Keep your speed up so you spend less time on the road","Use your low beams only, so that animals are not startled","Slow down, scan both shoulders far ahead, and use your high beams whenever nobody is coming"],
       e:"The advice is to buy yourself seeing time: less speed, eyes moving along both shoulders, high beams where they will blind nobody, and a clean windscreen and headlights. Everyone in the vehicle should be belted, because unbelted occupants are far more likely to be seriously hurt." },
  fr:{ q:"Vous roulez de nuit sur une route où des panneaux avertissent de la présence d'orignaux. Que conseille la province ?",
       a:["Suivre de près le véhicule devant pour profiter de ses phares","Maintenir votre vitesse pour passer moins de temps sur la route","N'utiliser que vos feux de croisement pour ne pas effrayer les animaux","Ralentir, balayer les deux accotements loin devant et utiliser les feux de route chaque fois que personne ne vient"],
       e:"Le conseil consiste à vous donner du temps pour voir : moins de vitesse, le regard qui balaie les deux accotements, les feux de route quand ils n'éblouissent personne, un pare-brise et des phares propres. Tout le monde doit être attaché, car les occupants sans ceinture risquent bien davantage d'être gravement blessés." },
  c:3 },
{ id:"nlr19", sec:"rules", topic:"conditions",
  en:{ q:"You plan to drive across the province at 3 a.m. after a snowfall. What should you expect of the roads?",
       a:["Ploughs generally do not run between about 10 p.m. and 4:30 or 5 a.m., so the road may not have been cleared for hours","Ploughs run around the clock, so the road will be clear","Ploughs work only at night, so the road will have just been cleared","The highway will be closed until morning"],
       e:"Outside a storm the province does not plough through the small hours except for emergencies. A road that looked fine at ten in the evening can be covered by three in the morning." },
  fr:{ q:"Vous prévoyez traverser la province à 3 h après une chute de neige. À quoi devez-vous vous attendre sur les routes ?",
       a:["Les chasse-neige ne circulent généralement pas entre environ 22 h et 4 h 30 ou 5 h : la route peut ne pas avoir été dégagée depuis des heures","Les chasse-neige roulent jour et nuit : la route sera dégagée","Les chasse-neige ne travaillent que la nuit : la route viendra d'être dégagée","La route sera fermée jusqu'au matin"],
       e:"En dehors d'une tempête, la province ne déneige pas au cœur de la nuit, sauf urgence. Une route qui semblait belle à 22 h peut être couverte à 3 h." },
  c:0 },
{ id:"nlr20", sec:"rules", topic:"conditions",
  en:{ q:"On an ordinary winter working day, when do the highway snow-clearing crews start?",
       a:["At about 8 a.m., like the rest of the working day","Between about 4:30 and 6 a.m., five days a week, working through to mid-afternoon","Only once a storm has finished","At noon, so that the salt works in the warmest part of the day"],
       e:"Crews are out well before the morning traffic and work into the afternoon, and during a storm the ploughing carries on until about 9:30 p.m. or later. Leaving a little later on a bad morning can mean meeting a cleared road instead of an uncleared one." },
  fr:{ q:"Lors d'une journée d'hiver ordinaire, quand les équipes de déneigement des routes commencent-elles ?",
       a:["Vers 8 h, comme le reste de la journée de travail","Entre environ 4 h 30 et 6 h, cinq jours par semaine, jusqu'au milieu de l'après-midi","Seulement une fois la tempête terminée","À midi, pour que le sel agisse au moment le plus chaud"],
       e:"Les équipes sortent bien avant la circulation du matin et travaillent jusqu'à l'après-midi, et pendant une tempête le déneigement se poursuit jusque vers 21 h 30, voire plus tard. Partir un peu plus tard un mauvais matin peut vouloir dire trouver une route déjà dégagée." },
  c:1 },
{ id:"nlr21", sec:"rules", topic:"conditions",
  en:{ q:"Does the law in this province require winter tires?",
       a:["Yes, from December to March","Yes, on all highways outside the cities","No, but the province encourages drivers to fit them","No, and the province advises against them"],
       e:"There is no winter tire requirement here, only encouragement. Four matching winter tires still stop you a great deal sooner on a cold, slippery road than all-season tires do." },
  fr:{ q:"La loi de la province exige-t-elle des pneus d'hiver ?",
       a:["Oui, de décembre à mars","Oui, sur toutes les routes à l'extérieur des villes","Non, mais la province encourage les conducteurs à en installer","Non, et la province en déconseille l'usage"],
       e:"Il n'existe pas d'obligation de pneus d'hiver ici, seulement une recommandation. Quatre pneus d'hiver identiques vous arrêtent tout de même bien plus tôt sur une chaussée froide et glissante que des pneus quatre saisons." },
  c:2 },
{ id:"nlr22", sec:"rules", topic:"conditions",
  en:{ q:"In winter the province reminds drivers that snow means slow. What does that ask of you in practice?",
       a:["Drive at the posted limit, since it already allows for winter","Switch on your hazard lights so that others can see you","Stay in the left lane, where the snow is thinner","Cut your speed to suit the surface, whatever the posted limit says"],
       e:"A posted limit is set for a clear, dry road. On snow the safe speed is whatever lets you stop inside the distance you can see, and that is often far below the number on the sign." },
  fr:{ q:"L'hiver, la province rappelle aux conducteurs que la neige impose de ralentir. Qu'est-ce que cela demande concrètement ?",
       a:["Rouler à la limite affichée, puisqu'elle tient déjà compte de l'hiver","Allumer vos feux de détresse pour que les autres vous voient","Rester dans la voie de gauche, où la neige est plus mince","Réduire votre vitesse selon l'état de la chaussée, quelle que soit la limite affichée"],
       e:"Une limite affichée vaut pour une chaussée dégagée et sèche. Sur la neige, la vitesse sécuritaire est celle qui vous permet d'arrêter dans la distance que vous voyez, souvent bien en deçà du chiffre du panneau." },
  c:3 },
{ id:"nlr23", sec:"rules", topic:"safe",
  en:{ q:"You are on the paved Trans-Canada Highway in this province and no speed sign is posted. What limit applies?",
       a:["100 km/h","90 km/h","80 km/h","110 km/h"],
       e:"Where nothing is posted on the paved Trans-Canada, the limit is 100 km/h. A default is not a target: fog, rain and moose all call for less." },
  fr:{ q:"Vous roulez sur la route Transcanadienne revêtue dans la province et aucun panneau de vitesse n'est affiché. Quelle limite s'applique ?",
       a:["100 km/h","90 km/h","80 km/h","110 km/h"],
       e:"Là où rien n'est affiché sur la Transcanadienne revêtue, la limite est de 100 km/h. Une limite par défaut n'est pas un objectif : le brouillard, la pluie et les orignaux commandent moins." },
  c:0 },
{ id:"nlr24", sec:"rules", topic:"safe",
  en:{ q:"No speed sign is posted on a paved highway that is not the Trans-Canada. What limit applies?",
       a:["60 km/h","80 km/h","90 km/h","100 km/h"],
       e:"Other paved highways fall back to 80 km/h. Once the road runs through a community, the default drops again, to 50 km/h." },
  fr:{ q:"Aucun panneau de vitesse n'est affiché sur une route revêtue qui n'est pas la Transcanadienne. Quelle limite s'applique ?",
       a:["60 km/h","80 km/h","90 km/h","100 km/h"],
       e:"Les autres routes revêtues reviennent à 80 km/h. Dès que la route traverse une localité, la limite par défaut descend encore, à 50 km/h." },
  c:1 },
{ id:"nlr25", sec:"rules", topic:"safe",
  en:{ q:"You turn onto a gravel road with no speed sign anywhere along it. What limit applies?",
       a:["40 km/h","50 km/h","60 km/h","80 km/h, the same as a paved highway"],
       e:"Gravel roads in this province fall back to 60 km/h, lower than the paved default for good reason: less grip, longer stopping distances, and stones thrown at whatever is behind you." },
  fr:{ q:"Vous vous engagez sur un chemin de gravier sans aucun panneau de vitesse sur tout son parcours. Quelle limite s'applique ?",
       a:["40 km/h","50 km/h","60 km/h","80 km/h, comme sur une route revêtue"],
       e:"Les chemins de gravier de la province reviennent à 60 km/h, moins que les routes revêtues pour de bonnes raisons : moins d'adhérence, des distances d'arrêt plus longues et des cailloux projetés vers ce qui vous suit." },
  c:2 },
{ id:"nlr26", sec:"rules", topic:"safe",
  en:{ q:"You drive through a school zone that carries no speed sign of its own. What limit applies?",
       a:["30 km/h","20 km/h","40 km/h","50 km/h"],
       e:"An unmarked school zone falls back to 50 km/h here. Where a school zone is signed, the posted figure sits somewhere between 30 and 50, and the sign always wins." },
  fr:{ q:"Vous traversez une zone scolaire qui ne porte aucun panneau de vitesse. Quelle limite s'applique ?",
       a:["30 km/h","20 km/h","40 km/h","50 km/h"],
       e:"Une zone scolaire non signalée revient ici à 50 km/h. Quand une zone scolaire est affichée, le chiffre se situe entre 30 et 50 km/h, et le panneau l'emporte toujours." },
  c:3 },
{ id:"nlr27", sec:"rules", topic:"safe",
  en:{ q:"A school bus ahead of you stops, its red lights flash and the stop arm swings out. What must you do?",
       a:["Stop, and stay stopped until the signals go off and the bus moves away","Pass slowly if no child is visible","Pass on the right","Sound your horn to warn the children"],
       e:"You may not pass a school bus that is stopped with its signals showing, and you must obey the signals of the bus and of its driver. The penalties here are heavy, and a child stepping out from in front of the bus is the reason." },
  fr:{ q:"Un autobus scolaire devant vous s'arrête, ses feux rouges clignotent et le bras d'arrêt se déploie. Que devez-vous faire ?",
       a:["Vous arrêter et rester immobile jusqu'à ce que les signaux cessent et que l'autobus reparte","Dépasser lentement si aucun enfant n'est visible","Dépasser par la droite","Klaxonner pour avertir les enfants"],
       e:"Vous ne pouvez pas dépasser un autobus scolaire arrêté dont les signaux fonctionnent, et vous devez obéir aux signaux de l'autobus comme aux gestes de son conducteur. Les peines sont lourdes ici, et un enfant qui surgit devant l'autobus en est la raison." },
  c:0 },
{ id:"nlr28", sec:"rules", topic:"vehicle",
  en:{ q:"When are studded tires permitted in Newfoundland and Labrador?",
       a:["All year round","Between 1 November and 30 April","Between 1 December and 31 March","Only on gravel roads"],
       e:"The studded tire season runs from the first of November to the end of April under the province's traffic law. Outside that window the studs have to come off." },
  fr:{ q:"Quand les pneus à crampons sont-ils permis à Terre-Neuve-et-Labrador ?",
       a:["Toute l'année","Entre le 1er novembre et le 30 avril","Entre le 1er décembre et le 31 mars","Seulement sur les chemins de gravier"],
       e:"La saison des pneus à crampons va du 1er novembre à la fin d'avril selon la loi routière de la province. En dehors de cette période, les crampons doivent être retirés." },
  c:1 },
{ id:"nlr29", sec:"rules", topic:"vehicle",
  en:{ q:"Spring is late and there is still ice on the roads at the end of April. What should a driver running studded tires do?",
       a:["Leave them on, since the date is only a guideline","Take them off the day the snow stops, whatever the date","Look for a government advisory, because the province has pushed the removal date back in some years","Have a garage certify the tires for summer use"],
       e:"The removal date is set in law, but the province has extended it by public advisory in years when winter held on. Look for the announcement rather than deciding for yourself." },
  fr:{ q:"Le printemps tarde et il reste de la glace sur les routes à la fin d'avril. Que devrait faire un conducteur muni de pneus à crampons ?",
       a:["Les garder, puisque la date n'est qu'une indication","Les retirer le jour où la neige cesse, quelle que soit la date","Chercher un avis du gouvernement, car la province a déjà repoussé la date de retrait certaines années","Faire certifier les pneus par un garage pour l'usage estival"],
       e:"La date de retrait est fixée par la loi, mais la province l'a repoussée par avis public durant des années où l'hiver s'est prolongé. Cherchez l'annonce au lieu de décider vous-même." },
  c:2 },
{ id:"nlr30", sec:"rules", topic:"vehicle",
  en:{ q:"What do you have to produce for your road test in this province?",
       a:["A vehicle borrowed from the examination centre","A doctor's note about your eyesight","A passenger holding a full licence to sit in the back","Your permit, proof of insurance, a valid registration, the Novice Driver sign, a vehicle in safe working order and your paid receipt"],
       e:"The examiner checks the paperwork and the vehicle before the drive begins, and the road test fee is paid through the province's online service in advance of the appointment. A vehicle that fails the check ends the appointment before it starts." },
  fr:{ q:"Que devez-vous fournir pour votre examen sur route dans la province ?",
       a:["Un véhicule emprunté au centre d'examen","Un billet du médecin au sujet de votre vue","Un passager titulaire d'un permis complet assis à l'arrière","Votre permis, une preuve d'assurance, un certificat d'immatriculation valide, le panneau NOVICE DRIVER, un véhicule en bon état de marche et votre reçu de paiement"],
       e:"L'examinateur vérifie les documents et le véhicule avant le départ, et les frais de l'examen sur route se paient à l'avance par le service en ligne de la province. Un véhicule qui échoue à la vérification met fin au rendez-vous avant qu'il ne commence." },
  c:3 }
);


/* ---------------------------------------------------------------------------
   Whose numbers these are. The 85% pass mark below is Newfoundland and
   Labrador's own published figure: the province states it on its licensing
   pages and in the Driver's Handbook. The question count and the timer are
   OURS, a practice standard, because the province publishes neither. It says
   only that the test covers the rules of the road, safe driving practices and
   road sign recognition. We ask 40 questions and require 34, which is 85%
   exactly, and each half is 20 questions with 17 to pass, so the arithmetic
   holds whichever way it is cut. The 40 minutes is ours too: no official time
   limit for this test is published anywhere.
   Commercial practice sites do state a question count, and one of them states
   a different pass mark (80%), neither citing any source. We are not repeating
   a number that decides whether somebody books a government test.
   --------------------------------------------------------------------------- */
window.CQ_PROVINCE = {
  code: "NL",
  name: { en: "Newfoundland and Labrador", fr: "Terre-Neuve-et-Labrador" },
  licence: "Class 5 Level I",
  minutes: 40,
  sections: [
    { id: "signs", ask: 20, pass: 17,
      name: { en: "Road Sign Recognition",
              fr: "Reconnaissance des panneaux routiers" } },
    { id: "rules", ask: 20, pass: 17,
      name: { en: "Rules of the Road and Safe Driving",
              fr: "Code de la route et conduite sécuritaire" } }
  ],
  handbook: { en: "Driver's Handbook", fr: "Manuel du conducteur" },
  handbookUrl: "https://www.gov.nl.ca/motorregistration/new-drivers/road-user-guide/",
  bookingUrl: "https://www.gov.nl.ca/motorregistration/new-drivers/written-tests/",
  topics: [
    { id:"licensing",  en:"Graduated Licensing",           fr:"Permis par étapes" },
    { id:"licence",    en:"Your Licence and the Test",     fr:"Votre permis et l'examen" },
    { id:"orv",        en:"Off-Road Vehicles and Highways", fr:"Véhicules hors route et routes" },
    { id:"wildlife",   en:"Moose and Wildlife",            fr:"Orignaux et faune" },
    { id:"conditions", en:"Winter and Road Conditions",    fr:"Hiver et état des routes" },
    { id:"safe",       en:"Safe and Responsible Driving",  fr:"Conduite sécuritaire et responsable" },
    { id:"vehicle",    en:"Your Vehicle",                  fr:"Votre véhicule" }
  ],
  questions: window.CQ_DRIVE_Q
};
