/* canada-quiz.com — NOVA SCOTIA Class 7 Learner practice data
   60 original bilingual questions (30 road signs + 30 rules of the road).
   Written in our own words from the free Nova Scotia Driver's Handbook and the
   Registry of Motor Vehicles pages on novascotia.ca.
   Not affiliated with Access Nova Scotia or the Government of Nova Scotia.

   The quiz code lives in js/driving-engine.js and never changes per province. */
window.CQ_DRIVE_Q = [];

/* ---------- road signs ---------- */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"nss1", sec:"signs", sign:"stop",
  en:{ q:"What must you do at this sign?",
       a:["Come to a complete stop, then go when it is safe","Slow down and keep rolling","Stop only if another car is coming","Sound your horn and continue"],
       e:"A full stop means the wheels stop turning. Stop at the line, or before the crosswalk if there is no line, then move off when the way is clear." },
  fr:{ q:"Que devez-vous faire à ce panneau ?",
       a:["Faire un arrêt complet, puis avancer quand c'est sécuritaire","Ralentir et continuer à rouler","Vous arrêter seulement si une autre voiture arrive","Klaxonner et continuer"],
       e:"Un arrêt complet signifie que les roues cessent de tourner. Arrêtez-vous à la ligne, ou avant le passage pour piétons s'il n'y a pas de ligne, puis repartez quand la voie est libre." },
  c:0 },
{ id:"nss2", sec:"signs", sign:"yield",
  en:{ q:"What does a yield sign ask of you?",
       a:["Let traffic and pedestrians already there go first","Stop every time","Speed up to merge","Turn right only"],
       e:"Yield means give way. Slow down, be ready to stop, and only go when you will not force anybody else to brake or swerve." },
  fr:{ q:"Que vous demande un panneau de cession de passage ?",
       a:["Laisser passer d'abord la circulation et les piétons déjà là","Vous arrêter chaque fois","Accélérer pour vous insérer","Tourner à droite seulement"],
       e:"Céder le passage veut dire laisser passer. Ralentissez, soyez prêt à arrêter, et n'avancez que si personne n'est forcé de freiner ou de faire un écart." },
  c:0 },
{ id:"nss3", sec:"signs", sign:"no-entry",
  en:{ q:"You see this sign at the mouth of a street. What does it mean?",
       a:["Do not enter, traffic comes the other way","Entry allowed after 6 p.m.","Trucks only","Parking area ahead"],
       e:"This is a one-way street facing you. Entering it puts you head-on against traffic, which is one of the most dangerous mistakes a new driver makes." },
  fr:{ q:"Vous voyez ce panneau à l'entrée d'une rue. Que signifie-t-il ?",
       a:["Entrée interdite, la circulation vient en sens inverse","Entrée permise après 18 h","Camions seulement","Aire de stationnement devant"],
       e:"C'est une rue à sens unique qui vient vers vous. Y entrer vous met face à la circulation, l'une des erreurs les plus dangereuses d'un nouveau conducteur." },
  c:0 },
{ id:"nss4", sec:"signs", sign:"one-way",
  en:{ q:"What is this sign telling you?",
       a:["Traffic on this street moves in the direction of the arrow only","You may drive either way","The road ends","Passing is allowed"],
       e:"One way. Every lane goes the same direction, so when you turn onto it you must end up going the way the arrow points." },
  fr:{ q:"Que vous indique ce panneau ?",
       a:["La circulation sur cette rue se fait seulement dans le sens de la flèche","Vous pouvez circuler dans les deux sens","La route se termine","Le dépassement est permis"],
       e:"Sens unique. Toutes les voies vont dans la même direction : quand vous y tournez, vous devez repartir dans le sens de la flèche." },
  c:0 },
{ id:"nss5", sec:"signs", sign:"no-u-turn",
  en:{ q:"What does this sign forbid?",
       a:["Turning around to go back the other way","Turning left","Stopping","Passing"],
       e:"No U-turn. Turning around here is banned because drivers coming towards you cannot see you doing it in time." },
  fr:{ q:"Qu'interdit ce panneau ?",
       a:["Faire demi-tour pour repartir en sens inverse","Tourner à gauche","Vous arrêter","Dépasser"],
       e:"Demi-tour interdit. Faire demi-tour ici est défendu parce que les conducteurs venant vers vous ne peuvent pas vous voir à temps." },
  c:0 },
{ id:"nss6", sec:"signs", sign:"no-passing",
  en:{ q:"What does this sign mean?",
       a:["Do not pass another vehicle here","No parking","No trucks","No turning"],
       e:"Passing is banned on this stretch, usually because you cannot see far enough ahead to get back in safely." },
  fr:{ q:"Que signifie ce panneau ?",
       a:["Ne dépassez aucun véhicule ici","Stationnement interdit","Camions interdits","Virage interdit"],
       e:"Le dépassement est interdit sur ce tronçon, généralement parce que vous ne voyez pas assez loin devant pour vous rabattre en sécurité." },
  c:0 },
{ id:"nss7", sec:"signs", sign:"keep-right",
  en:{ q:"What must you do when you see this sign?",
       a:["Pass to the right of the island or obstacle","Stop and wait","Pass on either side","Turn around"],
       e:"Keep right. There is something in the road ahead — an island, a median, a work area — and your side of it is the right side." },
  fr:{ q:"Que devez-vous faire en voyant ce panneau ?",
       a:["Passer à droite de l'îlot ou de l'obstacle","Vous arrêter et attendre","Passer d'un côté ou de l'autre","Faire demi-tour"],
       e:"Tenez la droite. Il y a quelque chose sur la route devant — un îlot, un terre-plein, une zone de travaux — et votre côté est la droite." },
  c:0 },
{ id:"nss8", sec:"signs", sign:"no-stopping",
  en:{ q:"What is not allowed where this sign is posted?",
       a:["Stopping at all, even for a moment","Parking overnight only","Loading passengers only","Nothing, it is a warning"],
       e:"No stopping is the strictest of the three. You may not stop for any reason, including to let somebody out. No parking and no standing are less strict than this." },
  fr:{ q:"Qu'est-ce qui est interdit là où ce panneau est affiché ?",
       a:["S'arrêter, même un instant","Stationner la nuit seulement","Faire monter des passagers seulement","Rien, c'est un avertissement"],
       e:"L'arrêt interdit est le plus strict des trois. Vous ne pouvez vous arrêter pour aucune raison, même pour laisser descendre quelqu'un. Stationnement interdit et immobilisation interdite sont moins stricts." },
  c:0 },
{ id:"nss9", sec:"signs", sign:"no-parking",
  en:{ q:"What does this sign allow you to do?",
       a:["Stop briefly to let someone in or out, but not park","Park for up to an hour","Nothing at all","Park only at night"],
       e:"No parking still lets you stop for a moment while somebody gets in or out. If it said no stopping, even that would be banned." },
  fr:{ q:"Que vous permet ce panneau ?",
       a:["Vous arrêter brièvement pour faire monter ou descendre quelqu'un, mais pas stationner","Stationner jusqu'à une heure","Rien du tout","Stationner seulement la nuit"],
       e:"Le stationnement interdit permet encore de s'arrêter un instant pour faire monter ou descendre quelqu'un. Si le panneau disait arrêt interdit, même cela serait défendu." },
  c:0 },
{ id:"nss10", sec:"signs", sign:"hov-lane",
  en:{ q:"Who may use the lane marked by this sign?",
       a:["Vehicles carrying the number of people shown, and buses","Anyone in a hurry","Trucks only","Nobody, it is closed"],
       e:"A high-occupancy vehicle lane is for vehicles carrying at least the posted number of people. Driving alone in it is an offence." },
  fr:{ q:"Qui peut utiliser la voie indiquée par ce panneau ?",
       a:["Les véhicules transportant le nombre de personnes indiqué, et les autobus","N'importe qui étant pressé","Les camions seulement","Personne, elle est fermée"],
       e:"Une voie réservée au covoiturage est destinée aux véhicules transportant au moins le nombre de personnes affiché. Y rouler seul est une infraction." },
  c:0 },
{ id:"nss11", sec:"signs", sign:"ped-crossover",
  en:{ q:"What must you do at a marked pedestrian crossover?",
       a:["Stop and let people cross the whole way, then go","Sound your horn","Drive around them","Speed up before they step out"],
       e:"Stop and wait. Do not creep forward behind somebody who is still crossing, and never pass another vehicle stopped at a crossover — there is a person you cannot see." },
  fr:{ q:"Que devez-vous faire à un passage pour piétons marqué ?",
       a:["Vous arrêter et laisser les gens traverser complètement, puis repartir","Klaxonner","Les contourner","Accélérer avant qu'ils s'engagent"],
       e:"Arrêtez-vous et attendez. N'avancez pas derrière une personne qui traverse encore, et ne dépassez jamais un véhicule arrêté à un passage : il y a quelqu'un que vous ne voyez pas." },
  c:0 },
{ id:"nss12", sec:"signs", sign:"stop-school-bus",
  en:{ q:"A school bus has its red lights flashing. What must you do in Nova Scotia?",
       a:["Stop, whichever direction you are coming from, even on a divided highway","Stop only if you are behind it","Slow to 30 km/h and pass","Nothing, if there is a median"],
       e:"Nova Scotia is stricter than most provinces here. Traffic stops from both directions, and there is no exception for a divided highway or a boulevard. Wait until the red lights stop flashing." },
  fr:{ q:"Un autobus scolaire fait clignoter ses feux rouges. Que devez-vous faire en Nouvelle-Écosse ?",
       a:["Vous arrêter, peu importe votre sens, même sur une route divisée","Vous arrêter seulement si vous êtes derrière","Ralentir à 30 km/h et dépasser","Rien, s'il y a un terre-plein"],
       e:"La Nouvelle-Écosse est plus stricte que la plupart des provinces ici. La circulation s'arrête dans les deux sens, et il n'y a aucune exception pour une route divisée ou un boulevard. Attendez que les feux rouges cessent de clignoter." },
  c:0 },
{ id:"nss13", sec:"signs", sign:"warn-school-bus",
  en:{ q:"What is this yellow sign warning you about?",
       a:["A school bus stop is ahead","A school is closed","Buses are banned","A bus terminal"],
       e:"A school bus stop ahead. Expect a bus to be stopped with children getting on or off, often just over a rise or around a bend." },
  fr:{ q:"De quoi ce panneau jaune vous avertit-il ?",
       a:["Un arrêt d'autobus scolaire se trouve devant","Une école est fermée","Les autobus sont interdits","Un terminus d'autobus"],
       e:"Un arrêt d'autobus scolaire devant. Attendez-vous à un autobus arrêté avec des enfants qui montent ou descendent, souvent juste après une butte ou une courbe." },
  c:0 },
{ id:"nss14", sec:"signs", sign:"community-safety-zone",
  en:{ q:"What is different inside a zone marked by this sign?",
       a:["Fines for driving offences are higher","The speed limit is always 30 km/h","Parking is free","Only local traffic may enter"],
       e:"This is an area where extra care is expected, usually near a school or a park, and the penalties for offences committed inside it are increased." },
  fr:{ q:"Qu'est-ce qui change dans une zone indiquée par ce panneau ?",
       a:["Les amendes pour les infractions sont plus élevées","La limite est toujours de 30 km/h","Le stationnement est gratuit","Seule la circulation locale peut entrer"],
       e:"C'est une zone où l'on attend une prudence accrue, souvent près d'une école ou d'un parc, et les peines pour les infractions commises à l'intérieur sont augmentées." },
  c:0 },
{ id:"nss15", sec:"signs", sign:"speed-limit-begins",
  en:{ q:"What does this sign tell you?",
       a:["A new speed limit starts here","The speed limit ended","A speed camera is ahead","Slow vehicles must exit"],
       e:"The posted limit changes from this point. It is not advice: the new number applies as soon as you pass the sign." },
  fr:{ q:"Que vous indique ce panneau ?",
       a:["Une nouvelle limite de vitesse commence ici","La limite de vitesse est terminée","Un radar photo est devant","Les véhicules lents doivent sortir"],
       e:"La limite affichée change à partir d'ici. Ce n'est pas un conseil : le nouveau chiffre s'applique dès que vous dépassez le panneau." },
  c:0 },
{ id:"nss16", sec:"signs", sign:"warn-slippery",
  en:{ q:"What does this yellow diamond warn about?",
       a:["The road may be slippery when wet","A car wash ahead","Loose gravel","A steep hill"],
       e:"Slippery when wet. Ease off the accelerator, avoid sudden steering, and leave far more room than usual." },
  fr:{ q:"De quoi ce losange jaune avertit-il ?",
       a:["La chaussée peut être glissante quand elle est mouillée","Un lave-auto devant","Du gravier meuble","Une pente raide"],
       e:"Chaussée glissante par temps humide. Relâchez l'accélérateur, évitez les coups de volant et laissez bien plus d'espace que d'habitude." },
  c:0 },
{ id:"nss17", sec:"signs", sign:"warn-narrow-bridge",
  en:{ q:"What is ahead?",
       a:["A bridge narrower than the road you are on","A bridge that is closed","A weight limit","A tunnel"],
       e:"The bridge is narrower than the road. Slow down, check for oncoming traffic, and do not try to pass on it." },
  fr:{ q:"Qu'y a-t-il devant ?",
       a:["Un pont plus étroit que la route où vous êtes","Un pont fermé","Une limite de poids","Un tunnel"],
       e:"Le pont est plus étroit que la route. Ralentissez, vérifiez la circulation en sens inverse et n'essayez pas d'y dépasser." },
  c:0 },
{ id:"nss18", sec:"signs", sign:"warn-two-way",
  en:{ q:"What does this sign mean?",
       a:["Traffic now comes towards you as well","The road becomes one way","Two lanes join","A passing lane starts"],
       e:"Two-way traffic ahead. A divided road is ending, so from here there is oncoming traffic on the other side of the line." },
  fr:{ q:"Que signifie ce panneau ?",
       a:["La circulation vient maintenant aussi vers vous","La route devient à sens unique","Deux voies se rejoignent","Une voie de dépassement commence"],
       e:"Circulation dans les deux sens devant. Une route divisée se termine : à partir d'ici, il y a des véhicules en sens inverse de l'autre côté de la ligne." },
  c:0 },
{ id:"nss19", sec:"signs", sign:"warn-merge",
  en:{ q:"What should you do when you see this sign?",
       a:["Expect traffic joining, and adjust your speed or lane","Stop and wait","Speed up so nobody gets in front","Turn right"],
       e:"Traffic is joining from the side. Merging works when both drivers adjust: match speeds and leave a gap rather than racing for the same space." },
  fr:{ q:"Que devriez-vous faire en voyant ce panneau ?",
       a:["Vous attendre à de la circulation qui s'insère et ajuster votre vitesse ou votre voie","Vous arrêter et attendre","Accélérer pour que personne ne passe devant","Tourner à droite"],
       e:"De la circulation s'insère depuis le côté. L'insertion fonctionne quand les deux conducteurs s'ajustent : accordez les vitesses et laissez un espace plutôt que de vous disputer la même place." },
  c:0 },
{ id:"nss20", sec:"signs", sign:"warn-divided-begins",
  en:{ q:"What is starting ahead?",
       a:["A divided road with a median between directions","A tunnel","A toll section","A gravel road"],
       e:"A divided highway begins. Traffic going the other way is now separated from you by a median." },
  fr:{ q:"Qu'est-ce qui commence devant ?",
       a:["Une route divisée avec un terre-plein entre les sens","Un tunnel","Une section à péage","Une route de gravier"],
       e:"Une route divisée commence. La circulation en sens inverse est désormais séparée de vous par un terre-plein." },
  c:0 },
{ id:"nss21", sec:"signs", sign:"warn-divided-ends",
  en:{ q:"What is about to happen?",
       a:["The divided road ends and traffic comes towards you again","The road widens","A rest area begins","The speed limit rises"],
       e:"The median is ending. This is a common place for head-on collisions because drivers keep left out of habit." },
  fr:{ q:"Que va-t-il se passer ?",
       a:["La route divisée se termine et la circulation revient vers vous","La route s'élargit","Une halte routière commence","La limite de vitesse augmente"],
       e:"Le terre-plein se termine. C'est un endroit fréquent de collisions frontales, parce que des conducteurs restent à gauche par habitude." },
  c:0 },
{ id:"nss22", sec:"signs", sign:"warn-stop-ahead",
  en:{ q:"Why does this sign exist?",
       a:["A stop sign is coming that you may not see in time","You must stop here","Traffic lights ahead","The road is closed"],
       e:"It gives you room to slow down for a stop sign hidden by a hill, a bend or trees." },
  fr:{ q:"Pourquoi ce panneau existe-t-il ?",
       a:["Un arrêt approche et vous pourriez ne pas le voir à temps","Vous devez vous arrêter ici","Des feux de circulation devant","La route est fermée"],
       e:"Il vous donne de l'espace pour ralentir avant un arrêt caché par une butte, une courbe ou des arbres." },
  c:0 },
{ id:"nss23", sec:"signs", sign:"warn-moose",
  en:{ q:"You see this sign on a Nova Scotia highway at dusk. What should you do?",
       a:["Slow down and scan both shoulders","Sound your horn continuously","Speed up to get past the area","Drive on the shoulder"],
       e:"A moose stands so tall that in a collision the bumper takes its legs and the body comes through the windscreen. Dawn and dusk are the worst times." },
  fr:{ q:"Vous voyez ce panneau sur une route de la Nouvelle-Écosse au crépuscule. Que devriez-vous faire ?",
       a:["Ralentir et surveiller les deux accotements","Klaxonner sans arrêt","Accélérer pour sortir de la zone","Rouler sur l'accotement"],
       e:"L'orignal est si haut qu'en cas de collision le pare-chocs lui prend les pattes et le corps traverse le pare-brise. L'aube et le crépuscule sont les pires moments." },
  c:0 },
{ id:"nss24", sec:"signs", sign:"warn-deer",
  en:{ q:"What should you expect where this sign is posted?",
       a:["Deer crossing, often more than one","A petting zoo","A hunting area","A farm entrance"],
       e:"Deer rarely travel alone. If one crosses in front of you, slow right down and expect another behind it." },
  fr:{ q:"À quoi devez-vous vous attendre là où ce panneau est affiché ?",
       a:["Une traversée de chevreuils, souvent plus d'un","Un zoo pour enfants","Une zone de chasse","Une entrée de ferme"],
       e:"Les chevreuils voyagent rarement seuls. Si l'un traverse devant vous, ralentissez fortement et attendez-vous à un autre derrière." },
  c:0 },
{ id:"nss25", sec:"signs", sign:"warn-crossbuck",
  en:{ q:"What does this X-shaped sign mark?",
       a:["A railway crossing","A crossroads","A hospital","A dead end"],
       e:"A railway crossing. Look both ways, and never start across unless you can clear the whole crossing without stopping." },
  fr:{ q:"Que marque ce panneau en forme de X ?",
       a:["Un passage à niveau","Un carrefour","Un hôpital","Un cul-de-sac"],
       e:"Un passage à niveau. Regardez des deux côtés et ne vous engagez jamais si vous ne pouvez pas dégager tout le passage sans arrêter." },
  c:0 },
{ id:"nss26", sec:"signs", sign:"warn-roundabout",
  en:{ q:"How do you drive through a roundabout?",
       a:["Yield to traffic already in it, then go around to the right","Stop at the entrance every time","Go left around the circle","Take the first exit always"],
       e:"Yield on entry to whoever is already going round, then travel to the right, around the circle, and signal before your exit." },
  fr:{ q:"Comment traverser un carrefour giratoire ?",
       a:["Céder le passage à ceux qui y circulent déjà, puis contourner par la droite","Vous arrêter à l'entrée chaque fois","Tourner à gauche autour du cercle","Prendre toujours la première sortie"],
       e:"Cédez le passage à l'entrée à ceux qui y circulent déjà, puis contournez par la droite et signalez avant votre sortie." },
  c:0 },
{ id:"nss27", sec:"signs", sign:"warn-checkerboard",
  en:{ q:"What is this black and yellow checkerboard telling you?",
       a:["The road ends or turns sharply here","A construction zone","A taxi stand","A speed change"],
       e:"The road you are on does not continue straight. Slow down well before it, because it is placed where drivers are most likely to keep going." },
  fr:{ q:"Que vous indique ce damier noir et jaune ?",
       a:["La route se termine ou tourne brusquement ici","Une zone de construction","Une station de taxis","Un changement de vitesse"],
       e:"La route sur laquelle vous êtes ne continue pas tout droit. Ralentissez bien avant, car ce panneau est placé là où les conducteurs risquent le plus de continuer." },
  c:0 },
{ id:"nss28", sec:"signs", sign:"warn-chevron",
  en:{ q:"What do a line of these arrow signs mark?",
       a:["The direction a sharp curve goes","The edge of the province","A passing lane","A bus route"],
       e:"Chevrons follow the outside of a bend and show you where the road goes when the headlights cannot." },
  fr:{ q:"Que marque une série de ces panneaux à flèche ?",
       a:["Le sens d'une courbe prononcée","La limite de la province","Une voie de dépassement","Un circuit d'autobus"],
       e:"Les chevrons suivent l'extérieur d'une courbe et vous montrent où va la route quand les phares ne le peuvent pas." },
  c:0 },
{ id:"nss29", sec:"signs", sign:"temp-flagger",
  en:{ q:"You see this orange sign, then a person holding a sign in the road. What must you do?",
       a:["Obey the flagger, even over a traffic light or sign","Ignore them and follow the signs","Drive around them","Stop and wait for the police"],
       e:"A traffic control person at a work zone directs you, and their instruction comes before the ordinary signs and signals." },
  fr:{ q:"Vous voyez ce panneau orange, puis une personne tenant un panneau sur la route. Que devez-vous faire ?",
       a:["Obéir au signaleur, même avant un feu ou un panneau","L'ignorer et suivre les panneaux","La contourner","Vous arrêter et attendre la police"],
       e:"Un signaleur dans une zone de travaux vous dirige, et son instruction passe avant les panneaux et les feux ordinaires." },
  c:0 },
{ id:"nss30", sec:"signs", sign:"mark-solid-yellow",
  en:{ q:"What does a solid yellow line beside your lane mean?",
       a:["Do not cross it to pass","Passing is allowed","Parking is allowed","The lane is closed"],
       e:"Solid means do not cross to pass. A broken yellow line on your side means passing is allowed when the way is clear." },
  fr:{ q:"Que signifie une ligne jaune continue à côté de votre voie ?",
       a:["Ne la franchissez pas pour dépasser","Le dépassement est permis","Le stationnement est permis","La voie est fermée"],
       e:"Continue veut dire qu'on ne la franchit pas pour dépasser. Une ligne jaune discontinue de votre côté signifie que le dépassement est permis quand la voie est libre." },
  c:0 }
);

/* ---------- rules of the road ---------- */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"nsr1", sec:"rules", topic:"licensing",
  en:{ q:"What is the first stage of Nova Scotia's graduated licensing programme called?",
       a:["The Learner's Licence, Class 7","The Newly Licensed Driver's Licence","The Restricted Individual licence","A full Class 5 licence"],
       e:"Nova Scotia has three stages before a full licence: Learner's Licence (Class 7), then Newly Licensed Driver, then Restricted Individual with Condition 47." },
  fr:{ q:"Comment s'appelle la première étape du programme de permis par étapes de la Nouvelle-Écosse ?",
       a:["Le permis d'apprenti, classe 7","Le permis de conducteur nouvellement titulaire","Le permis de conducteur restreint","Un permis complet de classe 5"],
       e:"La Nouvelle-Écosse compte trois étapes avant le permis complet : le permis d'apprenti (classe 7), puis le permis de conducteur nouvellement titulaire, puis le conducteur restreint avec la condition 47." },
  c:0 },
{ id:"nsr2", sec:"rules", topic:"licensing",
  en:{ q:"What is the youngest age you can get a Nova Scotia learner's licence?",
       a:["16","14","18","21"],
       e:"Sixteen. If you are 16 or 17 you also need a parent or guardian to sign the application." },
  fr:{ q:"Quel est l'âge minimal pour obtenir un permis d'apprenti en Nouvelle-Écosse ?",
       a:["16 ans","14 ans","18 ans","21 ans"],
       e:"Seize ans. À 16 ou 17 ans, il faut aussi la signature d'un parent ou tuteur sur la demande." },
  c:0 },
{ id:"nsr3", sec:"rules", topic:"test",
  en:{ q:"How is the Nova Scotia knowledge test organised?",
       a:["Two tests: Rules of the Road and Road Sign Recognition","One long test","Three tests","A spoken interview only"],
       e:"Two separate tests. Each has 20 multiple-choice questions and you need 16 right on each one, with 30 minutes for each." },
  fr:{ q:"Comment l'examen théorique de la Nouvelle-Écosse est-il organisé ?",
       a:["Deux examens : le code de la route et la reconnaissance des panneaux","Un seul long examen","Trois examens","Un entretien oral seulement"],
       e:"Deux examens distincts. Chacun compte 20 questions à choix multiple et il faut 16 bonnes réponses à chacun, avec 30 minutes par examen." },
  c:0 },
{ id:"nsr4", sec:"rules", topic:"test",
  en:{ q:"How many questions must you get right on each part of the Nova Scotia test?",
       a:["16 out of 20","10 out of 20","20 out of 20","12 out of 20"],
       e:"Sixteen out of twenty on each part, which is eighty percent. You can only afford four mistakes on each side." },
  fr:{ q:"Combien de bonnes réponses faut-il à chaque partie de l'examen néo-écossais ?",
       a:["16 sur 20","10 sur 20","20 sur 20","12 sur 20"],
       e:"Seize sur vingt à chaque partie, soit quatre-vingts pour cent. Vous ne pouvez vous permettre que quatre erreurs de chaque côté." },
  c:0 },
{ id:"nsr5", sec:"rules", topic:"test",
  en:{ q:"How long do you get for each part of the knowledge test?",
       a:["30 minutes","10 minutes","2 hours","There is no time limit"],
       e:"Thirty minutes for each part. Most people finish well inside that, but the clock is real, so do not linger on one question." },
  fr:{ q:"Combien de temps avez-vous pour chaque partie de l'examen théorique ?",
       a:["30 minutes","10 minutes","2 heures","Il n'y a pas de limite"],
       e:"Trente minutes par partie. La plupart des gens terminent bien avant, mais le chronomètre est réel : ne restez pas bloqué sur une question." },
  c:0 },
{ id:"nsr6", sec:"rules", topic:"test",
  en:{ q:"Where can you take the Nova Scotia knowledge test?",
       a:["Online with a webcam, or in person at Access Nova Scotia","Only in person","Only online","At any driving school"],
       e:"Both. The online test needs a desktop or laptop with a webcam, not a phone or tablet. In person, you go to Access Nova Scotia or a Registry of Motor Vehicles office." },
  fr:{ q:"Où pouvez-vous passer l'examen théorique en Nouvelle-Écosse ?",
       a:["En ligne avec une caméra, ou en personne à Access Nova Scotia","En personne seulement","En ligne seulement","Dans n'importe quelle école de conduite"],
       e:"Les deux. L'examen en ligne exige un ordinateur de bureau ou portable avec caméra, pas un téléphone ni une tablette. En personne, on se rend à Access Nova Scotia ou à un bureau du Registre des véhicules automobiles." },
  c:0 },
{ id:"nsr7", sec:"rules", topic:"test",
  en:{ q:"You fail the test at an office. When can you try again?",
       a:["The next day","The same hour","After one month","After one year"],
       e:"In person you wait until the next day. If you take it online there is no waiting period before you try again, but you pay again either way." },
  fr:{ q:"Vous échouez à l'examen dans un bureau. Quand pouvez-vous réessayer ?",
       a:["Le lendemain","La même heure","Après un mois","Après un an"],
       e:"En personne, vous attendez au lendemain. En ligne, il n'y a aucun délai d'attente avant de réessayer, mais vous payez de nouveau dans les deux cas." },
  c:0 },
{ id:"nsr8", sec:"rules", topic:"test",
  en:{ q:"What is checked besides your knowledge before you are given a learner's licence?",
       a:["Your eyesight","Your typing speed","Your school marks","Your height"],
       e:"A vision test. Nova Scotia checks colour perception, a field of vision of at least 120 degrees, and visual acuity of at least 6/12." },
  fr:{ q:"Qu'est-ce qui est vérifié en plus de vos connaissances avant l'obtention d'un permis d'apprenti ?",
       a:["Votre vue","Votre vitesse de frappe","Vos notes scolaires","Votre taille"],
       e:"Un examen de la vue. La Nouvelle-Écosse vérifie la perception des couleurs, un champ de vision d'au moins 120 degrés et une acuité visuelle d'au moins 6/12." },
  c:0 },
{ id:"nsr9", sec:"rules", topic:"licensing",
  en:{ q:"How long must you normally hold the learner's licence before the road test?",
       a:["12 months, or 9 with an approved driver-training course","3 months","6 months always","24 months"],
       e:"Twelve full months, or nine if you complete an approved driver-training course. An older rule said six months; that changed in 2016." },
  fr:{ q:"Combien de temps faut-il normalement détenir le permis d'apprenti avant l'examen pratique ?",
       a:["12 mois, ou 9 avec un cours de conduite reconnu","3 mois","6 mois toujours","24 mois"],
       e:"Douze mois complets, ou neuf avec un cours de conduite reconnu. Une ancienne règle parlait de six mois ; cela a changé en 2016." },
  c:0 },
{ id:"nsr10", sec:"rules", topic:"licensing",
  en:{ q:"How much alcohol may a driver in the graduated programme have?",
       a:["None at all","Under .05","Under .08","One drink only"],
       e:"Zero, and it stays zero through all three stages, not only while you are a learner. That is stricter than many provinces." },
  fr:{ q:"Quelle quantité d'alcool un conducteur du programme par étapes peut-il avoir ?",
       a:["Aucune","Moins de 0,05","Moins de 0,08","Une consommation seulement"],
       e:"Zéro, et cela reste zéro pendant les trois étapes, pas seulement comme apprenti. C'est plus strict que dans bien des provinces." },
  c:0 },
{ id:"nsr11", sec:"rules", topic:"licensing",
  en:{ q:"Who may sit beside you while you drive on a learner's licence?",
       a:["A driver with at least two years' experience who is not in the graduated programme","Anyone over 16","Any licensed driver","A friend with a learner's licence"],
       e:"They need a valid licence for the vehicle, at least two years of experience, and they must not be a learner, a newly licensed driver or a restricted individual themselves. They sit in the front passenger seat." },
  fr:{ q:"Qui peut s'asseoir à côté de vous pendant que vous conduisez avec un permis d'apprenti ?",
       a:["Un conducteur ayant au moins deux ans d'expérience et qui n'est pas dans le programme par étapes","N'importe qui de plus de 16 ans","Tout conducteur titulaire d'un permis","Un ami détenant un permis d'apprenti"],
       e:"Il lui faut un permis valide pour le véhicule, au moins deux ans d'expérience, et il ne doit pas être lui-même apprenti, nouvellement titulaire ou conducteur restreint. Il s'assoit à la place du passager avant." },
  c:0 },
{ id:"nsr12", sec:"rules", topic:"licensing",
  en:{ q:"Where must the supervising driver sit?",
       a:["In the front passenger seat","Anywhere in the vehicle","Directly behind you","In another car following you"],
       e:"The front passenger seat, so they can see what you see and reach the wheel or the handbrake if they have to." },
  fr:{ q:"Où doit s'asseoir l'accompagnateur ?",
       a:["À la place du passager avant","N'importe où dans le véhicule","Directement derrière vous","Dans une autre voiture qui vous suit"],
       e:"À la place du passager avant, pour voir ce que vous voyez et pouvoir atteindre le volant ou le frein à main au besoin." },
  c:0 },
{ id:"nsr13", sec:"rules", topic:"licensing",
  en:{ q:"A Newly Licensed Driver has one restriction about time of day. What is it?",
       a:["No driving between midnight and 5 a.m.","No driving before 7 a.m.","No driving on Sundays","No driving after dark at all"],
       e:"No driving between midnight and five in the morning. An exemption can be granted for work, and if you are under 18 a parent must consent to it." },
  fr:{ q:"Un conducteur nouvellement titulaire a une restriction liée à l'heure. Laquelle ?",
       a:["Aucune conduite entre minuit et 5 h","Aucune conduite avant 7 h","Aucune conduite le dimanche","Aucune conduite après la tombée du jour"],
       e:"Aucune conduite entre minuit et cinq heures du matin. Une exemption peut être accordée pour le travail, et si vous avez moins de 18 ans, un parent doit y consentir." },
  c:0 },
{ id:"nsr14", sec:"rules", topic:"licensing",
  en:{ q:"How many demerit points will suspend a learner in Nova Scotia?",
       a:["4 points","10 points","15 points","2 points"],
       e:"Four points brings a six-month suspension for a learner. Two points already brings a warning letter, so the margin is very small." },
  fr:{ q:"Combien de points d'inaptitude entraînent la suspension d'un apprenti en Nouvelle-Écosse ?",
       a:["4 points","10 points","15 points","2 points"],
       e:"Quatre points entraînent une suspension de six mois pour un apprenti. Deux points donnent déjà une lettre d'avertissement : la marge est très mince." },
  c:0 },
{ id:"nsr15", sec:"rules", topic:"safe",
  en:{ q:"What is the default speed limit in a built-up area unless a sign says otherwise?",
       a:["50 km/h","40 km/h","60 km/h","80 km/h"],
       e:"Fifty in business and residential areas. Outside a built-up area the general maximum is eighty unless the road is posted differently." },
  fr:{ q:"Quelle est la limite de vitesse par défaut en zone bâtie, sauf indication contraire ?",
       a:["50 km/h","40 km/h","60 km/h","80 km/h"],
       e:"Cinquante dans les zones commerciales et résidentielles. Hors zone bâtie, le maximum général est de quatre-vingts, sauf affichage différent." },
  c:0 },
{ id:"nsr16", sec:"rules", topic:"safe",
  en:{ q:"The road outside a built-up area has no speed sign. What is the maximum?",
       a:["80 km/h","50 km/h","100 km/h","There is no maximum"],
       e:"Eighty. Where a highway is posted higher, the sign is what counts, so read the signs rather than assuming a number." },
  fr:{ q:"La route hors zone bâtie n'a aucun panneau de vitesse. Quel est le maximum ?",
       a:["80 km/h","50 km/h","100 km/h","Il n'y a pas de maximum"],
       e:"Quatre-vingts. Là où une route affiche plus, c'est le panneau qui compte : lisez les panneaux plutôt que de supposer un chiffre." },
  c:0 },
{ id:"nsr17", sec:"rules", topic:"safe",
  en:{ q:"In a school zone where the approaching limit is 50 km/h, what is the limit when children are present?",
       a:["30 km/h","50 km/h","40 km/h","20 km/h"],
       e:"Thirty. Where the approaching road is posted higher than fifty, the school zone limit is fifty instead." },
  fr:{ q:"Dans une zone scolaire où la limite d'approche est de 50 km/h, quelle est la limite en présence d'enfants ?",
       a:["30 km/h","50 km/h","40 km/h","20 km/h"],
       e:"Trente. Là où la route d'approche affiche plus de cinquante, la limite en zone scolaire est plutôt de cinquante." },
  c:0 },
{ id:"nsr18", sec:"rules", topic:"sharing",
  en:{ q:"You are passing a stopped ambulance with its lights flashing. What speed applies?",
       a:["60 km/h, or the posted limit if it is lower","80 km/h","The normal limit","30 km/h"],
       e:"Slow to sixty, or to the posted limit if that is lower, and move over a lane if there are two or more in your direction and it is safe. The same applies to a tow truck with its lights on." },
  fr:{ q:"Vous dépassez une ambulance immobilisée dont les feux clignotent. Quelle vitesse s'applique ?",
       a:["60 km/h, ou la limite affichée si elle est inférieure","80 km/h","La limite normale","30 km/h"],
       e:"Ralentissez à soixante, ou à la limite affichée si elle est plus basse, et changez de voie s'il y en a deux ou plus dans votre sens et que c'est sécuritaire. Cela vaut aussi pour une dépanneuse dont les feux clignotent." },
  c:0 },
{ id:"nsr19", sec:"rules", topic:"sharing",
  en:{ q:"The emergency vehicle is stopped on the other side of a divided highway. Does the slow-down rule apply?",
       a:["No, not when a median separates you","Yes, always","Only at night","Only if you can see it"],
       e:"Not when there is a median between you. On an undivided road it applies from both directions." },
  fr:{ q:"Le véhicule d'urgence est immobilisé de l'autre côté d'une route divisée. La règle de ralentissement s'applique-t-elle ?",
       a:["Non, pas quand un terre-plein vous sépare","Oui, toujours","Seulement la nuit","Seulement si vous le voyez"],
       e:"Non lorsqu'un terre-plein vous sépare. Sur une route non divisée, elle s'applique dans les deux sens." },
  c:0 },
{ id:"nsr20", sec:"rules", topic:"safe",
  en:{ q:"How much space does the Nova Scotia handbook say to leave behind the vehicle ahead?",
       a:["Two seconds","One car length","Half a second","Ten metres"],
       e:"Two seconds on a good road. Pick a fixed object, and if you reach it before you finish counting, you are too close. On snow or ice you need far more." },
  fr:{ q:"Quel espace le guide de la Nouvelle-Écosse recommande-t-il derrière le véhicule qui précède ?",
       a:["Deux secondes","Une longueur de voiture","Une demi-seconde","Dix mètres"],
       e:"Deux secondes sur une bonne route. Choisissez un point fixe : si vous l'atteignez avant d'avoir fini de compter, vous êtes trop près. Sur la neige ou la glace, il en faut bien plus." },
  c:0 },
{ id:"nsr21", sec:"rules", topic:"safe",
  en:{ q:"What does the law say about a hand-held cellphone while driving?",
       a:["You may not use one, and texting is banned","You may use it at a red light","You may use it below 50 km/h","There is no rule"],
       e:"Hand-held use and texting are banned while driving. A conviction brings four demerit points as well as a fine, and the fines rise steeply for repeat offences." },
  fr:{ q:"Que dit la loi sur le téléphone tenu en main au volant ?",
       a:["Vous ne pouvez pas en utiliser un, et le texto est interdit","Vous pouvez l'utiliser à un feu rouge","Vous pouvez l'utiliser sous 50 km/h","Il n'y a aucune règle"],
       e:"L'usage tenu en main et le texto sont interdits au volant. Une condamnation entraîne quatre points d'inaptitude en plus d'une amende, et les amendes montent rapidement en cas de récidive." },
  c:0 },
{ id:"nsr22", sec:"rules", topic:"safe",
  en:{ q:"Who must wear a seatbelt in Nova Scotia?",
       a:["Everyone aged 16 and over, and the driver is responsible for younger passengers","Only the driver","Only people in the front","Only on the highway"],
       e:"Everyone sixteen and over must wear one where a belt is available, and the driver is responsible for every passenger under sixteen." },
  fr:{ q:"Qui doit porter la ceinture de sécurité en Nouvelle-Écosse ?",
       a:["Toute personne de 16 ans et plus, et le conducteur est responsable des passagers plus jeunes","Seulement le conducteur","Seulement les personnes à l'avant","Seulement sur l'autoroute"],
       e:"Toute personne de seize ans et plus doit la porter là où une ceinture est disponible, et le conducteur est responsable de chaque passager de moins de seize ans." },
  c:0 },
{ id:"nsr23", sec:"rules", topic:"safe",
  en:{ q:"When may a child stop using a booster seat in Nova Scotia?",
       a:["At 145 cm tall or age nine, whichever comes first","At age five","At 20 kg","When they ask to"],
       e:"A booster is used above 18 kg until the child is 145 centimetres tall or nine years old. A seatbelt alone does not sit correctly on a smaller child." },
  fr:{ q:"Quand un enfant peut-il cesser d'utiliser un siège d'appoint en Nouvelle-Écosse ?",
       a:["À 145 cm ou à neuf ans, selon la première éventualité","À cinq ans","À 20 kg","Quand il le demande"],
       e:"Le siège d'appoint s'utilise au-dessus de 18 kg jusqu'à ce que l'enfant atteigne 145 centimètres ou neuf ans. Seule, la ceinture ne se place pas correctement sur un enfant plus petit." },
  c:0 },
{ id:"nsr24", sec:"rules", topic:"safe",
  en:{ q:"Which way should an infant's car seat face?",
       a:["Backwards, until the child outgrows the seat","Forwards from birth","Sideways","It does not matter"],
       e:"Rear-facing, from birth until the child grows past the seat's limit. A rear-facing seat spreads the force of a crash across the whole back and head." },
  fr:{ q:"Dans quel sens doit être orienté le siège d'auto d'un bébé ?",
       a:["Vers l'arrière, jusqu'à ce que l'enfant dépasse la taille du siège","Vers l'avant dès la naissance","De côté","Cela n'a pas d'importance"],
       e:"Dos à la route, de la naissance jusqu'à ce que l'enfant dépasse la limite du siège. Un siège orienté vers l'arrière répartit la force d'un choc sur tout le dos et la tête." },
  c:0 },
{ id:"nsr25", sec:"rules", topic:"sharing",
  en:{ q:"A cyclist is riding in your lane on a narrow Nova Scotia road. What should you do?",
       a:["Stay back and pass only when you can leave plenty of room","Sound your horn to move them","Squeeze past in the same lane","Follow closely so they hurry"],
       e:"A bicycle is a vehicle and has a right to the lane. Wait for room and pass wide. Squeezing past inside the lane is how cyclists get hurt." },
  fr:{ q:"Un cycliste roule dans votre voie sur une route étroite de la Nouvelle-Écosse. Que devriez-vous faire ?",
       a:["Rester derrière et ne dépasser que si vous pouvez laisser beaucoup d'espace","Klaxonner pour le faire bouger","Vous faufiler dans la même voie","Le suivre de près pour qu'il se dépêche"],
       e:"Un vélo est un véhicule et a droit à la voie. Attendez d'avoir de la place et dépassez largement. Se faufiler dans la même voie est ainsi que les cyclistes sont blessés." },
  c:0 },
{ id:"nsr26", sec:"rules", topic:"conditions",
  en:{ q:"Fog is thick on a coastal road. Which lights should you use?",
       a:["Low beams","High beams","Hazard lights while moving","No lights"],
       e:"Low beams. High beams bounce off the fog and make it harder to see, exactly like blowing snow." },
  fr:{ q:"Le brouillard est épais sur une route côtière. Quels feux utiliser ?",
       a:["Les feux de croisement","Les feux de route","Les feux de détresse en roulant","Aucun feu"],
       e:"Les feux de croisement. Les feux de route se reflètent sur le brouillard et réduisent la visibilité, exactement comme dans la poudrerie." },
  c:0 },
{ id:"nsr27", sec:"rules", topic:"conditions",
  en:{ q:"What should you do before driving in winter weather?",
       a:["Clear the glass, lights and mirrors and check the wipers and defroster","Only clear a small hole in the windscreen","Nothing, the heater will do it","Drive slowly with the window open"],
       e:"Clear all the glass, the lights and the mirrors, and make sure wipers, washers and defrosters work. You cannot avoid what you cannot see." },
  fr:{ q:"Que devriez-vous faire avant de conduire par temps hivernal ?",
       a:["Dégager les vitres, les feux et les rétroviseurs, et vérifier les essuie-glaces et le dégivreur","Dégager seulement un petit trou dans le pare-brise","Rien, le chauffage s'en chargera","Rouler lentement avec la fenêtre ouverte"],
       e:"Dégagez toutes les vitres, les feux et les rétroviseurs, et assurez-vous que les essuie-glaces, les lave-glaces et les dégivreurs fonctionnent. On ne peut éviter ce qu'on ne voit pas." },
  c:0 },
{ id:"nsr28", sec:"rules", topic:"vehicle",
  en:{ q:"Your brakes have been through deep water. What should you do?",
       a:["Test them gently at low speed while it is safe","Drive faster to dry them","Nothing, they are fine","Pump the accelerator"],
       e:"Wet brakes grip poorly. Test them lightly at low speed where nobody is behind you, and keep testing until they feel normal again." },
  fr:{ q:"Vos freins ont traversé de l'eau profonde. Que devriez-vous faire ?",
       a:["Les tester doucement à basse vitesse quand c'est sécuritaire","Rouler plus vite pour les sécher","Rien, ils vont bien","Pomper l'accélérateur"],
       e:"Des freins mouillés adhèrent mal. Testez-les légèrement à basse vitesse là où personne ne vous suit, et continuez jusqu'à ce qu'ils redeviennent normaux." },
  c:0 },
{ id:"nsr29", sec:"rules", topic:"collisions",
  en:{ q:"You are in a collision where somebody is hurt. What must you do first?",
       a:["Stop, and call for help","Drive to the nearest garage","Exchange numbers and leave","Move all vehicles immediately"],
       e:"Stop. Leaving the scene of a collision is a serious offence. Call for help, and do not move an injured person unless they are in danger where they are." },
  fr:{ q:"Vous êtes impliqué dans une collision avec des blessés. Que devez-vous faire d'abord ?",
       a:["Vous arrêter et appeler les secours","Vous rendre au garage le plus proche","Échanger les numéros et partir","Déplacer tous les véhicules immédiatement"],
       e:"Arrêtez-vous. Quitter les lieux d'une collision est une infraction grave. Appelez les secours et ne déplacez pas un blessé, sauf s'il est en danger là où il se trouve." },
  c:0 },
{ id:"nsr30", sec:"rules", topic:"collisions",
  en:{ q:"A moose steps onto the highway in front of you. What is the safest response?",
       a:["Brake hard and steer for where the animal came from","Swerve into the oncoming lane","Accelerate past it","Close your eyes and hold the wheel"],
       e:"Brake as hard as you can and aim behind the animal, where it has already been. Swerving into oncoming traffic turns one problem into a worse one." },
  fr:{ q:"Un orignal s'engage sur la route devant vous. Quelle est la réaction la plus sûre ?",
       a:["Freiner fort et viser l'endroit d'où l'animal vient","Faire un écart dans la voie inverse","Accélérer pour le dépasser","Fermer les yeux et tenir le volant"],
       e:"Freinez le plus fort possible et visez derrière l'animal, là où il est déjà passé. Faire un écart dans la circulation inverse transforme un problème en un pire." },
  c:0 }
);


/* ---------------------------------------------------------------------------
   The real Nova Scotia format, as the province publishes it. Unlike Quebec,
   Manitoba and Saskatchewan, nothing below is a standard of ours: novascotia.ca
   states two tests, 20 questions each, 16 right to pass each, 30 minutes each.
   --------------------------------------------------------------------------- */
window.CQ_PROVINCE = {
  code: "NS",
  name: { en: "Nova Scotia", fr: "Nouvelle-\u00c9cosse" },
  licence: "Class 7",
  minutes: 60,
  sections: [
    { id: "signs", ask: 20, pass: 16,
      name: { en: "Road Sign Recognition Test",
              fr: "Examen de reconnaissance des panneaux" } },
    { id: "rules", ask: 20, pass: 16,
      name: { en: "Rules of the Road Test",
              fr: "Examen sur le code de la route" } }
  ],
  handbook: { en: "Nova Scotia Driver's Handbook",
              fr: "Guide du conducteur de la Nouvelle-\u00c9cosse" },
  handbookUrl: "https://novascotia.ca/sns/rmv/handbook/",
  bookingUrl: "https://www.novascotia.ca/take-driver-knowledge-test-learners-licence-class-7",
  topics: [
    { id:"licensing",  en:"Graduated Licensing",         fr:"Permis par \u00e9tapes" },
    { id:"test",       en:"Your Licence and the Test",   fr:"Votre permis et l'examen" },
    { id:"sharing",    en:"Sharing the Road",            fr:"Partager la route" },
    { id:"conditions", en:"Weather and Country Roads",   fr:"M\u00e9t\u00e9o et routes de campagne" },
    { id:"safe",       en:"Safe and Responsible Driving", fr:"Conduite s\u00e9curitaire et responsable" },
    { id:"vehicle",    en:"Your Vehicle",                fr:"Votre v\u00e9hicule" },
    { id:"collisions", en:"Emergencies and Collisions",  fr:"Urgences et collisions" }
  ],
  questions: window.CQ_DRIVE_Q
};
