/* canada-quiz.com — NORTHWEST TERRITORIES Class 7 Learner practice data
   60 original bilingual questions (30 road signs + 30 rules of the road).
   Written in our own words from the free NWT Basic Driver's Manual, the driver
   licensing pages on idmv.inf.gov.nt.ca, the driving safety, bison, winter
   road, school zone and ferry pages on inf.gov.nt.ca, and the Driver's Licence
   Demerit Point Regulations published by GNWT Justice.
   Not affiliated with Driver and Vehicle Services or the Government of the
   Northwest Territories.

   The quiz code lives in js/driving-engine.js and never changes per province. */
window.CQ_DRIVE_Q = [];

/* ---------- road signs ---------- */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"nts1", sec:"signs", sign:"stop",
  en:{ q:"You reach this sign where a gravel road meets a Northwest Territories highway. What does it require?",
       a:["A full stop, then go on only when the way is clear","A slow roll if you can see both ways","A stop only when another vehicle is in sight","A tap on the horn before you pull out"],
       e:"A stop sign means the wheels stop turning. Stop at the line, or before the crosswalk if none is painted, and pull out only when you will not force another driver to slow." },
  fr:{ q:"Vous arrivez à ce panneau là où une route de gravier rejoint une route des Territoires du Nord-Ouest. Qu'exige-t-il ?",
       a:["Un arrêt complet, puis repartir seulement quand la voie est libre","Un ralentissement si vous voyez des deux côtés","Un arrêt seulement si un autre véhicule est en vue","Un coup de klaxon avant de vous engager"],
       e:"Un panneau d'arrêt signifie que les roues cessent de tourner. Arrêtez-vous à la ligne, ou avant le passage pour piétons s'il n'y en a pas, et engagez-vous seulement si personne n'est forcé de ralentir." },
  c:0 },
{ id:"nts2", sec:"signs", sign:"yield",
  en:{ q:"This red and white triangle faces you where two roads join. What does it ask?",
       a:["Stop and wait until somebody waves you through","Sound your horn and merge at once","Give way to traffic and pedestrians already on the road","Come to a full stop every time, even on an empty road"],
       e:"Yield means give way. Slow right down, be ready to stop, and join only when nobody already using the road has to brake or steer around you." },
  fr:{ q:"Ce triangle rouge et blanc vous fait face là où deux routes se rejoignent. Que demande-t-il ?",
       a:["Vous arrêter et attendre qu'on vous fasse signe","Klaxonner et vous insérer immédiatement","Céder le passage aux véhicules et aux piétons déjà sur la chaussée","Faire un arrêt complet chaque fois, même sur une route déserte"],
       e:"Céder le passage veut dire laisser passer. Ralentissez beaucoup, soyez prêt à vous arrêter et engagez-vous seulement si personne n'a besoin de freiner ou de vous contourner." },
  c:2 },
{ id:"nts3", sec:"signs", sign:"no-entry",
  en:{ q:"This sign is mounted at the mouth of a street in a Northwest Territories community. What is it telling you?",
       a:["Only people who live on the street may drive in","You must not drive in, because traffic here comes towards you","Entry is allowed once the shops have closed","Heavy vehicles must use another street"],
       e:"The street runs the other way. Going past this sign puts you head-on into drivers who have no reason to expect you." },
  fr:{ q:"Ce panneau est installé à l'entrée d'une rue d'une collectivité des Territoires du Nord-Ouest. Que vous indique-t-il ?",
       a:["Seuls les résidents de la rue peuvent y entrer","Vous ne devez pas y entrer, car la circulation vient vers vous","L'entrée est permise une fois les commerces fermés","Les véhicules lourds doivent emprunter une autre rue"],
       e:"La rue circule en sens inverse. Franchir ce panneau vous place face à des conducteurs qui n'ont aucune raison de vous attendre." },
  c:1 },
{ id:"nts4", sec:"signs", sign:"one-way",
  en:{ q:"You are turning onto a street marked with this sign. What must be true once your turn is finished?",
       a:["You may pick either direction once you are on it","You must park before the next corner","You may drive against the arrow if you keep your speed down","You must be travelling the way the arrow points"],
       e:"Every lane on a one-way street runs the same way. Turning the wrong way here is one of the quickest ways for a new driver to end up facing traffic." },
  fr:{ q:"Vous tournez sur une rue portant ce panneau. Que doit-il être vrai une fois le virage terminé ?",
       a:["Vous pouvez choisir l'un ou l'autre sens une fois engagé","Vous devez stationner avant le prochain coin","Vous pouvez rouler contre la flèche si vous allez lentement","Vous devez circuler dans le sens de la flèche"],
       e:"Toutes les voies d'une rue à sens unique vont dans la même direction. Y tourner à l'envers est l'une des façons les plus rapides de se retrouver face à la circulation." },
  c:3 },
{ id:"nts5", sec:"signs", sign:"no-passing",
  en:{ q:"This sign stands beside a straight, open stretch of highway. Why does it still apply?",
       a:["Passing is banned here whatever the road looks like","It applies only while a vehicle is coming the other way","It applies only to trucks and buses","It is advice that may be ignored in daylight"],
       e:"A no passing sign is an order, not a suggestion. It is usually posted because of a hidden dip, a side road or a crest you cannot see past." },
  fr:{ q:"Ce panneau se trouve le long d'une portion droite et dégagée. Pourquoi s'applique-t-il quand même ?",
       a:["Le dépassement est interdit ici, peu importe l'allure de la route","Il s'applique seulement si un véhicule vient en sens inverse","Il vise seulement les camions et les autobus","C'est un conseil que l'on peut ignorer le jour"],
       e:"Un panneau de dépassement interdit est un ordre, pas une suggestion. Il est souvent posé à cause d'un creux, d'un chemin latéral ou d'un sommet que vous ne voyez pas." },
  c:0 },
{ id:"nts6", sec:"signs", sign:"no-stopping",
  en:{ q:"A friend asks you to pull over for a second where this sign is posted. What do you tell them?",
       a:["It is fine as long as the engine keeps running","No, this sign bans stopping even for a moment","It is fine if nobody gets out of the vehicle","It is fine outside business hours"],
       e:"No stopping is the strictest of the curbside signs. You may not stop here at all, not to wait and not to drop somebody off." },
  fr:{ q:"Un ami vous demande de vous ranger un instant là où ce panneau est affiché. Que lui répondez-vous ?",
       a:["C'est permis tant que le moteur tourne","Non, ce panneau interdit même un arrêt d'un instant","C'est permis si personne ne descend du véhicule","C'est permis en dehors des heures d'ouverture"],
       e:"L'arrêt interdit est le plus sévère des panneaux de bord de rue. Vous ne pouvez pas vous y arrêter du tout, ni pour attendre, ni pour laisser descendre quelqu'un." },
  c:1 },
{ id:"nts7", sec:"signs", sign:"keep-right",
  en:{ q:"The road divides around a raised island and this sign is fixed to it. What does it order?",
       a:["Stop before the island and let others go first","Choose whichever side carries less traffic","Pass on the right-hand side of the island","Reverse and find another route"],
       e:"Keep right of the island. Taking the wrong side puts you into traffic coming from the far side of the obstacle, which is the last thing those drivers expect." },
  fr:{ q:"La chaussée se sépare autour d'un îlot surélevé et ce panneau y est fixé. Qu'ordonne-t-il ?",
       a:["Vous arrêter avant l'îlot et laisser passer les autres","Choisir le côté où il y a le moins de circulation","Passer à droite de l'îlot","Reculer et trouver un autre chemin"],
       e:"Tenez la droite de l'îlot. Prendre le mauvais côté vous place face aux véhicules qui arrivent de l'autre côté de l'obstacle, ce à quoi ces conducteurs ne s'attendent pas du tout." },
  c:2 },
{ id:"nts8", sec:"signs", sign:"stop-school-bus",
  en:{ q:"A bus ahead shows this sign and flashing red lights on a two-lane Northwest Territories road. Who must stop?",
       a:["Drivers coming from both directions","Only the drivers behind the bus","Only drivers who can actually see children","Nobody, as long as the bus is on the shoulder"],
       e:"In the Northwest Territories traffic stops in both directions while the lights are flashing. Children cross without warning, and the driver cannot hold them back once they have stepped off." },
  fr:{ q:"Un autobus devant vous montre ce panneau et des feux rouges clignotants sur une route à deux voies des Territoires du Nord-Ouest. Qui doit s'arrêter ?",
       a:["Les conducteurs venant des deux sens","Seulement les conducteurs derrière l'autobus","Seulement ceux qui voient réellement des enfants","Personne, tant que l'autobus est sur l'accotement"],
       e:"Aux Territoires du Nord-Ouest, la circulation s'arrête dans les deux sens tant que les feux clignotent. Les enfants traversent sans prévenir et le conducteur ne peut pas les retenir une fois descendus." },
  c:0 },
{ id:"nts9", sec:"signs", sign:"speed-limit-begins",
  en:{ q:"You pass this sign on your way out of a community. What has just changed?",
       a:["Nothing until the next intersection","The number is only a suggestion on this stretch","The old limit stays until a second sign cancels it","A new posted limit applies from this sign onwards"],
       e:"A new limit takes effect at the sign itself, not somewhere further along. Have your speed right before you reach it rather than after." },
  fr:{ q:"Vous passez ce panneau en quittant une collectivité. Qu'est-ce qui vient de changer ?",
       a:["Rien avant la prochaine intersection","Le chiffre n'est ici qu'une suggestion","L'ancienne limite reste jusqu'à ce qu'un deuxième panneau l'annule","Une nouvelle limite affichée s'applique à partir de ce panneau"],
       e:"Une nouvelle limite entre en vigueur au panneau même, et non plus loin. Ajustez votre vitesse avant de l'atteindre plutôt qu'après." },
  c:3 },
{ id:"nts10", sec:"signs", sign:"warn-moose",
  en:{ q:"This yellow diamond appears on a northern highway. What is the real danger it points to?",
       a:["The animal may scratch the paintwork","The animal is tall, so a collision can bring it through the windshield","The animal always runs away from headlights","The animal is only about in summer"],
       e:"A moose carries its weight high on long legs. In a collision the body is often swept onto the windshield rather than the bumper, which is why cutting speed matters more than steering." },
  fr:{ q:"Ce losange jaune apparaît sur une route nordique. Quel danger réel signale-t-il ?",
       a:["L'animal peut égratigner la carrosserie","L'animal est haut sur pattes : une collision peut le projeter sur le pare-brise","L'animal fuit toujours devant les phares","L'animal ne circule qu'en été"],
       e:"L'orignal porte sa masse haut sur de longues pattes. Lors d'une collision, le corps est souvent projeté sur le pare-brise plutôt que sur le pare-chocs : réduire la vitesse compte plus que braquer." },
  c:1 },
{ id:"nts11", sec:"signs", sign:"warn-deer",
  en:{ q:"You brake for the animal shown on this sign and it reaches the far shoulder. Why should you stay slow?",
       a:["Because the road surface will have been damaged","Because your brakes need time to cool","Because more of the herd is probably still to cross","Because your headlights need time to recover"],
       e:"Most animals travel in herds, so where there is one there are often more. It is the second and third animal that catch drivers who speed up too soon." },
  fr:{ q:"Vous freinez pour l'animal illustré et il atteint l'autre accotement. Pourquoi rester lent ?",
       a:["Parce que la chaussée aura été endommagée","Parce que vos freins doivent refroidir","Parce que d'autres bêtes du troupeau vont probablement traverser","Parce que vos phares ont besoin de temps"],
       e:"La plupart des animaux se déplacent en troupeau : là où il y en a un, il y en a souvent d'autres. Ce sont le deuxième et le troisième qui surprennent ceux qui réaccélèrent trop tôt." },
  c:2 },
{ id:"nts12", sec:"signs", sign:"warn-pavement-ends",
  en:{ q:"You are travelling at highway speed when this sign appears. What is about to change under your tires?",
       a:["The pavement ends and a gravel surface begins","A bridge deck begins","A painted crosswalk begins","A tunnel begins"],
       e:"Loose gravel gives far less grip than pavement and tugs at the steering. Ease your speed off well before the change rather than at it." },
  fr:{ q:"Vous roulez à la vitesse de la route quand ce panneau apparaît. Qu'est-ce qui va changer sous vos pneus ?",
       a:["Le revêtement se termine et une surface de gravier commence","Un tablier de pont commence","Un passage pour piétons commence","Un tunnel commence"],
       e:"Le gravier meuble offre bien moins d'adhérence que l'asphalte et tire sur la direction. Relâchez l'accélérateur bien avant le changement, pas au moment même." },
  c:0 },
{ id:"nts13", sec:"signs", sign:"warn-slippery",
  en:{ q:"Freezing drizzle is falling where this sign is posted. What does that mean for your braking?",
       a:["Braking is unaffected once the wipers are running","You may brake later than usual because the surface is smooth","Braking hard is the safest way to test the surface","You need to brake far earlier and far more gently"],
       e:"A slippery surface stretches your stopping distance and punishes sudden movements. Brake early, steer smoothly, and leave much more room than you would on a dry road." },
  fr:{ q:"De la bruine verglaçante tombe là où ce panneau est affiché. Qu'est-ce que cela change pour le freinage ?",
       a:["Rien, dès que les essuie-glaces fonctionnent","Vous pouvez freiner plus tard, car la chaussée est lisse","Freiner fort est la meilleure façon de tester la surface","Vous devez freiner bien plus tôt et bien plus doucement"],
       e:"Une chaussée glissante allonge la distance d'arrêt et punit les gestes brusques. Freinez tôt, braquez en douceur et laissez beaucoup plus d'espace que sur une route sèche." },
  c:3 },
{ id:"nts14", sec:"signs", sign:"warn-bump",
  en:{ q:"This sign is posted on a stretch where the ground has heaved. What is the safe way through?",
       a:["Speed up so the wheels skip over it","Slow down before it and hold the wheel firmly","Brake hard as the wheels hit it","Move onto the shoulder and pass it there"],
       e:"Slow down before the rough section, not on it. Braking while the wheels are already bouncing takes weight off the tires just when you need grip." },
  fr:{ q:"Ce panneau est posé sur un tronçon où le sol s'est soulevé. Quelle est la façon sûre de le franchir ?",
       a:["Accélérer pour que les roues sautent par-dessus","Ralentir avant et tenir le volant fermement","Freiner fort au moment de l'impact","Passer sur l'accotement pour l'éviter"],
       e:"Ralentissez avant la section cahoteuse, pas dessus. Freiner pendant que les roues sautent enlève du poids aux pneus juste au moment où il faut de l'adhérence." },
  c:1 },
{ id:"nts15", sec:"signs", sign:"warn-steep-hill",
  en:{ q:"Why is holding the brakes on all the way down the hill this sign warns about a poor idea?",
       a:["It wears the tires out","It uses more fuel","The brakes heat up and lose their bite","It is only a problem for trucks"],
       e:"Brakes held on for a long descent get hot and fade. Choose a lower gear at the top so the engine holds the vehicle back and the brakes stay fresh for when you really need them." },
  fr:{ q:"Pourquoi est-il déconseillé de garder le pied sur le frein tout au long de la descente annoncée par ce panneau ?",
       a:["Cela use les pneus","Cela consomme plus de carburant","Les freins chauffent et perdent leur mordant","Cela ne pose problème qu'aux camions"],
       e:"Des freins maintenus longtemps en descente chauffent et s'affaiblissent. Choisissez un rapport inférieur au sommet : le moteur retient le véhicule et les freins restent efficaces au moment voulu." },
  c:2 },
{ id:"nts16", sec:"signs", sign:"warn-curve-right",
  en:{ q:"This sign appears on a gravel highway. Why is the bend it shows more serious there than on pavement?",
       a:["Loose gravel gives less grip, so the vehicle slides wide more easily","Gravel roads are always narrower","The sign means something different on gravel","Speed limits do not apply on gravel"],
       e:"Grip on loose stone is a fraction of what pavement offers. Get your speed down before the bend so you can hold one steady line all the way through it." },
  fr:{ q:"Ce panneau apparaît sur une route de gravier. Pourquoi ce virage y est-il plus sérieux que sur l'asphalte ?",
       a:["Le gravier meuble adhère moins et le véhicule dérape vers l'extérieur plus facilement","Les routes de gravier sont toujours plus étroites","Le panneau a un autre sens sur le gravier","Les limites de vitesse ne s'appliquent pas sur le gravier"],
       e:"L'adhérence sur la pierre meuble ne représente qu'une fraction de celle de l'asphalte. Réduisez votre vitesse avant le virage pour tenir une seule trajectoire régulière." },
  c:0 },
{ id:"nts17", sec:"signs", sign:"warn-chevron",
  en:{ q:"Your headlights pick up a row of these on a dark curve. How should you use them?",
       a:["Aim for the middle of the row","Follow the direction they point and set your speed for the bend","Treat them as the start of a passing lane","Ignore them, they mark private driveways"],
       e:"A chevron shows which way the road turns and how sharply. On an unlit northern highway they are often the first thing your headlights give you." },
  fr:{ q:"Vos phares éclairent une série de ces panneaux dans un virage sombre. Comment devez-vous les utiliser ?",
       a:["Viser le milieu de la rangée","Suivre la direction qu'ils indiquent et adapter votre vitesse au virage","Les traiter comme le début d'une voie de dépassement","Les ignorer, ils marquent des entrées privées"],
       e:"Un chevron indique de quel côté la route tourne et à quel point le virage est serré. Sur une route nordique sans éclairage, ils sont souvent la première chose que vos phares révèlent." },
  c:1 },
{ id:"nts18", sec:"signs", sign:"warn-school-zone",
  en:{ q:"It is a Sunday morning and this sign is posted. How should you drive?",
       a:["As though the zone were lifted for the weekend","Faster, because the school is empty","With the same care as on a weekday, because the zone never lifts","Slowly only if a crossing guard is on duty"],
       e:"In the Northwest Territories a school zone applies all day, every day of the year. Children use school grounds outside class hours, and the sign is not switched off at the weekend." },
  fr:{ q:"C'est un dimanche matin et ce panneau est affiché. Comment devez-vous conduire ?",
       a:["Comme si la zone était levée pour la fin de semaine","Plus vite, puisque l'école est vide","Avec la même prudence qu'en semaine, car la zone ne se lève jamais","Lentement seulement si un brigadier est en poste"],
       e:"Aux Territoires du Nord-Ouest, une zone scolaire s'applique toute la journée, tous les jours de l'année. Les enfants fréquentent la cour en dehors des heures de classe et le panneau ne s'éteint pas la fin de semaine." },
  c:2 },
{ id:"nts19", sec:"signs", sign:"warn-narrow-bridge",
  en:{ q:"Why do drivers get into trouble at the structure this sign warns about?",
       a:["The surface there is always icy","It is normally closed for the winter","Trucks are not allowed onto it","Two vehicles arrive together and neither one slows down"],
       e:"The bridge is narrower than the road leading to it. One of you has to give way, so decide early, slow down, and never try to pass on the bridge itself." },
  fr:{ q:"Pourquoi les conducteurs ont-ils des ennuis à l'ouvrage annoncé par ce panneau ?",
       a:["La surface y est toujours glacée","Il est habituellement fermé l'hiver","Les camions n'y sont pas admis","Deux véhicules y arrivent en même temps et aucun ne ralentit"],
       e:"Le pont est plus étroit que la route qui y mène. L'un des deux doit céder : décidez tôt, ralentissez et ne dépassez jamais sur le pont." },
  c:3 },
{ id:"nts20", sec:"signs", sign:"temp-construction",
  en:{ q:"The orange sign at the start of a work area is up but no machines are moving. What still applies?",
       a:["Nothing, until you can actually see workers","The work zone rules and the limit posted for the zone","Only the rule about headlights","Only the rules that apply to trucks"],
       e:"A work zone stays a work zone while the signs are up. The surface is often loose or uneven, lanes shift without warning, and a worker can step out from behind a parked machine." },
  fr:{ q:"Le panneau orange au début d'une zone de travaux est en place, mais aucune machine ne bouge. Qu'est-ce qui s'applique quand même ?",
       a:["Rien, tant que vous ne voyez pas d'ouvriers","Les règles de la zone de travaux et la limite qui y est affichée","Seulement la règle sur les phares","Seulement les règles visant les camions"],
       e:"Une zone de travaux le reste tant que les panneaux sont en place. La chaussée y est souvent meuble ou inégale, les voies se déplacent sans préavis et un ouvrier peut surgir derrière une machine." },
  c:1 },
{ id:"nts21", sec:"signs", sign:"temp-flagger",
  en:{ q:"This sign is posted ahead of a grader working on a gravel highway. What should you be ready to do?",
       a:["Stop for the person directing traffic, however clear the road looks","Pass the grader on the shoulder","Sound your horn and hold your speed","Turn around and take another route"],
       e:"A traffic control person's instructions carry the same weight as a sign or a signal. Stop when they tell you to, and move off only when they wave you on." },
  fr:{ q:"Ce panneau est posé avant une niveleuse qui travaille sur une route de gravier. À quoi devez-vous être prêt ?",
       a:["Vous arrêter pour le signaleur, même si la route semble libre","Dépasser la niveleuse par l'accotement","Klaxonner et garder votre vitesse","Faire demi-tour et prendre un autre chemin"],
       e:"Les instructions d'un signaleur ont la même valeur qu'un panneau ou un feu. Arrêtez-vous quand il vous l'indique et repartez seulement quand il vous fait signe." },
  c:0 },
{ id:"nts22", sec:"signs", sign:"temp-detour",
  en:{ q:"A highway is closed for repairs and this sign is out. What are you being asked to do?",
       a:["Wait at the barricade until the road reopens","Find your own way around using a map","Follow the marked route around the closure until it rejoins the highway","Drive through slowly if your vehicle sits high enough"],
       e:"A detour is a signed alternative route. Keep following the markers rather than guessing at side roads, which in the North may not be maintained and may not connect at all." },
  fr:{ q:"Une route est fermée pour réparations et ce panneau est installé. Que vous demande-t-on ?",
       a:["Attendre à la barrière la réouverture de la route","Trouver votre propre chemin avec une carte","Suivre l'itinéraire balisé qui contourne la fermeture jusqu'au raccordement","Passer lentement si votre véhicule est assez haut"],
       e:"Un détour est un itinéraire de remplacement balisé. Suivez les repères plutôt que de deviner par des chemins latéraux qui, dans le Nord, ne sont pas toujours entretenus ni raccordés." },
  c:2 },
{ id:"nts23", sec:"signs", sign:"info-hospital",
  en:{ q:"Blue signs like this one belong to which family?",
       a:["Warning signs about the road surface","Regulatory signs that carry a penalty","Temporary signs used in work zones","Information signs that point to services"],
       e:"Blue is the colour the sign system uses for services: hospitals, fuel, food and accessible parking. It tells you what is available, not what you must do." },
  fr:{ q:"Les panneaux bleus comme celui-ci appartiennent à quelle famille ?",
       a:["Les panneaux d'avertissement sur l'état de la chaussée","Les panneaux de prescription assortis d'une sanction","Les panneaux temporaires des zones de travaux","Les panneaux d'information qui indiquent des services"],
       e:"Le bleu est la couleur des services : hôpitaux, carburant, restauration et stationnement accessible. Il indique ce qui est offert, non ce que vous devez faire." },
  c:3 },
{ id:"nts24", sec:"signs", sign:"info-gas",
  en:{ q:"You are between communities with a quarter tank left when this sign appears. Why does it matter more here than in a city?",
       a:["The next chance to fill up may be a very long way off","Fuel is cheaper at stations that are signed","The sign guarantees the station is open all night","Filling up before a long trip is required by law"],
       e:"Distances between services on northern highways are long, and a station shown on a sign may be the last one for hours. Keeping the tank well up is also what the territory advises for winter travel." },
  fr:{ q:"Vous êtes entre deux collectivités avec un quart de réservoir quand ce panneau apparaît. Pourquoi compte-t-il plus qu'en ville ?",
       a:["La prochaine occasion de faire le plein peut être très loin","Le carburant coûte moins cher aux stations annoncées","Le panneau garantit que la station est ouverte la nuit","La loi oblige à faire le plein avant un long trajet"],
       e:"Les distances entre les services sur les routes nordiques sont longues et la station annoncée peut être la dernière avant des heures. Garder le réservoir bien rempli est aussi ce que le territoire conseille pour les déplacements d'hiver." },
  c:0 },
{ id:"nts25", sec:"signs", sign:"info-trans-canada",
  en:{ q:"You are following a route marked with this shield. What does the marker help you do?",
       a:["Judge the speed limit for the next section","Confirm you are still on the national route you meant to take","Find the nearest fuel station","Know when the road turns to gravel"],
       e:"Route markers confirm which road you are on. They are placed after junctions so a driver can check the turn was the right one without having to stop." },
  fr:{ q:"Vous suivez une route balisée par cet écusson. À quoi le repère vous sert-il ?",
       a:["À évaluer la limite de vitesse du prochain tronçon","À confirmer que vous êtes toujours sur l'itinéraire national voulu","À trouver la station-service la plus proche","À savoir quand la route devient du gravier"],
       e:"Les écussons de route confirment sur quelle route vous êtes. Ils sont posés après les carrefours pour qu'un conducteur vérifie son virage sans devoir s'arrêter." },
  c:1 },
{ id:"nts26", sec:"signs", sign:"info-accessible",
  en:{ q:"A space marked with this sign is the only one left and you are in a hurry. What is the correct decision?",
       a:["Use it briefly as long as you stay with the vehicle","Use it, because the lot is full","Park somewhere else, because the space is reserved for permit holders","Use it with your hazard lights on"],
       e:"The space exists so that somebody who needs the extra room and the short distance can get out of their vehicle. Being in a hurry is not a permit." },
  fr:{ q:"Une place portant ce panneau est la seule libre et vous êtes pressé. Quelle est la bonne décision ?",
       a:["L'utiliser brièvement en restant dans le véhicule","L'utiliser, puisque le stationnement est plein","Stationner ailleurs, car la place est réservée aux titulaires d'une vignette","L'utiliser en laissant vos feux de détresse allumés"],
       e:"Cette place existe pour qu'une personne qui a besoin d'espace et d'un court trajet puisse sortir de son véhicule. Être pressé ne tient pas lieu de vignette." },
  c:2 },
{ id:"nts27", sec:"signs", sign:"light-amber",
  en:{ q:"This light comes on while you are still well back from the intersection. What is expected of you?",
       a:["Stop before the line, because the red is about to appear","Speed up to clear the intersection","Cover the brake but carry on at the same speed","Stop only if a vehicle is waiting to cross"],
       e:"Amber means the red is coming. If you can stop safely before the line, that is what the light is asking for; carry on only when stopping would mean braking so hard that the driver behind could not." },
  fr:{ q:"Ce feu s'allume alors que vous êtes encore loin de l'intersection. Qu'attend-on de vous ?",
       a:["Vous arrêter avant la ligne, car le rouge va apparaître","Accélérer pour dégager l'intersection","Couvrir le frein et garder la même vitesse","Vous arrêter seulement si un véhicule attend pour traverser"],
       e:"Le jaune annonce le rouge. Si vous pouvez vous arrêter en sécurité avant la ligne, c'est ce que le feu demande ; ne continuez que si freiner obligerait le conducteur derrière à freiner brutalement." },
  c:0 },
{ id:"nts28", sec:"signs", sign:"light-flashing-red",
  en:{ q:"You reach an intersection where this light is showing on every approach. How do you treat it?",
       a:["As a green light taken with extra caution","As a yield sign that needs no stop","As a signal that is out of order and can be ignored","As a stop sign: stop, then go when it is your turn"],
       e:"A flashing red is a stop sign in light form. When every approach flashes red the intersection works as an all-way stop, and the first driver to stop is the first to go." },
  fr:{ q:"Vous arrivez à une intersection où ce feu clignote sur toutes les approches. Comment le traitez-vous ?",
       a:["Comme un feu vert pris avec un surcroît de prudence","Comme une cession de passage sans arrêt","Comme un feu défectueux que l'on peut ignorer","Comme un panneau d'arrêt : arrêtez-vous, puis repartez à votre tour"],
       e:"Un feu rouge clignotant est un panneau d'arrêt lumineux. Quand toutes les approches clignotent, l'intersection fonctionne comme un arrêt toutes directions et le premier arrêté est le premier reparti." },
  c:3 },
{ id:"nts29", sec:"signs", sign:"mark-solid-yellow",
  en:{ q:"What do a pair of solid yellow lines down the centre tell both directions of traffic?",
       a:["That the road ahead becomes one way","That the lanes may be shared when traffic is light","That passing is allowed for whichever direction has the shorter line","That neither direction may cross them to pass"],
       e:"Two solid yellow lines mean the view ahead is too short for either direction to pass safely. Yellow always separates traffic that is moving in opposite directions." },
  fr:{ q:"Que disent aux deux sens de circulation deux lignes jaunes continues au centre de la chaussée ?",
       a:["Que la route devient à sens unique","Que les voies peuvent être partagées quand il y a peu de circulation","Que le dépassement est permis au sens dont la ligne est la plus courte","Qu'aucun des deux sens ne peut les franchir pour dépasser"],
       e:"Deux lignes jaunes continues signifient que la visibilité est trop courte pour dépasser dans un sens comme dans l'autre. Le jaune sépare toujours des circulations de sens opposés." },
  c:3 },
{ id:"nts30", sec:"signs", sign:"mark-stop-line",
  en:{ q:"Why is the wide white line across your lane painted back from the cross street?",
       a:["To give cyclists somewhere to wait","To mark the edge of a parking area","To show where a bus has to stop","To keep stopped vehicles clear of crossing traffic and of people on foot"],
       e:"The stop line holds you back far enough that turning vehicles and people crossing have room. Stop with your bumper behind it, then edge forward only if you still cannot see." },
  fr:{ q:"Pourquoi la large ligne blanche tracée en travers de votre voie est-elle placée en retrait de la rue transversale ?",
       a:["Pour offrir un espace d'attente aux cyclistes","Pour marquer la limite d'une aire de stationnement","Pour indiquer où un autobus doit s'arrêter","Pour garder les véhicules arrêtés à l'écart de la circulation transversale et des piétons"],
       e:"La ligne d'arrêt vous retient assez loin pour laisser de la place aux véhicules qui tournent et aux personnes qui traversent. Arrêtez-vous derrière elle, puis avancez seulement si vous ne voyez toujours pas." },
  c:3 }
);

/* ---------- rules of the road ---------- */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"ntr1", sec:"rules", topic:"gdl",
  en:{ q:"What is the earliest a person may apply for a Class 7 learner's licence in the Northwest Territories, and how long must it then be held?",
       a:["At 14, and held for six months","At 15, and held for at least one year","At 16, and held for three months","At 18, and held for two years"],
       e:"Stage 1 opens at 15, and the Class 7 licence has to be held for at least twelve months before you can move up. The territory publishes no way of shortening that year." },
  fr:{ q:"À partir de quel âge peut-on demander un permis d'apprenti de classe 7 aux Territoires du Nord-Ouest, et combien de temps faut-il ensuite le garder ?",
       a:["À 14 ans, et le garder six mois","À 15 ans, et le garder au moins un an","À 16 ans, et le garder trois mois","À 18 ans, et le garder deux ans"],
       e:"L'étape 1 commence à 15 ans et le permis de classe 7 doit être détenu au moins douze mois avant de passer à l'étape suivante. Le territoire ne publie aucun moyen d'abréger cette année." },
  c:1 },
{ id:"ntr2", sec:"rules", topic:"gdl",
  en:{ q:"You have passed the road test and now hold a Class 5P licence. What does the second stage ask of you?",
       a:["Six months without carrying a passenger","Twelve months of driving in daylight only","Twelve months free of any suspension before you can upgrade","Three years and a second knowledge examination"],
       e:"Stage 2 is the probationary Class 5P licence. You have to complete twelve suspension-free months in it, so a suspension during that time sets the clock back." },
  fr:{ q:"Vous avez réussi l'examen pratique et détenez maintenant un permis de classe 5P. Qu'exige la deuxième étape ?",
       a:["Six mois sans transporter de passager","Douze mois de conduite de jour seulement","Douze mois sans aucune suspension avant de pouvoir passer à l'étape suivante","Trois ans et un deuxième examen théorique"],
       e:"L'étape 2 est le permis probatoire de classe 5P. Il faut y accumuler douze mois sans suspension : une suspension pendant cette période remet le compteur à zéro." },
  c:2 },
{ id:"ntr3", sec:"rules", topic:"gdl",
  en:{ q:"Counting both graduated stages, what is the shortest time the Northwest Territories programme can take?",
       a:["Two years","Six months","One year","Four years"],
       e:"Twelve months as a learner and twelve suspension-free months on a probationary licence add up to a minimum of two years before a full licence is possible." },
  fr:{ q:"En comptant les deux étapes, quelle est la durée minimale du programme des Territoires du Nord-Ouest ?",
       a:["Deux ans","Six mois","Un an","Quatre ans"],
       e:"Douze mois comme apprenti et douze mois sans suspension avec un permis probatoire font au minimum deux ans avant qu'un permis complet soit possible." },
  c:0 },
{ id:"ntr4", sec:"rules", topic:"learner",
  en:{ q:"Who may act as your supervisor while you drive on a Class 7 licence?",
       a:["Any licensed driver aged 18 or over","Anyone who has held any licence for six months","A driver who is still in the graduated programme","A driver at least 19 years old with a full Class 5 licence and 24 months of experience"],
       e:"The supervisor needs 24 months of experience on a full Class 5 licence and must be at least 19. Time spent holding a graduated licence does not count towards that experience." },
  fr:{ q:"Qui peut vous accompagner comme superviseur pendant que vous conduisez avec un permis de classe 7 ?",
       a:["N'importe quel conducteur titulaire d'un permis et âgé de 18 ans ou plus","Toute personne qui détient un permis depuis six mois","Un conducteur encore inscrit au programme par étapes","Un conducteur d'au moins 19 ans titulaire d'un permis complet de classe 5 et comptant 24 mois d'expérience"],
       e:"Le superviseur doit compter 24 mois d'expérience avec un permis complet de classe 5 et avoir au moins 19 ans. Le temps passé avec un permis du programme par étapes ne compte pas dans cette expérience." },
  c:3 },
{ id:"ntr5", sec:"rules", topic:"learner",
  en:{ q:"How much alcohol may be in the blood of a Class 7 driver and of the supervisor riding with them?",
       a:["The learner must be at zero; the supervisor may be under 0.08","Both of them must be at zero","Both of them may be under 0.05","The supervisor must be at zero; the learner may be under 0.05"],
       e:"The Northwest Territories puts the zero limit on both people. A supervisor who has been drinking cannot legally supervise, even if the learner has had nothing at all." },
  fr:{ q:"Quelle quantité d'alcool peut se trouver dans le sang d'un conducteur de classe 7 et de son superviseur ?",
       a:["L'apprenti doit être à zéro ; le superviseur peut être sous 0,08","Les deux doivent être à zéro","Les deux peuvent être sous 0,05","Le superviseur doit être à zéro ; l'apprenti peut être sous 0,05"],
       e:"Les Territoires du Nord-Ouest imposent la limite de zéro aux deux personnes. Un superviseur qui a bu ne peut pas accompagner légalement, même si l'apprenti n'a rien consommé." },
  c:1 },
{ id:"ntr6", sec:"rules", topic:"learner",
  en:{ q:"Your cousin asks for a ride while you are practising on your Class 7 licence, with your supervisor already in the vehicle. What does the law allow?",
       a:["One extra passenger is allowed","Extra passengers are allowed during daylight","No passenger other than the supervisor may be in the vehicle","Up to three passengers are allowed if everyone is belted"],
       e:"A Class 7 driver carries the supervisor and nobody else. It is a strict one-person rule, and the territory publishes no exception for family." },
  fr:{ q:"Votre cousin demande à monter pendant que vous vous exercez avec votre permis de classe 7, votre superviseur étant déjà à bord. Que permet la loi ?",
       a:["Un passager supplémentaire est permis","Des passagers supplémentaires sont permis le jour","Aucun passager autre que le superviseur ne peut être dans le véhicule","Jusqu'à trois passagers sont permis si chacun boucle sa ceinture de sécurité"],
       e:"Un conducteur de classe 7 transporte son superviseur et personne d'autre. C'est une règle stricte et le territoire ne publie aucune exception pour la famille." },
  c:2 },
{ id:"ntr7", sec:"rules", topic:"learner",
  en:{ q:"Between which hours may a Class 7 driver in the Northwest Territories not drive at all?",
       a:["Between 11 p.m. and 6 a.m.","Between midnight and 5 a.m.","Between 10 p.m. and 7 a.m.","There is no restriction on the hours"],
       e:"The learner stage bans driving between 11 p.m. and 6 a.m., supervisor or no supervisor. Across much of the territory those hours are dark all winter and bright much of the summer, but the rule goes by the clock." },
  fr:{ q:"Entre quelles heures un conducteur de classe 7 des Territoires du Nord-Ouest ne peut-il pas conduire du tout ?",
       a:["Entre 23 h et 6 h","Entre minuit et 5 h","Entre 22 h et 7 h","Il n'y a aucune restriction horaire"],
       e:"L'étape d'apprenti interdit de conduire entre 23 h et 6 h, avec ou sans superviseur. Dans une grande partie du territoire, ces heures sont sombres tout l'hiver et claires une bonne partie de l'été, mais la règle suit l'horloge." },
  c:0 },
{ id:"ntr8", sec:"rules", topic:"test",
  en:{ q:"How does the Northwest Territories organise the knowledge examination for a Class 7 licence?",
       a:["One test of 40 questions covering everything","One test of 20 questions drawn from both subjects","A written test followed by an oral interview","Two separate tests of 20 questions: one on the rules of the road and one on road signage"],
       e:"The territory publishes the format plainly: twenty multiple-choice questions on the rules of the road, and a separate test of twenty questions on road signage." },
  fr:{ q:"Comment les Territoires du Nord-Ouest organisent-ils l'examen théorique pour un permis de classe 7 ?",
       a:["Un seul examen de 40 questions couvrant tout","Un seul examen de 20 questions tirées des deux sujets","Un examen écrit suivi d'une entrevue orale","Deux examens distincts de 20 questions : un sur le code de la route et un sur la signalisation routière"],
       e:"Le territoire publie clairement le format : vingt questions à choix multiple sur le code de la route et un examen distinct de vingt questions sur la signalisation routière." },
  c:3 },
{ id:"ntr9", sec:"rules", topic:"test",
  en:{ q:"You get seventeen right on the signage test and fourteen right on the rules test. What is the outcome?",
       a:["A pass, because thirty-one out of forty is well over three quarters","A fail on the rules test, because you may miss no more than four questions in each test","A pass, because only the combined total counts","A fail on both, because the two results are averaged together"],
       e:"Each test stands on its own. You may not miss more than four questions in either one, so sixteen out of twenty is the mark to beat on each, and a strong score on one half cannot rescue the other." },
  fr:{ q:"Vous obtenez dix-sept bonnes réponses à l'examen de signalisation et quatorze au code de la route. Quel est le résultat ?",
       a:["Une réussite, car trente et un sur quarante dépasse largement les trois quarts","Un échec au code de la route, car on ne peut manquer plus de quatre questions par examen","Une réussite, car seul le total combiné compte","Un échec aux deux, car les deux résultats sont ramenés à une moyenne"],
       e:"Chaque examen se juge séparément. Vous ne pouvez manquer plus de quatre questions dans l'un comme dans l'autre : seize sur vingt est le seuil de chacun, et un bon résultat d'un côté ne sauve pas l'autre." },
  c:1 },
{ id:"ntr10", sec:"rules", topic:"test",
  en:{ q:"Besides the two knowledge tests, what does a fifteen-year-old applicant have to pass before a Class 7 licence is issued?",
       a:["A medical examination by a nurse practitioner","A hearing test","A vision screening","A first-aid course"],
       e:"A vision screening is required before the licence is issued. A medical report is a separate matter: a Class 5, 6 or 7 driver does not need one until age 75." },
  fr:{ q:"Outre les deux examens théoriques, que doit réussir une personne de quinze ans avant la délivrance d'un permis de classe 7 ?",
       a:["Un examen médical fait par une infirmière praticienne","Un test auditif","Un dépistage visuel","Un cours de secourisme"],
       e:"Un dépistage visuel est exigé avant la délivrance du permis. Le rapport médical est autre chose : un conducteur de classe 5, 6 ou 7 n'en a pas besoin avant l'âge de 75 ans." },
  c:2 },
{ id:"ntr11", sec:"rules", topic:"penalties",
  en:{ q:"At how many demerit points is a novice driver suspended, and at how many is a full licence holder suspended?",
       a:["Six for a novice, fifteen for a full licence holder","Nine for a novice, twelve for a full licence holder","Fifteen for both of them","Twelve for a novice, twenty for a full licence holder"],
       e:"A learner or probationary driver is suspended once six points have piled up, while a driver with a full licence is not suspended until fifteen. New drivers are given far less room for error." },
  fr:{ q:"À combien de points d'inaptitude un conducteur novice est-il suspendu, et à combien l'est un titulaire d'un permis complet ?",
       a:["Six pour le novice, quinze pour le titulaire d'un permis complet","Neuf pour le novice, douze pour le titulaire d'un permis complet","Quinze pour les deux","Douze pour le novice, vingt pour le titulaire d'un permis complet"],
       e:"Un apprenti ou un conducteur probatoire est suspendu dès six points, alors qu'un titulaire d'un permis complet ne l'est qu'à quinze. Les nouveaux conducteurs ont beaucoup moins de marge." },
  c:0 },
{ id:"ntr12", sec:"rules", topic:"penalties",
  en:{ q:"A novice driver in the Northwest Territories reaches twelve demerit points, and later fifteen. How long are those two suspensions?",
       a:["One month, then two months","Two weeks, then one month","Three months, then three months again","Three months at twelve points, and six months at fifteen"],
       e:"The scale climbs steeply for a novice: one month at six points, three months at twelve and six months at fifteen. The points themselves come off the record twenty-four months after they were added." },
  fr:{ q:"Un conducteur novice des Territoires du Nord-Ouest atteint douze points d'inaptitude, puis quinze. Quelle est la durée de ces deux suspensions ?",
       a:["Un mois, puis deux mois","Deux semaines, puis un mois","Trois mois, puis encore trois mois","Trois mois à douze points et six mois à quinze points"],
       e:"L'échelle monte vite pour un novice : un mois à six points, trois mois à douze et six mois à quinze. Les points, eux, disparaissent du dossier vingt-quatre mois après avoir été inscrits." },
  c:3 },
{ id:"ntr13", sec:"rules", topic:"penalties",
  en:{ q:"Which drivers in the Northwest Territories are banned from using a hand-held electronic device at the wheel?",
       a:["Only learner and probationary drivers","Every driver, and it has been the law here since January 2012","Only drivers under 21","Only drivers of commercial vehicles"],
       e:"The ban covers every driver and every hand-held device, from a phone to a portable navigation unit. A conviction carries three demerit points, and the fine doubles in a school or construction zone." },
  fr:{ q:"Quels conducteurs des Territoires du Nord-Ouest n'ont pas le droit d'utiliser un appareil électronique portatif au volant ?",
       a:["Seulement les apprentis et les conducteurs probatoires","Tous les conducteurs, et c'est la loi ici depuis janvier 2012","Seulement les conducteurs de moins de 21 ans","Seulement les conducteurs de véhicules commerciaux"],
       e:"L'interdiction vise tous les conducteurs et tous les appareils portatifs, du téléphone au navigateur de poche. Une condamnation entraîne trois points d'inaptitude, et l'amende double dans une zone scolaire ou de travaux." },
  c:1 },
{ id:"ntr14", sec:"rules", topic:"sharing",
  en:{ q:"A school bus stops on a Northwest Territories road with its lights flashing. What does the law require of the traffic around it?",
       a:["Only the vehicles behind the bus stop","Traffic slows to walking pace and eases past","Traffic stops in both directions","Traffic stops only when children can actually be seen"],
       e:"Passing a stopped school bus with its lights flashing is not allowed, and the duty to stop applies to both directions of travel. Wait until the lights stop flashing before you move off." },
  fr:{ q:"Un autobus scolaire s'arrête sur une route des Territoires du Nord-Ouest, feux clignotants. Qu'exige la loi des véhicules autour ?",
       a:["Seuls les véhicules derrière l'autobus s'arrêtent","La circulation ralentit au pas et se faufile","La circulation s'arrête dans les deux sens","La circulation s'arrête seulement si des enfants sont visibles"],
       e:"Il est interdit de dépasser un autobus scolaire arrêté dont les feux clignotent, et l'obligation de s'arrêter vaut dans les deux sens. Attendez que les feux cessent de clignoter avant de repartir." },
  c:2 },
{ id:"ntr15", sec:"rules", topic:"sharing",
  en:{ q:"What is unusual about the way the Northwest Territories runs its school zones?",
       a:["They are in effect 24 hours a day, 365 days a year, and speeding fines in them are doubled","They apply only between 8 a.m. and 5 p.m. on school days","They apply only while a crossing guard is on duty","They are lifted for the summer holidays"],
       e:"Most places limit a school zone to posted hours or to school days. Here the zone never switches off, and a speeding fine inside it is double what the same offence would cost elsewhere." },
  fr:{ q:"Qu'y a-t-il d'inhabituel dans la façon dont les Territoires du Nord-Ouest gèrent leurs zones scolaires ?",
       a:["Elles sont en vigueur 24 heures sur 24, 365 jours par année, et les amendes pour excès de vitesse y sont doublées","Elles s'appliquent seulement de 8 h à 17 h les jours d'école","Elles s'appliquent seulement quand un brigadier est en poste","Elles sont levées pendant les vacances d'été"],
       e:"Ailleurs, une zone scolaire se limite souvent à des heures affichées ou aux jours de classe. Ici, la zone ne s'éteint jamais et une amende pour excès de vitesse y vaut le double de ce que la même infraction coûterait ailleurs." },
  c:0 },
{ id:"ntr16", sec:"rules", topic:"sharing",
  en:{ q:"When does the Northwest Territories expect your headlights to be on?",
       a:["Only between dusk and dawn","At all times, because it is the law here","Only when the wipers are running","Only outside the communities"],
       e:"The territory tells drivers to keep their headlights on at all times and says plainly that it is the law. Long twilight, blowing snow and dust on gravel all make a lit vehicle far easier to pick out." },
  fr:{ q:"Quand les Territoires du Nord-Ouest exigent-ils que vos phares soient allumés ?",
       a:["Seulement du crépuscule à l'aube","En tout temps, car c'est la loi ici","Seulement quand les essuie-glaces fonctionnent","Seulement à l'extérieur des collectivités"],
       e:"Le territoire demande de garder les phares allumés en tout temps et précise que c'est la loi. Les longs crépuscules, la poudrerie et la poussière du gravier rendent un véhicule éclairé bien plus facile à repérer." },
  c:1 },
{ id:"ntr17", sec:"rules", topic:"wildlife",
  en:{ q:"On which Northwest Territories highways do most bison incidents happen?",
       a:["Highways 1 and 8","Highways 6 and 10","Highways 3 and 5, with bison also found on Highway 7","Highway 4 only"],
       e:"The territory reports that most bison incidents happen along Highways 3 and 5, and notes that bison are also found on and along Highway 7. Knowing which road you are on tells you how much to expect." },
  fr:{ q:"Sur quelles routes des Territoires du Nord-Ouest la plupart des incidents avec des bisons surviennent-ils ?",
       a:["Les routes 1 et 8","Les routes 6 et 10","Les routes 3 et 5, des bisons se trouvant aussi sur la route 7","La route 4 seulement"],
       e:"Le territoire signale que la plupart des incidents avec des bisons surviennent le long des routes 3 et 5, et que des bisons se trouvent aussi sur la route 7 et ses abords. Savoir sur quelle route vous circulez vous dit à quoi vous attendre." },
  c:2 },
{ id:"ntr18", sec:"rules", topic:"wildlife",
  en:{ q:"Along Highway 3, which stretch carries the greatest risk of a bison collision?",
       a:["From kilometre 21 near Fort Providence to kilometre 70","The first five kilometres out of Yellowknife","Only the sections that are lit","The stretch between kilometre 100 and kilometre 150"],
       e:"The territory names the stretch from kilometre 21 near Fort Providence to kilometre 70 as the highest risk on Highway 3. Treat those markers as a reason to drop your speed and lengthen your view." },
  fr:{ q:"Sur la route 3, quel tronçon présente le plus grand risque de collision avec un bison ?",
       a:["Du kilomètre 21, près de Fort Providence, au kilomètre 70","Les cinq premiers kilomètres au sortir de Yellowknife","Seulement les sections éclairées","Le tronçon entre le kilomètre 100 et le kilomètre 150"],
       e:"Le territoire désigne le tronçon allant du kilomètre 21, près de Fort Providence, au kilomètre 70 comme le plus risqué de la route 3. Voyez ces bornes comme une raison de ralentir et d'allonger votre regard." },
  c:0 },
{ id:"ntr19", sec:"rules", topic:"wildlife",
  en:{ q:"When is the risk of hitting a bison at its highest?",
       a:["Around midday, all year round","Early morning in spring only","At any hour during January and February","From dusk until dawn, and especially from August through November"],
       e:"The dangerous window runs from dusk until dawn, and the dangerous months run from August through November. Slowing down after dusk and again at dawn is the single most useful habit on those highways." },
  fr:{ q:"Quand le risque de heurter un bison est-il le plus élevé ?",
       a:["Vers midi, toute l'année","Tôt le matin, au printemps seulement","À n'importe quelle heure en janvier et en février","Du crépuscule à l'aube, et surtout d'août à novembre"],
       e:"La période dangereuse va du crépuscule à l'aube, et les mois dangereux vont d'août à novembre. Ralentir après le crépuscule et de nouveau à l'aube est l'habitude la plus utile sur ces routes." },
  c:3 },
{ id:"ntr20", sec:"rules", topic:"wildlife",
  en:{ q:"Bison are standing on the road ahead of you at dusk. What does the territory advise?",
       a:["Steer around them without slowing","Slow down, do not swerve suddenly, and stop and wait for them to clear the road","Sound your horn and drive between them","Switch your headlights off so they do not panic"],
       e:"A sudden swerve is how drivers lose control and end up in the ditch or in the oncoming lane. Use your high beams whenever you can, flash your hazard lights to warn the drivers behind you, and remember that most animals travel in herds." },
  fr:{ q:"Des bisons se tiennent sur la route devant vous, au crépuscule. Que conseille le territoire ?",
       a:["Les contourner sans ralentir","Ralentir, ne pas faire d'écart brusque, puis vous arrêter et attendre qu'ils libèrent la chaussée","Klaxonner et passer entre eux","Éteindre vos phares pour ne pas les affoler"],
       e:"Un écart brusque fait perdre la maîtrise du véhicule et finit dans le fossé ou dans la voie inverse. Utilisez vos feux de route quand c'est possible, faites clignoter vos feux de détresse pour avertir les conducteurs derrière vous, et rappelez-vous que la plupart des animaux se déplacent en troupeau." },
  c:1 },
{ id:"ntr21", sec:"rules", topic:"ice",
  en:{ q:"Why do winter roads and ice roads carry posted speed limits?",
       a:["To keep fuel use down over long distances","Because those roads are patrolled less often","Because speed creates waves under the ice that can crack it or make it fail","Because headlights work less well over ice"],
       e:"A vehicle moving too fast pushes a wave through the water under the ice. Speed limits keep the weight spread out and the surface stable, and the posted weight limits do the same job, which is also why heavy vehicles are asked to keep extra space between each other." },
  fr:{ q:"Pourquoi les routes d'hiver et les routes de glace ont-elles des limites de vitesse affichées ?",
       a:["Pour réduire la consommation de carburant sur de longues distances","Parce que ces routes sont moins souvent patrouillées","Parce que la vitesse crée sous la glace une vague qui peut la fissurer ou la faire céder","Parce que les phares éclairent moins bien sur la glace"],
       e:"Un véhicule trop rapide pousse une vague dans l'eau sous la glace. Les limites de vitesse répartissent le poids et gardent la surface stable ; les limites de charge affichées font le même travail, et c'est aussi pourquoi les véhicules lourds doivent garder une distance supplémentaire entre eux." },
  c:2 },
{ id:"ntr22", sec:"rules", topic:"ice",
  en:{ q:"A winter road you had planned to use has been closed. What is the only acceptable response?",
       a:["Do not drive on it, because a road is closed for the safety of everybody travelling","Drive on it slowly if your vehicle is a light one","Drive on it if somebody else has already left tracks","Drive on it during daylight only"],
       e:"A road is closed because the surface can no longer carry traffic safely. Tracks left by somebody else tell you nothing about what the ice will hold now." },
  fr:{ q:"Une route d'hiver que vous vouliez emprunter a été fermée. Quelle est la seule réponse acceptable ?",
       a:["Ne pas y rouler, car une route est fermée pour la sécurité de tous les voyageurs","Y rouler lentement si votre véhicule est léger","Y rouler si quelqu'un d'autre y a déjà laissé des traces","Y rouler seulement le jour"],
       e:"Une route est fermée parce que la surface ne peut plus supporter la circulation en sécurité. Les traces laissées par quelqu'un d'autre ne disent rien de ce que la glace supporte maintenant." },
  c:0 },
{ id:"ntr23", sec:"rules", topic:"ice",
  en:{ q:"The territory's winter advice includes keeping at least half a tank of fuel. What reason is given for it?",
       a:["A full tank makes the vehicle heavier and steadier on ice","Fuel is rationed along the winter roads","It keeps the engine from overheating","It stops the fuel lines from freezing"],
       e:"Fuel lines freeze when the tank runs low, and a stranded vehicle in the North can be a long way from help. The same advice covers a shovel, sand, booster cables, a flashlight, warm clothing, food and water, and a first-aid kit." },
  fr:{ q:"Les conseils d'hiver du territoire comprennent de garder au moins un demi-réservoir de carburant. Quelle raison en donne-t-on ?",
       a:["Un réservoir plein alourdit le véhicule et le rend plus stable sur la glace","Le carburant est rationné le long des routes d'hiver","Cela empêche le moteur de surchauffer","Cela empêche les conduites d'alimentation de geler"],
       e:"Les conduites d'alimentation gèlent quand le réservoir est bas, et un véhicule immobilisé dans le Nord peut être très loin de tout secours. Les mêmes conseils recommandent une pelle, du sable, des câbles de démarrage, une lampe de poche, des vêtements chauds, de la nourriture, de l'eau et une trousse de premiers soins." },
  c:3 },
{ id:"ntr24", sec:"rules", topic:"ice",
  en:{ q:"How much space does the territory ask you to keep behind the vehicle ahead on a winter highway?",
       a:["One car length for every ten kilometres an hour","At least four seconds","Two seconds, the same as in summer","Whatever feels comfortable at the speed you are driving"],
       e:"Four seconds gives you room to see and to stop on a surface that may be packed snow or glare ice. Counting seconds works at any speed, which is why it beats guessing at car lengths." },
  fr:{ q:"Quel espace le territoire demande-t-il de garder derrière le véhicule qui précède sur une route hivernale ?",
       a:["Une longueur de voiture par tranche de dix kilomètres à l'heure","Au moins quatre secondes","Deux secondes, comme en été","Ce qui vous semble confortable à la vitesse où vous roulez"],
       e:"Quatre secondes vous laissent le temps de voir et de vous arrêter sur une surface qui peut être de la neige durcie ou de la glace vive. Compter des secondes fonctionne à toute vitesse, ce qui vaut mieux que d'estimer des longueurs de voiture." },
  c:1 },
{ id:"ntr25", sec:"rules", topic:"gravel",
  en:{ q:"You are catching up to another vehicle on a dry gravel highway. What does the territory advise?",
       a:["Pass quickly, then close your windows afterwards","Stay behind until the road is paved again","Slow down as you pass to cut the dust and flying stones, and keep the windows closed with the vent fan running","Drive along the shoulder to stay out of the dust"],
       e:"Stones thrown up at speed break windshields and headlights, and a dust cloud hides whatever is inside it. Closed windows and the vent fan keep the inside of the vehicle liveable on a long gravel run." },
  fr:{ q:"Vous rattrapez un autre véhicule sur une route de gravier sèche. Que conseille le territoire ?",
       a:["Dépasser rapidement, puis fermer vos vitres ensuite","Rester derrière jusqu'au retour de l'asphalte","Ralentir en dépassant pour limiter la poussière et les cailloux projetés, et garder les vitres fermées avec la soufflerie en marche","Rouler sur l'accotement pour éviter la poussière"],
       e:"Les cailloux projetés à grande vitesse brisent pare-brise et phares, et un nuage de poussière cache ce qui s'y trouve. Les vitres fermées et la soufflerie gardent l'habitacle vivable sur un long parcours de gravier." },
  c:2 },
{ id:"ntr26", sec:"rules", topic:"gravel",
  en:{ q:"What should you know about the ferry crossings on Northwest Territories highways?",
       a:["There are four of them, they cost nothing, and vehicles board first come, first served","They have to be reserved a day ahead","They charge according to the length of the vehicle","They run right through the year"],
       e:"Four crossings operate, at no cost to the driver, and there is no booking: vehicles load in the order they arrive. Space on the last scheduled trip of the day is not guaranteed." },
  fr:{ q:"Que devez-vous savoir des traversiers sur les routes des Territoires du Nord-Ouest ?",
       a:["Il y en a quatre, ils sont gratuits et les véhicules embarquent selon leur ordre d'arrivée","Il faut réserver la veille","Le tarif dépend de la longueur du véhicule","Ils circulent toute l'année"],
       e:"Quatre traversées sont en service, sans frais pour le conducteur, et il n'y a pas de réservation : les véhicules embarquent dans l'ordre d'arrivée. La place n'est pas garantie sur le dernier départ de la journée." },
  c:0 },
{ id:"ntr27", sec:"rules", topic:"gravel",
  en:{ q:"You reach a ferry crossing during the first week of the season. What should you be ready for?",
       a:["A higher fare early in the season","A guaranteed place on every trip","A crossing reserved for local residents","Ice and changing water levels stopping the service with little or no warning"],
       e:"At the start and the end of the season the river decides. Service can stop with little or no notice, so build extra time into any trip that depends on a crossing." },
  fr:{ q:"Vous arrivez à une traversée durant la première semaine de la saison. À quoi devez-vous vous attendre ?",
       a:["À un tarif plus élevé en début de saison","À une place garantie à chaque départ","À une traversée réservée aux résidents","À des glaces et à des variations du niveau de l'eau qui interrompent le service avec peu ou pas de préavis"],
       e:"Au début et à la fin de la saison, c'est la rivière qui décide. Le service peut cesser avec peu ou pas de préavis : prévoyez du temps supplémentaire pour tout trajet qui dépend d'une traversée." },
  c:3 },
{ id:"ntr28", sec:"rules", topic:"emergencies",
  en:{ q:"Your vehicle breaks down on a remote winter highway. Why does the territory tell you to stay with it?",
       a:["Because leaving it is against the law","Because the heater works better when the vehicle is parked","Because the vehicle will be towed automatically","Because it gives you shelter and makes you far easier for rescuers to see"],
       e:"A vehicle is a windbreak, a landmark and a place to keep warm. Walking away from it in cold and blowing snow is how a breakdown turns into an emergency." },
  fr:{ q:"Votre véhicule tombe en panne sur une route hivernale isolée. Pourquoi le territoire dit-il d'y rester ?",
       a:["Parce que le quitter est contraire à la loi","Parce que le chauffage fonctionne mieux à l'arrêt","Parce que le véhicule sera remorqué automatiquement","Parce qu'il vous abrite et vous rend bien plus visible pour les secours"],
       e:"Un véhicule est un coupe-vent, un point de repère et un endroit où se réchauffer. S'en éloigner par grand froid et poudrerie transforme une panne en urgence." },
  c:3 },
{ id:"ntr29", sec:"rules", topic:"emergencies",
  en:{ q:"You are waiting for help in a stranded vehicle in deep cold. How should you use the engine?",
       a:["Run it without stopping so the inside never cools down","Run it sparingly, and keep the exhaust pipe clear of snow","Leave it switched off whatever happens","Run it only with the windows wide open"],
       e:"Snow packed around the exhaust pipe pushes fumes back into the vehicle. Running the engine in short spells also stretches the fuel you have, which matters when help is hours away." },
  fr:{ q:"Vous attendez du secours dans un véhicule immobilisé par grand froid. Comment devez-vous utiliser le moteur ?",
       a:["Le faire tourner sans arrêt pour que l'habitacle ne refroidisse jamais","Le faire tourner par courtes périodes et garder le tuyau d'échappement dégagé de la neige","Le laisser éteint quoi qu'il arrive","Le faire tourner seulement avec les vitres grandes ouvertes"],
       e:"La neige tassée autour du tuyau d'échappement renvoie les gaz dans le véhicule. Faire tourner le moteur par courtes périodes économise aussi le carburant, ce qui compte quand les secours sont à des heures de là." },
  c:1 },
{ id:"ntr30", sec:"rules", topic:"emergencies",
  en:{ q:"You have struck an animal on a highway and it is lying at the roadside. What does the territory tell you to do?",
       a:["Move it off the road yourself","Check whether it is still breathing before you call anybody","Stay away from it, move to the shoulder, and flag down a vehicle so the nearest Wildlife Officer can be called","Carry on to the next community without stopping"],
       e:"An injured animal is dangerous at close range, and a large one can still move. Bring your vehicle to the shoulder, keep well clear of the animal, and get word to a Wildlife Officer." },
  fr:{ q:"Vous avez heurté un animal sur une route et il gît au bord de la chaussée. Que dit le territoire de faire ?",
       a:["Le déplacer vous-même hors de la chaussée","Vérifier s'il respire encore avant d'appeler qui que ce soit","Ne pas vous en approcher, gagner l'accotement et faire signe à un véhicule pour que l'agent de la faune le plus proche soit prévenu","Continuer jusqu'à la prochaine collectivité sans vous arrêter"],
       e:"Un animal blessé est dangereux de près et un grand animal peut encore bouger. Rangez votre véhicule sur l'accotement, tenez-vous bien à l'écart et faites prévenir un agent de la faune." },
  c:2 }
);


/* ---------------------------------------------------------------------------
   The real Northwest Territories format, exactly as the territory publishes it.
   Unlike Prince Edward Island or Nunavut, nothing below is a standard of ours.
   The GNWT itself states 20 multiple-choice questions on the rules of the road
   and a separate test of 20 questions on road signage, and that you may not
   miss more than four questions in each test. That is 16 out of 20 on EACH
   test, not a combined score, and each test is passed or failed on its own.

   ON THE TIMER: the published wording is "the test lasts 30 minutes",
   singular, and the GNWT does not say whether that covers one test or both.
   We carry the 30 minutes because it is the only figure the government
   publishes, and we make no claim about which reading is the right one.

   FOR THE RECORD: at least one commercial practice site tells readers they
   need "25 of the questions correct". That is not how the real thing is
   scored: 25 out of 40 would still fail both halves.
   --------------------------------------------------------------------------- */
window.CQ_PROVINCE = {
  code: "NT",
  name: { en: "Northwest Territories", fr: "Territoires du Nord-Ouest" },
  licence: "Class 7 Learner",
  minutes: 30,
  sections: [
    { id: "signs", ask: 20, pass: 16,
      name: { en: "Road Signage Test",
              fr: "Examen de signalisation routière" } },
    { id: "rules", ask: 20, pass: 16,
      name: { en: "Rules of the Road Test",
              fr: "Examen sur le code de la route" } }
  ],
  handbook: { en: "NWT Basic Driver's Manual",
              fr: "Manuel du conducteur" },
  handbookUrl: "https://www.idmv.inf.gov.nt.ca/media/3b72b1b2-1ba9-4077-abd0-60d15a4ffe1d/FiOC-Q/Documents/Basic%20manual.pdf",
  bookingUrl: "https://www.idmv.inf.gov.nt.ca/Drivers/Drivers/Book-cancel-or-rebook-a-written-or-practical-examination",
  topics: [
    { id:"gdl",         en:"Graduated Licensing",             fr:"Permis par étapes" },
    { id:"learner",     en:"Learner Rules and Your Supervisor", fr:"Règles de l'apprenti et superviseur" },
    { id:"test",        en:"Your Licence and the Exams",      fr:"Votre permis et les examens" },
    { id:"penalties",   en:"Demerit Points and Penalties",    fr:"Points d'inaptitude et sanctions" },
    { id:"sharing",     en:"Sharing the Road",                fr:"Partager la route" },
    { id:"wildlife",    en:"Bison and Wildlife",              fr:"Bisons et faune" },
    { id:"ice",         en:"Ice Roads and Winter Driving",    fr:"Routes de glace et conduite hivernale" },
    { id:"gravel",      en:"Gravel Highways and Ferries",     fr:"Routes de gravier et traversiers" },
    { id:"emergencies", en:"Emergencies and Collisions",      fr:"Urgences et collisions" }
  ],
  questions: window.CQ_DRIVE_Q
};


/* Ten more rules questions, added 3 September 2026.
   Written from this jurisdiction's own official handbook, and
   chosen for what makes its rules different from its neighbours'.
   The French is written beside the English on purpose: see the
   note at the top of tools/newq/fr_qbank.py. */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"ntx1", sec:"rules",
  en:{ q:"What is the middle stage of the Northwest Territories licensing programme called?",
       a:["Novice","Level 2","Probationary Class 5P","G2"],
       e:"The Northwest Territories runs Learner Class 7, then Probationary Class 5P or 6P, then a full licence. The 5P name is unique to the territory." },
  fr:{ q:"Comment s'appelle l'étape intermédiaire du programme de permis des Territoires du Nord-Ouest ?",
       a:["Novice","Niveau 2","Probatoire de classe 5P","G2"],
       e:"Les Territoires du Nord-Ouest appliquent le permis d'apprenti de classe 7, puis le permis probatoire de classe 5P ou 6P, puis le permis complet. L'appellation 5P est propre au territoire." },
  c:2 },

{ id:"ntx2", sec:"rules",
  en:{ q:"Who may ride with a Northwest Territories Class 7 learner?",
       a:["Only the supervisor","Two passengers","Immediate family only","Anyone, up to the seat belts"],
       e:"A Class 7 learner may have no passengers other than the supervisor. Yukon next door allows two people including the co-driver." },
  fr:{ q:"Qui peut prendre place avec un apprenti de classe 7 des Territoires du Nord-Ouest ?",
       a:["Seulement le superviseur","Deux passagers","La famille immédiate seulement","N'importe qui, jusqu'au nombre de ceintures"],
       e:"Un apprenti de classe 7 ne peut avoir aucun passager autre que le superviseur. Le Yukon voisin permet deux personnes, y compris le co-conducteur." },
  c:0 },

{ id:"ntx3", sec:"rules",
  en:{ q:"When may a Northwest Territories Class 7 learner not drive?",
       a:["Midnight to 5 a.m.","11 p.m. to 6 a.m.","1 a.m. to 5 a.m.","There is no restriction"],
       e:"The Northwest Territories curfew is 11 p.m. to 6 a.m. — an hour earlier at each end than the midnight to 5 a.m. rule most provinces use." },
  fr:{ q:"Quand un apprenti de classe 7 des Territoires du Nord-Ouest ne peut-il pas conduire ?",
       a:["De minuit à 5 h","De 23 h à 6 h","De 1 h à 5 h","Il n'y a aucune restriction"],
       e:"Le couvre-feu des Territoires du Nord-Ouest va de 23 h à 6 h, soit une heure plus tôt de chaque côté que la règle de minuit à 5 h appliquée dans la plupart des provinces." },
  c:1 },

{ id:"ntx4", sec:"rules",
  en:{ q:"How much experience must a Northwest Territories learner's supervisor have?",
       a:["6 months","12 months","24 months with a full Class 5","5 years"],
       e:"The supervisor needs at least 24 months of experience with a full Class 5 licence, and both driver and supervisor must be at zero blood alcohol." },
  fr:{ q:"Quelle expérience le superviseur d'un apprenti des Territoires du Nord-Ouest doit-il avoir ?",
       a:["6 mois","12 mois","24 mois avec une classe 5 complète","5 ans"],
       e:"Le superviseur doit avoir au moins 24 mois d'expérience avec un permis de classe 5 complet, et le conducteur comme le superviseur doivent afficher un taux d'alcoolémie nul." },
  c:2 },

{ id:"ntx5", sec:"rules",
  en:{ q:"Which drivers must have no alcohol or drugs at all in the Northwest Territories?",
       a:["Only learners","Novice drivers and every driver under 22","Only drivers under 18","Nobody"],
       e:"Zero applies to novice drivers, to every driver under 22, and to certain commercial drivers. Any presence at all results in a suspension." },
  fr:{ q:"Quels conducteurs ne doivent avoir aucun alcool ni aucune drogue dans les Territoires du Nord-Ouest ?",
       a:["Seulement les apprentis","Les conducteurs novices et tout conducteur de moins de 22 ans","Seulement les conducteurs de moins de 18 ans","Personne"],
       e:"Le zéro s'applique aux conducteurs novices, à tout conducteur de moins de 22 ans et à certains conducteurs commerciaux. Toute présence entraîne une suspension." },
  c:1 },

{ id:"ntx6", sec:"rules",
  en:{ q:"What is the speed limit inside a Northwest Territories community when nothing is posted?",
       a:["50 km/h","40 km/h","60 km/h","90 km/h"],
       e:"Inside a settlement or municipality the maximum is 50 km/h unless otherwise posted. On a primary highway outside a community it is 90 km/h." },
  fr:{ q:"Quelle est la limite de vitesse dans une localité des Territoires du Nord-Ouest lorsque rien n'est affiché ?",
       a:["50 km/h","40 km/h","60 km/h","90 km/h"],
       e:"À l'intérieur d'une localité ou d'une municipalité, le maximum est de 50 km/h sauf indication contraire. Sur une route principale à l'extérieur d'une localité, il est de 90 km/h." },
  c:0 },

{ id:"ntx7", sec:"rules",
  en:{ q:"How many demerit points suspend a Northwest Territories learner or probationary driver?",
       a:["4","6","12","15"],
       e:"A Class 7 or 5P driver is suspended for 30 days at 6 points. A fully licensed driver has 15, and is contacted for an interview at 12." },
  fr:{ q:"Combien de points d'inaptitude entraînent la suspension d'un apprenti ou d'un conducteur probatoire des Territoires du Nord-Ouest ?",
       a:["4","6","12","15"],
       e:"Un conducteur de classe 7 ou 5P est suspendu 30 jours à 6 points. Un conducteur pleinement titulaire en a 15 et est convoqué en entrevue à 12 points." },
  c:1 },

{ id:"ntx8", sec:"rules",
  en:{ q:"Why are speed limits set on Northwest Territories ice roads?",
       a:["To save fuel","To reduce noise","To protect the structure of the ice","Because of wildlife only"],
       e:"A vehicle moving too fast pushes a pressure wave through the ice that can damage it. The limit protects the road itself, not just the driver." },
  fr:{ q:"Pourquoi des limites de vitesse sont-elles fixées sur les routes de glace des Territoires du Nord-Ouest ?",
       a:["Pour économiser du carburant","Pour réduire le bruit","Pour protéger la structure de la glace","Uniquement à cause de la faune"],
       e:"Un véhicule qui roule trop vite pousse une onde de pression dans la glace qui peut l'endommager. La limite protège la route elle-même, et pas seulement le conducteur." },
  c:2 },

{ id:"ntx9", sec:"rules",
  en:{ q:"What does the Northwest Territories advise carrying for winter road travel that a southern kit would not include?",
       a:["An extra pair of gloves","A road map","Bottled water","A satellite phone or two-way radio, and a sleeping bag rated to −20 °C"],
       e:"Winter road kits in the Northwest Territories include a satellite phone or two-way radio, an axe, flares and a sleeping bag rated to at least −20 °C. Help can be a very long way off." },
  fr:{ q:"Que conseillent d'emporter les Territoires du Nord-Ouest pour un trajet sur route d'hiver, qu'une trousse du Sud ne contiendrait pas ?",
       a:["Une paire de gants supplémentaire","Une carte routière","De l'eau embouteillée","Un téléphone satellite ou une radio bidirectionnelle, et un sac de couchage coté −20 °C"],
       e:"Les trousses pour routes d'hiver des Territoires du Nord-Ouest comprennent un téléphone satellite ou une radio bidirectionnelle, une hache, des fusées éclairantes et un sac de couchage coté au moins −20 °C. Les secours peuvent être très loin." },
  c:3 },

{ id:"ntx10", sec:"rules",
  en:{ q:"What must a driver check before setting out on a Northwest Territories ice road?",
       a:["The posted load limit and whether the road is open","Only the weather forecast","The price of fuel","Nothing — ice roads are always safe"],
       e:"Respect the posted load limit and never drive a closed road. Road status is published before you leave." },
  fr:{ q:"Que doit vérifier un conducteur avant de s'engager sur une route de glace des Territoires du Nord-Ouest ?",
       a:["La limite de charge affichée et l'état d'ouverture de la route","Seulement les prévisions météo","Le prix du carburant","Rien : les routes de glace sont toujours sûres"],
       e:"Respectez la limite de charge affichée et ne circulez jamais sur une route fermée. L'état des routes est publié avant votre départ." },
  c:0 }
);
