/* canada-quiz.com — NUNAVUT Class 7 Learner practice data
   60 original bilingual questions (30 road signs + 30 rules of the road).
   Written in our own words from the free Nunavut Driver's Manual and Nunavut's
   Restricted Driver's Manual, the Service Nunavut driver licensing pages on
   gov.nu.ca, and the Traffic Safety Act annual reports tabled in the
   Legislative Assembly of Nunavut.
   Not affiliated with the Motor Vehicles Division or the Government of Nunavut.

   The quiz code lives in js/driving-engine.js and never changes per province. */
window.CQ_DRIVE_Q = [];

/* ---------- road signs ---------- */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"nus1", sec:"signs", sign:"stop",
  en:{ q:"You come to this sign where two gravel streets meet in the community. What does it require?",
       a:["Slow down, look, then keep rolling","A stop only when another vehicle is in sight","A complete stop every time, then go when the way is clear","A tap on the horn before crossing"],
       e:"Stop means the wheels stop turning, whether or not anyone else is around. Stop first, look both ways, and move off only when nothing is coming." },
  fr:{ q:"Vous arrivez à ce panneau là où deux rues de gravier se croisent dans la communauté. Qu'exige-t-il ?",
       a:["Ralentir, regarder, puis continuer à rouler","Un arrêt seulement si un autre véhicule est en vue","Un arrêt complet chaque fois, puis repartir quand la voie est libre","Un coup de klaxon avant de traverser"],
       e:"Un arrêt signifie que les roues cessent de tourner, qu'il y ait quelqu'un ou non. Arrêtez-vous d'abord, regardez des deux côtés et ne repartez que si rien ne vient." },
  c:2 },
{ id:"nus2", sec:"signs", sign:"yield",
  en:{ q:"This sign faces you as you join a road that already carries traffic. What is expected?",
       a:["Come to a full stop and count to three","Give way to the vehicles and people already on the road","Take the gap and let the others adjust","Signal and hold your speed"],
       e:"Yield means give way. Slow down enough that you could stop, and go only when nobody else has to brake or steer around you." },
  fr:{ q:"Ce panneau vous fait face au moment de vous engager sur une route déjà occupée. Qu'attend-on de vous ?",
       a:["Faire un arrêt complet et compter jusqu'à trois","Céder le passage aux véhicules et aux personnes déjà sur la route","Prendre l'espace libre et laisser les autres s'ajuster","Mettre le clignotant et garder votre vitesse"],
       e:"Céder le passage veut dire laisser passer. Ralentissez assez pour pouvoir vous arrêter et n'avancez que si personne d'autre n'est obligé de freiner ou de vous contourner." },
  c:1 },
{ id:"nus3", sec:"signs", sign:"speed-50",
  en:{ q:"This sign is posted on a street inside a Nunavut community. What is it telling you?",
       a:["50 km/h is the most you may drive here","50 km/h is a suggestion in good weather","Traffic ahead is moving at 50 km/h","Slow vehicles must keep to 50 km/h"],
       e:"Inside communities the basic limit in Nunavut is 50 km/h, or whatever is posted. It is a ceiling for ideal conditions, not a target: dust, ice or children playing all call for less." },
  fr:{ q:"Ce panneau est installé dans une rue d'une communauté du Nunavut. Que vous indique-t-il ?",
       a:["50 km/h est la vitesse maximale permise ici","50 km/h est une suggestion par beau temps","La circulation devant roule à 50 km/h","Les véhicules lents doivent rouler à 50 km/h"],
       e:"Dans les communautés, la limite de base au Nunavut est de 50 km/h, ou celle qui est affichée. C'est un plafond pour des conditions idéales, pas un objectif : la poussière, la glace ou des enfants qui jouent commandent moins." },
  c:0 },
{ id:"nus4", sec:"signs", sign:"speed-limit-begins",
  en:{ q:"You pass this sign on your way out of the community. From when does the number on it apply?",
       a:["Only after the last house","From the next intersection","When traffic allows it","From the sign itself, onwards"],
       e:"A new limit starts at the sign, not somewhere past it. Outside communities the basic Nunavut limit is 90 km/h unless a sign says otherwise, so read the sign instead of assuming." },
  fr:{ q:"Vous croisez ce panneau en sortant de la communauté. À partir de quand le chiffre s'applique-t-il ?",
       a:["Seulement après la dernière maison","À partir de la prochaine intersection","Quand la circulation le permet","Dès le panneau lui-même"],
       e:"Une nouvelle limite commence au panneau, pas plus loin. À l'extérieur des communautés, la limite de base au Nunavut est de 90 km/h, sauf indication contraire : lisez le panneau au lieu de supposer." },
  c:3 },
{ id:"nus5", sec:"signs", sign:"no-entry",
  en:{ q:"This red and white sign faces you at the end of a short street. What does it mean?",
       a:["The street is closed for repairs","You may not drive in here","Only residents may drive in","Entry is allowed at walking speed"],
       e:"Do not enter. Something about that street, a one-way flow or a restricted yard, means traffic never comes in from your side." },
  fr:{ q:"Ce panneau rouge et blanc vous fait face au bout d'une petite rue. Que signifie-t-il ?",
       a:["La rue est fermée pour des travaux","Vous ne pouvez pas y entrer","Seuls les résidents peuvent y entrer","L'entrée est permise au pas"],
       e:"Accès interdit. Quelque chose sur cette rue, un sens unique ou une cour à accès restreint, fait que la circulation n'y entre jamais de votre côté." },
  c:1 },
{ id:"nus6", sec:"signs", sign:"one-way",
  en:{ q:"How may you drive on a street where this sign is posted?",
       a:["In either direction, keeping right","In either direction if you are turning","Only in the direction the arrow points","Only when no other vehicle is present"],
       e:"Every lane on a one-way street runs the same way. Once you have turned onto it you must be travelling the way the arrow points." },
  fr:{ q:"Comment pouvez-vous circuler dans une rue où ce panneau est affiché ?",
       a:["Dans les deux sens, en tenant la droite","Dans les deux sens si vous tournez","Seulement dans le sens de la flèche","Seulement si aucun autre véhicule n'est présent"],
       e:"Sur une rue à sens unique, toutes les voies vont dans la même direction. Une fois que vous y avez tourné, vous devez rouler dans le sens de la flèche." },
  c:2 },
{ id:"nus7", sec:"signs", sign:"no-parking",
  en:{ q:"You want to leave your vehicle where this sign stands while you go inside a building. May you?",
       a:["No, though you may stop briefly to let someone out","Yes, for up to fifteen minutes","Yes, if the engine is left running","Yes, outside business hours"],
       e:"No parking bans leaving the vehicle there, but a short stop to pick somebody up or drop them off is still allowed. Read the hours on any tab under the sign." },
  fr:{ q:"Vous voulez laisser votre véhicule là où se trouve ce panneau pendant que vous entrez dans un bâtiment. Le pouvez-vous ?",
       a:["Non, mais vous pouvez vous arrêter brièvement pour laisser descendre quelqu'un","Oui, jusqu'à quinze minutes","Oui, si le moteur reste en marche","Oui, en dehors des heures d'ouverture"],
       e:"Le stationnement interdit défend de laisser le véhicule là, mais un court arrêt pour faire monter ou descendre quelqu'un reste permis. Lisez les heures inscrites sur la plaquette sous le panneau." },
  c:0 },
{ id:"nus8", sec:"signs", sign:"no-passing",
  en:{ q:"What are you being told not to do where this sign is posted?",
       a:["Do not stop on this stretch","Do not turn around here","Do not go faster than the posted limit","Do not drive around the vehicle ahead of you"],
       e:"No passing. On a narrow or blind stretch there is no room to pull out and get back in, and in Nunavut there is no painted line to show you where your side of the road ends." },
  fr:{ q:"Que vous interdit-on de faire là où ce panneau est affiché ?",
       a:["Vous arrêter sur ce tronçon","Faire demi-tour ici","Rouler plus vite que la limite affichée","Contourner le véhicule qui vous précède"],
       e:"Dépassement interdit. Sur un tronçon étroit ou sans visibilité, il n'y a pas d'espace pour sortir et se rabattre, et au Nunavut aucune ligne peinte n'indique où se termine votre côté de la chaussée." },
  c:3 },
{ id:"nus9", sec:"signs", sign:"ped-crossover",
  en:{ q:"Someone steps onto the road at this sign as you approach. What must you do?",
       a:["Drive slowly around behind them","Stop and wait until they have finished crossing","Flash your headlights and carry on","Stop only if they raise a hand"],
       e:"Wait until the person is safely across before you move. Never drive past another vehicle that has stopped here: it may be hiding somebody you cannot see." },
  fr:{ q:"Une personne s'engage sur la chaussée à ce panneau pendant que vous approchez. Que devez-vous faire ?",
       a:["Passer lentement derrière elle","Vous arrêter et attendre qu'elle ait fini de traverser","Faire un appel de phares et continuer","Vous arrêter seulement si elle lève la main"],
       e:"Attendez que la personne ait terminé sa traversée avant d'avancer. Ne dépassez jamais un véhicule arrêté ici : il cache peut-être quelqu'un que vous ne voyez pas." },
  c:1 },
{ id:"nus10", sec:"signs", sign:"warn-slippery",
  en:{ q:"Cold rain has been falling on the road where this yellow diamond stands. What is it warning you about?",
       a:["Loose gravel has been spread","The road narrows","The surface can be slippery","A vehicle wash is ahead"],
       e:"A slippery surface takes far longer to stop on. Ease off early, steer smoothly, and leave much more space than usual behind the vehicle ahead." },
  fr:{ q:"Une pluie froide tombe sur la route où se dresse ce losange jaune. De quoi vous avertit-il ?",
       a:["Du gravier meuble a été épandu","La chaussée se rétrécit","La surface peut être glissante","Un lave-auto se trouve devant"],
       e:"Une chaussée glissante allonge beaucoup la distance de freinage. Relâchez l'accélérateur tôt, tournez le volant en douceur et laissez bien plus d'espace derrière le véhicule qui vous précède." },
  c:2 },
{ id:"nus11", sec:"signs", sign:"warn-bump",
  en:{ q:"This yellow sign appears on a gravel road. What should you expect just ahead?",
       a:["A rough spot that can throw the vehicle off line","A speed bump you may ignore","A change of surface to pavement","A stretch where passing is allowed"],
       e:"Slow down before you reach it. Hitting a bump at speed can bounce the steering out of your hands, and on loose gravel that easily becomes a skid." },
  fr:{ q:"Ce panneau jaune apparaît sur une route de gravier. À quoi devez-vous vous attendre juste devant ?",
       a:["Une irrégularité qui peut déporter le véhicule","Un ralentisseur que vous pouvez ignorer","Un passage au revêtement asphalté","Un tronçon où le dépassement est permis"],
       e:"Ralentissez avant de l'atteindre. Frapper une bosse à vitesse peut vous arracher le volant des mains, et sur du gravier meuble cela devient vite un dérapage." },
  c:0 },
{ id:"nus12", sec:"signs", sign:"warn-pavement-ends",
  en:{ q:"You are driving on a paved stretch and this sign appears. What happens next?",
       a:["The road ends completely","A bridge deck begins","A passing lane opens","The pavement gives way to gravel"],
       e:"Slow down before the change, not after it. Gravel offers much less grip than pavement, so braking and steering both need more room from that point on." },
  fr:{ q:"Vous roulez sur un tronçon asphalté et ce panneau apparaît. Que se passe-t-il ensuite ?",
       a:["La route se termine complètement","Un tablier de pont commence","Une voie de dépassement s'ouvre","Le revêtement cède la place au gravier"],
       e:"Ralentissez avant le changement, pas après. Le gravier offre bien moins d'adhérence que l'asphalte : le freinage comme la direction demandent alors plus d'espace." },
  c:3 },
{ id:"nus13", sec:"signs", sign:"warn-steep-hill",
  en:{ q:"What should you do before starting down the hill this sign warns about?",
       a:["Shift into neutral to save fuel","Choose a lower gear and check your speed early","Speed up so you can coast at the bottom","Hold the brake pedal down the whole way"],
       e:"A lower gear lets the engine hold the vehicle back. Riding the brakes all the way down heats them until they fade, exactly when you need them most." },
  fr:{ q:"Que devriez-vous faire avant d'entamer la descente annoncée par ce panneau ?",
       a:["Passer au point mort pour économiser du carburant","Choisir un rapport inférieur et contrôler votre vitesse tôt","Accélérer pour vous laisser rouler en bas","Garder le pied sur le frein tout le long"],
       e:"Un rapport inférieur laisse le moteur retenir le véhicule. Freiner sans arrêt jusqu'en bas fait chauffer les freins jusqu'à ce qu'ils perdent leur efficacité, juste au moment où vous en avez le plus besoin." },
  c:1 },
{ id:"nus14", sec:"signs", sign:"warn-curve-right",
  en:{ q:"Where should your braking be done for the curve this sign announces?",
       a:["Halfway around the curve","At the sharpest point","Before you enter it, while the wheels are still straight","After the curve straightens out"],
       e:"Brake in a straight line, then steer. Braking and turning at the same time on gravel is how vehicles end up sideways." },
  fr:{ q:"Où devez-vous freiner pour le virage annoncé par ce panneau ?",
       a:["À mi-chemin dans le virage","Au point le plus serré","Avant d'y entrer, les roues encore droites","Après la sortie du virage"],
       e:"Freinez en ligne droite, puis tournez. Freiner et braquer en même temps sur du gravier, c'est ainsi que des véhicules se retrouvent en travers." },
  c:2 },
{ id:"nus15", sec:"signs", sign:"warn-pedestrian",
  en:{ q:"This yellow sign is posted on a street with no sidewalk. What does it ask of you?",
       a:["Expect people to be walking on or near the road","Expect a bus stop","Expect a parking area","Expect a delivery entrance"],
       e:"Where there is no sidewalk, people walk on the road itself. Slow down, cover the brake and be ready for somebody to step out from between parked vehicles." },
  fr:{ q:"Ce panneau jaune est installé dans une rue sans trottoir. Que vous demande-t-il ?",
       a:["Vous attendre à des personnes qui marchent sur la chaussée ou tout près","Vous attendre à un arrêt d'autobus","Vous attendre à une aire de stationnement","Vous attendre à une entrée de livraison"],
       e:"Là où il n'y a pas de trottoir, les gens marchent sur la chaussée même. Ralentissez, couvrez le frein et soyez prêt à voir quelqu'un surgir entre des véhicules stationnés." },
  c:0 },
{ id:"nus16", sec:"signs", sign:"warn-playground",
  en:{ q:"What does this sign tell you about the area you are entering?",
       a:["Parking is reserved for families","Children are not allowed near the road","The area is closed in winter","Children may run out without looking"],
       e:"Nunavut asks drivers to keep to the posted speed near playgrounds and schools, and to a reasonable and prudent speed where nothing is posted. Children judge distance and speed poorly." },
  fr:{ q:"Que vous apprend ce panneau sur le secteur où vous entrez ?",
       a:["Le stationnement est réservé aux familles","Les enfants n'ont pas le droit d'être près de la chaussée","Le secteur est fermé l'hiver","Des enfants peuvent surgir sans regarder"],
       e:"Le Nunavut demande de respecter la vitesse affichée près des terrains de jeu et des écoles, et une vitesse raisonnable et prudente s'il n'y a rien d'affiché. Les enfants évaluent mal la distance et la vitesse." },
  c:3 },
{ id:"nus17", sec:"signs", sign:"warn-school-zone",
  en:{ q:"You are approaching the zone marked by this sign at the start of the school day. What is expected of you?",
       a:["Use your horn to warn children","Drive at the posted speed, or slowly and carefully if none is posted","Stop at every corner","Keep to the centre of the road"],
       e:"School zones in Nunavut are driven at the posted speed, and where no speed is posted the standard is a reasonable and prudent one. Watch for children crossing between vehicles." },
  fr:{ q:"Vous approchez de la zone indiquée par ce panneau au début de la journée d'école. Qu'attend-on de vous ?",
       a:["Klaxonner pour avertir les enfants","Rouler à la vitesse affichée, ou lentement et prudemment s'il n'y a rien d'affiché","Vous arrêter à chaque coin de rue","Rouler au centre de la chaussée"],
       e:"Les zones scolaires au Nunavut se parcourent à la vitesse affichée ; s'il n'y en a pas d'affichée, la norme est une vitesse raisonnable et prudente. Surveillez les enfants qui traversent entre les véhicules." },
  c:1 },
{ id:"nus18", sec:"signs", sign:"warn-t-intersection",
  en:{ q:"This sign stands ahead of you on a community road. What is about to happen?",
       a:["The road becomes one way","A bridge is coming","The road you are on ends and you must turn","A parking area opens on the right"],
       e:"The road ends in a T. Slow down early so you can choose a direction and turn, instead of sliding straight on into whatever lies beyond." },
  fr:{ q:"Ce panneau se trouve devant vous sur une route de communauté. Que va-t-il se passer ?",
       a:["La route devient à sens unique","Un pont approche","La route où vous êtes se termine et vous devez tourner","Une aire de stationnement s'ouvre à droite"],
       e:"La route se termine en T. Ralentissez tôt pour choisir une direction et tourner, au lieu de glisser tout droit vers ce qui se trouve au-delà." },
  c:2 },
{ id:"nus19", sec:"signs", sign:"hazard-marker",
  en:{ q:"A row of these markers stands where the road narrows beside a building. What are they for?",
       a:["They mark an obstacle you must keep away from","They mark a place to park","They mark the boundary of the community","They mark a bus route"],
       e:"A hazard marker shows something solid at the edge of the travelled road. The stripes slope down towards the side you should pass on." },
  fr:{ q:"Une rangée de ces marqueurs se dresse là où la route se rétrécit près d'un bâtiment. À quoi servent-ils ?",
       a:["Ils signalent un obstacle dont vous devez vous écarter","Ils indiquent un endroit où stationner","Ils marquent la limite de la communauté","Ils indiquent un circuit d'autobus"],
       e:"Un marqueur d'obstacle signale quelque chose de solide au bord de la partie carrossable. Les bandes descendent vers le côté par lequel vous devez passer." },
  c:0 },
{ id:"nus20", sec:"signs", sign:"temp-construction",
  en:{ q:"Why are the signs around a work area orange rather than yellow?",
       a:["Orange signs are only advice","Orange marks a temporary warning, for work going on now","Orange signs apply only at night","Orange means the road is closed"],
       e:"Orange marks a condition that was not there last week and may be gone next week: crews, equipment and people working close to moving traffic." },
  fr:{ q:"Pourquoi les panneaux autour d'une zone de travaux sont-ils orange plutôt que jaunes ?",
       a:["Les panneaux orange ne sont que des conseils","L'orange signale un avertissement temporaire, pour des travaux en cours","Les panneaux orange s'appliquent seulement la nuit","L'orange signifie que la route est fermée"],
       e:"L'orange indique une situation qui n'existait pas la semaine dernière et qui aura peut-être disparu la semaine prochaine : des équipes, de la machinerie et des personnes qui travaillent tout près de la circulation." },
  c:1 },
{ id:"nus21", sec:"signs", sign:"temp-flagger",
  en:{ q:"This sign warns that a person will be directing traffic ahead. Whose instructions do you follow there?",
       a:["Whichever sign was posted before the work started","Your own judgement about the safest path","The person directing traffic, ahead of any sign","The vehicle in front of you"],
       e:"A traffic control person stands in the middle of a work area that changes by the hour and can see what the signs cannot. Their signals come first." },
  fr:{ q:"Ce panneau annonce qu'une personne dirigera la circulation plus loin. À qui obéissez-vous à cet endroit ?",
       a:["Au panneau qui était en place avant les travaux","À votre propre jugement sur le trajet le plus sûr","À la personne qui dirige la circulation, avant tout panneau","Au véhicule qui vous précède"],
       e:"Le signaleur se tient au milieu d'une zone de travaux qui change d'heure en heure et voit ce que les panneaux ne peuvent pas montrer. Ses signaux passent en premier." },
  c:2 },
{ id:"nus22", sec:"signs", sign:"temp-detour",
  en:{ q:"The road ahead is dug up and this sign points to the side. What should you do?",
       a:["Follow the marked route around the closed section","Wait beside the work until it reopens","Drive through slowly at your own risk","Turn back the way you came"],
       e:"A detour is a temporary route around a closure. Follow the signs the whole way; they normally bring you back to the same road past the work." },
  fr:{ q:"La route devant est éventrée et ce panneau pointe sur le côté. Que devez-vous faire ?",
       a:["Suivre l'itinéraire indiqué pour contourner le tronçon fermé","Attendre à côté des travaux jusqu'à la réouverture","Passer lentement à vos risques","Rebrousser chemin"],
       e:"Un détour est un itinéraire temporaire qui contourne une fermeture. Suivez les panneaux jusqu'au bout : ils vous ramènent normalement sur la même route après les travaux." },
  c:0 },
{ id:"nus23", sec:"signs", sign:"info-hospital",
  en:{ q:"A passenger in your vehicle needs medical care. What does this blue sign point to?",
       a:["A pharmacy","A fire hall","A police detachment","A hospital"],
       e:"Blue signs point to services rather than telling you how to drive. Following this series of signs is faster and safer than trying to navigate from memory while worried." },
  fr:{ q:"Un passager de votre véhicule a besoin de soins. Vers quoi ce panneau bleu vous dirige-t-il ?",
       a:["Une pharmacie","Une caserne de pompiers","Un détachement de police","Un hôpital"],
       e:"Les panneaux bleus indiquent des services plutôt que la façon de conduire. Suivre cette série de panneaux est plus rapide et plus sûr que de chercher de mémoire quand on est inquiet." },
  c:3 },
{ id:"nus24", sec:"signs", sign:"info-gas",
  en:{ q:"You are low on fuel and see this sign. What is it showing?",
       a:["Where fuel can be bought","A vehicle inspection station","A truck route","A rest area"],
       e:"Fuel is not sold everywhere, so it is worth filling up before a long trip rather than once the gauge is already low." },
  fr:{ q:"Vous manquez de carburant et voyez ce panneau. Qu'indique-t-il ?",
       a:["L'endroit où acheter du carburant","Un poste d'inspection des véhicules","Un itinéraire pour camions","Une aire de repos"],
       e:"Le carburant ne se vend pas partout : mieux vaut faire le plein avant un long trajet plutôt qu'une fois la jauge déjà basse." },
  c:0 },
{ id:"nus25", sec:"signs", sign:"info-food",
  en:{ q:"You have been driving for hours and see this blue sign. What does it mark?",
       a:["A grocery delivery point","A place to stay overnight","Somewhere to stop and eat","A community hall"],
       e:"Service signs exist so drivers can plan a break instead of pushing on while tired. Stopping to eat does more for your alertness than opening a window." },
  fr:{ q:"Vous conduisez depuis des heures et voyez ce panneau bleu. Que signale-t-il ?",
       a:["Un point de livraison d'épicerie","Un endroit où passer la nuit","Un endroit où s'arrêter pour manger","Une salle communautaire"],
       e:"Les panneaux de services existent pour que les conducteurs planifient une pause au lieu de continuer fatigués. S'arrêter pour manger fait plus pour la vigilance qu'une fenêtre ouverte." },
  c:2 },
{ id:"nus26", sec:"signs", sign:"info-accessible",
  en:{ q:"Who may leave a vehicle in a space marked with this sign?",
       a:["Anyone, for a short stop","Delivery vehicles","Anyone outside business hours","Only a vehicle displaying a valid accessible parking permit"],
       e:"The space is wider than the others for a reason: somebody needs that room beside the vehicle to get out. Using it without a permit takes the room away." },
  fr:{ q:"Qui peut laisser un véhicule dans une place portant ce panneau ?",
       a:["N'importe qui, pour un court arrêt","Les véhicules de livraison","N'importe qui en dehors des heures d'ouverture","Seulement un véhicule qui affiche une vignette de stationnement accessible valide"],
       e:"Cette place est plus large que les autres pour une raison : il faut cet espace à côté du véhicule pour en sortir. L'occuper sans vignette enlève cet espace." },
  c:3 },
{ id:"nus27", sec:"signs", sign:"light-red",
  en:{ q:"What does a steady light of this colour require?",
       a:["Slow down and pass when the way is clear","Stop before the intersection and wait for the light to change","Stop only if another vehicle is crossing","Carry on if you are already close to it"],
       e:"A steady red means stop and stay stopped until the light changes. Where no line is painted on the road, stop before the part of the intersection other traffic uses." },
  fr:{ q:"Qu'exige un feu fixe de cette couleur ?",
       a:["Ralentir et passer quand la voie est libre","Vous arrêter avant l'intersection et attendre que le feu change","Vous arrêter seulement si un autre véhicule traverse","Continuer si vous en êtes déjà tout près"],
       e:"Un feu rouge fixe veut dire s'arrêter et rester arrêté jusqu'au changement. Là où aucune ligne n'est peinte sur la chaussée, arrêtez-vous avant la partie de l'intersection qu'utilise la circulation." },
  c:1 },
{ id:"nus28", sec:"signs", sign:"light-amber",
  en:{ q:"This light comes on while you are approaching the intersection. What is the rule?",
       a:["Speed up to clear the intersection","Treat it the same as a green light","Stop only if a vehicle is waiting to cross","Stop if you can do it safely, because the red is coming"],
       e:"Amber means the light is about to turn red. Stop, unless you are so close that braking would be more dangerous than carrying through." },
  fr:{ q:"Ce feu s'allume pendant que vous approchez de l'intersection. Quelle est la règle ?",
       a:["Accélérer pour franchir l'intersection","Le traiter comme un feu vert","Vous arrêter seulement si un véhicule attend pour traverser","Vous arrêter si vous pouvez le faire en sécurité, car le rouge s'en vient"],
       e:"Le feu jaune annonce le rouge. Arrêtez-vous, sauf si vous êtes si près que freiner serait plus dangereux que de continuer." },
  c:3 },
{ id:"nus29", sec:"signs", sign:"mark-solid-yellow",
  en:{ q:"Nunavut roads carry no painted lines, but your licence lets you drive elsewhere. What do these two solid yellow lines mean?",
       a:["Parking is allowed on both sides","The road is one way","Neither direction may pass here","Only the left lane may be used"],
       e:"A double solid line separates traffic going opposite ways and tells both sides that passing is not permitted. Nunavut has no road markings at all, so this is worth learning before you drive in another jurisdiction." },
  fr:{ q:"Les routes du Nunavut ne portent aucune ligne peinte, mais votre permis vous permet de conduire ailleurs. Que signifient ces deux lignes jaunes continues ?",
       a:["Le stationnement est permis des deux côtés","La route est à sens unique","Aucun des deux sens ne peut dépasser ici","Seule la voie de gauche peut être utilisée"],
       e:"Une ligne double continue sépare les circulations opposées et interdit le dépassement des deux côtés. Le Nunavut n'a aucun marquage routier : cela vaut donc la peine d'être appris avant de conduire ailleurs." },
  c:2 },
{ id:"nus30", sec:"signs", sign:"mark-white-lane",
  en:{ q:"On a road outside the territory you meet a broken white line between two lanes. What does it tell you?",
       a:["The lane beside you is closed","Both lanes go the same way and you may change lanes when it is safe","Traffic beside you comes the other way","You must stay in your lane until the next intersection"],
       e:"White lines separate traffic travelling the same way, and a broken one may be crossed. No such line exists anywhere in Nunavut, where you judge your position from the edges of the road instead." },
  fr:{ q:"Sur une route à l'extérieur du territoire, vous rencontrez une ligne blanche discontinue entre deux voies. Que vous indique-t-elle ?",
       a:["La voie à côté de vous est fermée","Les deux voies vont dans le même sens et vous pouvez changer de voie quand c'est sécuritaire","La circulation à côté de vous vient en sens inverse","Vous devez rester dans votre voie jusqu'à la prochaine intersection"],
       e:"Les lignes blanches séparent des circulations qui vont dans le même sens, et une ligne discontinue peut être franchie. Aucune ligne de ce genre n'existe au Nunavut, où l'on juge sa position d'après les bords de la chaussée." },
  c:1 }
);

/* ---------- rules of the road ---------- */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"nur1", sec:"rules", topic:"licence",
  en:{ q:"What is the youngest age at which you may hold a Class 7 learner licence in Nunavut?",
       a:["15 years old","16 years old","17 years old","18 years old"],
       e:"Nunavut sets 15 as the minimum age for the Class 7 learner licence. Some practice sites print 16, which is the minimum age for a full Class 5, not for the learner licence." },
  fr:{ q:"À quel âge minimum pouvez-vous détenir un permis d'apprenti de classe 7 au Nunavut ?",
       a:["15 ans","16 ans","17 ans","18 ans"],
       e:"Le Nunavut fixe à 15 ans l'âge minimum du permis d'apprenti de classe 7. Certains sites de pratique indiquent 16 ans, ce qui est l'âge minimum de la classe 5 complète, pas celui du permis d'apprenti." },
  c:0 },
{ id:"nur2", sec:"rules", topic:"licence",
  en:{ q:"What does a Class 7 licence allow you to do?",
       a:["Drive alone in anything up to a light truck","Operate any vehicle in Class 5 or Class 6 while you are learning to operate it","Drive a bus carrying fewer than 24 passengers","Drive during daylight hours only"],
       e:"The Class 7 is a learner licence: it covers the vehicles of Class 5 and Class 6 while you are learning them, and it is used with an accompanying driver rather than on your own." },
  fr:{ q:"Que vous permet un permis de classe 7 ?",
       a:["Conduire seul tout véhicule jusqu'à une camionnette","Conduire tout véhicule de classe 5 ou de classe 6 pendant que vous apprenez à le conduire","Conduire un autobus de moins de 24 passagers","Conduire seulement pendant les heures de clarté"],
       e:"La classe 7 est un permis d'apprenti : elle couvre les véhicules des classes 5 et 6 pendant l'apprentissage, et elle s'utilise avec un conducteur accompagnateur plutôt que seul." },
  c:1 },
{ id:"nur3", sec:"rules", topic:"licence",
  en:{ q:"How is the Nunavut knowledge test put together?",
       a:["One paper covering everything at once","Two papers written on separate days","Two parts at one sitting: rules of the road and safe driving, and sign identification","A spoken interview only"],
       e:"Nunavut's manual describes an examination in two parts taken together: one on the rules of the road and safe driving practices, and one on identifying signs." },
  fr:{ q:"Comment l'examen théorique du Nunavut est-il composé ?",
       a:["Une seule épreuve couvrant tout à la fois","Deux épreuves écrites des jours différents","Deux parties à la même séance : le code de la route et la conduite sécuritaire, puis la reconnaissance des panneaux","Un entretien oral seulement"],
       e:"Le manuel du Nunavut décrit un examen en deux parties passées ensemble : une sur le code de la route et la conduite sécuritaire, et une sur l'identification des panneaux." },
  c:2 },
{ id:"nur4", sec:"rules", topic:"licence",
  en:{ q:"You pass the sign identification part but fail the other one. What do you have to rewrite?",
       a:["Both parts, from the beginning","Nothing, a pass on one part carries the other","A road test instead","Only the part you failed"],
       e:"Nunavut has you rewrite only the part that was failed. The part you passed stands, so your studying can go where you actually came up short." },
  fr:{ q:"Vous réussissez la partie sur les panneaux, mais échouez à l'autre. Que devez-vous reprendre ?",
       a:["Les deux parties, depuis le début","Rien, la réussite d'une partie emporte l'autre","Un examen pratique à la place","Seulement la partie échouée"],
       e:"Au Nunavut, on ne reprend que la partie échouée. Celle que vous avez réussie demeure acquise : vos révisions peuvent donc porter là où vous avez vraiment manqué." },
  c:3 },
{ id:"nur5", sec:"rules", topic:"licence",
  en:{ q:"Which stages does a new Nunavut driver pass through after the learner licence?",
       a:["None, because Nunavut has no graduated licensing programme; a Class 7 holder who passes the road test moves to a full Class 5","A six-month probationary stage with a night curfew","Two novice stages of one year each","A three-stage programme that ends at age 18"],
       e:"Graduated licensing with stages, curfews and passenger limits is common elsewhere in Canada, but Nunavut publishes no such programme. Anything you read about Nunavut learner stages has been borrowed from another jurisdiction." },
  fr:{ q:"Par quelles étapes un nouveau conducteur du Nunavut passe-t-il après le permis d'apprenti ?",
       a:["Aucune, car le Nunavut n'a pas de programme de permis par étapes ; le titulaire d'une classe 7 qui réussit l'examen pratique obtient une classe 5 complète","Une étape probatoire de six mois avec couvre-feu la nuit","Deux étapes de novice d'un an chacune","Un programme en trois étapes se terminant à 18 ans"],
       e:"Le permis par étapes, avec ses paliers, ses couvre-feux et ses limites de passagers, est courant ailleurs au Canada, mais le Nunavut n'en publie aucun. Ce qu'on lit sur des étapes au Nunavut est emprunté à un autre territoire." },
  c:0 },
{ id:"nur6", sec:"rules", topic:"licence",
  en:{ q:"Who may sit with you while you drive on a Class 7 licence?",
       a:["Any adult who has driven before","Someone who holds a valid driver's licence and is authorised under the Act","Any passenger aged 18 or over","Nobody is needed once you have practised enough"],
       e:"The person beside you must genuinely be licensed and authorised to accompany you, and the examiner may ask to see that licence. Nunavut publishes no minimum age or years of experience for that person." },
  fr:{ q:"Qui peut prendre place à côté de vous quand vous conduisez avec un permis de classe 7 ?",
       a:["N'importe quel adulte ayant déjà conduit","Une personne titulaire d'un permis de conduire valide et autorisée en vertu de la Loi","N'importe quel passager de 18 ans ou plus","Personne n'est nécessaire une fois que vous avez assez pratiqué"],
       e:"La personne à côté de vous doit réellement détenir un permis et être autorisée à vous accompagner, et l'examinateur peut demander à voir ce permis. Le Nunavut ne publie ni âge minimum ni années d'expérience pour cette personne." },
  c:1 },
{ id:"nur7", sec:"rules", topic:"applying",
  en:{ q:"Your community has no Motor Vehicles Office. How are driver services delivered there?",
       a:["You must travel to Iqaluit for every service","Everything is handled by mail","Through the Government Liaison Officer programme, which has an office in every community","Only during one yearly visit by an examiner"],
       e:"Nunavut has Motor Vehicles Offices in Iqaluit, Rankin Inlet and Gjoa Haven, and Government Liaison Offices in all twenty-five communities support the rest of the territory. Some examining is also done by third-party examiners." },
  fr:{ q:"Votre communauté n'a pas de bureau des véhicules automobiles. Comment les services aux conducteurs y sont-ils offerts ?",
       a:["Il faut se rendre à Iqaluit pour chaque service","Tout se règle par la poste","Par le programme des agents de liaison gouvernementaux, qui compte un bureau dans chaque communauté","Seulement lors d'une visite annuelle d'un examinateur"],
       e:"Le Nunavut compte des bureaux des véhicules automobiles à Iqaluit, à Rankin Inlet et à Gjoa Haven, et des bureaux de liaison gouvernementaux dans les vingt-cinq communautés desservent le reste du territoire. Des examinateurs tiers font aussi passer des examens." },
  c:2 },
{ id:"nur8", sec:"rules", topic:"applying",
  en:{ q:"Reading the written test is difficult for you. What does Nunavut offer?",
       a:["The examiner may give you the test out loud instead","A shorter version of the test","A pass based on the road test alone","A friend may write it for you"],
       e:"Where somebody cannot read and understand the written test, the driver examiner may give a spoken test. It is the same material, asked aloud." },
  fr:{ q:"La lecture de l'examen écrit vous est difficile. Qu'offre le Nunavut ?",
       a:["L'examinateur peut plutôt vous faire passer l'examen à l'oral","Une version abrégée de l'examen","Une réussite fondée seulement sur l'examen pratique","Un ami peut le remplir à votre place"],
       e:"Lorsqu'une personne ne peut pas lire et comprendre l'examen écrit, l'examinateur peut lui faire passer un examen oral. C'est la même matière, posée à voix haute." },
  c:0 },
{ id:"nur9", sec:"rules", topic:"applying",
  en:{ q:"How long does a Nunavut driver's licence run before it has to be renewed?",
       a:["One year","Two years","Three years","Five years"],
       e:"Licences are issued for five years. Renew before the expiry date: a licence that has been expired for more than twelve months cannot simply be renewed and the examinations must be taken again." },
  fr:{ q:"Combien de temps un permis de conduire du Nunavut est-il valide avant son renouvellement ?",
       a:["Un an","Deux ans","Trois ans","Cinq ans"],
       e:"Les permis sont délivrés pour cinq ans. Renouvelez avant la date d'expiration : un permis expiré depuis plus de douze mois ne peut pas être simplement renouvelé et les examens doivent être repris." },
  c:3 },
{ id:"nur10", sec:"rules", topic:"applying",
  en:{ q:"You move to Nunavut holding a licence from another province. How long do you have to apply for a Nunavut licence?",
       a:["Fifteen days","Thirty days","Six months","One year"],
       e:"New residents have thirty days from the move to apply. Separately, a change of name or address has to be reported to your Motor Vehicle service provider within fifteen days." },
  fr:{ q:"Vous emménagez au Nunavut avec un permis d'une autre province. De combien de temps disposez-vous pour demander un permis du Nunavut ?",
       a:["Quinze jours","Trente jours","Six mois","Un an"],
       e:"Les nouveaux résidents ont trente jours à partir du déménagement pour faire la demande. Par ailleurs, tout changement de nom ou d'adresse doit être signalé à votre fournisseur de services des véhicules automobiles dans les quinze jours." },
  c:1 },
{ id:"nur11", sec:"rules", topic:"rules",
  en:{ q:"Nothing is posted on the street you are driving along inside a community. What speed applies?",
       a:["30 km/h","40 km/h","50 km/h","60 km/h"],
       e:"Inside communities the basic limit is 50 km/h unless a sign says otherwise. It is a ceiling for good conditions, not a speed to hold regardless of dust, ice or people on the road." },
  fr:{ q:"Aucune limite n'est affichée dans la rue où vous roulez à l'intérieur d'une communauté. Quelle vitesse s'applique ?",
       a:["30 km/h","40 km/h","50 km/h","60 km/h"],
       e:"Dans les communautés, la limite de base est de 50 km/h, sauf indication contraire. C'est un plafond pour de bonnes conditions, pas une vitesse à tenir malgré la poussière, la glace ou des gens sur la chaussée." },
  c:2 },
{ id:"nur12", sec:"rules", topic:"rules",
  en:{ q:"What is the basic speed limit outside the communities where nothing is posted?",
       a:["60 km/h","70 km/h","80 km/h","90 km/h"],
       e:"Outside communities the basic limit is 90 km/h, day or night, unless a sign says otherwise. Loose gravel and poor visibility very often call for far less than that." },
  fr:{ q:"Quelle est la limite de vitesse de base à l'extérieur des communautés, là où rien n'est affiché ?",
       a:["60 km/h","70 km/h","80 km/h","90 km/h"],
       e:"À l'extérieur des communautés, la limite de base est de 90 km/h, le jour comme la nuit, sauf indication contraire. Le gravier meuble et la mauvaise visibilité commandent très souvent bien moins." },
  c:3 },
{ id:"nur13", sec:"rules", topic:"rules",
  en:{ q:"What does Nunavut law require about seat belts and child seats?",
       a:["Every driver and passenger must be belted, and small children must be in a child car seat","Only the driver must be belted","Belts are required outside the communities only","Child seats are recommended but not required"],
       e:"The requirement covers everybody in the vehicle, and small children need a car seat rather than an adult belt across them. It applies on a two-minute trip across the community just as much as on a long one." },
  fr:{ q:"Qu'exige la loi du Nunavut au sujet des ceintures de sécurité et des sièges d'auto ?",
       a:["Chaque conducteur et chaque passager doit être attaché, et les jeunes enfants doivent être dans un siège d'auto","Seul le conducteur doit être attaché","Les ceintures sont exigées seulement à l'extérieur des communautés","Les sièges d'auto sont recommandés sans être obligatoires"],
       e:"L'exigence vise toutes les personnes à bord, et les jeunes enfants ont besoin d'un siège d'auto plutôt que d'une ceinture d'adulte. Elle s'applique pour un trajet de deux minutes dans la communauté comme pour un long trajet." },
  c:0 },
{ id:"nur14", sec:"rules", topic:"communities",
  en:{ q:"Which animal does the Nunavut driver's manual tell you to watch for around your vehicle?",
       a:["Caribou","Foxes","Dogs","Ravens"],
       e:"The manual names dogs. They are often close to parked vehicles and can move without warning, so look around the vehicle before you start off and stay alert for animals on the road." },
  fr:{ q:"Quel animal le manuel du conducteur du Nunavut vous dit-il de surveiller autour de votre véhicule ?",
       a:["Le caribou","Le renard","Le chien","Le corbeau"],
       e:"Le manuel nomme les chiens. Ils se tiennent souvent tout près des véhicules stationnés et peuvent bouger sans avertissement : regardez autour du véhicule avant de partir et restez attentif aux animaux sur la chaussée." },
  c:2 },
{ id:"nur15", sec:"rules", topic:"communities",
  en:{ q:"No speed is posted at a playground in your community. How fast should you drive past it?",
       a:["At a speed that is reasonable and prudent for what is happening there","At the highest speed the street allows","At the same speed as the vehicle ahead of you","Speed does not matter where nothing is posted"],
       e:"Where a school or playground zone has a posted speed you drive at it; where nothing is posted the standard is a reasonable and prudent speed, which means slow enough to stop for a child who runs out." },
  fr:{ q:"Aucune vitesse n'est affichée à un terrain de jeu de votre communauté. À quelle vitesse devez-vous passer ?",
       a:["À une vitesse raisonnable et prudente selon ce qui s'y passe","À la vitesse la plus élevée que la rue permet","À la même vitesse que le véhicule qui vous précède","La vitesse n'a pas d'importance si rien n'est affiché"],
       e:"Là où une zone scolaire ou un terrain de jeu affiche une vitesse, vous la respectez ; s'il n'y a rien d'affiché, la norme est une vitesse raisonnable et prudente, c'est-à-dire assez lente pour arrêter devant un enfant qui surgit." },
  c:0 },
{ id:"nur16", sec:"rules", topic:"communities",
  en:{ q:"You only ever drive inside your own community, never on a road out of it. Do you still need a licence?",
       a:["No, a licence is only needed between communities","No, as long as the vehicle stays off the main street","Only if the vehicle is registered","Yes, a valid licence is needed to operate any motor vehicle in Nunavut"],
       e:"Nunavut publishes no exemption for short local trips. To legally operate a motor vehicle anywhere in the territory you must hold a valid driver's licence." },
  fr:{ q:"Vous conduisez uniquement dans votre communauté, jamais sur une route qui en sort. Vous faut-il quand même un permis ?",
       a:["Non, le permis n'est exigé qu'entre les communautés","Non, tant que le véhicule évite la rue principale","Seulement si le véhicule est immatriculé","Oui, un permis valide est exigé pour conduire tout véhicule automobile au Nunavut"],
       e:"Le Nunavut ne publie aucune exemption pour les courts trajets locaux. Pour conduire légalement un véhicule automobile sur le territoire, vous devez détenir un permis de conduire valide." },
  c:3 },
{ id:"nur17", sec:"rules", topic:"gravel",
  en:{ q:"The vehicle ahead of you on a gravel road is throwing up a thick cloud of dust. What does the manual tell you to do?",
       a:["Pass quickly on the left before the dust thickens","Do not pass it, and stay back where you can see","Sound your horn and pass on the right","Switch on your high beams and pass"],
       e:"You cannot pass what you cannot see around. Inside a dust cloud you can see neither oncoming traffic, nor the edge of the road, nor anybody walking on it, so drop back and wait for a clear stretch." },
  fr:{ q:"Le véhicule devant vous sur une route de gravier soulève un épais nuage de poussière. Que dit le manuel de faire ?",
       a:["Le dépasser vite par la gauche avant que la poussière s'épaississe","Ne pas le dépasser et rester en arrière, là où vous voyez","Klaxonner et le dépasser par la droite","Allumer vos feux de route et le dépasser"],
       e:"On ne dépasse pas ce qu'on ne peut pas contourner du regard. Dans un nuage de poussière, vous ne voyez ni la circulation en sens inverse, ni le bord de la chaussée, ni les personnes qui s'y trouvent : restez en arrière et attendez un tronçon dégagé." },
  c:1 },
{ id:"nur18", sec:"rules", topic:"gravel",
  en:{ q:"Why does Nunavut warn drivers not to travel too fast on loose gravel?",
       a:["Gravel damages the paint on other vehicles","Fuel use rises sharply on gravel","The tires lose their grip, so braking and steering both take longer","Gravel roads carry a lower posted limit than paved ones"],
       e:"Loose stone rolls under the tires. The vehicle takes longer to stop, drifts wide in a turn, and one sudden movement of the wheel can put it sideways." },
  fr:{ q:"Pourquoi le Nunavut prévient-il de ne pas rouler trop vite sur du gravier meuble ?",
       a:["Le gravier abîme la peinture des autres véhicules","La consommation de carburant grimpe fortement sur le gravier","Les pneus perdent leur adhérence : freiner et diriger prennent plus de temps","Les routes de gravier ont une limite affichée plus basse que les routes asphaltées"],
       e:"Les cailloux roulent sous les pneus. Le véhicule met plus de temps à s'arrêter, s'élargit en virage, et un seul coup de volant brusque peut le mettre en travers." },
  c:2 },
{ id:"nur19", sec:"rules", topic:"gravel",
  en:{ q:"How much room should you leave behind a vehicle on a dusty gravel road?",
       a:["Enough to stay out of its dust and still see the road ahead","One vehicle length, so you do not lose sight of it","Close enough to follow its tracks","The same distance as on a paved road"],
       e:"The extra space does two jobs: it keeps you out of the dust so you can see, and it gives you the longer stopping distance that gravel demands." },
  fr:{ q:"Quel espace devez-vous laisser derrière un véhicule sur une route de gravier poussiéreuse ?",
       a:["Assez pour rester hors de sa poussière et voir encore la route devant","Une longueur de véhicule, pour ne pas le perdre de vue","Assez près pour suivre ses traces","La même distance que sur une route asphaltée"],
       e:"L'espace supplémentaire sert à deux choses : il vous garde hors de la poussière pour que vous voyiez, et il vous donne la distance d'arrêt plus longue qu'exige le gravier." },
  c:0 },
{ id:"nur20", sec:"rules", topic:"winter",
  en:{ q:"Which set of checks does the Nunavut manual ask you to make on the vehicle before winter?",
       a:["Paint, seats and radio","Tire colour, mirrors and mud flaps","Horn, plate light and spare key","Battery, brake adjustment, wipers, heater and defroster"],
       e:"Those are the parts that decide whether you can see and whether you can stop in the cold. A weak battery and a defroster that cannot clear the glass are winter problems, not summer ones." },
  fr:{ q:"Quelles vérifications le manuel du Nunavut demande-t-il de faire sur le véhicule avant l'hiver ?",
       a:["La peinture, les sièges et la radio","La couleur des pneus, les rétroviseurs et les garde-boue","Le klaxon, l'éclairage de la plaque et la clé de rechange","La batterie, le réglage des freins, les essuie-glaces, le chauffage et le dégivreur"],
       e:"Ce sont les éléments qui déterminent si vous voyez et si vous pouvez arrêter par temps froid. Une batterie faible et un dégivreur incapable de dégager les vitres sont des problèmes d'hiver, pas d'été." },
  c:3 },
{ id:"nur21", sec:"rules", topic:"winter",
  en:{ q:"What belongs in the kit the manual says to carry in winter?",
       a:["A spare windshield, an extinguisher and flares","A scraper brush, booster cables, a shovel, a tow strap, a traction mat, sand and a flashlight","A first aid kit and nothing else","A second set of keys and a road map"],
       e:"Every item on that list is there to get a stuck or dead vehicle moving again, or to let you see and be seen while you work on it. Carrying it costs nothing until the day it matters." },
  fr:{ q:"Que doit contenir la trousse que le manuel dit de transporter en hiver ?",
       a:["Un pare-brise de rechange, un extincteur et des fusées éclairantes","Un grattoir-brosse, des câbles de démarrage, une pelle, une sangle de remorquage, un tapis de traction, du sable et une lampe de poche","Une trousse de premiers soins et rien d'autre","Un deuxième jeu de clés et une carte routière"],
       e:"Chaque article de cette liste sert à remettre en marche un véhicule immobilisé, ou à voir et à être vu pendant que vous vous en occupez. La trousse ne coûte rien jusqu'au jour où elle compte." },
  c:1 },
{ id:"nur22", sec:"rules", topic:"winter",
  en:{ q:"The road has turned slippery and your vehicle has no anti-lock brakes. How does the manual say to brake?",
       a:["Press hard and hold the pedal down","Use the parking brake instead","Steer sharply to scrub off speed","Pump the brakes rather than locking the wheels"],
       e:"Locked wheels slide and cannot be steered. Pumping keeps them turning, which is what lets you slow down and still point the vehicle where you want it. Watch for patches of black ice, which look like nothing more than wet road." },
  fr:{ q:"La chaussée est devenue glissante et votre véhicule n'a pas de freins antiblocage. Comment le manuel dit-il de freiner ?",
       a:["Appuyer fort et garder la pédale enfoncée","Utiliser le frein de stationnement à la place","Braquer sèchement pour perdre de la vitesse","Pomper les freins plutôt que bloquer les roues"],
       e:"Des roues bloquées glissent et ne se dirigent plus. En pompant, elles continuent de tourner, ce qui vous permet de ralentir tout en gardant la maîtrise de la direction. Surveillez les plaques de glace noire, qui ressemblent à une simple chaussée mouillée." },
  c:3 },
{ id:"nur23", sec:"rules", topic:"winter",
  en:{ q:"You come up behind a vehicle showing flashing orange lights while it clears snow. What should you do?",
       a:["Pass it on whichever side is clearest","Follow it closely so you stay in the cleared track","Stay well back, because flashing orange marks slow work and thrown snow","Sound your horn until it pulls over"],
       e:"Flashing orange marks a vehicle working on the road, not an emergency. It moves slowly, stops without warning and throws snow and stone out to the side, so give it plenty of room." },
  fr:{ q:"Vous arrivez derrière un véhicule aux gyrophares orange qui déneige la route. Que devez-vous faire ?",
       a:["Le dépasser du côté le plus dégagé","Le suivre de près pour rester dans la trace déblayée","Rester bien en arrière, car l'orange clignotant signale un travail lent et de la neige projetée","Klaxonner jusqu'à ce qu'il se range"],
       e:"L'orange clignotant signale un véhicule qui travaille sur la route, pas une urgence. Il avance lentement, s'arrête sans prévenir et projette neige et cailloux sur le côté : laissez-lui beaucoup d'espace." },
  c:2 },
{ id:"nur24", sec:"rules", topic:"safe",
  en:{ q:"A Nunavut driver's record reaches twelve demerit points. What happens?",
       a:["The licence is cancelled at once","The Registrar sends a warning letter, and an interview follows","A fine is added to the next renewal","Nothing until the licence expires"],
       e:"Twelve points brings a warning letter and an interview. It is a chance to change how you drive before the next threshold is reached." },
  fr:{ q:"Le dossier d'un conducteur du Nunavut atteint douze points d'inaptitude. Que se passe-t-il ?",
       a:["Le permis est annulé sur-le-champ","Le registraire envoie une lettre d'avertissement, et une entrevue suit","Une amende s'ajoute au prochain renouvellement","Rien jusqu'à l'expiration du permis"],
       e:"Douze points entraînent une lettre d'avertissement et une entrevue. C'est l'occasion de changer votre conduite avant d'atteindre le seuil suivant." },
  c:1 },
{ id:"nur25", sec:"rules", topic:"safe",
  en:{ q:"How long is the suspension once a driver reaches fifteen demerit points?",
       a:["One month","One week","Three months","One year"],
       e:"At fifteen points the Registrar suspends the licence for one month. Points are added to the record as convictions come in, so they build up quietly." },
  fr:{ q:"Quelle est la durée de la suspension lorsqu'un conducteur atteint quinze points d'inaptitude ?",
       a:["Un mois","Une semaine","Trois mois","Un an"],
       e:"À quinze points, le registraire suspend le permis pour un mois. Les points s'ajoutent au dossier au fur et à mesure des condamnations : ils s'accumulent donc discrètement." },
  c:0 },
{ id:"nur26", sec:"rules", topic:"safe",
  en:{ q:"At what ages must a Class 5, 6 or 7 driver in Nunavut provide a driver's medical examination?",
       a:["At 65, then every five years","At 70 only","At 75, at 80, and every two years after 80","Only when a doctor asks for one"],
       e:"The schedule is set by age: once at 75, again at 80, and every second year from then on. The higher classes, such as buses and tractor-trailers, require a medical whatever the driver's age." },
  fr:{ q:"À quels âges un conducteur de classe 5, 6 ou 7 au Nunavut doit-il fournir un examen médical ?",
       a:["À 65 ans, puis tous les cinq ans","À 70 ans seulement","À 75 ans, à 80 ans, puis tous les deux ans après 80 ans","Seulement si un médecin le demande"],
       e:"Le calendrier est fixé par l'âge : une fois à 75 ans, de nouveau à 80 ans, puis tous les deux ans par la suite. Les classes supérieures, comme les autobus et les trains routiers, exigent un examen médical à tout âge." },
  c:2 },
{ id:"nur27", sec:"rules", topic:"safe",
  en:{ q:"Besides how clearly you see, what else does the Nunavut vision test look at?",
       a:["How quickly you read a page","Your hearing","Your reaction time","Colour perception and field of vision"],
       e:"Seeing to the sides matters as much as seeing straight ahead, and colour perception matters for signals and signs. If the standard is not met, a vision specialist gives a further test; glasses and contact lenses are allowed and are noted on the licence." },
  fr:{ q:"Outre la netteté de votre vue, que vérifie l'examen de la vision au Nunavut ?",
       a:["La rapidité avec laquelle vous lisez une page","Votre audition","Votre temps de réaction","La perception des couleurs et le champ de vision"],
       e:"Voir sur les côtés compte autant que voir droit devant, et la perception des couleurs importe pour les feux et les panneaux. Si la norme n'est pas atteinte, un spécialiste de la vue fait passer un examen supplémentaire ; les lunettes et les lentilles sont permises et sont inscrites au permis." },
  c:3 },
{ id:"nur28", sec:"rules", topic:"roadsigns",
  en:{ q:"How many painted centre lines and lane lines will you find on Nunavut roads?",
       a:["They are painted on the main roads of the larger communities","None at all, because Nunavut roads carry no road markings","Only on the roads between communities","Only in summer, once the snow has gone"],
       e:"Nunavut's own manual states that there are no road markings in the territory, although that may change one day. Practice questions about solid and broken lines are describing roads somewhere else." },
  fr:{ q:"Combien de lignes médianes et de lignes de voie peintes trouve-t-on sur les routes du Nunavut ?",
       a:["Elles sont peintes sur les artères des plus grandes communautés","Aucune, car les routes du Nunavut ne portent aucun marquage","Seulement sur les routes entre les communautés","Seulement l'été, une fois la neige partie"],
       e:"Le manuel du Nunavut indique lui-même qu'il n'y a aucun marquage routier sur le territoire, même si cela pourrait changer un jour. Les questions de pratique sur les lignes continues et discontinues décrivent des routes d'ailleurs." },
  c:1 },
{ id:"nur29", sec:"rules", topic:"roadsigns",
  en:{ q:"With no centre line to follow, how do you keep to your own side of the road?",
       a:["Drive down the middle and move over only when a vehicle appears","Follow the tracks left by the vehicle before you","Stay to the left, because the road is firmest there","Judge your position from the edges of the road, and keep right of oncoming traffic by eye"],
       e:"Without paint, the shoulders and the edges of the travelled surface are your reference. Keep inside them, look far ahead for oncoming vehicles, and move over early rather than at the last moment." },
  fr:{ q:"Sans ligne médiane à suivre, comment rester de votre côté de la chaussée ?",
       a:["Rouler au milieu et vous déporter seulement quand un véhicule paraît","Suivre les traces laissées par le véhicule précédent","Rester à gauche, car la chaussée y est plus ferme","Vous situer d'après les bords de la chaussée et rester à droite des véhicules qui viennent en sens inverse, à vue"],
       e:"Sans peinture, les accotements et les bords de la partie carrossable sont vos repères. Tenez-vous à l'intérieur, regardez loin devant pour repérer les véhicules qui arrivent et déportez-vous tôt plutôt qu'au dernier moment." },
  c:3 },
{ id:"nur30", sec:"rules", topic:"roadsigns",
  en:{ q:"You meet a yellow diamond-shaped sign. What kind of message does it carry?",
       a:["A warning about something ahead on the road","An order you can be fined for breaking","Directions towards a service","A temporary instruction for a work area"],
       e:"Shape and colour tell you the kind of message before you are close enough to read it. Yellow diamonds warn, red and white signs order, blue signs point to services, and orange signs mark temporary work." },
  fr:{ q:"Vous rencontrez un panneau jaune en losange. Quel genre de message porte-t-il ?",
       a:["Un avertissement au sujet de quelque chose plus loin sur la route","Un ordre dont le non-respect peut être puni d'une amende","Une indication vers un service","Une consigne temporaire pour une zone de travaux"],
       e:"La forme et la couleur annoncent le genre de message avant même que vous soyez assez près pour le lire. Les losanges jaunes avertissent, les panneaux rouge et blanc ordonnent, les panneaux bleus indiquent des services et les panneaux orange signalent des travaux temporaires." },
  c:0 }
);

/* ---------------------------------------------------------------------------
   WHOSE NUMBERS ARE THESE? Ours, and we say so plainly.

   Nunavut publishes the SHAPE of its knowledge test and nothing more. The
   Nunavut Driver's Manual says the examination has two parts — rules of the
   road and safe driving practices, and sign identification — taken at one
   sitting, and that a candidate who fails one part rewrites only that part.
   That is the whole of it. The Government of Nunavut publishes NO question
   count, NO pass mark, NO time limit and NO fee, for the knowledge test or for
   any other driver licensing service. A commercial practice site states "20
   questions, 16 correct, a passing score of 80%" and a "$30.35" testing fee
   and cites no government source for any of the four; another commercial site
   states the minimum age as 16, which is wrong — the Nunavut manual sets the
   Class 7 learner licence at 15. We will not repeat a number that decides
   whether somebody books a test, so the figures below — 20 signs, 20 rules,
   15 right to pass each part, 40 minutes — are a clearly stated practice
   standard of OUR OWN. Only the two-part structure below is the territory's.

   Nunavut also has NO graduated licensing programme: no stages, no stage
   lengths, no probationary period, no learner curfew or passenger limit. That
   is unusual in Canada, and we say so rather than borrow the stages of a
   neighbouring territory, which is what the practice sites do.

   The handbook title is given in English in the French field because there is
   no French edition to name. The Government of Nunavut publishes gov.nu.ca in
   Inuktitut, Inuinnaqtun, English and French, but all four of its driver's
   manuals are English only.
   --------------------------------------------------------------------------- */
window.CQ_PROVINCE = {
  code: "NU",
  name: { en: "Nunavut", fr: "Nunavut" },
  licence: "Class 7 Learner",
  minutes: 40,
  sections: [
    { id: "signs", ask: 20, pass: 15,
      name: { en: "Sign Identification",
              fr: "Reconnaissance des panneaux" } },
    { id: "rules", ask: 20, pass: 15,
      name: { en: "Rules of the Road and Safe Driving",
              fr: "Code de la route et conduite sécuritaire" } }
  ],
  handbook: { en: "Nunavut Driver's Manual",
              fr: "Nunavut Driver's Manual" },
  handbookUrl: "https://www.gov.nu.ca/sites/default/files/documents/2022-12/driversmanual_eng.pdf",
  bookingUrl: "https://www.gov.nu.ca/en/service-nunavut/apply-drivers-licence",
  topics: [
    { id:"licence",     en:"Your Licence and the Test",      fr:"Votre permis et l'examen" },
    { id:"applying",    en:"Applying, Testing and Renewing", fr:"Demande, examen et renouvellement" },
    { id:"rules",       en:"Rules of the Road",              fr:"Code de la route" },
    { id:"communities", en:"Driving in the Communities",     fr:"La conduite dans les communautés" },
    { id:"gravel",      en:"Gravel Roads and Dust",          fr:"Routes de gravier et poussière" },
    { id:"winter",      en:"Winter and Cold",                fr:"L'hiver et le froid" },
    { id:"safe",        en:"Safe and Responsible Driving",   fr:"Conduite sécuritaire et responsable" },
    { id:"roadsigns",   en:"Road Signs in Nunavut",          fr:"Les panneaux au Nunavut" }
  ],
  questions: window.CQ_DRIVE_Q
};


/* Ten more rules questions, added 3 September 2026.
   Written from this jurisdiction's own official handbook, and
   chosen for what makes its rules different from its neighbours'.
   The French is written beside the English on purpose: see the
   note at the top of tools/newq/fr_qbank.py. */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"nux1", sec:"rules",
  en:{ q:"How old must you be to get a Class 7 learner's licence in Nunavut?",
       a:["14","15","16","18"],
       e:"A Class 7 learner's licence is issued at 15, and a full Class 5 or 6 at 16." },
  fr:{ q:"Quel âge faut-il avoir pour obtenir un permis d'apprenti de classe 7 au Nunavut ?",
       a:["14 ans","15 ans","16 ans","18 ans"],
       e:"Le permis d'apprenti de classe 7 est délivré à 15 ans, et le permis complet de classe 5 ou 6 à 16 ans." },
  c:1 },

{ id:"nux2", sec:"rules",
  en:{ q:"How long must a first-time Nunavut driver practise before taking the driving exam?",
       a:["Four weeks with a learner's permit","Six months","One year","Two years"],
       e:"Nunavut requires four weeks of practice driving with a learner's permit. Yukon asks six months and the Northwest Territories a full year." },
  fr:{ q:"Combien de temps un nouveau conducteur du Nunavut doit-il pratiquer avant de passer l'examen de conduite ?",
       a:["Quatre semaines avec un permis d'apprenti","Six mois","Un an","Deux ans"],
       e:"Le Nunavut exige quatre semaines de pratique avec un permis d'apprenti. Le Yukon en demande six mois et les Territoires du Nord-Ouest, une année complète." },
  c:0 },

{ id:"nux3", sec:"rules",
  en:{ q:"What is the basic speed limit inside a Nunavut community?",
       a:["50 km/h or as posted","40 km/h","60 km/h","80 km/h"],
       e:"Inside communities the basic limit is 50 km/h or as posted. Outside communities it is 90 km/h." },
  fr:{ q:"Quelle est la limite de vitesse de base dans une localité du Nunavut ?",
       a:["50 km/h ou selon l'affichage","40 km/h","60 km/h","80 km/h"],
       e:"À l'intérieur des localités, la limite de base est de 50 km/h ou selon l'affichage. À l'extérieur des localités, elle est de 90 km/h." },
  c:0 },

{ id:"nux4", sec:"rules",
  en:{ q:"What is the speed limit for trucks outside Nunavut communities?",
       a:["90 km/h, the same as cars","100 km/h","80 km/h, day or night","There is no separate limit"],
       e:"Nunavut sets a separate truck limit of 80 km/h outside cities and towns, day or night, where cars may do 90." },
  fr:{ q:"Quelle est la limite de vitesse pour les camions à l'extérieur des localités du Nunavut ?",
       a:["90 km/h, comme les voitures","100 km/h","80 km/h, de jour comme de nuit","Il n'y a pas de limite distincte"],
       e:"Le Nunavut fixe une limite distincte de 80 km/h pour les camions à l'extérieur des villes et villages, de jour comme de nuit, là où les voitures peuvent rouler à 90." },
  c:2 },

{ id:"nux5", sec:"rules",
  en:{ q:"What does a Nunavut Restricted Driver's Licence allow?",
       a:["Driving only in summer","Driving only within Nunavut, or within 100 km of your home community","Driving only during daylight","Driving any vehicle anywhere in Canada"],
       e:"Nunavut publishes a separate manual for this licence, which limits driving to within the territory or within 100 kilometres of the holder's home community. Nothing like it exists in Yukon or the Northwest Territories." },
  fr:{ q:"Que permet un permis de conduire restreint du Nunavut ?",
       a:["De conduire seulement l'été","De conduire seulement au Nunavut, ou à moins de 100 km de sa localité","De conduire seulement le jour","De conduire n'importe quel véhicule partout au Canada"],
       e:"Le Nunavut publie un manuel distinct pour ce permis, qui limite la conduite au territoire ou à un rayon de 100 kilomètres de la localité du titulaire. Rien de tel n'existe au Yukon ni dans les Territoires du Nord-Ouest." },
  c:1 },

{ id:"nux6", sec:"rules",
  en:{ q:"What is the first rule for driving on a loose gravel road in Nunavut?",
       a:["Do not travel too fast","Use your high beams","Stay in the middle of the road","Brake hard on curves"],
       e:"Speed is the danger on gravel: traction is poor, stones fly up, and dust hides what is ahead. The first rule is simply not to go too fast." },
  fr:{ q:"Quelle est la première règle pour conduire sur une route de gravier meuble au Nunavut ?",
       a:["Ne pas rouler trop vite","Utiliser les feux de route","Rester au milieu de la route","Freiner fort dans les courbes"],
       e:"La vitesse est le danger sur le gravier : l'adhérence est faible, les cailloux volent et la poussière masque ce qui vient. La première règle est simplement de ne pas rouler trop vite." },
  c:0 },

{ id:"nux7", sec:"rules",
  en:{ q:"What should you not do behind a vehicle raising a heavy dust cloud in Nunavut?",
       a:["Slow down","Turn on your headlights","Try to pass it","Increase your following distance"],
       e:"Do not try to pass a vehicle creating a heavy dust cloud. You cannot see what is coming the other way until you are already committed." },
  fr:{ q:"Que ne devriez-vous pas faire derrière un véhicule soulevant un épais nuage de poussière au Nunavut ?",
       a:["Ralentir","Allumer vos phares","Tenter de le dépasser","Augmenter votre distance de suivi"],
       e:"N'essayez pas de dépasser un véhicule qui soulève un épais nuage de poussière. Vous ne voyez pas ce qui arrive en sens inverse avant d'être déjà engagé." },
  c:2 },

{ id:"nux8", sec:"rules",
  en:{ q:"What should a Nunavut driver watch for when parking or backing up in a community?",
       a:["Falling ice","Loose dogs around the vehicle","Low aircraft","Nothing in particular"],
       e:"The driver's manual asks drivers to look out for dogs around the car when parking, backing up or driving through town, as well as for wildlife on the road." },
  fr:{ q:"À quoi un conducteur du Nunavut doit-il faire attention en stationnant ou en reculant dans une localité ?",
       a:["La chute de glace","Des chiens en liberté autour du véhicule","Des avions volant bas","Rien de particulier"],
       e:"Le manuel du conducteur demande de surveiller les chiens autour du véhicule en stationnant, en reculant ou en circulant dans la localité, ainsi que la faune sur la route." },
  c:1 },

{ id:"nux9", sec:"rules",
  en:{ q:"When may a Nunavut motorcycle learner not ride?",
       a:["In the rain","On weekends","After dark, or where the limit is 70 km/h or more","There is no restriction"],
       e:"A motorcycle learner may not ride in the dark, or in speed zones of 70 km/h or greater, and must have a Class 6 licence holder with them." },
  fr:{ q:"Quand un apprenti motocycliste du Nunavut ne peut-il pas rouler ?",
       a:["Sous la pluie","La fin de semaine","Après la tombée du jour, ou là où la limite est de 70 km/h ou plus","Il n'y a aucune restriction"],
       e:"Un apprenti motocycliste ne peut pas rouler dans l'obscurité, ni dans les zones où la limite est de 70 km/h ou plus, et doit être accompagné d'un titulaire de permis de classe 6." },
  c:2 },

{ id:"nux10", sec:"rules",
  en:{ q:"What is the legal blood alcohol limit for a fully licensed Nunavut driver?",
       a:["0.08","0.05","Zero","0.10"],
       e:"The Nunavut driver's manual states the limit as 0.08. As everywhere in Canada, the safest amount before driving is none." },
  fr:{ q:"Quelle est la limite légale d'alcoolémie pour un conducteur pleinement titulaire au Nunavut ?",
       a:["0,08","0,05","Zéro","0,10"],
       e:"Le manuel du conducteur du Nunavut fixe la limite à 0,08. Comme partout au Canada, la quantité la plus sûre avant de conduire demeure zéro." },
  c:0 }
);
