/* canada-quiz.com — PRINCE EDWARD ISLAND Class 7 Instruction Permit practice data
   60 original bilingual questions (30 road signs + 30 rules of the road).
   Written in our own words from the free Driver's Handbook, the driver licensing
   and Rules of the Road pages on princeedwardisland.ca, and the Highway Traffic
   Act regulations on graduated driver licensing and demerit points.
   Not affiliated with Access PEI or the Government of Prince Edward Island.

   The quiz code lives in js/driving-engine.js and never changes per province. */
window.CQ_DRIVE_Q = [];

/* ---------- road signs ---------- */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"pes1", sec:"signs", sign:"stop",
  en:{ q:"You are the first vehicle at this sign and the road ahead is empty. What must you do?",
       a:["Slow to a crawl and keep going","Stop only if a pedestrian is waiting","Come to a complete stop before the line, then go when the way is clear","Sound the horn and carry on"],
       e:"A stop sign means a full stop every time, empty road or not. Stop before the stop line, or before the crosswalk if there is no line, and move off only once you can see that the way is clear." },
  fr:{ q:"Vous êtes le premier véhicule à ce panneau et la route est déserte. Que devez-vous faire ?",
       a:["Ralentir au pas et continuer","Vous arrêter seulement si un piéton attend","Faire un arrêt complet avant la ligne, puis repartir quand la voie est libre","Klaxonner et poursuivre"],
       e:"Un panneau d'arrêt exige un arrêt complet chaque fois, que la route soit vide ou non. Arrêtez-vous avant la ligne d'arrêt, ou avant le passage pour piétons s'il n'y a pas de ligne, et ne repartez qu'une fois la voie dégagée." },
  c:2 },

{ id:"pes2", sec:"signs", sign:"yield",
  en:{ q:"A yield sign faces you as you join a busier road. What does it require?",
       a:["Give way to traffic already on that road and enter only in a safe gap","Stop completely every time before entering","Accelerate so that others have to let you in","Enter only after sounding your horn"],
       e:"Yield means give way. Slow down, be ready to stop, and pull out only when nobody already on the road has to brake or swerve because of you." },
  fr:{ q:"Un panneau de cession de passage se présente à vous à l'entrée d'une route plus passante. Qu'exige-t-il ?",
       a:["Laisser passer la circulation déjà sur cette route et vous engager seulement dans un espace sécuritaire","Vous arrêter complètement chaque fois avant de vous engager","Accélérer pour forcer les autres à vous laisser entrer","Vous engager après avoir klaxonné"],
       e:"Céder le passage veut dire laisser passer. Ralentissez, soyez prêt à vous arrêter et engagez-vous seulement si personne n'est obligé de freiner ou de faire un écart à cause de vous." },
  c:0 },

{ id:"pes3", sec:"signs", sign:"no-entry",
  en:{ q:"This sign is posted at the mouth of a street. What is it telling you?",
       a:["Only residents may drive there","You may enter but not park","Trucks must use another route","You must not drive into that street at all"],
       e:"Do not enter. Traffic is coming towards you, so turning in would put you head-on against a one-way flow." },
  fr:{ q:"Ce panneau est installé à l'entrée d'une rue. Que vous indique-t-il ?",
       a:["Seuls les résidents peuvent y circuler","Vous pouvez y entrer mais non y stationner","Les camions doivent emprunter un autre chemin","Vous ne devez pas vous engager dans cette rue"],
       e:"Accès interdit. La circulation vient vers vous : vous y engager vous placerait face aux véhicules d'une rue à sens unique." },
  c:3 },

{ id:"pes4", sec:"signs", sign:"one-way",
  en:{ q:"You want to turn into a street marked with this sign. What does it allow?",
       a:["Driving either way as long as you keep right","Travel in the direction of the arrow only","Driving there during daylight only","Turning in from the left lane only"],
       e:"One way. Every lane runs the same direction, so your turn has to leave you travelling the way the arrow points." },
  fr:{ q:"Vous voulez tourner dans une rue portant ce panneau. Que permet-il ?",
       a:["Circuler dans les deux sens en tenant la droite","Circuler uniquement dans le sens de la flèche","Y circuler seulement le jour","Tourner seulement à partir de la voie de gauche"],
       e:"Sens unique. Toutes les voies vont dans la même direction, donc votre virage doit vous laisser dans le sens indiqué par la flèche." },
  c:1 },

{ id:"pes5", sec:"signs", sign:"no-passing",
  en:{ q:"What are you being told on the stretch of road where this sign stands?",
       a:["The lane ahead is closed","Only trucks may overtake","You may not overtake another vehicle here","Passing is allowed if you signal first"],
       e:"Overtaking is banned along this stretch, usually because you cannot see far enough ahead to pull back in before an oncoming vehicle arrives." },
  fr:{ q:"Que vous dit ce panneau sur le tronçon où il est installé ?",
       a:["La voie devant est fermée","Seuls les camions peuvent dépasser","Vous ne pouvez dépasser aucun véhicule ici","Le dépassement est permis si vous mettez votre clignotant"],
       e:"Le dépassement est interdit sur ce tronçon, le plus souvent parce que la visibilité ne suffit pas pour vous rabattre avant qu'un véhicule arrive en sens inverse." },
  c:2 },

{ id:"pes6", sec:"signs", sign:"no-parking",
  en:{ q:"Where this sign is posted, what may you not do?",
       a:["Leave your vehicle standing at the roadside","Drive past without stopping","Turn right","Use the lane at all"],
       e:"Parking is banned here. A brief stop while somebody gets in or out is still allowed; a no stopping sign would forbid even that." },
  fr:{ q:"Là où ce panneau est affiché, qu'est-ce qui vous est interdit ?",
       a:["Laisser votre véhicule immobilisé au bord de la route","Passer sans vous arrêter","Tourner à droite","Emprunter la voie"],
       e:"Le stationnement est interdit à cet endroit. Un court arrêt pour faire monter ou descendre quelqu'un reste permis ; un panneau d'arrêt interdit défendrait même cela." },
  c:0 },

{ id:"pes7", sec:"signs", sign:"no-u-turn",
  en:{ q:"You have missed your street and you see this sign. What does it prevent?",
       a:["Turning left at the next street","Turning around to travel back the way you came","Reversing into a driveway","Stopping at the kerb"],
       e:"Turning around is banned here. Carry on to an intersection where the manoeuvre is permitted rather than swinging across in front of oncoming traffic." },
  fr:{ q:"Vous avez manqué votre rue et vous apercevez ce panneau. Qu'empêche-t-il ?",
       a:["De tourner à gauche à la prochaine rue","De faire demi-tour pour revenir d'où vous venez","De reculer dans une entrée","De vous arrêter au bord du trottoir"],
       e:"Le demi-tour est interdit ici. Continuez jusqu'à une intersection où la manoeuvre est permise plutôt que de traverser devant les véhicules qui arrivent." },
  c:1 },

{ id:"pes8", sec:"signs", sign:"stop-school-bus",
  en:{ q:"This sign appears on the back of a school bus. What does it require of drivers in Prince Edward Island?",
       a:["Vehicles behind the bus stop, oncoming vehicles may pass slowly","Only vehicles in the same lane must stop","Drivers must slow down but need not stop","Vehicles travelling in both directions must stop when the red lights flash"],
       e:"In Prince Edward Island traffic stops in both directions as soon as a school bus has its red lights flashing, and stays stopped until those lights go out." },
  fr:{ q:"Ce panneau se trouve à l'arrière d'un autobus scolaire. Qu'exige-t-il des conducteurs à l'Île-du-Prince-Édouard ?",
       a:["Les véhicules derrière l'autobus s'arrêtent, ceux qui arrivent en sens inverse peuvent passer lentement","Seuls les véhicules de la même voie doivent s'arrêter","Les conducteurs doivent ralentir sans s'arrêter","Les véhicules des deux sens doivent s'arrêter quand les feux rouges clignotent"],
       e:"À l'Île-du-Prince-Édouard, la circulation s'arrête dans les deux sens dès que les feux rouges d'un autobus scolaire clignotent, et elle reste arrêtée jusqu'à ce qu'ils s'éteignent." },
  c:3 },

{ id:"pes9", sec:"signs", sign:"speed-50",
  en:{ q:"You pass this sign on a street in town. What does the number mean?",
       a:["The speed most drivers choose here","A suggested speed for fine weather","The maximum speed allowed, not a target to reach","The slowest speed you are allowed to drive"],
       e:"It is a maximum. In a residential area of the Island the default limit is 50 km/h, and rain, fog or children near the street often mean a safe speed is well below the posted number." },
  fr:{ q:"Vous passez devant ce panneau dans une rue en ville. Que signifie le nombre ?",
       a:["La vitesse que la plupart des conducteurs adoptent ici","Une vitesse suggérée par beau temps","La vitesse maximale permise, et non une vitesse à atteindre","La vitesse la plus lente que vous ayez le droit de rouler"],
       e:"C'est un maximum. Dans un secteur résidentiel de l'Île, la limite par défaut est de 50 km/h, et la pluie, le brouillard ou des enfants près de la chaussée imposent souvent d'aller bien plus lentement." },
  c:2 },

{ id:"pes10", sec:"signs", sign:"warn-farm-machinery",
  en:{ q:"What should you expect after this yellow sign on a Prince Edward Island country road?",
       a:["Farm equipment using the road","A farm market with parking","Livestock crossing at fixed hours","A weigh station for trucks"],
       e:"Farm equipment is wide and slow. The Island's rural roads carry a great deal of it, especially at harvest, so ease off early and overtake only where you can see far ahead." },
  fr:{ q:"À quoi devez-vous vous attendre après ce panneau jaune sur une route de campagne de l'Île-du-Prince-Édouard ?",
       a:["À de la machinerie agricole qui circule sur la route","À un marché agricole avec stationnement","À du bétail qui traverse à heures fixes","À une station de pesée pour camions"],
       e:"La machinerie agricole est large et lente. Les routes rurales de l'Île en comptent beaucoup, surtout à la récolte : levez le pied tôt et ne dépassez que si vous voyez loin devant." },
  c:0 },

{ id:"pes11", sec:"signs", sign:"slow-vehicle",
  en:{ q:"You catch up to a vehicle displaying this orange triangle. What does it tell you?",
       a:["The vehicle has broken down","The vehicle travels much more slowly than normal traffic","The vehicle is carrying dangerous goods","The vehicle is a school bus"],
       e:"The orange triangle marks a slow-moving vehicle such as a tractor. On the Island a slow vehicle that is blocking traffic must pull over and let it by, so wait for that rather than crowding it." },
  fr:{ q:"Vous rattrapez un véhicule portant ce triangle orange. Que vous apprend-il ?",
       a:["Le véhicule est immobilisé en panne","Le véhicule roule beaucoup plus lentement que la circulation normale","Le véhicule transporte des matières dangereuses","Le véhicule est un autobus scolaire"],
       e:"Le triangle orange signale un véhicule lent, comme un tracteur. À l'Île, un véhicule lent qui bloque la circulation doit se ranger pour la laisser passer : attendez ce moment sans le talonner." },
  c:1 },

{ id:"pes12", sec:"signs", sign:"warn-school-bus",
  en:{ q:"What lies ahead when you see this yellow sign?",
       a:["A crossing guard on duty","A bus station","A place where a school bus stops to pick up or set down children","A parking area reserved for buses"],
       e:"A school bus stop is coming up. Expect a bus at a standstill and children near the roadway, often just over a rise or around a bend." },
  fr:{ q:"Qu'y a-t-il devant lorsque vous voyez ce panneau jaune ?",
       a:["Un brigadier scolaire en poste","Une gare d'autobus","Un endroit où un autobus scolaire s'arrête pour faire monter ou descendre des enfants","Un stationnement réservé aux autobus"],
       e:"Un arrêt d'autobus scolaire approche. Attendez-vous à un autobus immobilisé et à des enfants près de la chaussée, souvent juste après une butte ou une courbe." },
  c:2 },

{ id:"pes13", sec:"signs", sign:"warn-deer",
  en:{ q:"This sign is posted along a stretch of road. What is the danger?",
       a:["Animals may step onto the road, most often at dawn and dusk","The entrance to a wildlife park","Hunting is permitted nearby","A farm gate ahead"],
       e:"Slow down and scan both shoulders. If one animal crosses, others often follow, so do not accelerate away the moment the first one is past." },
  fr:{ q:"Ce panneau est installé le long d'un tronçon de route. Quel est le danger ?",
       a:["Des animaux peuvent surgir sur la chaussée, surtout à l'aube et au crépuscule","L'entrée d'un parc animalier","La chasse est permise à proximité","Une barrière de ferme devant"],
       e:"Ralentissez et balayez les deux accotements du regard. Si un animal traverse, d'autres suivent souvent : ne repartez pas dès que le premier est passé." },
  c:0 },

{ id:"pes14", sec:"signs", sign:"warn-railway",
  en:{ q:"What does this round yellow sign marked with a cross announce?",
       a:["A crossroads ahead","A route to the hospital","A dead end","A railway crossing ahead"],
       e:"A level crossing is coming up. Slow down, look and listen, and never start across unless you can clear the tracks completely on the far side." },
  fr:{ q:"Que vous annonce ce panneau jaune rond marqué d'une croix ?",
       a:["Un carrefour devant","Un itinéraire vers l'hôpital","Une voie sans issue","Un passage à niveau devant"],
       e:"Un passage à niveau approche. Ralentissez, regardez et écoutez, et ne vous engagez jamais si vous ne pouvez pas dégager complètement les rails de l'autre côté." },
  c:3 },

{ id:"pes15", sec:"signs", sign:"warn-curve-right",
  en:{ q:"What should you do when this sign appears?",
       a:["Brake hard in the middle of the bend","Slow down before the curve, then steer smoothly through it","Move over into the left lane","Sound your horn all the way round"],
       e:"Braking belongs before the curve. Braking once you are in it unsettles the vehicle at the moment the tyres are already working hardest." },
  fr:{ q:"Que devriez-vous faire lorsque ce panneau apparaît ?",
       a:["Freiner fortement au milieu de la courbe","Ralentir avant la courbe, puis la négocier d'un mouvement de volant régulier","Vous déplacer dans la voie de gauche","Klaxonner tout au long de la courbe"],
       e:"Le freinage se fait avant la courbe. Freiner une fois engagé déséquilibre le véhicule au moment où les pneus travaillent déjà le plus fort." },
  c:1 },

{ id:"pes16", sec:"signs", sign:"warn-slippery",
  en:{ q:"Why does this sign matter most in wet or freezing weather?",
       a:["It marks the entrance to a car wash","It shows where gravel has been spread","The surface can lose grip, so braking and steering take longer","It announces a steep descent"],
       e:"Grip disappears long before you feel it going. Cut your speed, avoid sudden movements of the wheel, and stretch out the gap to the vehicle in front." },
  fr:{ q:"Pourquoi ce panneau compte-t-il surtout par temps pluvieux ou glacial ?",
       a:["Il indique l'entrée d'un lave-auto","Il montre où du gravier a été épandu","La chaussée peut perdre son adhérence, donc freiner et braquer prend plus de temps","Il annonce une descente abrupte"],
       e:"L'adhérence disparaît bien avant que vous le sentiez. Réduisez la vitesse, évitez les gestes brusques au volant et allongez la distance avec le véhicule devant." },
  c:2 },

{ id:"pes17", sec:"signs", sign:"warn-pavement-ends",
  en:{ q:"What is about to change where this sign is posted?",
       a:["The paved surface ends and a gravel road begins","The street becomes one way","The shoulder is closed","A toll section starts"],
       e:"Gravel offers far less grip than pavement. Slow down before the change, hold the wheel firmly, and leave extra room because of dust and flying stones." },
  fr:{ q:"Qu'est-ce qui change là où ce panneau est installé ?",
       a:["Le revêtement se termine et une route de gravier commence","La rue devient à sens unique","L'accotement est fermé","Un tronçon à péage commence"],
       e:"Le gravier offre beaucoup moins d'adhérence que l'asphalte. Ralentissez avant le changement, tenez le volant fermement et laissez plus d'espace à cause de la poussière et des pierres projetées." },
  c:0 },

{ id:"pes18", sec:"signs", sign:"warn-t-intersection",
  en:{ q:"This yellow sign appears on a country road. What is it warning you about?",
       a:["The pavement narrows ahead","The road you are on ends and you will have to turn left or right","A side road joins from the right","A divided highway begins"],
       e:"Your road ends in a T. Slow down early enough to choose your direction and to give way to traffic already on the road that crosses in front of you." },
  fr:{ q:"Ce panneau jaune apparaît sur une route de campagne. De quoi vous avertit-il ?",
       a:["La chaussée se rétrécit devant","La route où vous êtes se termine et vous devrez tourner à gauche ou à droite","Une route secondaire arrive de la droite","Une route divisée commence"],
       e:"Votre route se termine en T. Ralentissez assez tôt pour choisir votre direction et céder le passage à la circulation de la route transversale." },
  c:1 },

{ id:"pes19", sec:"signs", sign:"warn-signal-ahead",
  en:{ q:"You see this sign where the intersection is not yet visible. What is coming?",
       a:["A flashing beacon above a school","A railway signal","A set of traffic lights","A pedestrian crossover"],
       e:"Traffic lights are ahead, often hidden by a rise or a bend. Ease off the accelerator and be ready to stop in case the light changes as you arrive." },
  fr:{ q:"Vous voyez ce panneau là où l'intersection n'est pas encore visible. Qu'annonce-t-il ?",
       a:["Un gyrophare au-dessus d'une école","Un signal ferroviaire","Des feux de circulation","Un passage pour piétons"],
       e:"Des feux de circulation approchent, souvent cachés par une butte ou une courbe. Levez le pied et soyez prêt à vous arrêter si le feu change au moment où vous arrivez." },
  c:2 },

{ id:"pes20", sec:"signs", sign:"temp-construction",
  en:{ q:"What does an orange diamond sign mean?",
       a:["Road work is going on ahead","A detour has just ended","A rest area is coming up","The road is closed to all traffic"],
       e:"Orange marks a temporary condition: workers on foot, machinery entering the road, lanes shifted from where they normally run. Slow down and expect the road not to be where you assume." },
  fr:{ q:"Que signifie un panneau orange en losange ?",
       a:["Des travaux routiers sont en cours devant","Un détour vient de se terminer","Une halte routière approche","La route est fermée à toute circulation"],
       e:"L'orange annonce une situation temporaire : des travailleurs à pied, de la machinerie qui entre sur la route, des voies déplacées. Ralentissez et attendez-vous à une chaussée qui n'est pas où vous la croyez." },
  c:0 },

{ id:"pes21", sec:"signs", sign:"temp-flagger",
  en:{ q:"A person in a safety vest is holding a sign at road works. What is your obligation?",
       a:["Pass slowly on the left","Obey their directions exactly as you would a traffic sign","Carry on if the way looks clear","Stop only if they blow a whistle"],
       e:"A traffic control person directs traffic through the work zone with the same authority as a sign, and their instruction overrides what the road ahead looks like to you." },
  fr:{ q:"Une personne en veste de sécurité tient un panneau à un chantier routier. Quelle est votre obligation ?",
       a:["Passer lentement par la gauche","Obéir à ses indications exactement comme à un panneau de signalisation","Continuer si la voie semble libre","Vous arrêter seulement si elle siffle"],
       e:"Le signaleur dirige la circulation dans la zone de travaux avec la même autorité qu'un panneau, et son indication prime sur ce que la route devant vous semble permettre." },
  c:1 },

{ id:"pes22", sec:"signs", sign:"temp-detour",
  en:{ q:"What does this orange sign with an arrow ask you to do?",
       a:["Take the next exit for services","Return to the main road immediately","Wait for a pilot vehicle","Follow the marked route around a closed section of road"],
       e:"It is a detour. Follow the signs the whole way through, because they bring you back to your original road, while an improvised short cut leaves the marked route." },
  fr:{ q:"Que vous demande ce panneau orange muni d'une flèche ?",
       a:["De prendre la prochaine sortie pour des services","De revenir immédiatement sur la route principale","D'attendre un véhicule d'escorte","De suivre l'itinéraire balisé qui contourne un tronçon fermé"],
       e:"C'est un détour. Suivez les panneaux jusqu'au bout, car ils vous ramènent sur votre route d'origine, alors qu'un raccourci improvisé vous fait quitter l'itinéraire balisé." },
  c:3 },

{ id:"pes23", sec:"signs", sign:"info-hospital",
  en:{ q:"What does this blue sign direct you to?",
       a:["A hospital","A rest area","A police station","A tourist information booth"],
       e:"Blue signs point to services for road users. Knowing where the nearest hospital is matters most in the country, where the next town can be a long way off." },
  fr:{ q:"Vers quoi ce panneau bleu vous dirige-t-il ?",
       a:["Un hôpital","Une halte routière","Un poste de police","Un kiosque d'information touristique"],
       e:"Les panneaux bleus indiquent des services offerts aux usagers de la route. Savoir où se trouve l'hôpital le plus proche compte surtout en région, où le prochain village peut être loin." },
  c:0 },

{ id:"pes24", sec:"signs", sign:"info-trans-canada",
  en:{ q:"What does this green and white shield with a maple leaf mark?",
       a:["The entrance to a provincial park","The Trans-Canada Highway","A scenic drive maintained by a town","A ferry terminal"],
       e:"It is the Trans-Canada Highway marker. It confirms you are still on the national route, which is useful where several roads meet and the signs come up quickly." },
  fr:{ q:"Que marque cet écusson vert et blanc orné d'une feuille d'érable ?",
       a:["L'entrée d'un parc provincial","La route Transcanadienne","Une route panoramique entretenue par une municipalité","Un terminal de traversier"],
       e:"C'est l'écusson de la route Transcanadienne. Il confirme que vous suivez toujours la route nationale, ce qui aide là où plusieurs routes se rejoignent." },
  c:1 },

{ id:"pes25", sec:"signs", sign:"info-exit",
  en:{ q:"What is the purpose of this sign on a main highway?",
       a:["It gives the speed limit for the ramp","It marks a rest area","It shows where to leave the highway","It marks the end of a passing lane"],
       e:"It announces the exit. Move into the right lane well before it, then do your slowing down on the ramp rather than in the through lane." },
  fr:{ q:"À quoi sert ce panneau sur une route principale ?",
       a:["Il indique la limite de vitesse de la bretelle","Il signale une halte routière","Il indique où quitter la route","Il marque la fin d'une voie de dépassement"],
       e:"Il annonce la sortie. Placez-vous dans la voie de droite bien avant, puis ralentissez une fois dans la bretelle plutôt que dans la voie de circulation." },
  c:2 },

{ id:"pes26", sec:"signs", sign:"info-accessible",
  en:{ q:"A space in a shopping-centre lot carries this sign. Who is it for?",
       a:["Any driver, for a short stop","Delivery vehicles","Visitors to the building only","Only a vehicle displaying a valid accessible parking permit"],
       e:"These spaces are kept for permit holders. Taking one for a few minutes can leave somebody without the only spot where they can get out of their vehicle." },
  fr:{ q:"Une place dans le terrain d'un centre commercial porte ce panneau. À qui est-elle réservée ?",
       a:["Tout conducteur, pour un court arrêt","Les véhicules de livraison","Les visiteurs de l'immeuble seulement","Seulement un véhicule affichant une vignette de stationnement accessible valide"],
       e:"Ces places sont réservées aux détenteurs de la vignette. Les occuper quelques minutes prive quelqu'un du seul endroit où il peut sortir de son véhicule." },
  c:3 },

{ id:"pes27", sec:"signs", sign:"light-amber",
  en:{ q:"The light turns amber as you approach the intersection. What is the rule?",
       a:["Stop if you can do so safely, and carry on only if stopping would be dangerous","Speed up to clear the intersection","Stop no matter where you are","Treat it as a yield sign"],
       e:"Amber warns that red is next. The question is not whether you can get through, but whether you can stop without the vehicle behind running into you." },
  fr:{ q:"Le feu passe au jaune alors que vous approchez de l'intersection. Quelle est la règle ?",
       a:["Vous arrêter si vous pouvez le faire sans danger, et poursuivre seulement si l'arrêt serait dangereux","Accélérer pour dégager l'intersection","Vous arrêter peu importe où vous vous trouvez","Le traiter comme un panneau de cession de passage"],
       e:"Le jaune annonce le rouge. La question n'est pas de savoir si vous pouvez passer, mais si vous pouvez vous arrêter sans que le véhicule derrière vous heurte." },
  c:0 },

{ id:"pes28", sec:"signs", sign:"light-flashing-red",
  en:{ q:"What must you do at a flashing red light?",
       a:["Slow down and go through with care","Stop completely, then go when the way is clear","Wait for it to turn green","Treat it as a broken signal and ignore it"],
       e:"A flashing red light works exactly like a stop sign: a complete stop, then go only when the way is clear. It is not going to turn green." },
  fr:{ q:"Que devez-vous faire à un feu rouge clignotant ?",
       a:["Ralentir et passer avec prudence","Vous arrêter complètement, puis repartir quand la voie est libre","Attendre qu'il passe au vert","Le considérer comme un feu défectueux et l'ignorer"],
       e:"Un feu rouge clignotant s'applique exactement comme un panneau d'arrêt : arrêt complet, puis départ seulement quand la voie est libre. Il ne passera pas au vert." },
  c:1 },

{ id:"pes29", sec:"signs", sign:"mark-solid-yellow",
  en:{ q:"What do two solid yellow lines down the middle of the road mean?",
       a:["Passing is allowed in both directions","Passing is allowed for the uphill lane only","Neither direction may cross them to pass","The road is one way"],
       e:"Two solid lines forbid passing in both directions, because sight distance is too short for a driver to pull back in before meeting oncoming traffic." },
  fr:{ q:"Que signifient deux lignes jaunes continues au milieu de la chaussée ?",
       a:["Le dépassement est permis dans les deux sens","Le dépassement est permis seulement dans la voie qui monte","Aucun des deux sens ne peut les franchir pour dépasser","La route est à sens unique"],
       e:"Deux lignes continues interdisent le dépassement dans les deux sens, parce que la visibilité est trop courte pour se rabattre avant de croiser un véhicule." },
  c:2 },

{ id:"pes30", sec:"signs", sign:"mark-broken-yellow",
  en:{ q:"A broken yellow line runs along your side of the centre of a two-way road. What does it mean?",
       a:["You must stay in your lane at all times","The road is about to become one way","Only buses may cross it","You may cross it to pass when the road ahead is clear"],
       e:"A broken line on your side permits passing. It is still up to you to judge that the sight distance is long enough before you pull out." },
  fr:{ q:"Une ligne jaune discontinue longe votre côté du centre d'une route à double sens. Que signifie-t-elle ?",
       a:["Vous devez rester dans votre voie en tout temps","La route va devenir à sens unique","Seuls les autobus peuvent la franchir","Vous pouvez la franchir pour dépasser quand la voie devant est libre"],
       e:"La ligne discontinue de votre côté autorise le dépassement. C'est à vous de juger que la distance de visibilité suffit avant de vous déporter." },
  c:3 }

);

/* ---------- rules of the road ---------- */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"per1", sec:"rules", topic:"licensing",
  en:{ q:"How long must a Stage 1 driver in Prince Edward Island hold the instruction permit before moving on?",
       a:["At least 365 days, or 275 days with a certified driver-education course","At least 90 days","At least six months for everybody","There is no minimum period"],
       e:"Stage 1 lasts a full year, and a certified driver-education course brings it down to 275 days. The time is there to build real experience, and nothing else shortens it." },
  fr:{ q:"Combien de temps un conducteur de l'étape 1 doit-il détenir son permis d'apprenti à l'Île-du-Prince-Édouard avant de passer à l'étape suivante ?",
       a:["Au moins 365 jours, ou 275 jours avec un cours de conduite reconnu","Au moins 90 jours","Au moins six mois pour tout le monde","Il n'y a aucune durée minimale"],
       e:"L'étape 1 dure une année complète, et un cours de conduite reconnu la ramène à 275 jours. Ce temps sert à accumuler de l'expérience et rien d'autre ne l'abrège." },
  c:0 },

{ id:"per2", sec:"rules", topic:"licensing",
  en:{ q:"What is the shortest possible time from a new instruction permit to the end of the graduated program?",
       a:["One year","Two years and 275 days, with certified driver education","Six months","Five years"],
       e:"Each of the three stages runs a year, so the usual route takes three years. Certified driver education shortens Stage 1 only, which is where the 275 days comes from." },
  fr:{ q:"Quel est le temps le plus court possible entre un nouveau permis d'apprenti et la fin du programme de permis progressif ?",
       a:["Un an","Deux ans et 275 jours, avec un cours de conduite reconnu","Six mois","Cinq ans"],
       e:"Chacune des trois étapes dure une année, donc le parcours habituel prend trois ans. Le cours de conduite reconnu n'abrège que l'étape 1, d'où les 275 jours." },
  c:1 },

{ id:"per3", sec:"rules", topic:"licensing",
  en:{ q:"What must a Stage 1 driver display on the vehicle?",
       a:["A green triangle in the rear window","No marking at all","A yellow decal bearing the letter L","A sign reading LEARNER ON BOARD"],
       e:"Stage 1 is marked by the yellow decal with a black L, so that other drivers and police can see at a glance that a learner is at the wheel." },
  fr:{ q:"Qu'un conducteur de l'étape 1 doit-il afficher sur le véhicule ?",
       a:["Un triangle vert dans la lunette arrière","Aucune marque","Un autocollant jaune portant la lettre L","Une affiche indiquant APPRENTI À BORD"],
       e:"L'étape 1 se signale par l'autocollant jaune à lettre noire L, pour que les autres conducteurs et les policiers voient d'un coup d'oeil qu'un apprenti est au volant." },
  c:2 },

{ id:"per4", sec:"rules", topic:"licensing",
  en:{ q:"What must most new drivers finish before they are allowed to book a first Class 5 road test?",
       a:["A first-aid certificate","A written test at a private school","Nothing extra is required","The Novice Driver Course, unless they completed certified private driver training"],
       e:"Prince Edward Island will not let you book that first road test until the Novice Driver Course, or a certified private driver-training program, has been completed." },
  fr:{ q:"Que doit avoir terminé la plupart des nouveaux conducteurs avant de pouvoir fixer un premier examen de conduite de classe 5 ?",
       a:["Un certificat de secourisme","Un examen théorique dans une école privée","Rien de plus n'est exigé","Le cours pour conducteurs débutants, sauf s'ils ont suivi une formation privée reconnue"],
       e:"L'Île-du-Prince-Édouard ne permet pas de réserver ce premier examen de conduite tant que le cours pour conducteurs débutants, ou une formation privée reconnue, n'est pas terminé." },
  c:3 },

{ id:"per5", sec:"rules", topic:"permit",
  en:{ q:"What must you pass at an Access PEI office to be issued an instruction permit?",
       a:["A road test only","A written test only","A medical examination arranged by your own doctor","A vision test and a written test on the rules of the road"],
       e:"Both are required. Students in a certified driver-education course write the test in class, but they still have to attend an Access PEI office for the vision test." },
  fr:{ q:"Que devez-vous réussir à un bureau d'Accès Î.-P.-É. pour obtenir un permis d'apprenti ?",
       a:["Un examen de conduite seulement","Un examen théorique seulement","Un examen médical organisé par votre propre médecin","Un examen de la vue et un examen théorique sur le code de la route"],
       e:"Les deux sont exigés. Les élèves d'un cours de conduite reconnu écrivent l'examen en classe, mais doivent tout de même se présenter à un bureau d'Accès Î.-P.-É. pour l'examen de la vue." },
  c:3 },

{ id:"per6", sec:"rules", topic:"permit",
  en:{ q:"You did not pass the written exam for your instruction permit. When may you try again, and what does it cost?",
       a:["The next day, paying the full fee again","After at least seven days, with no extra fee","After thirty days, at a reduced fee","Only after paying for a course"],
       e:"The province publishes a wait of at least seven days before rewriting, and charges nothing for the rewrite. Use the week to go back through the handbook instead of guessing twice." },
  fr:{ q:"Vous avez échoué à l'examen théorique du permis d'apprenti. Quand pouvez-vous le reprendre et à quel prix ?",
       a:["Dès le lendemain, en payant de nouveau le plein tarif","Après au moins sept jours, sans frais supplémentaires","Après trente jours, à tarif réduit","Seulement après avoir payé un cours"],
       e:"La province publie un délai d'au moins sept jours avant de réécrire l'examen et n'exige aucuns frais pour la reprise. Servez-vous de la semaine pour relire le guide." },
  c:1 },

{ id:"per7", sec:"rules", topic:"permit",
  en:{ q:"You failed a road test. How soon may the next one be scheduled?",
       a:["The same week, at the examiner's discretion","After seven days","Not for at least fourteen days","Only after another full year of driving"],
       e:"Fourteen days is the published minimum between road tests. It is the time set aside to work on whatever caused the test to be failed." },
  fr:{ q:"Vous avez échoué à un examen de conduite. Dans quel délai le suivant peut-il avoir lieu ?",
       a:["La même semaine, selon le jugement de l'examinateur","Après sept jours","Pas avant au moins quatorze jours","Seulement après une autre année complète de conduite"],
       e:"Quatorze jours est le délai minimal publié entre deux examens de conduite. C'est le temps prévu pour corriger ce qui a fait échouer l'examen." },
  c:2 },

{ id:"per8", sec:"rules", topic:"permit",
  en:{ q:"How long is a Prince Edward Island instruction permit valid once it has been issued?",
       a:["Six months","One year","Until your eighteenth birthday","Two years"],
       e:"The permit itself is valid for two years. That expiry date is separate from the minimum time you have to spend in Stage 1 before moving on." },
  fr:{ q:"Combien de temps un permis d'apprenti de l'Île-du-Prince-Édouard est-il valide une fois délivré ?",
       a:["Six mois","Un an","Jusqu'à votre dix-huitième anniversaire","Deux ans"],
       e:"Le permis lui-même est valide deux ans. Cette date d'expiration est distincte de la durée minimale que vous devez passer à l'étape 1." },
  c:3 },

{ id:"per9", sec:"rules", topic:"stage1",
  en:{ q:"Who is allowed to supervise a Stage 1 driver in Prince Edward Island?",
       a:["A fully licensed driver who has held a licence for at least four years and sits in the front passenger seat","Any licensed driver over eighteen, sitting anywhere in the vehicle","A Stage 3 driver seated in the back","A parent, whether or not they hold a licence"],
       e:"Four years of licence holding is the published minimum, and the accompanying driver has to be beside you, where they can see the road and reach the wheel." },
  fr:{ q:"Qui peut accompagner un conducteur de l'étape 1 à l'Île-du-Prince-Édouard ?",
       a:["Un titulaire d'un permis complet depuis au moins quatre ans, assis sur le siège avant du passager","Tout conducteur détenteur d'un permis et âgé de plus de dix-huit ans, assis n'importe où","Un conducteur de l'étape 3 assis à l'arrière","Un parent, qu'il détienne un permis ou non"],
       e:"Quatre années de détention du permis sont le minimum publié, et l'accompagnatrice ou l'accompagnateur doit être assis à côté de vous, où il voit la route et peut atteindre le volant." },
  c:0 },

{ id:"per10", sec:"rules", topic:"stage1",
  en:{ q:"What are the alcohol limits for a Stage 1 driver and for the accompanying driver?",
       a:["Both may be up to 0.08","The learner must be at zero and the accompanying driver under 0.05","Both must be at zero","Neither has a limit while the vehicle is stopped"],
       e:"The province publishes two different limits. A driver at any stage of the graduated program must be at zero for alcohol and drugs, while the accompanying driver has to stay under 0.05." },
  fr:{ q:"Quelles sont les limites d'alcool pour le conducteur de l'étape 1 et pour la personne qui l'accompagne ?",
       a:["Les deux peuvent aller jusqu'à 0,08","L'apprenti doit être à zéro et l'accompagnateur sous 0,05","Les deux doivent être à zéro","Ni l'un ni l'autre n'a de limite quand le véhicule est immobilisé"],
       e:"La province publie deux limites différentes. Un conducteur de n'importe quelle étape du programme progressif doit être à zéro pour l'alcool et les drogues, tandis que la personne qui l'accompagne doit rester sous 0,05." },
  c:1 },

{ id:"per11", sec:"rules", topic:"stage1",
  en:{ q:"Who may sit in the front seat while a Stage 1 driver is at the wheel?",
       a:["Nobody except the learner and the accompanying driver","Anyone, as long as everybody wears a seat belt","Two passengers as well as the learner","Only members of the learner's own family"],
       e:"The front seat is kept for those two people. That keeps the accompanying driver within reach of the wheel and removes a distraction from right beside the learner." },
  fr:{ q:"Qui peut prendre place sur le siège avant pendant qu'un conducteur de l'étape 1 est au volant ?",
       a:["Personne d'autre que l'apprenti et la personne qui l'accompagne","N'importe qui, tant que chacun porte sa ceinture de sécurité","Deux passagers en plus de l'apprenti","Seulement les membres de la famille de l'apprenti"],
       e:"Le siège avant est réservé à ces deux personnes. Cela garde l'accompagnateur à portée du volant et enlève une source de distraction juste à côté de l'apprenti." },
  c:0 },

{ id:"per12", sec:"rules", topic:"stage1",
  en:{ q:"Apart from the accompanying driver, who may ride in the vehicle with a Stage 1 driver?",
       a:["Any number of friends, provided all are belted","One passenger of any kind","Nobody at all","Immediate family members of the accompanying driver"],
       e:"Other passengers have to be immediate family of the accompanying driver. The rule is aimed at the carload of friends, which is one of the riskiest situations for a beginner." },
  fr:{ q:"Outre la personne qui l'accompagne, qui peut prendre place dans le véhicule d'un conducteur de l'étape 1 ?",
       a:["Autant d'amis qu'on veut, si chacun porte sa ceinture","Un seul passager, peu importe qui","Absolument personne","Les membres de la famille immédiate de la personne qui accompagne"],
       e:"Les autres passagers doivent être des membres de la famille immédiate de l'accompagnateur. La règle vise la voiture pleine d'amis, l'une des situations les plus risquées pour un débutant." },
  c:3 },

{ id:"per13", sec:"rules", topic:"stage1",
  en:{ q:"A Stage 1 driver under 21 wants to drive home at 2 a.m. with a proper accompanying driver. Is that allowed?",
       a:["Yes, the night restriction applies only at Stage 2","Yes, because somebody is supervising","No, drivers under 21 may not drive between 1 a.m. and 5 a.m.","Only at weekends"],
       e:"The night restriction runs from 1 a.m. to 5 a.m. for drivers under 21, and at Stage 1 having an accompanying driver in the car does not lift it." },
  fr:{ q:"Un conducteur de l'étape 1 de moins de 21 ans veut rentrer à 2 h du matin avec un accompagnateur en règle. Est-ce permis ?",
       a:["Oui, la restriction de nuit ne vise que l'étape 2","Oui, puisque quelqu'un le supervise","Non, les conducteurs de moins de 21 ans ne peuvent pas conduire entre 1 h et 5 h","Seulement la fin de semaine"],
       e:"La restriction de nuit court de 1 h à 5 h pour les moins de 21 ans. À l'étape 1, la présence d'un accompagnateur ne la lève pas." },
  c:2 },

{ id:"per14", sec:"rules", topic:"demerits",
  en:{ q:"What happens to a Stage 1 permit when the driver is convicted of an offence that carries demerit points?",
       a:["Nothing until six points have built up","A warning letter is sent for a first offence","The points are recorded but never lead to a suspension","The permit is suspended for at least 30 days, however few the points"],
       e:"At Stage 1 there is no allowance at all. Any conviction carrying demerit points suspends the instruction permit for a minimum of 30 days, which is stricter than the thresholds that apply later on." },
  fr:{ q:"Qu'arrive-t-il au permis d'apprenti lorsque son titulaire est déclaré coupable d'une infraction assortie de points d'inaptitude ?",
       a:["Rien tant que six points ne sont pas accumulés","Une lettre d'avertissement est envoyée à la première infraction","Les points sont inscrits mais n'entraînent jamais de suspension","Le permis est suspendu au moins 30 jours, si peu de points que ce soit"],
       e:"À l'étape 1, il n'y a aucune marge. Toute condamnation assortie de points d'inaptitude suspend le permis d'apprenti pendant au moins 30 jours, une règle plus sévère que les seuils des étapes suivantes." },
  c:3 },

{ id:"per15", sec:"rules", topic:"demerits",
  en:{ q:"How many demerit points bring a suspension for a Stage 2 or Stage 3 driver?",
       a:["Twelve, over any period","Three within six months","Six within 12 months, or nine within 24 months","There is no threshold at these stages"],
       e:"A newly licensed driver is suspended at six points within 12 months or nine within 24. A repeat offence also lengthens the time spent in the graduated program." },
  fr:{ q:"Combien de points d'inaptitude entraînent une suspension pour un conducteur de l'étape 2 ou de l'étape 3 ?",
       a:["Douze, sur n'importe quelle période","Trois en six mois","Six en 12 mois, ou neuf en 24 mois","Il n'y a aucun seuil à ces étapes"],
       e:"Un conducteur récemment titulaire d'un permis est suspendu à six points en 12 mois ou à neuf points en 24 mois. Une récidive allonge aussi la durée du programme progressif." },
  c:2 },

{ id:"per16", sec:"rules", topic:"demerits",
  en:{ q:"How many demerit points bring a suspension for the holder of a full licence?",
       a:["A single point is enough","Six","Nine","Twelve"],
       e:"Twelve points is the threshold for a full licence. Points come off the record two years after the date of the conviction, not two years after the offence was noticed." },
  fr:{ q:"Combien de points d'inaptitude entraînent une suspension pour un titulaire d'un permis complet ?",
       a:["Un seul point suffit","Six","Neuf","Douze"],
       e:"Douze points est le seuil pour un permis complet. Les points sont retirés du dossier deux ans après la date de la condamnation." },
  c:3 },

{ id:"per17", sec:"rules", topic:"schoolbus",
  en:{ q:"A school bus ahead of you switches on its flashing red lights. Who has to stop?",
       a:["Vehicles travelling in both directions","Only the vehicles behind the bus","Only vehicles in the same lane as the bus","Nobody, if a painted centre line separates the directions"],
       e:"On the Island traffic stops in both directions for a bus loading or unloading with its red lights flashing, and stays stopped until those lights stop flashing." },
  fr:{ q:"Un autobus scolaire devant vous allume ses feux rouges clignotants. Qui doit s'arrêter ?",
       a:["Les véhicules circulant dans les deux sens","Seulement les véhicules derrière l'autobus","Seulement les véhicules de la même voie que l'autobus","Personne, si une ligne médiane sépare les sens"],
       e:"À l'Île, la circulation s'arrête dans les deux sens pour un autobus qui fait monter ou descendre des enfants avec ses feux rouges clignotants, et reste arrêtée jusqu'à ce qu'ils cessent." },
  c:0 },

{ id:"per18", sec:"rules", topic:"schoolbus",
  en:{ q:"A school bus has stopped with its red lights flashing. Where should your vehicle come to rest?",
       a:["Directly behind it, as close as you can get","Not less than six metres from the front or the rear of the bus","Two car lengths, measured from your mirror","Anywhere in the lane will do"],
       e:"Six metres, about twenty feet, gives children room to walk around the bus and gives you the distance you need to see them before you move again." },
  fr:{ q:"Un autobus scolaire s'est arrêté, feux rouges clignotants. Où votre véhicule doit-il s'immobiliser ?",
       a:["Juste derrière lui, le plus près possible","À au moins six mètres de l'avant ou de l'arrière de l'autobus","À deux longueurs de voiture, mesurées depuis votre rétroviseur","N'importe où dans la voie fait l'affaire"],
       e:"Six mètres, environ vingt pieds, laissent aux enfants la place de contourner l'autobus et vous donnent la distance nécessaire pour les voir avant de repartir." },
  c:1 },

{ id:"per19", sec:"rules", topic:"schoolbus",
  en:{ q:"A school bus ahead of you has its amber lights flashing. What does that mean?",
       a:["The bus is about to stop, so get ready to stop as well","The bus is pulling away and you may follow it","The bus has broken down","The bus is empty and may be passed"],
       e:"Amber is the warning that the bus is slowing to load or unload. Red follows, and by the time it comes on you should already be at a standstill." },
  fr:{ q:"Un autobus scolaire devant vous fait clignoter ses feux jaunes. Qu'est-ce que cela signifie ?",
       a:["L'autobus va s'arrêter : préparez-vous à vous arrêter aussi","L'autobus repart et vous pouvez le suivre","L'autobus est en panne","L'autobus est vide et peut être dépassé"],
       e:"Le jaune avertit que l'autobus ralentit pour faire monter ou descendre des enfants. Le rouge suit, et vous devriez déjà être immobilisé quand il s'allume." },
  c:0 },

{ id:"per20", sec:"rules", topic:"schoolbus",
  en:{ q:"What does a driver face for going past a school bus while its red lights are flashing?",
       a:["A written warning for a first offence","Three demerit points","A parking ticket","Twelve demerit points, a three-month suspension and a fine of up to $5,000"],
       e:"Prince Edward Island treats this as one of the most serious offences on the road. The twelve points on their own are enough to suspend a full licence." },
  fr:{ q:"Que risque un conducteur qui dépasse un autobus scolaire dont les feux rouges clignotent ?",
       a:["Un avertissement écrit à la première infraction","Trois points d'inaptitude","Une contravention de stationnement","Douze points d'inaptitude, une suspension de trois mois et une amende pouvant atteindre 5 000 $"],
       e:"L'Île-du-Prince-Édouard traite cette infraction parmi les plus graves de la route. Les douze points suffisent à eux seuls à faire suspendre un permis complet." },
  c:3 },

{ id:"per21", sec:"rules", topic:"rules",
  en:{ q:"You are stopped at a red light and want to turn right. What does Prince Edward Island allow?",
       a:["Turn without stopping if the way looks clear","Never turn right while the light is red","Turn after a full stop and after yielding, unless a sign forbids it","Turn only once a green arrow appears"],
       e:"A right turn on a red light is permitted unless a sign says otherwise. The full stop comes first, then you give way to pedestrians and to traffic already coming." },
  fr:{ q:"Vous êtes arrêté à un feu rouge et vous voulez tourner à droite. Que permet l'Île-du-Prince-Édouard ?",
       a:["Tourner sans vous arrêter si la voie semble libre","Ne jamais tourner à droite pendant que le feu est rouge","Tourner après un arrêt complet et après avoir cédé le passage, sauf si un panneau l'interdit","Tourner seulement quand une flèche verte apparaît"],
       e:"Le virage à droite au feu rouge est permis sauf indication contraire d'un panneau. L'arrêt complet vient d'abord, puis vous cédez le passage aux piétons et aux véhicules qui arrivent." },
  c:2 },

{ id:"per22", sec:"rules", topic:"rules",
  en:{ q:"Two vehicles reach an intersection with no signs and no signals at the same moment. Who goes first?",
       a:["The larger vehicle","The vehicle on the right, because the driver on the left yields","The vehicle going straight ahead, in every case","Whichever driver signals first"],
       e:"At an uncontrolled intersection the right of way belongs to the vehicle on the right. Make eye contact all the same, because the rule protects nobody if the other driver does not know it." },
  fr:{ q:"Deux véhicules arrivent en même temps à une intersection sans panneau ni feu. Qui passe en premier ?",
       a:["Le plus gros véhicule","Le véhicule de droite, car le conducteur de gauche cède le passage","Le véhicule qui va tout droit, dans tous les cas","Le conducteur qui met son clignotant en premier"],
       e:"À une intersection non contrôlée, la priorité va au véhicule de droite. Établissez tout de même un contact visuel : la règle ne protège personne si l'autre conducteur l'ignore." },
  c:1 },

{ id:"per23", sec:"rules", topic:"rules",
  en:{ q:"When does Prince Edward Island require your headlights to be on?",
       a:["Only between midnight and dawn","Only during the winter months","From sunset to sunrise, and whenever you cannot see more than 500 feet","Only when it is raining"],
       e:"The rule combines the hour and the visibility. As soon as fog, rain or blowing snow cuts your view to 500 feet or less, the headlights go on whatever the time of day." },
  fr:{ q:"Quand l'Île-du-Prince-Édouard exige-t-elle que vos phares soient allumés ?",
       a:["Seulement entre minuit et l'aube","Seulement pendant les mois d'hiver","Du coucher au lever du soleil, et dès que vous ne voyez pas au-delà de 500 pieds","Seulement quand il pleut"],
       e:"La règle combine l'heure et la visibilité. Dès que le brouillard, la pluie ou la poudrerie réduit votre vue à 500 pieds ou moins, les phares s'allument, quelle que soit l'heure." },
  c:2 },

{ id:"per24", sec:"rules", topic:"rules",
  en:{ q:"Unless a sign says otherwise, what are the speed limits in a Prince Edward Island residential area and business district?",
       a:["40 km/h and 50 km/h","30 km/h and 40 km/h","50 km/h in both","50 km/h in a residential area and 60 km/h in a business district"],
       e:"The 60 km/h default in business districts catches visitors out, because they expect the same number as on a residential street. Both figures apply only where no sign says otherwise." },
  fr:{ q:"Sauf indication contraire, quelles sont les limites de vitesse dans un secteur résidentiel et dans un quartier commercial de l'Île-du-Prince-Édouard ?",
       a:["40 km/h et 50 km/h","30 km/h et 40 km/h","50 km/h dans les deux cas","50 km/h en secteur résidentiel et 60 km/h en quartier commercial"],
       e:"Le 60 km/h des quartiers commerciaux surprend les visiteurs, qui s'attendent au même chiffre que dans une rue résidentielle. Les deux limites ne valent que là où aucun panneau n'indique autre chose." },
  c:3 },

{ id:"per25", sec:"rules", topic:"rules",
  en:{ q:"Is it legal to use a working radar detector in a vehicle in Prince Edward Island?",
       a:["No, radar detectors are illegal here","Yes, as long as it is not fixed to the windscreen","Yes, for drivers over 25 with a full licence","Yes, outside built-up areas"],
       e:"Radar detectors are against the law in the province. Drivers arriving from a place where they are tolerated need to leave the device behind." },
  fr:{ q:"Est-il légal d'utiliser un détecteur de radar en fonction dans un véhicule à l'Île-du-Prince-Édouard ?",
       a:["Non, les détecteurs de radar y sont illégaux","Oui, tant qu'il n'est pas fixé au pare-brise","Oui, pour les conducteurs de plus de 25 ans détenant un permis complet","Oui, en dehors des zones bâties"],
       e:"Les détecteurs de radar sont interdits dans la province. Les conducteurs venant d'un endroit où ils sont tolérés doivent laisser l'appareil derrière eux." },
  c:0 },

{ id:"per26", sec:"rules", topic:"rules",
  en:{ q:"May passengers ride in the open box of a pickup truck in Prince Edward Island?",
       a:["Yes, if they sit down on the floor of the box","Yes, on country roads only","No, riding in the open box is prohibited","Yes, provided the truck stays below 50 km/h"],
       e:"It is prohibited. Nothing holds a person in an open box, so a hard stop or a sharp curve is enough to throw them out of the vehicle." },
  fr:{ q:"Des passagers peuvent-ils voyager dans la boîte ouverte d'une camionnette à l'Île-du-Prince-Édouard ?",
       a:["Oui, s'ils s'assoient au fond de la boîte","Oui, sur les routes de campagne seulement","Non, voyager dans la boîte ouverte est interdit","Oui, si la camionnette reste sous 50 km/h"],
       e:"C'est interdit. Rien ne retient une personne dans une boîte ouverte : un freinage brusque ou une courbe serrée suffit à l'éjecter du véhicule." },
  c:2 },

{ id:"per27", sec:"rules", topic:"roads",
  en:{ q:"There is no speed sign in sight on an open Prince Edward Island highway. What limit applies?",
       a:["100 km/h, as on most Canadian highways","80 km/h, and no limit posted anywhere in the province is higher than 90","90 km/h everywhere outside a town","Whatever suits the conditions, with no fixed number"],
       e:"The open-highway default is 80 km/h and the highest limit posted anywhere in the province is 90. Drivers used to 100 or 110 km/h elsewhere in Canada are the ones who get caught." },
  fr:{ q:"Aucun panneau de vitesse n'est visible sur une route de campagne de l'Île-du-Prince-Édouard. Quelle limite s'applique ?",
       a:["100 km/h, comme sur la plupart des routes canadiennes","80 km/h, et aucune limite affichée dans la province ne dépasse 90","90 km/h partout hors des villes","Celle que les conditions permettent, sans chiffre fixe"],
       e:"La limite par défaut en rase campagne est de 80 km/h et la plus élevée affichée dans la province est de 90. Ce sont les conducteurs habitués au 100 ou au 110 ailleurs au pays qui se font prendre." },
  c:1 },

{ id:"per28", sec:"rules", topic:"roads",
  en:{ q:"It is harvest time and you catch up to a wide, slow tractor on a country road. What is the sensible thing to do?",
       a:["Sound your horn until it moves over","Overtake at once, since it is slow anyway","Follow within a metre so you can see past it","Hold well back, stay patient, and pass only where you can see far enough ahead"],
       e:"Farm machinery is a normal part of traffic on the Island and it is wider than it looks. Sitting close behind hides the road from you and hides you from the machine's driver." },
  fr:{ q:"C'est la saison des récoltes et vous rattrapez un tracteur large et lent sur une route de campagne. Quelle est la bonne façon d'agir ?",
       a:["Klaxonner jusqu'à ce qu'il se range","Dépasser tout de suite, puisqu'il est lent de toute façon","Le suivre à un mètre pour mieux voir devant","Rester bien en arrière, être patient et ne dépasser que là où la visibilité est suffisante"],
       e:"La machinerie agricole fait partie de la circulation normale de l'Île et elle est plus large qu'elle en a l'air. Coller derrière vous cache la route et vous cache aussi au conducteur du tracteur." },
  c:3 },

{ id:"per29", sec:"rules", topic:"roads",
  en:{ q:"You are driving something slow and a line of traffic has built up behind you. What does Prince Edward Island require?",
       a:["Pull over where it is safe and let the traffic go by","Keep your speed and let them wait","Drive along the shoulder and carry on","Speed up to the limit even if the load makes that unsafe"],
       e:"A slow vehicle that is impeding or blocking traffic has to pull over and let it pass. Drivers trapped behind take chances, so letting them by is the safer choice for everyone." },
  fr:{ q:"Vous conduisez un véhicule lent et une file s'est formée derrière vous. Qu'exige l'Île-du-Prince-Édouard ?",
       a:["Vous ranger là où c'est sécuritaire et laisser passer la circulation","Garder votre vitesse et les laisser attendre","Rouler sur l'accotement et continuer","Accélérer jusqu'à la limite même si le chargement rend cela dangereux"],
       e:"Un véhicule lent qui gêne ou bloque la circulation doit se ranger pour la laisser passer. Les conducteurs coincés derrière prennent des risques : les laisser passer est plus sûr pour tout le monde." },
  c:0 },

{ id:"per30", sec:"rules", topic:"roads",
  en:{ q:"How much room must you leave when you overtake a cyclist?",
       a:["Half a metre is enough on a quiet road","At least one metre, or as close to that as you can manage","Enough that your mirror clears them","Nothing is set out, you only have to slow down"],
       e:"The law on the Island sets one metre as the passing distance, or as near to it as possible. Where the road is too narrow to give that, stay behind until it opens up." },
  fr:{ q:"Quel espace devez-vous laisser en dépassant une personne à vélo ?",
       a:["Un demi-mètre suffit sur une route tranquille","Au moins un mètre, ou le plus près possible de cette distance","Assez pour que votre rétroviseur ne la touche pas","Rien n'est prévu, il suffit de ralentir"],
       e:"La loi de l'Île fixe un mètre comme distance de dépassement, ou le plus près possible de cette distance. Si la chaussée est trop étroite pour l'offrir, restez derrière jusqu'à ce qu'elle s'élargisse." },
  c:1 }

);

/* ---------------------------------------------------------------------------
   WHOSE NUMBERS ARE THESE? Ours, and we say so.

   Prince Edward Island publishes NEITHER a question count, NOR a pass mark,
   NOR a time limit for the written knowledge test. Nothing on
   princeedwardisland.ca, nothing in the Driver's Licenses Regulations and
   nothing in the Graduated Driver Licensing Regulations states any of the
   three. Three commercial practice sites all state "40 questions, 32 to pass,
   80%", and not one of them cites a government source for it. We are not going
   to repeat a number that decides whether somebody books a test, so the
   figures below — 15 signs, 15 rules, 12 to pass each, 30 minutes — are a
   clearly stated practice standard of OUR OWN. They are not the Province's.

   What the Province DOES publish, and what we use as fact on this page:
     - a wait of at least 7 days before rewriting a failed written exam,
     - no fee to rewrite that exam,
     - a wait of at least 14 days before a second road test,
     - a $20 instruction permit and a $20 test for the instruction permit.
   Those four are the Province's own.
   --------------------------------------------------------------------------- */
window.CQ_PROVINCE = {
  code: "PE",
  name: { en: "Prince Edward Island", fr: "Île-du-Prince-Édouard" },
  licence: "Class 7 Instruction Permit",
  minutes: 30,
  sections: [
    { id: "signs", ask: 15, pass: 12,
      name: { en: "Road Signs", fr: "Panneaux routiers" } },
    { id: "rules", ask: 15, pass: 12,
      name: { en: "Rules of the Road", fr: "Code de la route" } }
  ],
  handbook: { en: "Driver's Handbook",
              fr: "Guide du conducteur" },
  handbookUrl: "https://www.princeedwardisland.ca/en/publication/drivers-handbook",
  bookingUrl: "https://www.princeedwardisland.ca/en/information/transportation-and-infrastructure/drivers-license-exam-appointments",
  topics: [
    { id:"licensing", en:"Graduated Licensing",            fr:"Permis progressif" },
    { id:"permit",    en:"Your Permit and the Exams",      fr:"Votre permis et les examens" },
    { id:"stage1",    en:"Stage 1 Rules for Learners",     fr:"Règles de l'étape 1 pour les apprentis" },
    { id:"demerits",  en:"Demerit Points and Suspensions", fr:"Points d'inaptitude et suspensions" },
    { id:"schoolbus", en:"School Buses and School Zones",  fr:"Autobus scolaires et zones scolaires" },
    { id:"rules",     en:"Rules of the Road",              fr:"Code de la route" },
    { id:"roads",     en:"Country Roads and Farm Machinery", fr:"Routes de campagne et machinerie agricole" }
  ],
  questions: window.CQ_DRIVE_Q
};


/* Ten more rules questions, added 3 September 2026.
   Written from this jurisdiction's own official handbook, and
   chosen for what makes its rules different from its neighbours'.
   The French is written beside the English on purpose: see the
   note at the top of tools/newq/fr_qbank.py. */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"pex1", sec:"rules",
  en:{ q:"How long does the whole Prince Edward Island graduated programme take at minimum?",
       a:["One year","Two years","Three years","Five years"],
       e:"Three stages of 365 days each make three years, or a little under with driver education. It is the longest graduated programme in Atlantic Canada." },
  fr:{ q:"Combien de temps dure au minimum tout le programme d'accès graduel de l'Île-du-Prince-Édouard ?",
       a:["Un an","Deux ans","Trois ans","Cinq ans"],
       e:"Trois étapes de 365 jours chacune font trois ans, ou un peu moins avec une formation de conducteur. C'est le plus long programme d'accès graduel du Canada atlantique." },
  c:2 },

{ id:"pex2", sec:"rules",
  en:{ q:"Which hours are closed to a Prince Edward Island driver under 21 in the first two stages?",
       a:["Midnight to 5 a.m.","1 a.m. to 5 a.m.","11 p.m. to 6 a.m.","There is no curfew"],
       e:"Prince Edward Island's curfew starts at 1 a.m., an hour later than its Atlantic neighbours, and applies only to drivers under 21." },
  fr:{ q:"Quelles heures sont interdites à un conducteur de moins de 21 ans aux deux premières étapes, à l'Île-du-Prince-Édouard ?",
       a:["De minuit à 5 h","De 1 h à 5 h","De 23 h à 6 h","Il n'y a pas de couvre-feu"],
       e:"Le couvre-feu de l'Île-du-Prince-Édouard commence à 1 h, une heure plus tard que chez ses voisins de l'Atlantique, et ne s'applique qu'aux conducteurs de moins de 21 ans." },
  c:1 },

{ id:"pex3", sec:"rules",
  en:{ q:"How many non-family passengers may a Prince Edward Island Stage 2 driver carry?",
       a:["None","One","Three","As many as there are seat belts"],
       e:"Only one passenger may be outside the immediate family. Immediate family may fill the remaining seat belts — so a carload of cousins is fine, but two friends is not." },
  fr:{ q:"Combien de passagers hors de la famille un conducteur de l'étape 2 peut-il transporter à l'Île-du-Prince-Édouard ?",
       a:["Aucun","Un","Trois","Autant qu'il y a de ceintures"],
       e:"Un seul passager peut être hors de la famille immédiate. La famille immédiate peut occuper les autres ceintures : une voiture pleine de cousins est permise, mais deux amis ne le sont pas." },
  c:1 },

{ id:"pex4", sec:"rules",
  en:{ q:"Until what age must a Prince Edward Island driver keep a zero blood alcohol level?",
       a:["18","19","22","25"],
       e:"Zero tolerance carries on past the graduated programme: every driver under 22 must have no alcohol at all, even with a full licence." },
  fr:{ q:"Jusqu'à quel âge un conducteur de l'Île-du-Prince-Édouard doit-il maintenir un taux d'alcoolémie nul ?",
       a:["18 ans","19 ans","22 ans","25 ans"],
       e:"La tolérance zéro se poursuit au-delà du programme gradué : tout conducteur de moins de 22 ans ne doit avoir aucun alcool, même avec un permis complet." },
  c:2 },

{ id:"pex5", sec:"rules",
  en:{ q:"What must a Prince Edward Island new driver display on the vehicle?",
       a:["Nothing","A yellow 'L' or 'G' decal","A red triangle","The learner's permit itself"],
       e:"Stage 1 drivers display a yellow L decal and later stages a G decal. Replacements are free." },
  fr:{ q:"Que doit afficher sur son véhicule un nouveau conducteur de l'Île-du-Prince-Édouard ?",
       a:["Rien","Un autocollant jaune « L » ou « G »","Un triangle rouge","Le permis d'apprenti lui-même"],
       e:"Les conducteurs de l'étape 1 affichent un autocollant jaune « L » et les étapes suivantes un autocollant « G ». Les remplacements sont gratuits." },
  c:1 },

{ id:"pex6", sec:"rules",
  en:{ q:"What does a distracted driving ticket cost on Prince Edward Island?",
       a:["$172.50","$233.95","$340.50","$575 to $1,275 and 5 demerit points"],
       e:"Prince Edward Island has the steepest hand-held phone fine in Atlantic Canada. New drivers are also barred from headphones and every hand-held device." },
  fr:{ q:"Combien coûte une contravention pour conduite distraite à l'Île-du-Prince-Édouard ?",
       a:["172,50 $","233,95 $","340,50 $","De 575 $ à 1 275 $ et 5 points d'inaptitude"],
       e:"L'Île-du-Prince-Édouard impose l'amende la plus élevée du Canada atlantique pour le téléphone à main. Les nouveaux conducteurs ne peuvent non plus porter d'écouteurs ni utiliser d'appareil à main." },
  c:3 },

{ id:"pex7", sec:"rules",
  en:{ q:"What blood alcohol level must a Prince Edward Island accompanying driver stay under?",
       a:["Under 0.05","Zero","Under 0.08","There is no limit for the supervisor"],
       e:"The accompanying driver must be under 0.05, hold a licence for at least four years, and sit in the front seat at all times. In Newfoundland and Labrador the supervisor must be at zero." },
  fr:{ q:"Quel taux d'alcoolémie l'accompagnateur doit-il respecter à l'Île-du-Prince-Édouard ?",
       a:["Moins de 0,05","Zéro","Moins de 0,08","Aucune limite pour l'accompagnateur"],
       e:"L'accompagnateur doit avoir moins de 0,05, détenir un permis depuis au moins quatre ans et occuper le siège avant en tout temps. À Terre-Neuve-et-Labrador, l'accompagnateur doit être à zéro." },
  c:0 },

{ id:"pex8", sec:"rules",
  en:{ q:"What happens to a Prince Edward Island Stage 1 driver who collects any demerit points?",
       a:["Nothing until six points","A suspension of at least 30 days","A written warning only","A fine but no suspension"],
       e:"At Stage 1 any conviction carrying demerit points brings a suspension of at least 30 days. Stage 2 allows 6 points and Stage 3 allows 9." },
  fr:{ q:"Qu'arrive-t-il à un conducteur de l'étape 1 qui accumule des points d'inaptitude à l'Île-du-Prince-Édouard ?",
       a:["Rien avant six points","Une suspension d'au moins 30 jours","Un simple avertissement écrit","Une amende sans suspension"],
       e:"À l'étape 1, toute condamnation entraînant des points d'inaptitude donne lieu à une suspension d'au moins 30 jours. L'étape 2 permet 6 points et l'étape 3, 9 points." },
  c:1 },

{ id:"pex9", sec:"rules",
  en:{ q:"When may a child stop using a booster seat on Prince Edward Island?",
       a:["At age 6","At 18 kg","At age 10 or 145 cm, whichever comes first","At age 12"],
       e:"A child may leave the booster on turning 10 or reaching 145 cm, whichever comes first — an older age than most provinces use." },
  fr:{ q:"Quand un enfant peut-il cesser d'utiliser un siège d'appoint à l'Île-du-Prince-Édouard ?",
       a:["À 6 ans","À 18 kg","À 10 ans ou 145 cm, selon la première éventualité","À 12 ans"],
       e:"Un enfant peut quitter le siège d'appoint à 10 ans ou à 145 cm, selon la première éventualité, soit un âge plus avancé que dans la plupart des provinces." },
  c:2 },

{ id:"pex10", sec:"rules",
  en:{ q:"How much may driver education shorten Stage 1 on Prince Edward Island?",
       a:["To 180 days","To 275 days","To 90 days","It cannot be shortened"],
       e:"Certified driver education cuts Stage 1 from 365 days to 275. Stages 2 and 3 remain 365 days each." },
  fr:{ q:"De combien une formation de conducteur peut-elle raccourcir l'étape 1 à l'Île-du-Prince-Édouard ?",
       a:["À 180 jours","À 275 jours","À 90 jours","Elle ne peut pas être raccourcie"],
       e:"Une formation reconnue réduit l'étape 1 de 365 à 275 jours. Les étapes 2 et 3 demeurent de 365 jours chacune." },
  c:1 }
);
