/* canada-quiz.com — QUEBEC Class 5 learner's licence practice data
   Test format, and 60 original bilingual questions (30 road signs + 30 rules).
   Written in our own words from the free public information published by the SAAQ.
   Not affiliated with the SAAQ or the Gouvernement du Québec.

   The quiz code lives in js/driving-engine.js and never changes per province. */
window.CQ_DRIVE_Q = [];

/* ---------- road signs ---------- */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"qcs1", sec:"signs", sign:"stop",
  en:{ q:"In Quebec this sign reads ARRÊT. What must you do at it?",
       a:["Come to a complete stop every time, then go when it is safe","Stop only in daylight","Yield to the right only","Slow and continue if clear"],
       e:"Quebec uses the French word ARRÊT on its octagonal stop signs. The rule is the same everywhere: a full stop, at the line, every time." },
  fr:{ q:"Au Québec, ce panneau indique ARRÊT. Que devez-vous y faire ?",
       a:["Faire un arrêt complet chaque fois, puis repartir quand c'est sécuritaire","Arrêter seulement le jour","Céder le passage à droite seulement","Ralentir et continuer si la voie est libre"],
       e:"Le Québec utilise le mot ARRÊT sur ses panneaux octogonaux. La règle est la même partout : un arrêt complet, à la ligne, chaque fois." },
  c:0 },

{ id:"qcs2", sec:"signs", sign:"yield",
  en:{ q:"What does this triangular sign require of you?",
       a:["Stop completely every time","Let traffic already on the road go first","Speed up to merge","Turn right only"],
       e:"Slow down, look, and enter only when there is a safe gap. Stop if there is no gap — yielding does not mean forcing your way in." },
  fr:{ q:"Qu'exige de vous ce panneau triangulaire ?",
       a:["Un arrêt complet chaque fois","Laisser passer d'abord la circulation déjà sur la route","Accélérer pour vous insérer","Tourner à droite seulement"],
       e:"Ralentissez, regardez et engagez-vous seulement s'il y a un espace sécuritaire. Arrêtez-vous s'il n'y en a pas : céder le passage n'est pas s'imposer." },
  c:1 },

{ id:"qcs3", sec:"signs", sign:"speed-50",
  en:{ q:"What does this sign tell you?",
       a:["A recommended speed in good weather","The minimum speed allowed","The maximum speed allowed here","The distance to the next town"],
       e:"It is a legal maximum, not a target. In rain, snow or heavy traffic you must drive slower than the number shown." },
  fr:{ q:"Que vous indique ce panneau ?",
       a:["Une vitesse conseillée par beau temps","La vitesse minimale permise","La vitesse maximale permise ici","La distance jusqu'au prochain village"],
       e:"C'est un maximum légal, pas un objectif. Sous la pluie, la neige ou dans une circulation dense, vous devez rouler plus lentement." },
  c:2 },

{ id:"qcs4", sec:"signs", sign:"no-entry",
  en:{ q:"You are facing this sign. What does it mean?",
       a:["Stop and wait for a signal","Parking is banned","Trucks only","Do not enter — traffic comes the other way"],
       e:"Entering here would put you head-on into traffic. Find another route rather than reversing into the intersection you just left." },
  fr:{ q:"Vous faites face à ce panneau. Que signifie-t-il ?",
       a:["Arrêtez et attendez un signal","Le stationnement est interdit","Camions seulement","Entrée interdite — la circulation vient en sens inverse"],
       e:"Entrer ici vous placerait face à la circulation. Prenez un autre chemin plutôt que de reculer dans l'intersection que vous venez de quitter." },
  c:3 },

{ id:"qcs5", sec:"signs", sign:"one-way",
  en:{ q:"What does this arrow sign tell you about the street?",
       a:["Traffic flows in one direction only","Parking is on one side only","The street is closed","Cyclists only"],
       e:"Follow the arrow. If it points against you, the street is one way and you must not enter." },
  fr:{ q:"Que vous indique ce panneau fléché au sujet de la rue ?",
       a:["La circulation se fait dans un seul sens","Le stationnement n'est que d'un côté","La rue est fermée","Cyclistes seulement"],
       e:"Suivez la flèche. Si elle pointe contre vous, la rue est à sens unique et vous ne devez pas vous y engager." },
  c:0 },

{ id:"qcs6", sec:"signs", sign:"no-left-turn",
  en:{ q:"What is forbidden where this sign stands?",
       a:["Parking","Turning left","Going straight","Stopping"],
       e:"A red ring with a slash bans what is drawn inside it. Continue and turn where it is permitted instead." },
  fr:{ q:"Qu'est-ce qui est interdit là où se trouve ce panneau ?",
       a:["Le stationnement","Le virage à gauche","Aller tout droit","L'arrêt"],
       e:"Un cercle rouge barré interdit ce qui est illustré à l'intérieur. Continuez et tournez là où c'est permis." },
  c:1 },

{ id:"qcs7", sec:"signs", sign:"no-u-turn",
  en:{ q:"What manoeuvre does this sign prohibit?",
       a:["Passing","Reversing","A U-turn","A three-point turn in a driveway"],
       e:"U-turns are also banned wherever you cannot be seen from far enough away — on curves, near the crest of a hill and across a median." },
  fr:{ q:"Quelle manœuvre ce panneau interdit-il ?",
       a:["Le dépassement","La marche arrière","Le demi-tour","Un virage en trois points dans une entrée"],
       e:"Le demi-tour est aussi interdit partout où l'on ne peut pas vous voir venir d'assez loin : courbes, sommets de côtes et terre-pleins." },
  c:2 },

{ id:"qcs8", sec:"signs", sign:"no-parking",
  en:{ q:"What does this sign allow you to still do?",
       a:["Park overnight","Park on weekends","Leave the car and go shopping","Stop briefly to drop someone off"],
       e:"No parking still permits a brief stop with the driver present, for example to let a passenger out. No stopping would forbid even that." },
  fr:{ q:"Que vous permet encore ce panneau ?",
       a:["Stationner la nuit","Stationner la fin de semaine","Laisser la voiture et aller magasiner","Vous immobiliser brièvement pour déposer quelqu'un"],
       e:"Le stationnement interdit permet encore un arrêt bref avec le conducteur au volant, par exemple pour laisser descendre un passager. L'arrêt interdit l'empêcherait." },
  c:3 },

{ id:"qcs9", sec:"signs", sign:"no-stopping",
  en:{ q:"How is this sign stricter than a no-parking sign?",
       a:["You may not halt at all, even briefly","It applies only to trucks","It bans left turns as well","It applies only at night"],
       e:"No stopping means exactly that. You may only stop to obey a police officer, a traffic signal or to avoid a collision." },
  fr:{ q:"En quoi ce panneau est-il plus strict qu'un panneau de stationnement interdit ?",
       a:["Vous ne pouvez pas vous immobiliser du tout, même brièvement","Il ne vise que les camions","Il interdit aussi les virages à gauche","Il ne s'applique que la nuit"],
       e:"Arrêt interdit veut dire exactement cela. Vous ne pouvez vous immobiliser que pour obéir à un policier, à un feu, ou pour éviter une collision." },
  c:0 },

{ id:"qcs10", sec:"signs", sign:"no-passing",
  en:{ q:"Why is passing banned where this sign stands?",
       a:["The road is newly paved","You cannot see far enough ahead to pass safely","Trucks use the road","There is a school nearby"],
       e:"No-passing zones sit where a hill or curve shortens your view. A car can appear in the seconds you would spend on the wrong side." },
  fr:{ q:"Pourquoi le dépassement est-il interdit là où se trouve ce panneau ?",
       a:["La chaussée est neuve","Vous ne voyez pas assez loin devant pour dépasser en sécurité","Des camions empruntent la route","Il y a une école à proximité"],
       e:"Les zones sans dépassement se trouvent là où une côte ou une courbe raccourcit la vue. Une voiture peut surgir pendant les secondes passées du mauvais côté." },
  c:1 },

{ id:"qcs11", sec:"signs", sign:"keep-right",
  en:{ q:"An island splits the road and this sign faces you. Which side do you take?",
       a:["Stop and wait","Either side","The side the arrow points to","Always the left"],
       e:"Follow the arrow. Going the wrong way around the island puts you into oncoming traffic." },
  fr:{ q:"Un îlot sépare la route et ce panneau vous fait face. De quel côté passez-vous ?",
       a:["Arrêtez et attendez","De n'importe quel côté","Du côté indiqué par la flèche","Toujours à gauche"],
       e:"Suivez la flèche. Contourner l'îlot du mauvais côté vous place face à la circulation." },
  c:2 },

{ id:"qcs12", sec:"signs", sign:"no-trucks",
  en:{ q:"Who may not use the road past this sign?",
       a:["Motorcycles","Cyclists","Buses","Trucks"],
       e:"Trucks must take another route, while cars and other small vehicles may still use this road." },
  fr:{ q:"Qui ne peut pas emprunter la route après ce panneau ?",
       a:["Les motocyclettes","Les cyclistes","Les autobus","Les camions"],
       e:"Les camions doivent prendre un autre chemin, tandis que les autos et les autres petits véhicules peuvent encore utiliser cette route." },
  c:3 },

{ id:"qcs13", sec:"signs", sign:"ped-crossover",
  en:{ q:"A person is crossing at this sign. When may you drive on?",
       a:["Once they are all the way across and back on the sidewalk","Immediately, if you steer around","After counting to three","As soon as they leave your lane"],
       e:"Wait until the person has finished crossing. A driver in another lane may not see them, so nobody moves until the crossing is complete." },
  fr:{ q:"Une personne traverse à ce panneau. Quand pouvez-vous repartir ?",
       a:["Une fois qu'elle a fini de traverser et qu'elle est sur le trottoir","Tout de suite, en la contournant","Après avoir compté jusqu'à trois","Dès qu'elle quitte votre voie"],
       e:"Attendez que la personne ait fini de traverser. Un conducteur dans une autre voie pourrait ne pas la voir : personne ne bouge avant la fin." },
  c:0 },

{ id:"qcs14", sec:"signs", sign:"stop-school-bus",
  en:{ q:"A Quebec school bus has its red lights flashing and this arm out. What must you do?",
       a:["Pass slowly on the left","Stop, whether behind the bus or coming toward it","Stop only if behind it","Sound your horn"],
       e:"Traffic in both directions stops, unless a median separates the road. Failing to stop for a school bus is among the heaviest fines in Quebec." },
  fr:{ q:"Un autobus scolaire québécois a ses feux rouges clignotants et ce bras déployé. Que devez-vous faire ?",
       a:["Dépasser lentement par la gauche","Vous arrêter, que vous soyez derrière ou en sens inverse","Vous arrêter seulement si vous êtes derrière","Klaxonner"],
       e:"La circulation s'arrête dans les deux sens, sauf si un terre-plein sépare la route. Ne pas s'arrêter pour un autobus scolaire compte parmi les amendes les plus lourdes au Québec." },
  c:1 },

{ id:"qcs15", sec:"signs", sign:"warn-school-zone",
  en:{ q:"What should you watch for most in the area this sign marks?",
       a:["Falling rock","Trucks reversing","Children stepping out from between parked cars","Farm machinery"],
       e:"Children do not check before they step out. Cover the brake, keep your eyes moving and expect someone you have not seen yet." },
  fr:{ q:"Que devez-vous surveiller le plus dans le secteur indiqué par ce panneau ?",
       a:["Des chutes de pierres","Des camions qui reculent","Des enfants qui surgissent d'entre les voitures stationnées","De la machinerie agricole"],
       e:"Les enfants ne regardent pas avant de s'élancer. Gardez le pied près du frein, balayez la scène du regard et attendez-vous à voir surgir quelqu'un." },
  c:2 },

{ id:"qcs16", sec:"signs", sign:"warn-pedestrian",
  en:{ q:"What is this yellow diamond warning you about?",
       a:["A parking entrance","A hospital","A bus terminal","People crossing the road ahead"],
       e:"Yellow diamonds warn of what is coming. Ease off the gas and scan both shoulders as you approach." },
  fr:{ q:"De quoi ce losange jaune vous avertit-il ?",
       a:["L'entrée d'un stationnement","Un hôpital","Un terminus d'autobus","Des gens qui traversent la route plus loin"],
       e:"Les losanges jaunes annoncent ce qui s'en vient. Levez le pied et surveillez les deux accotements en approchant." },
  c:3 },

{ id:"qcs17", sec:"signs", sign:"warn-slippery",
  en:{ q:"What does this sign warn you about?",
       a:["The road may be slippery when wet","A gravel road begins","A bridge is ahead","Snow removal in progress"],
       e:"Slow before the slippery section, not on it. Braking hard on a low-grip surface is what starts a skid." },
  fr:{ q:"De quoi ce panneau vous avertit-il ?",
       a:["La chaussée peut être glissante lorsqu'elle est mouillée","Un chemin de gravier commence","Un pont approche","Déneigement en cours"],
       e:"Ralentissez avant la section glissante, pas dessus. Freiner fort sur une surface peu adhérente est ce qui déclenche un dérapage." },
  c:0 },

{ id:"qcs18", sec:"signs", sign:"warn-curve-right",
  en:{ q:"How should you take the curve this sign announces?",
       a:["Brake in the middle of it","Slow before it, then hold a steady speed through","Accelerate into it","Change lanes inside it"],
       e:"Set your speed before you turn the wheel. Braking mid-curve shifts weight off the rear tires just when you need their grip." },
  fr:{ q:"Comment aborder la courbe annoncée par ce panneau ?",
       a:["Freiner en plein milieu","Ralentir avant, puis garder une vitesse stable dans la courbe","Accélérer en y entrant","Changer de voie à l'intérieur"],
       e:"Réglez votre vitesse avant de tourner le volant. Freiner au milieu de la courbe allège les pneus arrière au moment où leur adhérence compte." },
  c:1 },

{ id:"qcs19", sec:"signs", sign:"warn-steep-hill",
  en:{ q:"You see this sign before a long descent. What is the right technique?",
       a:["Coast in neutral","Turn off the engine","Shift to a lower gear and let the engine slow you","Ride the brakes all the way"],
       e:"Constant braking heats the brakes until they fade. A lower gear does the work and keeps the brakes ready for when you truly need them." },
  fr:{ q:"Vous voyez ce panneau avant une longue descente. Quelle est la bonne technique ?",
       a:["Rouler au point mort","Couper le moteur","Rétrograder et laisser le moteur vous ralentir","Freiner sans arrêt tout le long"],
       e:"Un freinage constant chauffe les freins jusqu'à les rendre inefficaces. Un rapport inférieur fait le travail et garde les freins disponibles." },
  c:2 },

{ id:"qcs20", sec:"signs", sign:"warn-merge",
  en:{ q:"This sign warns of merging traffic. What is the courteous, safe response?",
       a:["Drive in their blind spot","Stop on the main road","Speed up so nobody gets in","Adjust your speed or move over to leave a gap"],
       e:"Merging works when both drivers help. Move over a lane where safe, or ease off slightly so the joining vehicle can blend in at speed." },
  fr:{ q:"Ce panneau annonce une insertion. Quelle est la réaction courtoise et sécuritaire ?",
       a:["Rouler dans son angle mort","Vous arrêter sur la route principale","Accélérer pour que personne ne s'insère","Ajuster votre vitesse ou vous déplacer pour laisser un espace"],
       e:"L'insertion fonctionne quand les deux conducteurs collaborent. Changez de voie si c'est sécuritaire, ou levez légèrement le pied." },
  c:3 },

{ id:"qcs21", sec:"signs", sign:"warn-railway",
  en:{ q:"What must you never do at the crossing this sign announces?",
       a:["Start across before you can see the far side is clear","Look both ways","Open your window to listen","Slow down"],
       e:"Never enter a crossing you cannot clear. One train can also hide another, so check every track before you move." },
  fr:{ q:"Que ne devez-vous jamais faire au passage à niveau annoncé par ce panneau ?",
       a:["Vous engager avant de voir que l'autre côté est dégagé","Regarder des deux côtés","Ouvrir votre fenêtre pour écouter","Ralentir"],
       e:"Ne vous engagez jamais dans un passage que vous ne pouvez pas dégager. Un train peut en cacher un autre : vérifiez chaque voie avant d'avancer." },
  c:0 },

{ id:"qcs22", sec:"signs", sign:"warn-roundabout",
  en:{ q:"Who has the right of way in the roundabout this sign announces?",
       a:["Whoever arrives first","Traffic already circulating inside","The largest vehicle","Traffic entering from the right"],
       e:"Yield to traffic already going around, look left for a gap, travel counter-clockwise and signal right just before your exit." },
  fr:{ q:"Qui a la priorité dans le carrefour giratoire annoncé par ce panneau ?",
       a:["Le premier arrivé","La circulation qui tourne déjà dans l'anneau","Le plus gros véhicule","La circulation venant de la droite"],
       e:"Cédez le passage à la circulation déjà engagée, cherchez un espace à gauche, tournez dans le sens antihoraire et signalez à droite juste avant votre sortie." },
  c:1 },

{ id:"qcs23", sec:"signs", sign:"warn-deer",
  en:{ q:"When is the animal on this sign most likely to be on the road?",
       a:["Only during rain","At midday","At dawn and dusk","Only in July"],
       e:"Deer move most at first and last light, exactly when your eyes are adjusting. Scan the ditches, and expect more than one." },
  fr:{ q:"Quand l'animal de ce panneau risque-t-il le plus d'être sur la route ?",
       a:["Seulement sous la pluie","À midi","À l'aube et au crépuscule","Seulement en juillet"],
       e:"Les chevreuils bougent surtout aux premières et dernières lueurs, quand vos yeux s'adaptent. Surveillez les fossés et attendez-vous à en voir plusieurs." },
  c:2 },

{ id:"qcs24", sec:"signs", sign:"temp-construction",
  en:{ q:"What changes in the orange zone this sign marks?",
       a:["Parking becomes free","The road becomes one way","Nothing changes","Speeding fines can be doubled when workers are present"],
       e:"Slow to the posted work-zone limit as soon as you see orange, and watch for people working close to your lane." },
  fr:{ q:"Qu'est-ce qui change dans la zone orange indiquée par ce panneau ?",
       a:["Le stationnement devient gratuit","La route devient à sens unique","Rien ne change","Les amendes pour excès de vitesse peuvent doubler en présence de travailleurs"],
       e:"Ralentissez à la limite affichée dès que vous voyez de l'orange, et surveillez les personnes qui travaillent près de votre voie." },
  c:3 },

{ id:"qcs25", sec:"signs", sign:"temp-flagger",
  en:{ q:"A traffic control person signals you to stop while the light is green. Who do you obey?",
       a:["The traffic control person","Whichever is closer","Neither","The green light"],
       e:"A person directing traffic overrides signs and signals. Ignoring them in a work zone puts workers in danger and is an offence." },
  fr:{ q:"Un signaleur vous fait signe d'arrêter alors que le feu est vert. Qui écoutez-vous ?",
       a:["Le signaleur","Le plus proche des deux","Ni l'un ni l'autre","Le feu vert"],
       e:"Une personne qui dirige la circulation a préséance sur les panneaux et les feux. L'ignorer dans une zone de travaux met les travailleurs en danger et constitue une infraction." },
  c:0 },

{ id:"qcs26", sec:"signs", sign:"light-amber",
  en:{ q:"The light turns amber as you approach. What is correct?",
       a:["Always accelerate through","Stop if you can do so safely; continue only if stopping would be dangerous","Always brake hard","Sound your horn"],
       e:"Amber means the red is coming. If you are so close that hard braking would cause a rear-end collision, carry on and clear the intersection." },
  fr:{ q:"Le feu passe au jaune à votre approche. Quelle est la bonne conduite ?",
       a:["Toujours accélérer pour passer","Arrêter si vous pouvez le faire en sécurité ; continuer seulement si l'arrêt serait dangereux","Toujours freiner brusquement","Klaxonner"],
       e:"Le jaune annonce le rouge. Si vous êtes si près qu'un freinage brusque provoquerait une collision arrière, continuez et dégagez l'intersection." },
  c:1 },

{ id:"qcs27", sec:"signs", sign:"light-red",
  en:{ q:"Where in Quebec is a right turn on a red light forbidden?",
       a:["Only at night","Nowhere, it is always allowed","On the island of Montreal, and wherever a sign forbids it","Only on highways"],
       e:"Right on red is allowed in most of Quebec after a complete stop, but not on the island of Montreal, and never where a sign prohibits it." },
  fr:{ q:"Où, au Québec, le virage à droite au feu rouge est-il interdit ?",
       a:["Seulement la nuit","Nulle part, il est toujours permis","Sur l'île de Montréal, et partout où un panneau l'interdit","Seulement sur les autoroutes"],
       e:"Le virage à droite au feu rouge est permis dans la plus grande partie du Québec après un arrêt complet, mais pas sur l'île de Montréal, et jamais là où un panneau l'interdit." },
  c:2 },

{ id:"qcs28", sec:"signs", sign:"mark-solid-yellow",
  en:{ q:"A double solid yellow line runs down the middle of the road. What does it stop you doing?",
       a:["Stopping at the curb","Signalling","Turning left into a driveway","Crossing it to pass another vehicle"],
       e:"You may not cross it to pass. You may still cross it to turn left into a driveway or side road when it is safe." },
  fr:{ q:"Une double ligne jaune continue court au milieu de la route. Qu'est-ce qu'elle vous interdit ?",
       a:["Vous arrêter le long du trottoir","Signaler","Tourner à gauche dans une entrée","La franchir pour dépasser un véhicule"],
       e:"Vous ne pouvez pas la franchir pour dépasser. Vous pouvez toutefois la traverser pour tourner à gauche dans une entrée ou une rue transversale." },
  c:3 },

{ id:"qcs29", sec:"signs", sign:"mark-crosswalk",
  en:{ q:"Someone has stepped onto these painted lines. What must you do?",
       a:["Yield and wait","Drive around behind them","Flash your lights","Reverse"],
       e:"Painted lines mark where people cross. Once someone is on them, you wait — turning across in front of them is dangerous and an offence." },
  fr:{ q:"Quelqu'un s'est engagé sur ces lignes peintes. Que devez-vous faire ?",
       a:["Céder le passage et attendre","Le contourner par l'arrière","Faire un appel de phares","Reculer"],
       e:"Les lignes peintes indiquent où les gens traversent. Dès que quelqu'un s'y engage, vous attendez : lui couper le chemin est dangereux et constitue une infraction." },
  c:0 },

{ id:"qcs30", sec:"signs", sign:"info-hospital",
  en:{ q:"What kind of sign is this blue one?",
       a:["A warning of danger","An information sign showing a service nearby","An order you must obey","A construction sign"],
       e:"Blue signs point to services — hospital, fuel, food, accessible parking. They inform rather than command." },
  fr:{ q:"De quel type est ce panneau bleu ?",
       a:["Un avertissement de danger","Un panneau d'information indiquant un service à proximité","Un ordre à respecter","Un panneau de chantier"],
       e:"Les panneaux bleus indiquent des services : hôpital, carburant, restauration, stationnement accessible. Ils informent plutôt qu'ils n'ordonnent." },
  c:1 }

);

/* ---------- rules of the road ---------- */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"qcr1", sec:"rules", topic:"licensing",
  en:{ q:"How much alcohol may a Quebec learner's licence holder have in their blood?",
       a:["Under .08","No limit applies","Zero","Under .05"],
       e:"The zero-alcohol rule applies for the whole learning period, and to every driver aged 21 and under regardless of licence." },
  fr:{ q:"Quel taux d'alcool un titulaire de permis d'apprenti conducteur au Québec peut-il avoir dans le sang ?",
       a:["Moins de 0,08","Aucune limite ne s'applique","Zéro","Moins de 0,05"],
       e:"La règle du zéro alcool s'applique pendant toute la période d'apprentissage, et à tout conducteur de 21 ans ou moins peu importe son permis." },
  c:2 },

{ id:"qcr2", sec:"rules", topic:"licensing",
  en:{ q:"Who may accompany a Quebec learner driver?",
       a:["A parent only","Anyone over 18","Anyone with a licence","A holder of a valid Quebec Class 5 licence with at least two years of experience"],
       e:"The accompanying driver needs a valid Class 5 and at least two years of driving experience, and must be able to help you at any moment." },
  fr:{ q:"Qui peut accompagner un apprenti conducteur au Québec ?",
       a:["Un parent seulement","Toute personne de plus de 18 ans","N'importe quel titulaire de permis","Une personne détenant un permis québécois de classe 5 valide avec au moins deux ans d'expérience"],
       e:"L'accompagnateur doit détenir un permis de classe 5 valide et au moins deux ans d'expérience de conduite, et pouvoir vous aider à tout moment." },
  c:3 },

{ id:"qcr3", sec:"rules", topic:"licensing",
  en:{ q:"Between which hours may a Quebec learner not drive?",
       a:["Midnight and 5 a.m.","10 p.m. and 6 a.m.","1 a.m. and 4 a.m.","There is no restriction"],
       e:"Learners must be off the road between midnight and 5 a.m., the hours when fatigue, poor visibility and impaired drivers combine." },
  fr:{ q:"Entre quelles heures un apprenti conducteur québécois ne peut-il pas conduire ?",
       a:["Minuit et 5 h","22 h et 6 h","1 h et 4 h","Il n'y a aucune restriction"],
       e:"Les apprentis doivent quitter la route entre minuit et 5 h, les heures où la fatigue, la faible visibilité et les conducteurs aux facultés affaiblies se combinent." },
  c:0 },

{ id:"qcr4", sec:"rules", topic:"licensing",
  en:{ q:"What is the minimum age to hold a learner's licence in Quebec?",
       a:["18","16","15","17"],
       e:"Sixteen. If you are under 18 you also need the written consent of a parent or guardian." },
  fr:{ q:"Quel est l'âge minimal pour détenir un permis d'apprenti conducteur au Québec ?",
       a:["18 ans","16 ans","15 ans","17 ans"],
       e:"Seize ans. Si vous avez moins de 18 ans, vous devez aussi obtenir le consentement écrit d'un parent ou tuteur." },
  c:1 },

{ id:"qcr5", sec:"rules", topic:"licensing",
  en:{ q:"How long must you hold a Quebec learner's licence before the road test?",
       a:["6 months","24 months","At least 12 months","3 months"],
       e:"At least twelve months. The learner's licence itself is valid for eighteen months." },
  fr:{ q:"Combien de temps devez-vous détenir un permis d'apprenti au Québec avant l'examen sur route ?",
       a:["6 mois","24 mois","Au moins 12 mois","3 mois"],
       e:"Au moins douze mois. Le permis d'apprenti conducteur est lui-même valide pendant dix-huit mois." },
  c:2 },

{ id:"qcr6", sec:"rules", topic:"licence",
  en:{ q:"What demerit point bracket applies to a Quebec learner driver?",
       a:["Fifteen points","Eight points","There is no limit","Four points"],
       e:"A learner is in the four-point bracket, far tighter than an experienced driver. Points accumulate quickly on a new record." },
  fr:{ q:"Quelle marge de points d'inaptitude s'applique à un apprenti conducteur au Québec ?",
       a:["Quinze points","Huit points","Il n'y a aucune limite","Quatre points"],
       e:"Un apprenti se trouve dans la marge de quatre points, bien plus serrée que celle d'un conducteur expérimenté. Les points s'accumulent vite sur un nouveau dossier." },
  c:3 },

{ id:"qcr7", sec:"rules", topic:"licence",
  en:{ q:"What must you carry with you whenever you drive in Quebec?",
       a:["Your licence, the registration certificate and proof of insurance","Only your licence",
          "Only the registration","Nothing, records are electronic"],
       e:"All three. A police officer may ask for each one, and driving without them can bring a fine even if you own the car." },
  fr:{ q:"Que devez-vous avoir avec vous chaque fois que vous conduisez au Québec ?",
       a:["Votre permis, le certificat d'immatriculation et la preuve d'assurance","Seulement votre permis",
          "Seulement l'immatriculation","Rien, les dossiers sont électroniques"],
       e:"Les trois. Un policier peut exiger chacun d'eux, et conduire sans eux peut valoir une amende même si la voiture vous appartient." },
  c:0 },

{ id:"qcr8", sec:"rules", topic:"safe",
  en:{ q:"What is the default speed limit on a Quebec city street with no posted sign?",
       a:["80 km/h","50 km/h","30 km/h","60 km/h"],
       e:"Fifty in a built-up area. On a rural road with no sign it is 90 km/h, and most autoroutes are posted at 100." },
  fr:{ q:"Quelle est la limite de vitesse par défaut dans une rue de ville au Québec sans panneau ?",
       a:["80 km/h","50 km/h","30 km/h","60 km/h"],
       e:"Cinquante en zone bâtie. Sur une route rurale sans panneau, c'est 90 km/h, et la plupart des autoroutes sont affichées à 100." },
  c:1 },

{ id:"qcr9", sec:"rules", topic:"safe",
  en:{ q:"What is the standard following distance in good conditions?",
       a:["Half a second","Ten metres at any speed","Two seconds","One car length"],
       e:"Pick a fixed object and count. Reaching it less than two seconds after the car ahead means you are too close — and double that in rain or snow." },
  fr:{ q:"Quelle est la distance de suivi normale par bonnes conditions ?",
       a:["Une demi-seconde","Dix mètres à toute vitesse","Deux secondes","Une longueur de voiture"],
       e:"Choisissez un point fixe et comptez. L'atteindre moins de deux secondes après la voiture devant signifie que vous êtes trop près — doublez sous la pluie ou la neige." },
  c:2 },

{ id:"qcr10", sec:"rules", topic:"safe",
  en:{ q:"What must you check that your mirrors cannot show you before changing lanes?",
       a:["The fuel gauge","The radio","The odometer","The blind spot, by looking over your shoulder"],
       e:"Mirrors leave a gap beside and behind you large enough to hide a car or a motorcycle. Only a shoulder check reveals it." },
  fr:{ q:"Que devez-vous vérifier, que vos rétroviseurs ne montrent pas, avant de changer de voie ?",
       a:["La jauge d'essence","La radio","L'odomètre","L'angle mort, en regardant par-dessus votre épaule"],
       e:"Les rétroviseurs laissent à côté et derrière vous un espace assez grand pour cacher une voiture ou une moto. Seul un coup d'œil par-dessus l'épaule le révèle." },
  c:3 },

{ id:"qcr11", sec:"rules", topic:"safe",
  en:{ q:"You want to turn left at a green light with oncoming traffic. Where do you wait?",
       a:["In the intersection with your wheels straight","In the intersection with your wheels turned left",
          "Behind the stop line","On the shoulder"],
       e:"Wheels straight. If you are struck from behind with the wheels turned, your car is pushed into oncoming traffic instead of straight ahead." },
  fr:{ q:"Vous voulez tourner à gauche à un feu vert avec de la circulation en sens inverse. Où attendez-vous ?",
       a:["Dans l'intersection, les roues droites","Dans l'intersection, les roues tournées vers la gauche",
          "Derrière la ligne d'arrêt","Sur l'accotement"],
       e:"Les roues droites. Si vous êtes heurté par l'arrière avec les roues tournées, votre voiture est poussée vers la circulation en sens inverse." },
  c:0 },

{ id:"qcr12", sec:"rules", topic:"safe",
  en:{ q:"Two vehicles reach an all-way stop at exactly the same moment, side by side. Who goes first?",
       a:["Whoever moves first","The vehicle on the right","The vehicle on the left","The larger vehicle"],
       e:"The driver on the right. Make eye contact and be ready to yield even when the rule is on your side." },
  fr:{ q:"Deux véhicules arrivent en même temps à un arrêt toutes directions, côte à côte. Qui passe en premier ?",
       a:["Le premier qui avance","Le véhicule de droite","Le véhicule de gauche","Le plus gros véhicule"],
       e:"Le conducteur de droite. Établissez un contact visuel et soyez prêt à céder même quand la règle vous favorise." },
  c:1 },

{ id:"qcr13", sec:"rules", topic:"sharing",
  en:{ q:"How much room must you leave when passing a cyclist on a Quebec road posted over 50 km/h?",
       a:["One metre","No set distance","At least 1.5 metres","Half a metre"],
       e:"A metre and a half where the limit is over 50 km/h, and one metre where it is 50 or under. If the lane is too narrow, change lanes or wait." },
  fr:{ q:"Quel espace devez-vous laisser en dépassant un cycliste sur une route québécoise affichée à plus de 50 km/h ?",
       a:["Un mètre","Aucune distance précise","Au moins 1,5 mètre","Un demi-mètre"],
       e:"Un mètre et demi là où la limite dépasse 50 km/h, et un mètre là où elle est de 50 ou moins. Si la voie est trop étroite, changez de voie ou attendez." },
  c:2 },

{ id:"qcr14", sec:"rules", topic:"sharing",
  en:{ q:"An emergency vehicle approaches with lights and siren. What should you do?",
       a:["Speed up to clear the road","Stop in the middle of the lane","Follow closely behind it","Pull as far right as you safely can and stop"],
       e:"Signal, move right and stop clear of the intersection. Never follow closely — a second emergency vehicle may be right behind." },
  fr:{ q:"Un véhicule d'urgence approche, gyrophares et sirène en marche. Que devriez-vous faire ?",
       a:["Accélérer pour dégager la route","Vous arrêter au milieu de la voie","Le suivre de près","Vous ranger le plus à droite possible en sécurité et vous arrêter"],
       e:"Signalez, rangez-vous à droite et arrêtez-vous hors de l'intersection. Ne le suivez jamais de près : un second véhicule peut arriver derrière." },
  c:3 },

{ id:"qcr15", sec:"rules", topic:"sharing",
  en:{ q:"Why should you avoid sitting beside a large truck's rear wheels?",
       a:["It is the driver's worst blind spot","It uses more fuel","It is illegal everywhere","The noise is loud"],
       e:"If you cannot see the driver's face in their mirror, they cannot see you. Pass decisively or hold well back." },
  fr:{ q:"Pourquoi éviter de rouler à côté des roues arrière d'un gros camion ?",
       a:["C'est le pire angle mort du conducteur","Cela consomme plus de carburant","C'est illégal partout","Le bruit est fort"],
       e:"Si vous ne voyez pas le visage du conducteur dans son rétroviseur, il ne vous voit pas. Dépassez franchement ou restez bien en retrait." },
  c:0 },

{ id:"qcr16", sec:"rules", topic:"sharing",
  en:{ q:"What must you do before opening your door on a Montreal street?",
       a:["Sound your horn","Check your mirror and look over your shoulder for cyclists","Open slowly, that is enough","Nothing, cyclists must avoid doors"],
       e:"A cyclist struck by an opening door can be thrown into traffic. Checking first takes a second and prevents a serious injury." },
  fr:{ q:"Que devez-vous faire avant d'ouvrir votre portière dans une rue de Montréal ?",
       a:["Klaxonner","Vérifier votre rétroviseur et regarder par-dessus l'épaule pour les cyclistes","Ouvrir lentement, cela suffit","Rien, les cyclistes doivent éviter les portières"],
       e:"Un cycliste heurté par une portière peut être projeté dans la circulation. Vérifier prend une seconde et évite une blessure grave." },
  c:1 },

{ id:"qcr17", sec:"rules", topic:"conditions",
  en:{ q:"When are winter tires mandatory on passenger vehicles registered in Quebec?",
       a:["From 1 November to 30 April","Only north of Quebec City","From 1 December to 15 March","All year"],
       e:"Quebec is the only province with a mandatory winter tire law for passenger vehicles. Driving without them in that window brings a fine." },
  fr:{ q:"Quand les pneus d'hiver sont-ils obligatoires sur les véhicules de promenade immatriculés au Québec ?",
       a:["Du 1er novembre au 30 avril","Seulement au nord de Québec","Du 1er décembre au 15 mars","Toute l'année"],
       e:"Le Québec est la seule province où les pneus d'hiver sont obligatoires sur les véhicules de promenade. Rouler sans eux durant cette période vaut une amende." },
  c:2 },

{ id:"qcr18", sec:"rules", topic:"conditions",
  en:{ q:"When is a wet Quebec road usually most slippery?",
       a:["After hours of rain","Only when freezing","Only on gravel","In the first minutes of rain"],
       e:"Rain lifts oil and rubber off the pavement first, leaving a greasy film. Slow down as soon as the first drops fall." },
  fr:{ q:"Quand une chaussée mouillée est-elle habituellement la plus glissante au Québec ?",
       a:["Après des heures de pluie","Seulement par temps de gel","Seulement sur le gravier","Dans les premières minutes de pluie"],
       e:"La pluie soulève d'abord l'huile et la gomme, laissant une pellicule glissante. Ralentissez dès les premières gouttes." },
  c:3 },

{ id:"qcr19", sec:"rules", topic:"conditions",
  en:{ q:"Where does black ice usually form first on a Quebec road?",
       a:["On bridges, overpasses and shaded spots","In the middle of a sunny street","Only in parking lots","Only on gravel"],
       e:"Bridges lose heat from above and below, so they freeze before the road does. Shaded curves are the other classic trap." },
  fr:{ q:"Où la glace noire se forme-t-elle d'abord sur une route québécoise ?",
       a:["Sur les ponts, les viaducs et les endroits ombragés","Au milieu d'une rue ensoleillée","Seulement dans les stationnements","Seulement sur le gravier"],
       e:"Les ponts perdent leur chaleur par le dessus et le dessous : ils gèlent avant la route. Les courbes ombragées sont l'autre piège classique." },
  c:0 },

{ id:"qcr20", sec:"rules", topic:"conditions",
  en:{ q:"Which lights should you use in heavy fog?",
       a:["Hazard lights while moving","Low beams","High beams","No lights"],
       e:"High beams reflect off the fog and blind you. Low beams sit under the fog layer and light the road ahead." },
  fr:{ q:"Quels feux devez-vous utiliser dans un brouillard épais ?",
       a:["Les feux de détresse en roulant","Les feux de croisement","Les feux de route","Aucun feu"],
       e:"Les feux de route se reflètent sur le brouillard et vous aveuglent. Les feux de croisement passent sous la couche et éclairent la route." },
  c:1 },

{ id:"qcr21", sec:"rules", topic:"impaired",
  en:{ q:"Is a hands-free phone allowed while driving in Quebec?",
       a:["Yes, holding is fine at red lights","Only for calls under one minute","Yes, but holding any device is prohibited","No device of any kind is allowed"],
       e:"Holding a phone or any portable screen while driving is prohibited, even stopped at a light. Hands-free use is permitted." },
  fr:{ q:"Le téléphone mains libres est-il permis au volant au Québec ?",
       a:["Oui, le tenir est correct aux feux rouges","Seulement pour les appels de moins d'une minute","Oui, mais tenir un appareil en main est interdit","Aucun appareil n'est permis"],
       e:"Tenir un téléphone ou tout écran portatif en conduisant est interdit, même à l'arrêt à un feu. L'usage mains libres est permis." },
  c:2 },

{ id:"qcr22", sec:"rules", topic:"impaired",
  en:{ q:"Cannabis is legal in Canada. What does that mean for driving in Quebec?",
       a:["You may drive after using it","It only matters under 25","It is fine if you feel alert","Driving while impaired by it remains a criminal offence"],
       e:"Legal to buy is not legal to drive on. Cannabis slows reaction time and judgement, and the impaired driving law applies as it does with alcohol." },
  fr:{ q:"Le cannabis est légal au Canada. Qu'est-ce que cela signifie pour la conduite au Québec ?",
       a:["Vous pouvez conduire après en avoir pris","Cela ne compte que sous 25 ans","C'est acceptable si vous vous sentez alerte","Conduire avec les facultés affaiblies par le cannabis demeure une infraction criminelle"],
       e:"Légal à acheter ne veut pas dire légal pour conduire. Le cannabis ralentit les réflexes et le jugement, et la loi s'applique comme pour l'alcool." },
  c:3 },

{ id:"qcr23", sec:"rules", topic:"impaired",
  en:{ q:"What actually makes a person who has been drinking safe to drive again?",
       a:["Only time","Strong coffee","A cold shower","Fresh air"],
       e:"Nothing speeds up how fast the body clears alcohol. Coffee produces a wide-awake impaired driver, which is no safer." },
  fr:{ q:"Qu'est-ce qui rend vraiment une personne qui a bu de nouveau apte à conduire ?",
       a:["Seulement le temps","Un café fort","Une douche froide","De l'air frais"],
       e:"Rien n'accélère l'élimination de l'alcool. Le café produit un conducteur bien éveillé mais toujours aux facultés affaiblies." },
  c:0 },

{ id:"qcr24", sec:"rules", topic:"vehicle",
  en:{ q:"Who is responsible for making sure every passenger under 16 is buckled up?",
       a:["A parent, even if absent","The driver","Each passenger","The vehicle owner"],
       e:"The driver answers for every passenger under 16, including the correct child seat or booster for their size." },
  fr:{ q:"Qui doit s'assurer que chaque passager de moins de 16 ans est bien attaché ?",
       a:["Un parent, même absent","Le conducteur","Chaque passager","Le propriétaire du véhicule"],
       e:"Le conducteur répond de chaque passager de moins de 16 ans, y compris du siège d'auto ou du siège d'appoint adapté à sa taille." },
  c:1 },

{ id:"qcr25", sec:"rules", topic:"vehicle",
  en:{ q:"Why must you clear snow from the roof of your car, not just the windows?",
       a:["It saves fuel","It is not necessary","It can slide onto your windshield or fly into the car behind","It looks better"],
       e:"A slab of roof snow blinds you the moment you brake, or strikes the driver behind at speed. Clear the lights and plate too." },
  fr:{ q:"Pourquoi faut-il déneiger le toit de votre voiture, et pas seulement les vitres ?",
       a:["Cela économise du carburant","Ce n'est pas nécessaire","La neige peut glisser sur votre pare-brise ou s'envoler vers la voiture derrière","C'est plus joli"],
       e:"Une plaque de neige vous aveugle dès que vous freinez, ou frappe le conducteur derrière à vitesse. Dégagez aussi les feux et la plaque." },
  c:2 },

{ id:"qcr26", sec:"rules", topic:"vehicle",
  en:{ q:"How often should you check your tire pressure?",
       a:["Once a year","Only when one looks flat","Never, sensors handle it","About monthly, when the tires are cold"],
       e:"Cold weather lowers pressure, and underinflated tires grip worse and wear faster. Check monthly and before a long trip." },
  fr:{ q:"À quelle fréquence vérifier la pression de vos pneus ?",
       a:["Une fois par année","Seulement quand un pneu semble dégonflé","Jamais, les capteurs s'en chargent","Environ une fois par mois, à froid"],
       e:"Le froid fait baisser la pression, et des pneus sous-gonflés adhèrent moins bien et s'usent plus vite. Vérifiez chaque mois et avant un long trajet." },
  c:3 },

{ id:"qcr27", sec:"rules", topic:"collisions",
  en:{ q:"You are first at the scene of a collision in Quebec. What comes first?",
       a:["Make the scene safe and call 911","Move the injured out of the cars","Photograph everything","Move the vehicles"],
       e:"Protect the scene and call for help. Do not move an injured person unless there is an immediate danger such as fire." },
  fr:{ q:"Vous arrivez le premier sur les lieux d'une collision au Québec. Que faites-vous d'abord ?",
       a:["Sécuriser les lieux et appeler le 911","Sortir les blessés des voitures","Tout photographier","Déplacer les véhicules"],
       e:"Protégez les lieux et appelez à l'aide. Ne déplacez pas une personne blessée sauf danger immédiat, comme un incendie." },
  c:0 },

{ id:"qcr28", sec:"rules", topic:"collisions",
  en:{ q:"A tire blows out at highway speed. What should you do first?",
       a:["Switch off the engine","Hold the wheel firmly and ease off the gas","Brake hard immediately","Steer sharply to the shoulder"],
       e:"A blowout pulls the car sideways. Grip the wheel, come off the gas gently, and brake only once the car is slow and straight." },
  fr:{ q:"Un pneu éclate à vitesse d'autoroute. Que faites-vous en premier ?",
       a:["Couper le moteur","Tenir fermement le volant et lever le pied","Freiner brusquement tout de suite","Braquer vivement vers l'accotement"],
       e:"Un éclatement tire la voiture de côté. Tenez le volant, relâchez doucement l'accélérateur, et ne freinez qu'une fois la voiture lente et droite." },
  c:1 },

{ id:"qcr29", sec:"rules", topic:"collisions",
  en:{ q:"Why is fatigue treated as seriously as alcohol behind the wheel?",
       a:["It only matters on long trips","Coffee removes the risk","It slows reaction and judgement much like impairment, and can cause microsleeps","It is not, fatigue is harmless"],
       e:"A driver awake too long makes the same kind of mistakes as an impaired one. The only real fix is to stop and rest." },
  fr:{ q:"Pourquoi la fatigue est-elle prise aussi au sérieux que l'alcool au volant ?",
       a:["Cela ne compte que sur les longs trajets","Le café élimine le risque","Elle ralentit les réflexes et le jugement comme les facultés affaiblies, et peut causer des micro-sommeils","Elle ne l'est pas, la fatigue est sans danger"],
       e:"Un conducteur éveillé depuis trop longtemps commet le même genre d'erreurs qu'un conducteur aux facultés affaiblies. Le seul remède est de s'arrêter et de se reposer." },
  c:2 },

{ id:"qcr30", sec:"rules", topic:"collisions",
  en:{ q:"Your vehicle breaks down on a Quebec autoroute. Where should you stop?",
       a:["In the right lane with hazards on","In the left lane","On the median","As far onto the right shoulder as possible"],
       e:"Get right off the travelled lanes, put on your hazard lights, and if it is safe leave the car on the passenger side, away from traffic." },
  fr:{ q:"Votre véhicule tombe en panne sur une autoroute québécoise. Où devez-vous vous arrêter ?",
       a:["Dans la voie de droite avec les feux de détresse","Dans la voie de gauche","Sur le terre-plein","Le plus loin possible sur l'accotement de droite"],
       e:"Dégagez complètement les voies, allumez vos feux de détresse et, si c'est sécuritaire, sortez du côté passager, loin de la circulation." },
  c:3 }

);

/* ---------------------------------------------------------------------------
   THE PROVINCE. Everything the engine needs to run the Quebec practice test.
   --------------------------------------------------------------------------- */
window.CQ_PROVINCE = {
  code: "QC",
  name: { en: "Quebec", fr: "Québec" },
  licence: "Class 5",
  minutes: 30,
  /* The SAAQ knowledge test has three sections and you must reach 75% in EACH
     of them. It does not publish the exact number of questions, so our mock
     test uses a fair, clearly-stated approximation: 12 per section, pass 9. */
  sections: [
    { id: "signs", ask: 12, pass: 9,
      name: { en: "Road Signs and Signals", fr: "Panneaux et signaux" } },
    { id: "rules", ask: 12, pass: 9,
      name: { en: "Highway Safety Code and Driving", fr: "Code de la sécurité routière et conduite" } }
  ],
  handbook: { en: "SAAQ driver's guides and online knowledge test",
              fr: "Guides de la SAAQ et test de connaissances en ligne" },
  handbookUrl: "https://saaq.gouv.qc.ca/en/drivers-licences/obtaining-licence/passenger-vehicle-class-5",
  bookingUrl: "https://saaq.gouv.qc.ca/en/make-appointment/knowledge-road-test",
  topics: [
    { id:"licensing",  en:"Learner's Licence Rules",     fr:"Règles du permis d'apprenti" },
    { id:"safe",       en:"Safe and Responsible Driving", fr:"Conduite sécuritaire et responsable" },
    { id:"sharing",    en:"Sharing the Road",            fr:"Partager la route" },
    { id:"conditions", en:"Driving Conditions",          fr:"Conditions de conduite" },
    { id:"licence",    en:"Keeping Your Licence",        fr:"Conserver votre permis" },
    { id:"impaired",   en:"Impaired and Distracted Driving", fr:"Facultés affaiblies et distraction" },
    { id:"vehicle",    en:"Your Vehicle",                fr:"Votre véhicule" },
    { id:"collisions", en:"Emergencies and Collisions",  fr:"Urgences et collisions" }
  ],
  questions: window.CQ_DRIVE_Q
};


/* Ten more rules questions, added 3 September 2026.
   Written from this jurisdiction's own official handbook, and
   chosen for what makes its rules different from its neighbours'.
   The French is written beside the English on purpose: see the
   note at the top of tools/newq/fr_qbank.py. */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"qcx1", sec:"rules",
  en:{ q:"What must you complete in Quebec before you can even get a learner's licence?",
       a:["Nothing extra","A first aid course","The first modules of a recognised driving course","A year of supervised driving"],
       e:"Quebec requires the driving course to begin before the learner's licence is issued: you complete the first phase and pass the driving school's test first. Most provinces let you start driving before any course." },
  fr:{ q:"Que devez-vous faire au Québec avant même de pouvoir obtenir un permis d'apprenti conducteur ?",
       a:["Rien de plus","Un cours de premiers soins","Les premiers modules d'un cours de conduite reconnu","Un an de conduite accompagnée"],
       e:"Le Québec exige que le cours de conduite débute avant la délivrance du permis d'apprenti : vous terminez la première phase et réussissez l'examen de l'école de conduite d'abord. La plupart des provinces permettent de commencer à conduire avant tout cours." },
  c:2 },

{ id:"qcx2", sec:"rules",
  en:{ q:"Which drivers in Quebec must have zero alcohol in their blood?",
       a:["Only learner licence holders","Learners, probationary holders, and every driver under 22","Only drivers under 18","Nobody — the limit is .08 for all"],
       e:"Zero alcohol applies to learners and probationary holders whatever their age, and to every driver under 22. Note the cut-off: Quebec says under 22, Ontario says 21 and under." },
  fr:{ q:"Quels conducteurs au Québec doivent avoir zéro alcool dans le sang ?",
       a:["Seulement les titulaires d'un permis d'apprenti","Les apprentis, les titulaires d'un permis probatoire et tout conducteur de moins de 22 ans","Seulement les conducteurs de moins de 18 ans","Personne : la limite est de 0,08 pour tous"],
       e:"Le zéro alcool s'applique aux apprentis et aux titulaires d'un permis probatoire, quel que soit leur âge, et à tout conducteur de moins de 22 ans. Attention au seuil : le Québec dit moins de 22 ans, l'Ontario dit 21 ans ou moins." },
  c:1 },

{ id:"qcx3", sec:"rules",
  en:{ q:"How long must a Quebec accompanying rider have held a Class 5 licence?",
       a:["One year","Two years","Four years","Ten years"],
       e:"The accompanying rider must have held a valid Class 5 licence for at least two years. Someone still on a probationary licence may not act as an accompanying rider." },
  fr:{ q:"Depuis combien de temps l'accompagnateur québécois doit-il détenir un permis de classe 5 ?",
       a:["Un an","Deux ans","Quatre ans","Dix ans"],
       e:"L'accompagnateur doit détenir un permis de classe 5 valide depuis au moins deux ans. Une personne encore titulaire d'un permis probatoire ne peut pas servir d'accompagnateur." },
  c:1 },

{ id:"qcx4", sec:"rules",
  en:{ q:"How many demerit points cost a Quebec learner or probationary driver their licence?",
       a:["8","6","4","15"],
       e:"A learner or probationary licence is revoked at 4 points. A regular licence holder under 23 has 8, from 23 to 24 has 12, and from 25 has 15." },
  fr:{ q:"Combien de points d'inaptitude font perdre son permis à un apprenti ou à un conducteur probatoire au Québec ?",
       a:["8","6","4","15"],
       e:"Le permis d'apprenti ou probatoire est révoqué à 4 points. Le titulaire d'un permis régulier de moins de 23 ans en a 8 ; de 23 à 24 ans, 12 ; et à partir de 25 ans, 15." },
  c:2 },

{ id:"qcx5", sec:"rules",
  en:{ q:"What does a first distracted driving offence cost in Quebec?",
       a:["$100 and 2 points","A warning","$200 and 3 points","$300 to $600 and 5 demerit points"],
       e:"The fine is $300 to $600 with 5 demerit points, and the same penalty applies to every driver. Note that 5 points is more than the 4 a learner is allowed." },
  fr:{ q:"Que coûte une première infraction de conduite distraite au Québec ?",
       a:["100 $ et 2 points","Un avertissement","200 $ et 3 points","De 300 $ à 600 $ et 5 points d'inaptitude"],
       e:"L'amende va de 300 $ à 600 $ avec 5 points d'inaptitude, et la même sanction s'applique à tout conducteur. Notez que 5 points dépassent les 4 points permis à un apprenti." },
  c:3 },

{ id:"qcx6", sec:"rules",
  en:{ q:"When are winter tires mandatory in Quebec?",
       a:["1 November to 30 April","1 December to 15 March","Only when snow is on the ground","They are not mandatory"],
       e:"Every passenger vehicle registered in Quebec must have winter tires from 1 December to 15 March, marked with the mountain-and-snowflake pictogram. The fine is $200 to $300." },
  fr:{ q:"Quand les pneus d'hiver sont-ils obligatoires au Québec ?",
       a:["Du 1er novembre au 30 avril","Du 1er décembre au 15 mars","Seulement quand il y a de la neige au sol","Ils ne sont pas obligatoires"],
       e:"Tout véhicule de promenade immatriculé au Québec doit être muni de pneus d'hiver du 1er décembre au 15 mars, portant le pictogramme de la montagne et du flocon. L'amende va de 200 $ à 300 $." },
  c:1 },

{ id:"qcx7", sec:"rules",
  en:{ q:"Where in Quebec is turning right on a red light forbidden?",
       a:["On the whole island of Montreal","In Quebec City","On every autoroute","Nowhere — it is allowed everywhere"],
       e:"Right on red is allowed across Quebec except on the island of Montreal, and anywhere a sign forbids it. Quebec only allowed it province-wide in 2003." },
  fr:{ q:"Où, au Québec, le virage à droite au feu rouge est-il interdit ?",
       a:["Sur toute l'île de Montréal","À Québec","Sur toutes les autoroutes","Nulle part : c'est permis partout"],
       e:"Le virage à droite au feu rouge est permis partout au Québec, sauf sur l'île de Montréal et là où un panneau l'interdit. Le Québec ne l'a autorisé à l'échelle de la province qu'en 2003." },
  c:0 },

{ id:"qcx8", sec:"rules",
  en:{ q:"In Quebec, how do two drivers facing each other and both turning left pass one another?",
       a:["Behind each other","In front of each other","The larger vehicle goes first","Both must wait for a green arrow"],
       e:"In Quebec you turn in front of the oncoming vehicle that is also turning left. Drivers arriving from provinces where you pass behind each other need to unlearn the habit." },
  fr:{ q:"Au Québec, comment deux conducteurs qui se font face et tournent tous deux à gauche se croisent-ils ?",
       a:["L'un derrière l'autre","L'un devant l'autre","Le plus gros véhicule passe en premier","Les deux doivent attendre une flèche verte"],
       e:"Au Québec, vous tournez devant le véhicule venant en sens inverse qui tourne aussi à gauche. Les conducteurs venant de provinces où l'on se croise par l'arrière doivent désapprendre cette habitude." },
  c:1 },

{ id:"qcx9", sec:"rules",
  en:{ q:"How much space must a Quebec driver leave when passing a cyclist where the limit is over 50 km/h?",
       a:["No set distance","1 metre","1.5 metres","3 metres"],
       e:"Quebec sets the distance in law: 1 metre where the limit is 50 km/h or less, and 1.5 metres where it is higher." },
  fr:{ q:"Quel espace un conducteur québécois doit-il laisser en dépassant un cycliste là où la limite dépasse 50 km/h ?",
       a:["Aucune distance précise","1 mètre","1,5 mètre","3 mètres"],
       e:"Le Québec fixe la distance dans la loi : 1 mètre là où la limite est de 50 km/h ou moins, et 1,5 mètre là où elle est supérieure." },
  c:2 },

{ id:"qcx10", sec:"rules",
  en:{ q:"Until when must a child in Quebec use a car seat or booster?",
       a:["Until age 6","Until age 9 or 145 cm tall","Until 18 kg","Until age 12"],
       e:"Quebec uses one simple threshold: a car seat is needed until the child is 9 years old or at least 145 cm tall. Getting it wrong costs $80 to $100 and 3 demerit points." },
  fr:{ q:"Jusqu'à quand un enfant doit-il utiliser un siège d'auto ou un siège d'appoint au Québec ?",
       a:["Jusqu'à 6 ans","Jusqu'à 9 ans ou 145 cm","Jusqu'à 18 kg","Jusqu'à 12 ans"],
       e:"Le Québec applique un seuil simple : le siège d'auto est requis jusqu'à ce que l'enfant ait 9 ans ou mesure au moins 145 cm. Une erreur coûte de 80 $ à 100 $ et 3 points d'inaptitude." },
  c:1 }
);
