/* canada-quiz.com — SASKATCHEWAN Class 7 Learner practice data
   60 original bilingual questions (30 road signs + 30 rules of the road).
   Written in our own words from the free public information published by SGI.
   Not affiliated with SGI or the Government of Saskatchewan.

   The quiz code lives in js/driving-engine.js and never changes per province. */
window.CQ_DRIVE_Q = [];

/* ---------- road signs ---------- */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"sks1", sec:"signs", sign:"stop",
  en:{ q:"Where must you stop at this sign?",
       a:["At the stop line, or before the crosswalk if there is no line","Level with the sign post","Anywhere inside the intersection","Only if another vehicle is coming"],
       e:"Stop at the line first. If a snowbank or a parked truck blocks your view from there, creep forward and stop a second time once you can actually see." },
  fr:{ q:"Où devez-vous vous arrêter à ce panneau ?",
       a:["À la ligne d'arrêt, ou avant le passage pour piétons s'il n'y a pas de ligne","À la hauteur du poteau","N'importe où dans l'intersection","Seulement si un véhicule arrive"],
       e:"Arrêtez-vous d'abord à la ligne. Si un banc de neige ou un camion stationné bloque la vue, avancez lentement et arrêtez-vous une deuxième fois quand vous voyez vraiment." },
  c:0 },
{ id:"sks2", sec:"signs", sign:"yield",
  en:{ q:"What does this sign require?",
       a:["Slow down and give way, stopping only if you must","A full stop every time","Speed up to merge","Nothing, it is a warning"],
       e:"Yield means the other traffic goes first. You may keep rolling if the way is genuinely clear, but you must be ready to stop." },
  fr:{ q:"Qu'exige ce panneau ?",
       a:["Ralentir et céder le passage, en arrêtant seulement si nécessaire","Un arrêt complet chaque fois","Accélérer pour vous insérer","Rien, c'est un avertissement"],
       e:"Céder le passage veut dire que les autres passent d'abord. Vous pouvez continuer si la voie est vraiment libre, mais vous devez être prêt à arrêter." },
  c:0 },
{ id:"sks3", sec:"signs", sign:"speed-50",
  en:{ q:"What does a sign like this tell you?",
       a:["The maximum speed in good conditions","The speed you must drive","The minimum speed","A suggested speed for trucks"],
       e:"A posted limit is a maximum for ideal conditions. On glare ice or in blowing snow the safe speed is far lower, and driving the posted number can still be too fast." },
  fr:{ q:"Que vous indique un panneau comme celui-ci ?",
       a:["La vitesse maximale dans de bonnes conditions","La vitesse à laquelle vous devez rouler","La vitesse minimale","Une vitesse suggérée pour les camions"],
       e:"Une limite affichée est un maximum pour des conditions idéales. Sur la glace vive ou par poudrerie, la vitesse sécuritaire est bien plus basse, et rouler au chiffre affiché peut être trop vite." },
  c:0 },
{ id:"sks4", sec:"signs", sign:"speed-limit-begins",
  en:{ q:"What is about to happen?",
       a:["A new speed limit starts ahead","The road ends","Speeding is not enforced here","The limit you see applies behind you"],
       e:"This is your warning to be at the new speed by the time you reach the sign, not to start slowing after it." },
  fr:{ q:"Que va-t-il se passer ?",
       a:["Une nouvelle limite de vitesse commence plus loin","La route se termine","La vitesse n'est pas contrôlée ici","La limite affichée s'applique derrière vous"],
       e:"C'est un avertissement pour être à la nouvelle vitesse en arrivant au panneau, et non pour commencer à ralentir après." },
  c:0 },
{ id:"sks5", sec:"signs", sign:"no-entry",
  en:{ q:"What does this sign mean?",
       a:["Do not drive in past this point","No parking","Road closed to trucks only","Enter slowly"],
       e:"You are looking at the wrong end of a one-way street or an exit ramp. Traffic here is coming at you." },
  fr:{ q:"Que signifie ce panneau ?",
       a:["Ne pas entrer au-delà de ce point","Stationnement interdit","Route fermée aux camions seulement","Entrer lentement"],
       e:"Vous regardez le mauvais bout d'une rue à sens unique ou d'une bretelle de sortie. La circulation vient vers vous." },
  c:0 },
{ id:"sks6", sec:"signs", sign:"one-way",
  en:{ q:"What must you do here?",
       a:["Travel only in the direction of the arrow","Choose either direction","Stop and wait","Use this lane only to turn"],
       e:"One way means one way. Check the arrow before you turn in, especially downtown where two one-way streets often run side by side." },
  fr:{ q:"Que devez-vous faire ici ?",
       a:["Circuler seulement dans le sens de la flèche","Choisir l'un ou l'autre sens","Arrêter et attendre","Utiliser cette voie seulement pour tourner"],
       e:"Sens unique veut dire sens unique. Vérifiez la flèche avant de tourner, surtout au centre-ville où deux rues à sens unique se suivent souvent." },
  c:0 },
{ id:"sks7", sec:"signs", sign:"no-left-turn",
  en:{ q:"What is not allowed at this intersection?",
       a:["Turning left","Turning right","Going straight through","Stopping"],
       e:"Carry on and turn left further along. Three right turns around a block will get you there legally." },
  fr:{ q:"Qu'est-ce qui est interdit à cette intersection ?",
       a:["Tourner à gauche","Tourner à droite","Continuer tout droit","S'arrêter"],
       e:"Continuez et tournez à gauche plus loin. Trois virages à droite autour d'un pâté vous y mèneront légalement." },
  c:0 },
{ id:"sks8", sec:"signs", sign:"no-passing",
  en:{ q:"What does this sign prohibit?",
       a:["Passing another vehicle","Parking on the shoulder","Driving over 60 km/h","Trucks in the right lane"],
       e:"You cannot see far enough ahead to pass safely. On a two-lane highway that is exactly where head-on crashes happen." },
  fr:{ q:"Qu'interdit ce panneau ?",
       a:["Dépasser un autre véhicule","Stationner sur l'accotement","Rouler à plus de 60 km/h","Les camions dans la voie de droite"],
       e:"Vous ne voyez pas assez loin pour dépasser en sécurité. Sur une route à deux voies, c'est exactement là que surviennent les collisions frontales." },
  c:0 },
{ id:"sks9", sec:"signs", sign:"no-parking",
  en:{ q:"What does this sign mean?",
       a:["You may stop briefly to load or drop someone off, but not park","You may not stop for any reason","Parking is free here","Parking for residents only"],
       e:"No parking still lets you pause to let a passenger out. No stopping does not — the two signs are different." },
  fr:{ q:"Que signifie ce panneau ?",
       a:["Vous pouvez arrêter brièvement pour charger ou déposer quelqu'un, mais pas stationner","Vous ne pouvez arrêter pour aucune raison","Le stationnement est gratuit ici","Stationnement réservé aux résidents"],
       e:"Interdiction de stationner permet encore de faire descendre un passager. Interdiction d'arrêter, non : les deux panneaux sont différents." },
  c:0 },
{ id:"sks10", sec:"signs", sign:"no-stopping",
  en:{ q:"How is this different from a no parking sign?",
       a:["You may not stop at all, even to drop someone off","It is the same thing","It applies only overnight","It applies only to trucks"],
       e:"No stopping means keep moving unless traffic or a police officer makes you stop. These go where a stopped car would be dangerous." },
  fr:{ q:"En quoi est-ce différent d'un panneau d'interdiction de stationner ?",
       a:["Vous ne pouvez pas arrêter du tout, même pour laisser descendre quelqu'un","C'est la même chose","Cela s'applique seulement la nuit","Cela s'applique seulement aux camions"],
       e:"Interdiction d'arrêter veut dire continuez, sauf si la circulation ou un policier vous oblige à arrêter. On les place là où une voiture arrêtée serait dangereuse." },
  c:0 },
{ id:"sks11", sec:"signs", sign:"no-u-turn",
  en:{ q:"What does this sign forbid?",
       a:["Turning around to go back the way you came","Turning left","Reversing","Three-point turns only"],
       e:"U-turns are banned where oncoming drivers would not see you swing across in time." },
  fr:{ q:"Qu'interdit ce panneau ?",
       a:["Faire demi-tour pour repartir d'où vous venez","Tourner à gauche","Reculer","Seulement les demi-tours en trois manoeuvres"],
       e:"Les demi-tours sont interdits là où les conducteurs venant en sens inverse ne vous verraient pas traverser à temps." },
  c:0 },
{ id:"sks12", sec:"signs", sign:"keep-right",
  en:{ q:"What must you do when you see this?",
       a:["Pass to the right of the obstacle","Pass on either side","Stop and wait","Turn right at the next street"],
       e:"Something splits the road — a median, an island, a work zone. Take the right side of it." },
  fr:{ q:"Que devez-vous faire en voyant ceci ?",
       a:["Passer à droite de l'obstacle","Passer de chaque côté","Arrêter et attendre","Tourner à droite à la prochaine rue"],
       e:"Quelque chose sépare la route : un terre-plein, un îlot, une zone de travaux. Prenez le côté droit." },
  c:0 },
{ id:"sks13", sec:"signs", sign:"turn-left-only",
  en:{ q:"What does this lane sign require?",
       a:["Everyone in this lane must turn left","Left turns are allowed but not required","Left turns are banned","Only buses may turn left"],
       e:"If you are in this lane you are turning. Change lanes well before the intersection if you meant to go straight." },
  fr:{ q:"Qu'exige ce panneau de voie ?",
       a:["Tout le monde dans cette voie doit tourner à gauche","Le virage à gauche est permis mais non obligatoire","Le virage à gauche est interdit","Seuls les autobus peuvent tourner à gauche"],
       e:"Si vous êtes dans cette voie, vous tournez. Changez de voie bien avant l'intersection si vous vouliez continuer tout droit." },
  c:0 },
{ id:"sks14", sec:"signs", sign:"ped-crossover",
  en:{ q:"What must you do at this crossing?",
       a:["Yield to pedestrians and wait until they are safely across","Sound your horn","Speed up to clear the crossing","Stop only if a light is flashing"],
       e:"Wait until the person is fully across, not just past your own bumper." },
  fr:{ q:"Que devez-vous faire à ce passage ?",
       a:["Céder le passage aux piétons et attendre qu'ils aient traversé en sécurité","Klaxonner","Accélérer pour dégager le passage","Arrêter seulement si un feu clignote"],
       e:"Attendez que la personne ait complètement traversé, pas seulement dépassé votre pare-chocs." },
  c:0 },
{ id:"sks15", sec:"signs", sign:"stop-school-bus",
  en:{ q:"A school bus ahead has its red lights flashing. What must you do?",
       a:["Stop no closer than 5 metres from the bus and wait","Slow to 30 km/h and pass","Pass on the left only","Stop only if children are visible"],
       e:"In Saskatchewan you stop no closer than 5 m (15 ft) from the front or the back, from either direction on an undivided highway, until the lights go off and the stop arm folds in." },
  fr:{ q:"Un autobus scolaire devant vous a ses feux rouges clignotants. Que devez-vous faire ?",
       a:["Arrêter à au moins 5 mètres de l'autobus et attendre","Ralentir à 30 km/h et dépasser","Dépasser par la gauche seulement","Arrêter seulement si des enfants sont visibles"],
       e:"En Saskatchewan, vous arrêtez à au moins 5 m (15 pi) de l'avant ou de l'arrière, dans les deux sens sur une route non divisée, jusqu'à ce que les feux s'éteignent et que le bras d'arrêt se referme." },
  c:0 },
{ id:"sks16", sec:"signs", sign:"warn-school-zone",
  en:{ q:"What does this sign tell you?",
       a:["A school zone is ahead and a lower posted limit may apply","School is closed","Children may not cross here","Parking for school staff"],
       e:"Watch for the posted speed and the hours on the sign itself. Children step out from between parked cars without looking." },
  fr:{ q:"Que vous indique ce panneau ?",
       a:["Une zone scolaire approche et une limite réduite peut s'appliquer","L'école est fermée","Les enfants ne peuvent pas traverser ici","Stationnement pour le personnel"],
       e:"Surveillez la vitesse affichée et les heures inscrites sur le panneau. Les enfants surgissent d'entre les voitures stationnées sans regarder." },
  c:0 },
{ id:"sks17", sec:"signs", sign:"warn-playground",
  en:{ q:"What should you expect after this sign?",
       a:["Children playing near the road","A rest area","A sports stadium","A parking lot"],
       e:"A ball rolling onto the road is usually followed by a child. Cover the brake." },
  fr:{ q:"À quoi vous attendre après ce panneau ?",
       a:["Des enfants qui jouent près de la route","Une halte routière","Un stade","Un stationnement"],
       e:"Un ballon qui roule sur la route est presque toujours suivi d'un enfant. Gardez le pied près du frein." },
  c:0 },
{ id:"sks18", sec:"signs", sign:"warn-crossbuck",
  en:{ q:"What does this marker identify?",
       a:["A railway crossing","A crossroads","A bridge","A hospital"],
       e:"Look both ways and listen. A long freight train is quieter and far faster than it looks from the side." },
  fr:{ q:"Que signale ce repère ?",
       a:["Un passage à niveau","Un carrefour","Un pont","Un hôpital"],
       e:"Regardez des deux côtés et écoutez. Un long train de marchandises est plus silencieux et bien plus rapide qu'il n'y paraît de côté." },
  c:0 },
{ id:"sks19", sec:"signs", sign:"warn-railway",
  en:{ q:"You see this sign. What is coming?",
       a:["A railway crossing ahead","A level crossing you have already passed","A train station","A truck route"],
       e:"Be ready to stop. Never start across unless there is room for your whole vehicle on the far side." },
  fr:{ q:"Vous voyez ce panneau. Qu'est-ce qui approche ?",
       a:["Un passage à niveau devant","Un passage à niveau déjà franchi","Une gare","Une route pour camions"],
       e:"Soyez prêt à arrêter. Ne vous engagez jamais s'il n'y a pas de place pour tout votre véhicule de l'autre côté." },
  c:0 },
{ id:"sks20", sec:"signs", sign:"warn-deer",
  en:{ q:"What does this sign warn you about?",
       a:["Deer may cross the road here","A hunting area","A farm entrance","A wildlife park"],
       e:"Dawn and dusk are the worst hours, and deer travel in groups — if one crosses, slow right down and expect another." },
  fr:{ q:"Contre quoi ce panneau vous met-il en garde ?",
       a:["Des chevreuils peuvent traverser ici","Une zone de chasse","Une entrée de ferme","Un parc animalier"],
       e:"L'aube et le crépuscule sont les pires heures, et les chevreuils se déplacent en groupe : si un traverse, ralentissez et attendez-vous à un autre." },
  c:0 },
{ id:"sks21", sec:"signs", sign:"warn-moose",
  en:{ q:"Why is this animal a particular danger at highway speed?",
       a:["It is tall, so the body comes through the windshield","It always runs away from cars","It is only active in summer","It is smaller than a deer"],
       e:"A moose stands so high that the bumper takes out its legs and the body lands on the roof and windshield. Brake hard and aim behind it, never in front." },
  fr:{ q:"Pourquoi cet animal est-il particulièrement dangereux à vitesse d'autoroute ?",
       a:["Il est haut, alors le corps arrive dans le pare-brise","Il fuit toujours les voitures","Il n'est actif qu'en été","Il est plus petit qu'un chevreuil"],
       e:"Un orignal est si haut que le pare-chocs lui fauche les pattes et que le corps arrive sur le toit et le pare-brise. Freinez fort et visez derrière lui, jamais devant." },
  c:0 },
{ id:"sks22", sec:"signs", sign:"warn-slippery",
  en:{ q:"What does this sign mean?",
       a:["The road may be slippery, especially when wet or icy","The road is closed","A car wash is ahead","Loose gravel ahead"],
       e:"Ease off before you reach it. Braking or steering hard on a slippery surface is how a skid starts." },
  fr:{ q:"Que signifie ce panneau ?",
       a:["La chaussée peut être glissante, surtout mouillée ou glacée","La route est fermée","Un lave-auto approche","Gravier meuble devant"],
       e:"Ralentissez avant d'y arriver. Freiner ou braquer brusquement sur une surface glissante, c'est ainsi que commence un dérapage." },
  c:0 },
{ id:"sks23", sec:"signs", sign:"warn-steep-hill",
  en:{ q:"What should you do when you see this?",
       a:["Shift to a lower gear and control your speed before the descent","Speed up to get it over with","Turn off the engine to save fuel","Use the shoulder"],
       e:"Let the engine hold you back. Riding the brakes all the way down heats them until they fade." },
  fr:{ q:"Que faire en voyant ceci ?",
       a:["Rétrograder et maîtriser votre vitesse avant la descente","Accélérer pour en finir","Couper le moteur pour économiser","Utiliser l'accotement"],
       e:"Laissez le moteur vous retenir. Freiner sans arrêt jusqu'en bas chauffe les freins jusqu'à ce qu'ils perdent leur efficacité." },
  c:0 },
{ id:"sks24", sec:"signs", sign:"warn-curve-right",
  en:{ q:"What is ahead?",
       a:["A curve to the right","A right turn only lane","A road that ends","A right hand exit"],
       e:"Slow down before the curve, not in it. Braking mid-corner unsettles the car." },
  fr:{ q:"Qu'y a-t-il devant ?",
       a:["Une courbe vers la droite","Une voie de virage à droite obligatoire","Une route sans issue","Une sortie à droite"],
       e:"Ralentissez avant la courbe, pas dedans. Freiner en plein virage déséquilibre l'auto." },
  c:0 },
{ id:"sks25", sec:"signs", sign:"warn-chevron",
  en:{ q:"What is this sign telling you?",
       a:["The road turns sharply in this direction","You may pass here","The lane is closed","There is a picnic area"],
       e:"Several in a row mark a bend that is much tighter than it looks in the dark." },
  fr:{ q:"Que vous dit ce panneau ?",
       a:["La route tourne brusquement dans cette direction","Vous pouvez dépasser ici","La voie est fermée","Il y a une aire de pique-nique"],
       e:"Plusieurs à la suite marquent un virage bien plus serré qu'il n'y paraît dans le noir." },
  c:0 },
{ id:"sks26", sec:"signs", sign:"warn-merge",
  en:{ q:"What does this sign warn about?",
       a:["Traffic is joining your road ahead","Your lane ends immediately","A passing lane starts","A truck stop is ahead"],
       e:"Merging works when both sides adjust. Make room where you can and match the speed of the traffic you are joining." },
  fr:{ q:"Contre quoi ce panneau vous prévient-il ?",
       a:["De la circulation rejoint votre route plus loin","Votre voie se termine immédiatement","Une voie de dépassement commence","Une halte pour camions approche"],
       e:"L'insertion fonctionne quand les deux côtés s'ajustent. Faites de la place si vous le pouvez et adaptez votre vitesse à celle de la circulation." },
  c:0 },
{ id:"sks27", sec:"signs", sign:"warn-roundabout",
  en:{ q:"How do you drive a roundabout?",
       a:["Yield to traffic already in the circle, then enter and keep right around","Stop fully before entering","Traffic entering has the right of way","Drive around it the other way"],
       e:"Signal your exit, not your entry, and never stop inside the circle." },
  fr:{ q:"Comment aborder un carrefour giratoire ?",
       a:["Céder le passage à la circulation déjà engagée, puis entrer en tournant à droite","Arrêter complètement avant d'entrer","Les véhicules qui entrent ont priorité","En faire le tour dans l'autre sens"],
       e:"Signalez votre sortie, pas votre entrée, et n'arrêtez jamais à l'intérieur du giratoire." },
  c:0 },
{ id:"sks28", sec:"signs", sign:"warn-farm-machinery",
  en:{ q:"What should you expect on this road?",
       a:["Slow farm equipment that may be wider than a lane","A farmers market","Livestock on the road","A weigh station"],
       e:"A combine at 25 km/h closes on you fast at highway speed. Wait for a long clear stretch before passing, and expect it to be wider than it looks." },
  fr:{ q:"À quoi vous attendre sur cette route ?",
       a:["De la machinerie agricole lente, parfois plus large qu'une voie","Un marché de producteurs","Du bétail sur la route","Une station de pesage"],
       e:"Une moissonneuse à 25 km/h se rapproche vite à vitesse d'autoroute. Attendez une longue ligne droite dégagée avant de dépasser, et attendez-vous à ce qu'elle soit plus large qu'elle n'en a l'air." },
  c:0 },
{ id:"sks29", sec:"signs", sign:"temp-flagger",
  en:{ q:"You see this sign and then a person holding a sign in the road. What must you do?",
       a:["Obey the flagger, even if it contradicts the signs or lights","Ignore them and follow the signs","Sound your horn and continue","Stop only if the road is blocked"],
       e:"A traffic control person's direction overrides everything else on the road. Workers are metres from your bumper." },
  fr:{ q:"Vous voyez ce panneau puis une personne avec une pancarte sur la route. Que devez-vous faire ?",
       a:["Obéir au signaleur, même si cela contredit les panneaux ou les feux","L'ignorer et suivre les panneaux","Klaxonner et continuer","Arrêter seulement si la route est bloquée"],
       e:"Les directives d'un signaleur ont priorité sur tout le reste. Les travailleurs sont à quelques mètres de votre pare-chocs." },
  c:0 },
{ id:"sks30", sec:"signs", sign:"light-flashing-red",
  en:{ q:"What does a flashing red light mean?",
       a:["Treat it exactly like a stop sign","Slow down and continue","The light is broken, so proceed","Stop only if traffic is coming"],
       e:"Come to a complete stop, then go when it is safe." },
  fr:{ q:"Que signifie un feu rouge clignotant ?",
       a:["Le traiter exactement comme un panneau d'arrêt","Ralentir et continuer","Le feu est brisé, donc passer","Arrêter seulement s'il y a de la circulation"],
       e:"Faites un arrêt complet, puis repartez quand c'est sécuritaire." },
  c:0 }
);

/* ---------- rules of the road ---------- */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"skr1", sec:"rules", topic:"licensing",
  en:{ q:"How long must you hold a Class 7 learner licence in Saskatchewan before moving on?",
       a:["Nine months","Three months","One year","Six weeks"],
       e:"The learner stage lasts nine months. Time does not count while your licence is suspended, refused or not renewed." },
  fr:{ q:"Combien de temps devez-vous détenir un permis d'apprenti de classe 7 en Saskatchewan avant de passer à l'étape suivante ?",
       a:["Neuf mois","Trois mois","Un an","Six semaines"],
       e:"L'étape d'apprenti dure neuf mois. Le temps ne compte pas pendant une suspension, un refus ou un non-renouvellement." },
  c:0 },
{ id:"skr2", sec:"rules", topic:"licensing",
  en:{ q:"Where must your supervising driver sit while you drive on a Class 7 licence?",
       a:["In the front passenger seat, at all hours","Anywhere in the vehicle","In the back seat","They do not have to be in the vehicle"],
       e:"Front passenger seat, every trip, day or night. From there they can see what you see and reach the wheel if they must." },
  fr:{ q:"Où doit s'asseoir votre accompagnateur pendant que vous conduisez avec un permis de classe 7 ?",
       a:["Sur le siège avant du passager, à toute heure","N'importe où dans le véhicule","Sur la banquette arrière","Il n'a pas à être dans le véhicule"],
       e:"Sur le siège avant du passager, à chaque trajet, jour ou nuit. De là, il voit ce que vous voyez et peut atteindre le volant au besoin." },
  c:0 },
{ id:"skr3", sec:"rules", topic:"licensing",
  en:{ q:"Who is allowed to be your supervising driver?",
       a:["Someone with a Class 5 or better licence held for at least 365 days in the past three years","Any licensed driver over 18","Any adult in the car","A driving instructor only"],
       e:"The licence must be from Canada or the United States, at least Class 5, and held for 365 days or more within the preceding three years." },
  fr:{ q:"Qui peut être votre accompagnateur ?",
       a:["Une personne titulaire d'un permis de classe 5 ou mieux, détenu au moins 365 jours au cours des trois dernières années","Tout conducteur licencié de plus de 18 ans","N'importe quel adulte dans l'auto","Un moniteur de conduite seulement"],
       e:"Le permis doit venir du Canada ou des États-Unis, être au moins de classe 5, et avoir été détenu 365 jours ou plus au cours des trois années précédentes." },
  c:0 },
{ id:"skr4", sec:"rules", topic:"licensing",
  en:{ q:"What is the minimum age for a Class 7 learner licence in Saskatchewan?",
       a:["16, or 15 with high school driver education","14","17","18"],
       e:"Sixteen normally, and fifteen if you are taking driver education through a high school." },
  fr:{ q:"Quel est l'âge minimal pour un permis d'apprenti de classe 7 en Saskatchewan ?",
       a:["16 ans, ou 15 ans avec un cours de conduite au secondaire","14 ans","17 ans","18 ans"],
       e:"Seize ans normalement, et quinze ans si vous suivez un cours de conduite au secondaire." },
  c:0 },
{ id:"skr5", sec:"rules", topic:"licensing",
  en:{ q:"Between midnight and 5 a.m. on a Class 7 licence, who may be in your vehicle?",
       a:["Your supervising driver and immediate family members","Anyone at all","Nobody but you","Up to three friends"],
       e:"Late at night your passengers must be immediate family, apart from the supervising driver who has to be there anyway." },
  fr:{ q:"Entre minuit et 5 h avec un permis de classe 7, qui peut se trouver dans votre véhicule ?",
       a:["Votre accompagnateur et des membres de la famille immédiate","N'importe qui","Personne d'autre que vous","Jusqu'à trois amis"],
       e:"Tard la nuit, vos passagers doivent être de la famille immédiate, à part l'accompagnateur qui doit de toute façon être présent." },
  c:0 },
{ id:"skr6", sec:"rules", topic:"licensing",
  en:{ q:"How many passengers may ride with you on a Class 7 licence?",
       a:["No more than the number of working seatbelts","As many as will fit","Only one","Six"],
       e:"Every person needs a working seatbelt of their own. That is the limit, whatever the vehicle." },
  fr:{ q:"Combien de passagers peuvent monter avec vous avec un permis de classe 7 ?",
       a:["Pas plus que le nombre de ceintures de sécurité fonctionnelles","Autant qu'il en entre","Un seul","Six"],
       e:"Chaque personne a besoin de sa propre ceinture fonctionnelle. C'est la limite, quel que soit le véhicule." },
  c:0 },
{ id:"skr7", sec:"rules", topic:"licensing",
  en:{ q:"Which is true about cellphones for a new driver in Saskatchewan?",
       a:["You cannot use any cellphone, hand-held or hands-free","Hands-free is allowed","You may use one while stopped at a red light","You may use one on rural roads"],
       e:"New drivers get no phone at all. Hands-free is legal for fully licensed drivers, not for you." },
  fr:{ q:"Qu'est-ce qui est vrai au sujet du cellulaire pour un nouveau conducteur en Saskatchewan ?",
       a:["Vous ne pouvez utiliser aucun cellulaire, ni tenu en main ni mains libres","Le mains libres est permis","Vous pouvez l'utiliser à l'arrêt à un feu rouge","Vous pouvez l'utiliser sur les routes rurales"],
       e:"Les nouveaux conducteurs n'ont droit à aucun téléphone. Le mains libres est légal pour les conducteurs pleinement licenciés, pas pour vous." },
  c:0 },
{ id:"skr8", sec:"rules", topic:"licensing",
  en:{ q:"How much alcohol may a learner or novice driver have in their blood?",
       a:["None at all","Under 0.05","Under 0.08","One drink is allowed"],
       e:"Zero. The rule runs right through the learner and both novice stages." },
  fr:{ q:"Quelle quantité d'alcool un conducteur apprenti ou novice peut-il avoir dans le sang ?",
       a:["Aucune","Moins de 0,05","Moins de 0,08","Un verre est permis"],
       e:"Zéro. La règle s'applique tout au long de l'étape apprenti et des deux étapes novices." },
  c:0 },
{ id:"skr9", sec:"rules", topic:"licensing",
  en:{ q:"After the learner stage, how long do the two novice stages last?",
       a:["Six months for Novice 1, then twelve months for Novice 2","Three months each","Twelve months for each","There are no novice stages"],
       e:"Novice 1 is six months and Novice 2 is twelve, so the whole programme runs about twenty-seven months from your first learner day." },
  fr:{ q:"Après l'étape d'apprenti, combien de temps durent les deux étapes novices ?",
       a:["Six mois pour Novice 1, puis douze mois pour Novice 2","Trois mois chacune","Douze mois chacune","Il n'y a pas d'étapes novices"],
       e:"Novice 1 dure six mois et Novice 2 douze mois : le programme complet s'étend sur environ vingt-sept mois depuis votre premier jour comme apprenti." },
  c:0 },
{ id:"skr10", sec:"rules", topic:"licensing",
  en:{ q:"Can you act as a supervising driver for someone else while you hold a Class 7?",
       a:["No","Yes, if you are over 18","Yes, for a family member","Yes, in daylight"],
       e:"A learner cannot supervise a learner. You also cannot get a commercial licence or a school bus endorsement at this stage." },
  fr:{ q:"Pouvez-vous servir d'accompagnateur pour quelqu'un d'autre avec un permis de classe 7 ?",
       a:["Non","Oui, si vous avez plus de 18 ans","Oui, pour un membre de la famille","Oui, le jour"],
       e:"Un apprenti ne peut pas accompagner un apprenti. Vous ne pouvez pas non plus obtenir un permis commercial ni une autorisation d'autobus scolaire à cette étape." },
  c:0 },
{ id:"skr11", sec:"rules", topic:"licence",
  en:{ q:"The Saskatchewan knowledge test comes in how many parts?",
       a:["Two — a Basic test and a Sign test","One test covering everything","Three parts","Four parts"],
       e:"SGI runs two: the Basic test on driving situations and the rules of the road, and the Sign test on sign identification." },
  fr:{ q:"En combien de parties se divise l'examen théorique en Saskatchewan ?",
       a:["Deux : un examen de base et un examen sur les panneaux","Un seul examen couvrant tout","Trois parties","Quatre parties"],
       e:"SGI en donne deux : l'examen de base sur les situations de conduite et le code de la route, et l'examen sur l'identification des panneaux." },
  c:0 },
{ id:"skr12", sec:"rules", topic:"licence",
  en:{ q:"You pass the Sign test but fail the Basic test. What happens?",
       a:["You rewrite only the part you failed","You rewrite both parts","You wait six months","You must take a driving course"],
       e:"Only the failed part is rewritten. This is why it is worth studying signs and rules separately." },
  fr:{ q:"Vous réussissez l'examen sur les panneaux mais échouez l'examen de base. Que se passe-t-il ?",
       a:["Vous reprenez seulement la partie échouée","Vous reprenez les deux parties","Vous attendez six mois","Vous devez suivre un cours de conduite"],
       e:"Seule la partie échouée est reprise. C'est pourquoi il vaut la peine d'étudier les panneaux et le code séparément." },
  c:0 },
{ id:"skr13", sec:"rules", topic:"licence",
  en:{ q:"How often may you write the knowledge test?",
       a:["Once per day","Twice per day","Once per week","As often as you like"],
       e:"One attempt a day. Use the gap to study the part you missed rather than guessing again." },
  fr:{ q:"À quelle fréquence pouvez-vous passer l'examen théorique ?",
       a:["Une fois par jour","Deux fois par jour","Une fois par semaine","Aussi souvent que vous voulez"],
       e:"Une tentative par jour. Profitez du délai pour étudier la partie manquée plutôt que de deviner de nouveau." },
  c:0 },
{ id:"skr14", sec:"rules", topic:"licence",
  en:{ q:"How long does a passed written exam result stay valid?",
       a:["One year","Thirty days","Three months","Forever"],
       e:"A successful result is good for one year, so do not let too long pass before the next step." },
  fr:{ q:"Combien de temps un résultat d'examen écrit réussi reste-t-il valide ?",
       a:["Un an","Trente jours","Trois mois","Pour toujours"],
       e:"Un résultat réussi est valide un an : ne laissez pas trop de temps passer avant l'étape suivante." },
  c:0 },
{ id:"skr15", sec:"rules", topic:"licence",
  en:{ q:"You do not understand what a test question is asking. What can you do?",
       a:["Ask the examiner to explain what the question means","Skip it and come back later only","Use your phone to look it up","Guess, and nothing else"],
       e:"You may ask the examiner about the meaning of a question. You may not use a phone or any electronic device in the test area." },
  fr:{ q:"Vous ne comprenez pas ce qu'une question demande. Que pouvez-vous faire ?",
       a:["Demander à l'examinateur d'expliquer le sens de la question","Seulement la sauter et y revenir","Utiliser votre téléphone pour chercher","Deviner, et rien d'autre"],
       e:"Vous pouvez demander à l'examinateur le sens d'une question. Vous ne pouvez pas utiliser de téléphone ni d'appareil électronique dans la salle d'examen." },
  c:0 },
{ id:"skr16", sec:"rules", topic:"sharing",
  en:{ q:"An emergency vehicle or tow truck is stopped ahead with its lights flashing. What speed must you pass at?",
       a:["60 km/h","The posted limit","80 km/h","30 km/h"],
       e:"Slow to 60 km/h to pass. On an undivided highway this applies from both directions; on a divided highway it does not apply to traffic going the other way." },
  fr:{ q:"Un véhicule d'urgence ou une dépanneuse est arrêté devant, gyrophares allumés. À quelle vitesse devez-vous passer ?",
       a:["60 km/h","La limite affichée","80 km/h","30 km/h"],
       e:"Ralentissez à 60 km/h pour passer. Sur une route non divisée, cela vaut dans les deux sens ; sur une route divisée, cela ne vise pas la circulation en sens inverse." },
  c:0 },
{ id:"skr17", sec:"rules", topic:"sharing",
  en:{ q:"An emergency vehicle is coming toward you with lights and siren. What do you do?",
       a:["Pull as close as possible to the right edge of the road and stop","Speed up to clear the way","Stop where you are in the lane","Turn left out of the way"],
       e:"Right edge, stop, and do not enter the next intersection until it has gone by." },
  fr:{ q:"Un véhicule d'urgence vient vers vous, gyrophares et sirène en marche. Que faites-vous ?",
       a:["Vous serrer le plus possible à droite et arrêter","Accélérer pour dégager","Arrêter en pleine voie","Tourner à gauche pour vous écarter"],
       e:"Serrez à droite, arrêtez, et n'entrez pas dans la prochaine intersection avant son passage." },
  c:0 },
{ id:"skr18", sec:"rules", topic:"sharing",
  en:{ q:"How far from a school bus with flashing red lights must you stop?",
       a:["No closer than 5 metres","No closer than 20 metres","Right behind it","There is no set distance"],
       e:"Five metres, about fifteen feet, from the front or the back. Wait for the lights to stop and the stop arm to fold in." },
  fr:{ q:"À quelle distance d'un autobus scolaire aux feux rouges clignotants devez-vous arrêter ?",
       a:["À au moins 5 mètres","À au moins 20 mètres","Juste derrière lui","Il n'y a pas de distance fixée"],
       e:"Cinq mètres, environ quinze pieds, de l'avant ou de l'arrière. Attendez que les feux cessent et que le bras d'arrêt se referme." },
  c:0 },
{ id:"skr19", sec:"rules", topic:"sharing",
  en:{ q:"On a divided highway, when must you stop for a school bus with flashing red lights?",
       a:["Only when you are approaching it from behind","From both directions always","Never on a divided highway","Only if children are crossing"],
       e:"A median between you and the bus means only traffic behind it has to stop. On an undivided road, both directions stop." },
  fr:{ q:"Sur une route divisée, quand devez-vous arrêter pour un autobus scolaire aux feux rouges clignotants ?",
       a:["Seulement si vous l'approchez par l'arrière","Toujours dans les deux sens","Jamais sur une route divisée","Seulement si des enfants traversent"],
       e:"Un terre-plein entre vous et l'autobus signifie que seule la circulation derrière lui doit arrêter. Sur une route non divisée, les deux sens arrêtent." },
  c:0 },
{ id:"skr20", sec:"rules", topic:"sharing",
  en:{ q:"How should you pass a cyclist?",
       a:["Like any other vehicle, giving them plenty of room","As close as you can to save time","By sounding your horn first","Only on the right"],
       e:"Treat a cyclist as traffic. Wait for room, then leave a wide gap — wind from a passing vehicle can push a bike sideways." },
  fr:{ q:"Comment devez-vous dépasser un cycliste ?",
       a:["Comme tout autre véhicule, en lui laissant beaucoup d'espace","Le plus près possible pour gagner du temps","En klaxonnant d'abord","Seulement par la droite"],
       e:"Traitez le cycliste comme un usager de la route. Attendez d'avoir de la place, puis laissez un large écart : le souffle d'un véhicule qui passe peut déporter un vélo." },
  c:0 },
{ id:"skr21", sec:"rules", topic:"conditions",
  en:{ q:"Snow is blowing across the highway and you cannot see far. What is the safest thing to do?",
       a:["Slow down, increase your following distance, and pull well off the road if it gets worse","Turn on your high beams and keep your speed","Stop in the driving lane","Follow the tail lights ahead closely"],
       e:"Following someone's tail lights in blowing snow is how chain collisions start. If you must stop, get right off the road and put your hazards on." },
  fr:{ q:"La poudrerie traverse la route et vous ne voyez pas loin. Quelle est la chose la plus sécuritaire à faire ?",
       a:["Ralentir, augmenter votre distance et vous ranger loin de la route si ça empire","Allumer vos feux de route et garder votre vitesse","Arrêter dans la voie de circulation","Suivre de près les feux arrière devant vous"],
       e:"Suivre les feux arrière d'un autre par poudrerie, c'est ainsi que commencent les carambolages. S'il faut arrêter, quittez complètement la route et allumez vos feux de détresse." },
  c:0 },
{ id:"skr22", sec:"rules", topic:"conditions",
  en:{ q:"Why are high beams a bad idea in falling snow or fog?",
       a:["The light bounces back off the snow or fog and blinds you","They use too much power","They are illegal in winter","They melt the snow"],
       e:"Bright light reflects off the particles in the air and reduces what you can see. Low beams do better." },
  fr:{ q:"Pourquoi les feux de route sont-ils une mauvaise idée sous la neige ou dans le brouillard ?",
       a:["La lumière est renvoyée par la neige ou le brouillard et vous aveugle","Ils consomment trop","Ils sont interdits en hiver","Ils font fondre la neige"],
       e:"La lumière vive se reflète sur les particules en suspension et réduit ce que vous voyez. Les feux de croisement font mieux." },
  c:0 },
{ id:"skr23", sec:"rules", topic:"conditions",
  en:{ q:"What is black ice and where does it form first?",
       a:["A thin clear layer of ice, forming first on bridges and shaded spots","Ice mixed with gravel, on hills","Ice only found in parking lots","Snow packed down by traffic"],
       e:"Bridges and overpasses freeze first because cold air passes underneath them as well as over." },
  fr:{ q:"Qu'est-ce que la glace noire et où se forme-t-elle en premier ?",
       a:["Une fine couche de glace transparente, d'abord sur les ponts et les endroits ombragés","De la glace mêlée de gravier, dans les côtes","De la glace seulement dans les stationnements","De la neige tassée par la circulation"],
       e:"Les ponts et les viaducs gèlent en premier parce que l'air froid passe aussi en dessous." },
  c:0 },
{ id:"skr24", sec:"rules", topic:"conditions",
  en:{ q:"Your back wheels start to slide out on an icy corner. What do you do?",
       a:["Ease off the accelerator and steer where you want to go","Brake hard","Steer the opposite way","Pull the parking brake"],
       e:"Look and steer where you want the car to end up. Hard braking mid-skid takes away what little grip you have left." },
  fr:{ q:"Vos roues arrière commencent à glisser dans une courbe glacée. Que faites-vous ?",
       a:["Relâcher l'accélérateur et diriger vers où vous voulez aller","Freiner fort","Braquer dans l'autre sens","Tirer le frein de stationnement"],
       e:"Regardez et dirigez là où vous voulez que l'auto aille. Freiner brusquement en plein dérapage enlève le peu d'adhérence qui reste." },
  c:0 },
{ id:"skr25", sec:"rules", topic:"conditions",
  en:{ q:"On a gravel grid road, what changes about the way you drive?",
       a:["Stopping takes longer and dust can hide oncoming traffic","Nothing changes","You can drive faster because there is no traffic","Signals are not needed"],
       e:"Loose gravel lengthens every stop, and a dust cloud from another vehicle can hide a whole truck. Slow down at every uncontrolled crossroad." },
  fr:{ q:"Sur une route de gravier en quadrillé, qu'est-ce qui change dans votre conduite ?",
       a:["Les distances d'arrêt s'allongent et la poussière peut cacher un véhicule qui arrive","Rien ne change","Vous pouvez rouler plus vite car il n'y a pas de circulation","Les clignotants sont inutiles"],
       e:"Le gravier meuble allonge chaque arrêt, et un nuage de poussière soulevé par un autre véhicule peut cacher un camion entier. Ralentissez à chaque croisement sans priorité." },
  c:0 },
{ id:"skr26", sec:"rules", topic:"safe",
  en:{ q:"What is a safe following distance in good conditions, and what about on ice?",
       a:["At least two seconds in good conditions, and far more on ice","One car length at any speed","Two seconds always, whatever the surface","Half a second"],
       e:"Two seconds is the dry-road minimum. On snow or ice you may need three or four times that, because stopping distance can grow tenfold." },
  fr:{ q:"Quelle est une distance de suivi sécuritaire par beau temps, et sur la glace ?",
       a:["Au moins deux secondes par beau temps, et beaucoup plus sur la glace","Une longueur d'auto à toute vitesse","Deux secondes toujours, quelle que soit la surface","Une demi-seconde"],
       e:"Deux secondes est le minimum sur route sèche. Sur neige ou glace, il en faut trois ou quatre fois plus, car la distance d'arrêt peut être décuplée." },
  c:0 },
{ id:"skr27", sec:"rules", topic:"safe",
  en:{ q:"Who is responsible for making sure everyone in the vehicle is buckled up?",
       a:["The driver is responsible for passengers under 16","Each passenger only","Nobody, it is a personal choice","The front seat passenger"],
       e:"You are responsible for younger passengers, and everyone needs their own working belt." },
  fr:{ q:"Qui doit s'assurer que tout le monde est bien attaché dans le véhicule ?",
       a:["Le conducteur est responsable des passagers de moins de 16 ans","Chaque passager seulement","Personne, c'est un choix personnel","Le passager avant"],
       e:"Vous êtes responsable des passagers plus jeunes, et chacun a besoin de sa propre ceinture fonctionnelle." },
  c:0 },
{ id:"skr28", sec:"rules", topic:"safe",
  en:{ q:"You are tired on a long drive across the prairies. What actually works?",
       a:["Stop and rest or swap drivers","Open the window and turn up the radio","Drink coffee and keep going","Drive faster to arrive sooner"],
       e:"Only sleep fixes tiredness. Long straight roads and an unchanging horizon make drowsiness worse, not better." },
  fr:{ q:"Vous êtes fatigué sur un long trajet dans les Prairies. Qu'est-ce qui fonctionne vraiment ?",
       a:["Arrêter et vous reposer, ou changer de conducteur","Ouvrir la fenêtre et monter la radio","Boire un café et continuer","Rouler plus vite pour arriver plus tôt"],
       e:"Seul le sommeil corrige la fatigue. Les longues routes droites et un horizon immuable aggravent la somnolence." },
  c:0 },
{ id:"skr29", sec:"rules", topic:"vehicle",
  en:{ q:"Why clear snow from the whole vehicle and not just a patch of windshield?",
       a:["Snow blows off onto the driver behind and blocks your own view","It is only about appearance","It saves fuel","It is not required in Saskatchewan"],
       e:"A slab of snow off a roof can blind the car behind you completely. Clear the roof, lights, mirrors and all the glass." },
  fr:{ q:"Pourquoi déneiger tout le véhicule et pas seulement un coin du pare-brise ?",
       a:["La neige s'envole sur le conducteur derrière et bloque votre propre vue","C'est seulement une question d'apparence","Cela économise du carburant","Ce n'est pas exigé en Saskatchewan"],
       e:"Une plaque de neige partie du toit peut aveugler complètement l'auto derrière. Dégagez le toit, les feux, les rétroviseurs et toutes les vitres." },
  c:0 },
{ id:"skr30", sec:"rules", topic:"collisions",
  en:{ q:"You are in a collision with injuries. What is the first thing to do?",
       a:["Call for help and do not move injured people unless they are in danger","Move all vehicles off the road first","Leave to find a phone","Take photographs first"],
       e:"Get help coming, warn other traffic, and leave injured people where they are unless there is fire or another immediate danger." },
  fr:{ q:"Vous êtes impliqué dans une collision avec des blessés. Quelle est la première chose à faire ?",
       a:["Appeler à l'aide et ne pas déplacer les blessés sauf s'ils sont en danger","Dégager d'abord tous les véhicules de la route","Partir chercher un téléphone","Prendre des photos d'abord"],
       e:"Faites venir les secours, avertissez la circulation, et laissez les blessés où ils sont sauf en cas d'incendie ou d'autre danger immédiat." },
  c:0 }
);


/* ---------------------------------------------------------------------------
   The test format, as SGI publishes it — and honestly where it does not.
   SGI states that the knowledge test comes in two parts, Basic and Sign, that
   they are marked separately, and that you rewrite only the part you fail.
   It does NOT publish a question count, a pass mark or a time limit, so the
   30 questions in 30 minutes below are OUR clearly-stated practice standard
   and the pages say so in as many words.
   --------------------------------------------------------------------------- */
window.CQ_PROVINCE = {
  code: "SK",
  name: { en: "Saskatchewan", fr: "Saskatchewan" },
  licence: "Class 7",
  minutes: 30,
  sections: [
    { id: "signs", ask: 15, pass: 12,
      name: { en: "Sign Test", fr: "Examen sur les panneaux" } },
    { id: "rules", ask: 15, pass: 12,
      name: { en: "Basic Test — Rules and Driving Situations",
              fr: "Examen de base — code et situations de conduite" } }
  ],
  handbook: { en: "Saskatchewan Driver's Handbook (SGI)",
              fr: "Guide du conducteur de la Saskatchewan (SGI)" },
  handbookUrl: "https://sgi.sk.ca/handbook",
  bookingUrl: "https://sgi.sk.ca/licensing",
  topics: [
    { id:"licensing",  en:"Graduated Licensing",          fr:"Permis par étapes" },
    { id:"licence",    en:"Your Licence and the Test",     fr:"Votre permis et l'examen" },
    { id:"sharing",    en:"Sharing the Road",              fr:"Partager la route" },
    { id:"conditions", en:"Winter and Rural Driving",      fr:"Conduite hivernale et rurale" },
    { id:"safe",       en:"Safe and Responsible Driving",  fr:"Conduite sécuritaire et responsable" },
    { id:"vehicle",    en:"Your Vehicle",                  fr:"Votre véhicule" },
    { id:"collisions", en:"Emergencies and Collisions",    fr:"Urgences et collisions" }
  ],
  questions: window.CQ_DRIVE_Q
};
