/* canada-quiz.com — YUKON Class 7 Learner practice data
   60 original bilingual questions (30 road signs + 30 rules of the road).
   Written in our own words from the free Yukon Driver's Basic Handbook, the
   driver licensing and road safety pages on yukon.ca, and the Motor Vehicles
   Regulations published at laws.yukon.ca.
   Not affiliated with Yukon Motor Vehicles or the Government of Yukon.

   The quiz code lives in js/driving-engine.js and never changes per province. */
window.CQ_DRIVE_Q = [];

/* ---------- road signs ---------- */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"yts1", sec:"signs", sign:"stop",
  en:{ q:"You reach this sign at a Yukon intersection. What does it require?",
       a:["A complete stop, then go on only when the way is clear","A rolling stop if nothing is coming","Stopping only when a pedestrian is waiting","Flashing your headlights and carrying on"],
       e:"A stop means the wheels stop turning. Stop at the stop line, or before the crosswalk if none is painted, and move off only when you can do it without forcing anyone else to slow down." },
  fr:{ q:"Vous arrivez à ce panneau à une intersection du Yukon. Qu'exige-t-il ?",
       a:["Un arrêt complet, puis repartir seulement quand la voie est libre","Un arrêt roulant si personne ne vient","Vous arrêter seulement si un piéton attend","Faire un appel de phares et continuer"],
       e:"Un arrêt signifie que les roues cessent de tourner. Arrêtez-vous à la ligne d'arrêt, ou avant le passage pour piétons s'il n'y en a pas, et repartez seulement si personne n'est forcé de ralentir." },
  c:0 },
{ id:"yts2", sec:"signs", sign:"yield",
  en:{ q:"What does this red and white triangle require of you?",
       a:["Stop and stay stopped until someone waves you on","Give way to the traffic and pedestrians already using the road","Speed up so you fit into the gap","Turn right without checking"],
       e:"Yield means give way. Slow right down, be ready to stop, and join only when you will not make another driver or a pedestrian change what they are doing." },
  fr:{ q:"Qu'exige de vous ce triangle rouge et blanc ?",
       a:["Vous arrêter et attendre que quelqu'un vous fasse signe","Céder le passage à la circulation et aux piétons déjà sur la chaussée","Accélérer pour vous glisser dans l'espace libre","Tourner à droite sans vérifier"],
       e:"Céder le passage veut dire laisser passer. Ralentissez beaucoup, soyez prêt à vous arrêter et engagez-vous seulement si aucun conducteur ni piéton ne doit modifier sa trajectoire." },
  c:1 },
{ id:"yts3", sec:"signs", sign:"no-entry",
  en:{ q:"This sign faces you at the mouth of a street. What does it mean?",
       a:["Local traffic only","Entry allowed outside busy hours","You must not enter, because traffic here comes towards you","Heavy vehicles must find another route"],
       e:"The street runs the other way. Driving past this sign puts you head-on into traffic that has no reason to expect you." },
  fr:{ q:"Ce panneau vous fait face à l'entrée d'une rue. Que signifie-t-il ?",
       a:["Circulation locale seulement","Entrée permise en dehors des heures de pointe","Vous ne devez pas entrer, car la circulation vient vers vous","Les véhicules lourds doivent emprunter un autre chemin"],
       e:"La rue circule en sens inverse. Franchir ce panneau vous place face à des véhicules qui n'ont aucune raison de vous attendre." },
  c:2 },
{ id:"yts4", sec:"signs", sign:"speed-50",
  en:{ q:"A sign like this is posted beside a Yukon road. What does the number mean?",
       a:["A speed suggested only for good weather","The slowest speed you may legally travel","An average speed to hold over the whole trip","The highest speed allowed, and only when conditions are good"],
       e:"A posted limit is a ceiling, never a target. Yukon states that speed limits are set for optimal road conditions, so on gravel, frost heaves, ice or poor visibility the safe speed is lower than the number on the sign." },
  fr:{ q:"Un panneau comme celui-ci est installé le long d'une route du Yukon. Que signifie le chiffre ?",
       a:["Une vitesse suggérée par beau temps seulement","La vitesse la plus basse permise par la loi","Une vitesse moyenne à maintenir pendant tout le trajet","La vitesse maximale permise, et seulement si les conditions sont bonnes"],
       e:"Une limite affichée est un plafond, jamais un objectif. Le Yukon précise que les limites de vitesse sont fixées pour des conditions routières optimales : sur le gravier, les bosses de gel, la glace ou par mauvaise visibilité, la vitesse sécuritaire est plus basse que le chiffre affiché." },
  c:3 },
{ id:"yts5", sec:"signs", sign:"no-passing",
  en:{ q:"What does this regulatory sign prohibit?",
       a:["Stopping on the shoulder","Passing another vehicle along this stretch","Parking overnight","Towing a trailer"],
       e:"Passing is banned here, normally because you cannot see far enough ahead to pull back in safely. On a northern highway that view can also be blocked by dust or blowing snow." },
  fr:{ q:"Qu'interdit ce panneau de prescription ?",
       a:["S'arrêter sur l'accotement","Dépasser un autre véhicule sur ce tronçon","Stationner pour la nuit","Tirer une remorque"],
       e:"Le dépassement est interdit ici, normalement parce que vous ne voyez pas assez loin devant pour vous rabattre en sécurité. Sur une route nordique, la poussière ou la neige soufflée peuvent aussi masquer la vue." },
  c:1 },
{ id:"yts6", sec:"signs", sign:"no-parking",
  en:{ q:"Where this sign is posted, what are you still allowed to do?",
       a:["Leave the vehicle for a few minutes","Park if you switch on your hazard lights","Stop briefly while somebody gets in or out","Nothing at all is permitted here"],
       e:"No parking still lets you pause while a passenger gets in or out. It is the sign that bans stopping altogether that takes even that away." },
  fr:{ q:"Là où ce panneau est affiché, que pouvez-vous encore faire ?",
       a:["Laisser le véhicule quelques minutes","Stationner si vous allumez vos feux de détresse","Vous arrêter brièvement pendant que quelqu'un monte ou descend","Rien n'est permis à cet endroit"],
       e:"Le stationnement interdit permet encore une courte pause pendant qu'un passager monte ou descend. C'est le panneau d'arrêt interdit qui enlève même cette possibilité." },
  c:2 },
{ id:"yts7", sec:"signs", sign:"no-stopping",
  en:{ q:"This sign goes further than a no-parking sign. In what way?",
       a:["It applies only during the winter months","It applies only to trucks","It bans parking but still allows loading","It bans stopping for any reason, even to let someone out"],
       e:"This is the strictest of the stopping signs. You may not halt here at all, so plan to drop a passenger somewhere else." },
  fr:{ q:"Ce panneau va plus loin que celui du stationnement interdit. De quelle façon ?",
       a:["Il s'applique seulement pendant les mois d'hiver","Il s'applique seulement aux camions","Il interdit de stationner mais permet encore le chargement","Il interdit de vous arrêter pour quelque raison que ce soit, même pour laisser descendre quelqu'un"],
       e:"C'est le plus strict des panneaux d'immobilisation. Vous ne pouvez pas vous arrêter du tout ici : prévoyez un autre endroit pour laisser descendre un passager." },
  c:3 },
{ id:"yts8", sec:"signs", sign:"keep-right",
  en:{ q:"A traffic island lies ahead with this sign on it. What must you do?",
       a:["Pass to the right of the island","Pass on whichever side is clear","Stop before the island and wait","Reverse and find another route"],
       e:"Keep right of the island. The sign is placed where the road splits around something, and your half of the road is the right-hand half." },
  fr:{ q:"Un îlot se trouve devant vous et porte ce panneau. Que devez-vous faire ?",
       a:["Passer à droite de l'îlot","Passer du côté qui est libre","Vous arrêter avant l'îlot et attendre","Reculer et prendre un autre chemin"],
       e:"Tenez la droite de l'îlot. Ce panneau est placé là où la chaussée se sépare autour d'un obstacle, et votre moitié de la route est celle de droite." },
  c:0 },
{ id:"yts9", sec:"signs", sign:"no-u-turn",
  en:{ q:"Which manoeuvre does this sign forbid?",
       a:["Turning left at the next street","Reversing into a driveway","Turning around to head back the way you came","Passing a slower vehicle"],
       e:"No U-turn. Turning right around is banned here because oncoming drivers cannot see what you are doing early enough to react." },
  fr:{ q:"Quelle manoeuvre ce panneau interdit-il ?",
       a:["Tourner à gauche à la rue suivante","Reculer dans une entrée","Faire demi-tour pour repartir d'où vous venez","Dépasser un véhicule plus lent"],
       e:"Demi-tour interdit. La manoeuvre est défendue ici parce que les conducteurs venant en sens inverse ne voient pas assez tôt ce que vous faites." },
  c:2 },
{ id:"yts10", sec:"signs", sign:"warn-deer",
  en:{ q:"This yellow diamond stands beside a Yukon highway. What is it telling you?",
       a:["Hunting is permitted beside the road","A wildlife viewing area is ahead","Livestock may be loose on the road","Deer may be on or near the road ahead"],
       e:"The handbook uses this sign to mean watch for deer ahead. Ease off, keep scanning both shoulders and be ready for an animal to step out where you cannot see far." },
  fr:{ q:"Ce losange jaune est planté le long d'une route du Yukon. Que vous indique-t-il ?",
       a:["La chasse est permise en bordure de la route","Une aire d'observation de la faune se trouve devant","Du bétail peut être en liberté sur la chaussée","Des cerfs peuvent se trouver sur la route ou tout près"],
       e:"Le guide utilise ce panneau pour dire de surveiller les cerfs devant vous. Levez le pied, balayez les deux accotements du regard et attendez-vous à voir surgir un animal là où la vue est courte." },
  c:3 },
{ id:"yts11", sec:"signs", sign:"warn-fallen-rock",
  en:{ q:"What hazard does this warning sign describe?",
       a:["Rock may fall onto the road, and rock may already be lying on it","A quarry entrance is ahead","Loose gravel has just been spread on the surface","A rock crusher is working nearby"],
       e:"The handbook wording is to beware of falling rock and to watch for rock already on the road ahead. Keep your eyes well down the road rather than on the cliff face." },
  fr:{ q:"Quel danger ce panneau d'avertissement décrit-il ?",
       a:["Des pierres peuvent tomber sur la route, et il peut déjà y en avoir dessus","L'entrée d'une carrière se trouve devant","Du gravier meuble vient d'être épandu sur la chaussée","Un concasseur fonctionne à proximité"],
       e:"Le guide parle de se méfier des chutes de pierres et de surveiller les pierres déjà présentes sur la chaussée. Gardez le regard loin devant plutôt que sur la paroi rocheuse." },
  c:0 },
{ id:"yts12", sec:"signs", sign:"warn-pavement-ends",
  en:{ q:"You meet this sign on a northern highway. What is ahead?",
       a:["A bridge deck","The paved surface ends and the road turns to gravel","A closed section of road","A weigh station"],
       e:"Gravel gives less grip than pavement, and Yukon warns that stopping distances get longer on it. Slow down before the surface changes and leave far more room to the vehicle ahead." },
  fr:{ q:"Vous croisez ce panneau sur une route nordique. Qu'y a-t-il devant ?",
       a:["Un tablier de pont","La fin du revêtement : la route devient une route de gravier","Un tronçon de route fermé","Une station de pesée"],
       e:"Le gravier offre moins d'adhérence que l'asphalte, et le Yukon prévient que les distances de freinage y sont plus longues. Ralentissez avant le changement de surface et laissez beaucoup plus d'espace devant vous." },
  c:1 },
{ id:"yts13", sec:"signs", sign:"warn-bump",
  en:{ q:"What is this warning sign telling you about the road surface?",
       a:["A speed hump has been built to slow traffic","A cattle guard crosses the road","Road work is under way","The surface is uneven, so slow down before you reach it"],
       e:"Yukon roads built over permafrost can settle into waves and dips that the territory describes as feeling like a roller coaster. Take your speed off before the rough part, not in the middle of it." },
  fr:{ q:"Que vous apprend ce panneau d'avertissement sur l'état de la chaussée ?",
       a:["Un dos d'âne a été aménagé pour ralentir la circulation","Une grille à bestiaux traverse la route","Des travaux routiers sont en cours","La chaussée est inégale : ralentissez avant d'y arriver"],
       e:"Les routes du Yukon construites sur le pergélisol peuvent s'affaisser en vagues et en creux que le territoire compare à des montagnes russes. Réduisez votre vitesse avant la section cahoteuse, pas au milieu de celle-ci." },
  c:3 },
{ id:"yts14", sec:"signs", sign:"warn-slippery",
  en:{ q:"What is this yellow diamond warning you to expect?",
       a:["The road can turn slippery, so brake and steer gently","A car wash entrance","A river crossing","A section closed each winter"],
       e:"Grip can disappear without warning on a wet or icy surface. Smooth inputs keep the tires working; sudden braking or steering is what breaks them loose." },
  fr:{ q:"À quoi ce losange jaune vous prépare-t-il ?",
       a:["La chaussée peut devenir glissante : freinez et braquez en douceur","L'entrée d'un lave-auto","La traversée d'une rivière","Un tronçon fermé chaque hiver"],
       e:"L'adhérence peut disparaître sans prévenir sur une chaussée mouillée ou glacée. Des gestes doux gardent les pneus en prise ; ce sont les coups de frein ou de volant qui les font décrocher." },
  c:0 },
{ id:"yts15", sec:"signs", sign:"warn-steep-hill",
  en:{ q:"You meet this sign at the top of a long grade. What is the safe way down?",
       a:["Coast down in neutral to save fuel","Pick a lower gear before the descent and hold your speed down","Speed up so you do not lose momentum","Run your hazard lights the whole way down"],
       e:"A lower gear lets the engine do part of the braking. Riding the brakes the whole way down heats them until they stop working well, which matters most with a loaded vehicle." },
  fr:{ q:"Vous rencontrez ce panneau en haut d'une longue pente. Quelle est la façon sûre de descendre ?",
       a:["Descendre au point mort pour économiser du carburant","Choisir un rapport inférieur avant la descente et contenir votre vitesse","Accélérer pour ne pas perdre votre élan","Garder les feux de détresse allumés jusqu'en bas"],
       e:"Un rapport inférieur laisse le moteur freiner en partie. Rester sur la pédale de frein toute la descente les fait chauffer jusqu'à perdre leur efficacité, surtout avec un véhicule chargé." },
  c:1 },
{ id:"yts16", sec:"signs", sign:"warn-winding",
  en:{ q:"What does this yellow sign say about the road in front of you?",
       a:["The road ends shortly","There is one sharp bend and then it straightens","There is a series of bends, so lose speed before the first one","The road narrows to a single lane"],
       e:"Braking is for the straight before the bend, not for the bend itself. Set your speed early, then steer smoothly through each curve." },
  fr:{ q:"Que dit ce panneau jaune au sujet de la route qui vous attend ?",
       a:["La route se termine bientôt","Il y a un seul virage serré, puis la route redevient droite","Il y a une suite de virages : ralentissez avant le premier","La route se réduit à une seule voie"],
       e:"On freine dans la ligne droite avant le virage, pas dans le virage. Réglez votre vitesse tôt, puis braquez souplement dans chaque courbe." },
  c:2 },
{ id:"yts17", sec:"signs", sign:"warn-railway",
  en:{ q:"This round yellow sign appears beside the road. What is coming up?",
       a:["A railway crossing","A roundabout","A rest area","A tunnel entrance"],
       e:"A railway crossing is coming. Slow down, look and listen both ways, and never start across unless you can clear the far side without stopping." },
  fr:{ q:"Ce panneau jaune rond apparaît au bord de la route. Qu'est-ce qui approche ?",
       a:["Un passage à niveau","Un carrefour giratoire","Une halte routière","L'entrée d'un tunnel"],
       e:"Un passage à niveau approche. Ralentissez, regardez et écoutez des deux côtés, et ne vous engagez jamais si vous ne pouvez pas dégager complètement l'autre côté sans vous arrêter." },
  c:0 },
{ id:"yts18", sec:"signs", sign:"warn-school-zone",
  en:{ q:"This sign marks the start of what?",
       a:["A bus terminal","A playground with no road beside it","A school zone, where you must drop to 30 km/h","A crossing used only in summer"],
       e:"Yukon asks drivers to reduce speed to 30 kilometres an hour in school zones. Children step out from between parked cars, and 30 is the speed that leaves you time to stop." },
  fr:{ q:"Ce panneau marque le début de quoi ?",
       a:["Un terminus d'autobus","Un terrain de jeu sans route à côté","Une zone scolaire, où vous devez ralentir à 30 km/h","Un passage utilisé seulement l'été"],
       e:"Le Yukon demande aux conducteurs de réduire leur vitesse à 30 kilomètres à l'heure dans les zones scolaires. Les enfants surgissent entre les voitures stationnées, et 30 est la vitesse qui vous laisse le temps d'arrêter." },
  c:2 },
{ id:"yts19", sec:"signs", sign:"warn-narrow-bridge",
  en:{ q:"What does this diamond warn you about?",
       a:["A bridge closed to all traffic","A bridge narrower than the road you are on","A ferry landing","A culvert with a weight restriction"],
       e:"The bridge is tighter than the road leading to it. Check for oncoming traffic, hold your lane position and never try to pass on the structure." },
  fr:{ q:"De quoi ce losange vous avertit-il ?",
       a:["Un pont fermé à toute circulation","Un pont plus étroit que la route où vous roulez","Un débarcadère de traversier","Un ponceau avec limite de poids"],
       e:"Le pont est plus étroit que la route qui y mène. Vérifiez la circulation en sens inverse, gardez bien votre voie et n'essayez jamais de dépasser sur l'ouvrage." },
  c:1 },
{ id:"yts20", sec:"signs", sign:"temp-construction",
  en:{ q:"An orange diamond like this stands beside the highway. What does the orange colour mean?",
       a:["The warning is permanent","The sign applies only after dark","The sign marks a scenic route","The conditions are temporary, such as road work ahead"],
       e:"Orange means temporary. Work zones on northern highways often involve loose gravel and equipment crossing the road, so the posted work-zone speed applies whether or not you can see a crew." },
  fr:{ q:"Un losange orange comme celui-ci se dresse au bord de la route. Que signifie la couleur orange ?",
       a:["L'avertissement est permanent","Le panneau ne s'applique qu'à la nuit tombée","Le panneau indique une route panoramique","Les conditions sont temporaires, par exemple des travaux devant"],
       e:"L'orange signifie temporaire. Les zones de travaux sur les routes nordiques comportent souvent du gravier meuble et de la machinerie qui traverse la chaussée : la vitesse affichée s'applique même si vous ne voyez aucun ouvrier." },
  c:3 },
{ id:"yts21", sec:"signs", sign:"temp-flagger",
  en:{ q:"What does this orange sign tell you to expect?",
       a:["A police checkpoint","A weigh scale","A traffic control person directing traffic ahead","A closed rest area"],
       e:"Someone will be controlling traffic through the work zone. Slow right down, be ready to stop, and do exactly what they signal, even when the road ahead looks empty." },
  fr:{ q:"À quoi ce panneau orange vous dit-il de vous attendre ?",
       a:["Un contrôle policier","Une balance de pesée","Un signaleur qui dirige la circulation devant","Une halte routière fermée"],
       e:"Quelqu'un dirigera la circulation dans la zone de travaux. Ralentissez beaucoup, soyez prêt à vous arrêter et faites exactement ce qu'on vous indique, même si la route semble déserte." },
  c:2 },
{ id:"yts22", sec:"signs", sign:"temp-detour",
  en:{ q:"What is this orange sign asking you to do?",
       a:["Follow the marked route around a closed piece of road","Stop and turn back the way you came","Use the shoulder to get past the work","Report to the work crew before continuing"],
       e:"A detour sends you along a signed alternative. Keep following the detour markers rather than guessing a shortcut, because the side roads may be gravel or dead ends." },
  fr:{ q:"Ce panneau orange apparaît devant une route fermée. Que vous demande-t-il ?",
       a:["Suivre l'itinéraire indiqué pour contourner un tronçon fermé","Vous arrêter et rebrousser chemin","Emprunter l'accotement pour dépasser les travaux","Vous présenter à l'équipe de travaux avant de continuer"],
       e:"Un détour vous dirige sur un parcours balisé. Continuez de suivre les marqueurs plutôt que d'inventer un raccourci : les chemins secondaires peuvent être en gravier ou sans issue." },
  c:0 },
{ id:"yts23", sec:"signs", sign:"info-hospital",
  en:{ q:"What service does this blue sign point you to?",
       a:["A pharmacy","A first-aid post at a rest stop","A veterinary clinic","A hospital"],
       e:"Blue signs point to services rather than telling you a rule. Knowing where the hospital sign is on your route matters more in a territory where the next community can be far away." },
  fr:{ q:"Vers quel service ce panneau bleu vous dirige-t-il ?",
       a:["Une pharmacie","Un poste de premiers soins dans une halte","Une clinique vétérinaire","Un hôpital"],
       e:"Les panneaux bleus indiquent des services plutôt qu'une règle. Repérer le panneau d'hôpital sur votre trajet compte davantage dans un territoire où la prochaine communauté peut être très loin." },
  c:3 },
{ id:"yts24", sec:"signs", sign:"info-gas",
  en:{ q:"What is this blue information sign telling you?",
       a:["A vehicle inspection station is ahead","Fuel is available at the turn or exit ahead","A truck route begins here","Parking here is free"],
       e:"On long Yukon highways the gap between fuel stops can be very large, so fill up when you get the chance. The territory also suggests carrying extra fuel when you travel in remote areas." },
  fr:{ q:"Que vous indique ce panneau d'information bleu ?",
       a:["Un centre d'inspection des véhicules se trouve devant","Du carburant est offert à la sortie ou au virage devant","Une route de camionnage commence ici","Le stationnement est gratuit ici"],
       e:"Sur les longues routes du Yukon, la distance entre deux postes d'essence peut être énorme : faites le plein dès que vous le pouvez. Le territoire conseille aussi d'emporter du carburant supplémentaire en région éloignée." },
  c:1 },
{ id:"yts25", sec:"signs", sign:"info-food",
  en:{ q:"What is this blue sign showing you?",
       a:["A picnic shelter with no services","A grocery store only","A weigh station","Food services are available ahead"],
       e:"The symbol marks a place to eat. On a long northern drive, planning stops around fuel and food is part of preparing the trip, not a luxury." },
  fr:{ q:"Que vous montre ce panneau bleu ?",
       a:["Un abri de pique-nique sans services","Une épicerie seulement","Une station de pesée","Des services de restauration sont offerts devant"],
       e:"Le pictogramme indique un endroit où manger. Sur un long trajet nordique, planifier ses arrêts en fonction du carburant et des repas fait partie de la préparation, ce n'est pas un luxe." },
  c:3 },
{ id:"yts26", sec:"signs", sign:"info-accessible",
  en:{ q:"This sign is painted on a parking space outside a store. What does it reserve the space for?",
       a:["Anyone stopping for less than five minutes","Only a vehicle displaying a valid accessible parking permit","Delivery vehicles","Anyone, once the business has closed"],
       e:"The space is reserved for a permit holder. Taking it, even briefly, can leave someone with no way to reach the door." },
  fr:{ q:"Ce panneau marque une place de stationnement devant un commerce. À quoi réserve-t-il cette place ?",
       a:["N'importe qui s'arrêtant moins de cinq minutes","Seulement un véhicule affichant une vignette valide de stationnement accessible","Les véhicules de livraison","N'importe qui, une fois le commerce fermé"],
       e:"La place est réservée au détenteur d'une vignette. L'occuper, même un instant, peut priver quelqu'un du seul accès possible à la porte." },
  c:1 },
{ id:"yts27", sec:"signs", sign:"light-amber",
  en:{ q:"The light turns amber as you come up to the intersection. What does that require?",
       a:["Stop if you can do it safely, and carry on only if stopping would be dangerous","Always stop, whatever your speed","Always continue through","Sound your horn and keep going"],
       e:"Amber means the red is coming. The decision is made by where you already are: close enough that hard braking would be dangerous, keep going; far enough back, stop." },
  fr:{ q:"Le feu passe au jaune au moment où vous approchez de l'intersection. Qu'est-ce que cela exige ?",
       a:["Vous arrêter si vous pouvez le faire en sécurité, et continuer seulement si l'arrêt serait dangereux","Vous arrêter chaque fois, peu importe votre vitesse","Continuer chaque fois","Klaxonner et poursuivre"],
       e:"Le jaune annonce le rouge. Votre position décide : trop près pour freiner sans danger, vous passez ; assez loin, vous arrêtez." },
  c:0 },
{ id:"yts28", sec:"signs", sign:"light-flashing-red",
  en:{ q:"A signal at an intersection is flashing red. What does it require of you?",
       a:["Treat it exactly like a green light","Slow down but keep rolling through","Come to a full stop, then go when the way is clear","Stop and wait there until it turns green"],
       e:"A flashing red works like a stop sign. Stop completely, look both ways, and go only when the intersection is clear. It will not change colour." },
  fr:{ q:"Un feu à une intersection clignote au rouge. Que vous impose-t-il ?",
       a:["Le traiter exactement comme un feu vert","Ralentir sans vous arrêter","Faire un arrêt complet, puis repartir quand la voie est libre","Vous arrêter et attendre qu'il devienne vert"],
       e:"Un feu rouge clignotant fonctionne comme un panneau d'arrêt. Immobilisez-vous complètement, regardez des deux côtés et repartez seulement si l'intersection est libre. Il ne changera pas de couleur." },
  c:2 },
{ id:"yts29", sec:"signs", sign:"mark-solid-yellow",
  en:{ q:"You are behind a slow truck and a double solid yellow line separates you from the oncoming lane. What does that line mean?",
       a:["You may cross it because the truck is holding up traffic","Traffic in each direction must stay on its own side and must not cross to pass","You may cross it in daylight only","It marks the outer edge of the travelled road"],
       e:"Double solid yellow lines separate opposing traffic where passing is not safe for either side. Wait for a passing lane or a broken line rather than gambling on the view ahead." },
  fr:{ q:"Vous suivez un camion lent et une double ligne jaune continue vous sépare de la voie inverse. Que signifie cette ligne ?",
       a:["Vous pouvez la franchir puisque le camion ralentit la circulation","La circulation de chaque sens doit rester de son côté et ne peut pas la franchir pour dépasser","Vous pouvez la franchir de jour seulement","Elle marque la limite extérieure de la chaussée"],
       e:"Une double ligne jaune continue sépare les sens opposés là où le dépassement n'est sécuritaire pour personne. Attendez une voie de dépassement ou une ligne discontinue plutôt que de miser sur la visibilité." },
  c:1 },
{ id:"yts30", sec:"signs", sign:"mark-broken-yellow",
  en:{ q:"The centre line beside your lane is a broken yellow line. What does that allow?",
       a:["Parking along the centre of the road","Driving in either lane whenever you like","Passing, but only for large vehicles","Passing when the way ahead is clear and it is safe to do it"],
       e:"A broken yellow line permits passing; it does not promise that passing is a good idea. You still need clear sight distance, a gap long enough to get back in, and a surface with enough grip." },
  fr:{ q:"La ligne centrale à côté de votre voie est une ligne jaune discontinue. Qu'est-ce que cela permet ?",
       a:["Stationner le long du centre de la chaussée","Rouler dans l'une ou l'autre voie quand bon vous semble","Dépasser, mais seulement pour les gros véhicules","Dépasser quand la voie est libre devant et que c'est sécuritaire"],
       e:"Une ligne jaune discontinue permet le dépassement ; elle ne garantit pas que c'est une bonne idée. Il vous faut encore de la visibilité, un espace assez long pour vous rabattre et une adhérence suffisante." },
  c:3 }
);

/* ---------- rules of the road ---------- */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"ytr1", sec:"rules", topic:"gdl",
  en:{ q:"What is the youngest age at which you can apply for a Yukon learner licence?",
       a:["14","15","16","17"],
       e:"Yukon sets 15 as the minimum age for a Class 7 learner licence. You must be at least 16 before you can move up to the Class 5 Novice licence." },
  fr:{ q:"À quel âge minimal pouvez-vous demander un permis d'apprenti au Yukon ?",
       a:["14 ans","15 ans","16 ans","17 ans"],
       e:"Le Yukon fixe à 15 ans l'âge minimal pour un permis d'apprenti de classe 7. Il faut avoir au moins 16 ans pour passer au permis de classe 5, conducteur intermédiaire." },
  c:1 },
{ id:"ytr2", sec:"rules", topic:"gdl",
  en:{ q:"Before a Yukon learner can move on to the next stage, what does the programme ask for?",
       a:["At least six months holding the learner licence and 50 hours of driving","Three months and 20 hours of driving","One full year and 100 hours of driving","No minimum period, only a passing road test"],
       e:"The learner licence must be held continuously for six months, and 50 hours of driving must be completed with a co-driver before you apply for the road test." },
  fr:{ q:"Avant qu'un apprenti du Yukon puisse passer à l'étape suivante, qu'exige le programme ?",
       a:["Au moins six mois de détention du permis d'apprenti et 50 heures de conduite","Trois mois et 20 heures de conduite","Une année complète et 100 heures de conduite","Aucune période minimale, seulement la réussite de l'examen de conduite"],
       e:"Le permis d'apprenti doit être détenu sans interruption pendant six mois, et 50 heures de conduite doivent être accumulées avec un accompagnateur avant de demander l'examen de conduite." },
  c:0 },
{ id:"ytr3", sec:"rules", topic:"gdl",
  en:{ q:"Where are those practice driving hours written down?",
       a:["In any notebook you keep for yourself","On the back of the learner licence","On a form that only a driving school may complete","On the GDL Driver Record and Declaration, signed by you and your co-driver"],
       e:"Yukon publishes the GDL Driver Record and Declaration for exactly this purpose. A parent, guardian or other valid co-driver signs it, so fill it in as you go rather than the night before you apply." },
  fr:{ q:"Où ces heures de pratique sont-elles consignées ?",
       a:["Dans n'importe quel carnet que vous tenez vous-même","Au verso du permis d'apprenti","Sur un formulaire que seule une école de conduite peut remplir","Sur le relevé et la déclaration du conducteur du programme par étapes, signés par vous et votre accompagnateur"],
       e:"Le Yukon publie ce relevé et cette déclaration précisément à cette fin. Un parent, un tuteur ou un autre accompagnateur valide le signe : remplissez-le au fur et à mesure plutôt que la veille de votre demande." },
  c:3 },
{ id:"ytr4", sec:"rules", topic:"gdl",
  en:{ q:"How long must the novice stage be held before you can apply for a full Class 5 licence in Yukon?",
       a:["Six months","Twelve months","Eighteen months","Three years"],
       e:"The Class 5 Novice licence must be held continuously for eighteen months before the application for a full licence. Counting from the day you started your learner licence, the whole programme takes a minimum of two years." },
  fr:{ q:"Combien de temps faut-il détenir l'étape intermédiaire avant de demander un permis complet de classe 5 au Yukon ?",
       a:["Six mois","Douze mois","Dix-huit mois","Trois ans"],
       e:"Le permis de classe 5, conducteur intermédiaire, doit être détenu sans interruption pendant dix-huit mois avant la demande de permis complet. À partir du jour du permis d'apprenti, le programme dure donc au moins deux ans." },
  c:2 },
{ id:"ytr5", sec:"rules", topic:"gdl",
  en:{ q:"Who is allowed to sit beside you as your co-driver while you hold a Yukon learner licence?",
       a:["Someone who has held at least a Class 5 licence for two years or more","Any adult with a valid licence of any class","Any driver over the age of 25","Anyone who has passed a road test at some point"],
       e:"The co-driver must hold a valid licence of at least Class 5, and must have held it for at least two years. They have to be with you every single time you drive." },
  fr:{ q:"Qui peut prendre place à côté de vous comme accompagnateur pendant que vous détenez un permis d'apprenti du Yukon ?",
       a:["Une personne qui détient au moins un permis de classe 5 depuis deux ans ou plus","Tout adulte titulaire d'un permis valide, peu importe la classe","Tout conducteur de plus de 25 ans","Toute personne ayant déjà réussi un examen de conduite"],
       e:"L'accompagnateur doit détenir un permis valide d'au moins la classe 5, et le détenir depuis au moins deux ans. Il doit être avec vous chaque fois que vous conduisez." },
  c:0 },
{ id:"ytr6", sec:"rules", topic:"restrict",
  en:{ q:"Your co-driver has had one beer with dinner and feels completely normal. May they supervise you?",
       a:["Yes, as long as they stay under the criminal limit","Yes, if the drive is short","Yes, if you keep to quiet streets","No, because your co-driver must have no alcohol in their blood"],
       e:"Yukon's zero tolerance binds the supervisor as well as the learner. The co-driver must have no alcohol in their blood and must not be impaired by drugs or any other substance." },
  fr:{ q:"Votre accompagnateur a bu une bière au souper et se sent tout à fait normal. Peut-il vous accompagner ?",
       a:["Oui, tant qu'il reste sous la limite criminelle","Oui, si le trajet est court","Oui, si vous restez dans des rues tranquilles","Non, car votre accompagnateur ne doit avoir aucun alcool dans le sang"],
       e:"La tolérance zéro du Yukon vise l'accompagnateur autant que l'apprenti. L'accompagnateur ne doit avoir aucun alcool dans le sang et ne doit pas avoir les facultés affaiblies par la drogue ou toute autre substance." },
  c:3 },
{ id:"ytr7", sec:"rules", topic:"restrict",
  en:{ q:"During which hours may a Yukon learner drive?",
       a:["Any hour, provided the co-driver is present","In daylight only","Between 5 a.m. and midnight","Between 6 a.m. and 10 p.m."],
       e:"The learner stage carries a curfew: driving is allowed between 5 a.m. and midnight. A co-driver beside you does not lift it." },
  fr:{ q:"Pendant quelles heures un apprenti du Yukon peut-il conduire ?",
       a:["À toute heure, pourvu que l'accompagnateur soit présent","De jour seulement","Entre 5 h et minuit","Entre 6 h et 22 h"],
       e:"L'étape d'apprenti comporte un couvre-feu : la conduite est permise entre 5 h et minuit. La présence d'un accompagnateur ne le lève pas." },
  c:2 },
{ id:"ytr8", sec:"rules", topic:"restrict",
  en:{ q:"Apart from your co-driver, how many passengers may a Yukon learner carry?",
       a:["None at all","One, unless the additional passengers are a parent, grandparent, brother, sister or child","Two, with no exceptions","One for every working seat belt"],
       e:"The limit is one passenger in addition to the co-driver. Close family members named in the rule do not count against that limit, so a full car of siblings is allowed while a full car of friends is not." },
  fr:{ q:"En plus de votre accompagnateur, combien de passagers un apprenti du Yukon peut-il transporter ?",
       a:["Aucun","Un seul, sauf si les passagers supplémentaires sont un parent, un grand-parent, un frère, une soeur ou un enfant","Deux, sans exception","Un par ceinture de sécurité fonctionnelle"],
       e:"La limite est d'un passager en plus de l'accompagnateur. Les proches nommés dans la règle ne comptent pas dans cette limite : une voiture pleine de frères et soeurs est permise, une voiture pleine d'amis ne l'est pas." },
  c:1 },
{ id:"ytr9", sec:"rules", topic:"restrict",
  en:{ q:"What sort of vehicle may a Yukon learner drive?",
       a:["Any vehicle the co-driver is licensed for","Any vehicle under 10,000 kilograms","A passenger van of any size","A car or light truck up to 4,000 kilograms registered gross vehicle weight, seating no more than seven including the driver"],
       e:"The weight cap stays at 4,000 kilograms at the novice stage, but the seating limit rises to nine including the driver. Learners and novice drivers may not tow a trailer." },
  fr:{ q:"Quel type de véhicule un apprenti du Yukon peut-il conduire ?",
       a:["Tout véhicule pour lequel l'accompagnateur est autorisé","Tout véhicule de moins de 10 000 kilogrammes","Une fourgonnette de n'importe quelle taille","Une automobile ou une camionnette d'au plus 4 000 kilogrammes de poids nominal brut, avec au plus sept places, conducteur compris"],
       e:"La limite de poids reste de 4 000 kilogrammes à l'étape intermédiaire, mais le nombre de places passe à neuf, conducteur compris. Les apprentis et les conducteurs intermédiaires ne peuvent pas tirer de remorque." },
  c:3 },
{ id:"ytr10", sec:"rules", topic:"restrict",
  en:{ q:"What has to be shown on the vehicle every time a Yukon learner drives?",
       a:["A green sticker on the windshield","A sign on each front door","An L sign on the back, where drivers behind you can see it","Nothing extra, the licence in your pocket is enough"],
       e:"The learner L sign goes on the rear of the vehicle every time you drive, visible to drivers approaching from behind. It tells the traffic behind you to expect a driver who is still learning." },
  fr:{ q:"Que faut-il afficher sur le véhicule chaque fois qu'un apprenti du Yukon conduit ?",
       a:["Un autocollant vert sur le pare-brise","Une affiche sur chaque portière avant","Une vignette d'apprenti conducteur portant la mention L à l'arrière, visible des conducteurs qui vous suivent","Rien de plus, le permis dans votre poche suffit"],
       e:"La vignette d'apprenti conducteur se pose à l'arrière du véhicule chaque fois que vous conduisez, visible des conducteurs qui approchent par derrière. Elle prévient la circulation derrière vous qu'un conducteur en apprentissage est au volant." },
  c:2 },
{ id:"ytr11", sec:"rules", topic:"test",
  en:{ q:"What score does Yukon require to pass the knowledge test for a driver's licence?",
       a:["70 per cent","80 per cent","85 per cent","90 per cent"],
       e:"The Motor Vehicles Regulations set a passing score of 80 per cent, and the same figure applies to every class of licence. The regulations describe a single combined written and sign-recognition test rather than two separate exams." },
  fr:{ q:"Quelle note le Yukon exige-t-il pour réussir l'examen théorique en vue d'un permis de conduire ?",
       a:["70 pour cent","80 pour cent","85 pour cent","90 pour cent"],
       e:"Le règlement sur les véhicules automobiles fixe la note de passage à 80 pour cent, et ce chiffre vaut pour toutes les classes de permis. Le règlement décrit un seul examen combiné, écrit et de reconnaissance des panneaux, et non deux examens distincts." },
  c:1 },
{ id:"ytr12", sec:"rules", topic:"test",
  en:{ q:"You do not pass the Yukon knowledge test. When can you try again, and what does it cost?",
       a:["As early as the following day, for another 20 dollars","After seven days, at no charge","After thirty days, for 20 dollars","Only once more, and only on the same day"],
       e:"The test fee is 20 dollars, and a failed attempt can be repeated as early as the next day for another 20 dollars. Coming back the following morning with the handbook read properly is cheaper than guessing twice." },
  fr:{ q:"Vous échouez à l'examen théorique du Yukon. Quand pouvez-vous le reprendre et à quel prix ?",
       a:["Dès le lendemain, pour 20 dollars de plus","Après sept jours, sans frais","Après trente jours, pour 20 dollars","Une seule autre fois, et seulement le jour même"],
       e:"L'examen coûte 20 dollars, et un échec peut être repris dès le lendemain pour 20 dollars de plus. Revenir le lendemain matin après avoir bien lu le guide coûte moins cher que de deviner deux fois." },
  c:0 },
{ id:"ytr13", sec:"rules", topic:"test",
  en:{ q:"What else is checked when you apply for a Yukon driver's licence?",
       a:["Your hearing","A short drive around the parking lot","Your eyesight","A first-aid certificate"],
       e:"A vision test is part of the process. If you do not pass it you are sent for further testing by an optometrist or ophthalmologist, and if you need glasses or contact lenses to meet the standard, that condition is recorded on your licence." },
  fr:{ q:"Qu'est-ce qui est aussi vérifié lorsque vous demandez un permis de conduire du Yukon ?",
       a:["Votre audition","Un court trajet dans le stationnement","Votre vue","Un certificat de secourisme"],
       e:"Un examen de la vue fait partie du processus. Si vous n'y réussissez pas, vous êtes dirigé vers un optométriste ou un ophtalmologiste ; et s'il vous faut des lunettes ou des lentilles pour atteindre la norme, cette condition est inscrite sur votre permis." },
  c:2 },
{ id:"ytr14", sec:"rules", topic:"penalties",
  en:{ q:"How many demerit points bring a suspension for a driver in the graduated licensing programme in Yukon?",
       a:["Five","Seven","Ten","Fifteen"],
       e:"Graduated licensing drivers are suspended at seven demerit points. Every other licence holder is suspended at fifteen, so a new driver has less than half the margin." },
  fr:{ q:"Combien de points d'inaptitude entraînent une suspension pour un conducteur du programme par étapes au Yukon ?",
       a:["Cinq","Sept","Dix","Quinze"],
       e:"Les conducteurs du programme par étapes sont suspendus à sept points d'inaptitude. Tous les autres titulaires le sont à quinze : la marge d'un nouveau conducteur est donc moins de la moitié." },
  c:1 },
{ id:"ytr15", sec:"rules", topic:"penalties",
  en:{ q:"May a Yukon learner or novice driver use a phone mounted in a hands-free holder?",
       a:["No, learners and novice drivers may not use any electronic device, hands-free included","Yes, hands-free use is always allowed","Yes, but only for navigation","Yes, once the vehicle is moving at a steady speed"],
       e:"Only full licence holders may use a device that is set up and used in a hands-free way. For learners and novice drivers the ban covers hand-held and hands-free alike, so the phone goes away before you start the engine." },
  fr:{ q:"Un apprenti ou un conducteur intermédiaire du Yukon peut-il utiliser un téléphone installé en mode mains libres ?",
       a:["Non, les apprentis et les conducteurs intermédiaires ne peuvent utiliser aucun appareil électronique, même mains libres","Oui, le mode mains libres est toujours permis","Oui, mais seulement pour la navigation","Oui, une fois que le véhicule roule à vitesse constante"],
       e:"Seuls les titulaires d'un permis complet peuvent utiliser un appareil configuré et utilisé en mode mains libres. Pour les apprentis et les conducteurs intermédiaires, l'interdiction vise autant le tenu en main que le mains libres : rangez le téléphone avant de démarrer." },
  c:0 },
{ id:"ytr16", sec:"rules", topic:"penalties",
  en:{ q:"What can a distracted driving conviction cost a driver in Yukon?",
       a:["A written warning only","A fine but never any points","One demerit point and no fine","A fine of up to 600 dollars and three demerit points"],
       e:"Distracted driving carries a fine of up to 600 dollars and three demerit points, for full licence holders and graduated licensing drivers alike. For a graduated licensing driver those three points are almost half the way to a suspension." },
  fr:{ q:"Que peut coûter une condamnation pour distraction au volant à un conducteur du Yukon ?",
       a:["Un simple avertissement écrit","Une amende, mais jamais de points","Un point d'inaptitude et aucune amende","Une amende pouvant atteindre 600 dollars et trois points d'inaptitude"],
       e:"La distraction au volant entraîne une amende pouvant atteindre 600 dollars et trois points d'inaptitude, autant pour les titulaires d'un permis complet que pour les conducteurs du programme par étapes. Pour ces derniers, ces trois points représentent presque la moitié du chemin vers une suspension." },
  c:3 },
{ id:"ytr17", sec:"rules", topic:"penalties",
  en:{ q:"What happens to your graduated licensing time if you are convicted of a graduated licensing violation?",
       a:["The time already served stops counting towards the next stage, so the clock starts again","Nothing changes, the months keep counting","You move up one month later than planned","Only your insurance is affected"],
       e:"Yukon's regulations state that the time the licence was held before the violation does not count towards the total required for the next stage. One conviction can therefore cost you the whole six or eighteen months you had already built up." },
  fr:{ q:"Qu'advient-il de votre temps accumulé si vous êtes déclaré coupable d'une infraction au programme par étapes ?",
       a:["Le temps déjà accumulé cesse de compter pour l'étape suivante : le compte recommence","Rien ne change, les mois continuent de compter","Vous passez à l'étape suivante un mois plus tard que prévu","Seule votre assurance est touchée"],
       e:"Le règlement du Yukon prévoit que le temps de détention du permis avant l'infraction ne compte pas dans le total exigé pour l'étape suivante. Une seule condamnation peut donc effacer les six ou dix-huit mois déjà accumulés." },
  c:0 },
{ id:"ytr18", sec:"rules", topic:"sharing",
  en:{ q:"You are on an undivided Yukon highway and a school bus ahead stops with its upper red lights flashing. What must you do?",
       a:["Pass slowly on the left","Stop, whichever direction you are travelling in","Stop only if you can see children","Sound your horn and keep going"],
       e:"On a street, an undivided highway or a roadway, traffic in every direction must stop for a stopped school bus showing flashing upper red lights. Children may be crossing in front of the bus where you cannot see them." },
  fr:{ q:"Vous roulez sur une route non divisée du Yukon et un autobus scolaire devant vous s'arrête, feux rouges supérieurs clignotants. Que devez-vous faire ?",
       a:["Le dépasser lentement par la gauche","Vous arrêter, peu importe votre sens de circulation","Vous arrêter seulement si vous voyez des enfants","Klaxonner et poursuivre votre route"],
       e:"Sur une rue, une route non divisée ou une chaussée, la circulation doit s'arrêter dans tous les sens devant un autobus scolaire immobilisé dont les feux rouges supérieurs clignotent. Des enfants peuvent traverser devant l'autobus, hors de votre vue." },
  c:1 },
{ id:"ytr19", sec:"rules", topic:"sharing",
  en:{ q:"The same bus is stopped on a highway that is physically divided by a median into two separate roadways. Who has to stop?",
       a:["Everybody, from both directions","Nobody, because the median keeps children away","Only the drivers approaching the bus from behind","Only the drivers in the left lane"],
       e:"Where a median physically divides the highway into two roadways, only drivers coming up behind the bus must stop. On any street or undivided road, both directions stop." },
  fr:{ q:"Le même autobus est immobilisé sur une route physiquement divisée par un terre-plein en deux chaussées distinctes. Qui doit s'arrêter ?",
       a:["Tout le monde, dans les deux sens","Personne, puisque le terre-plein éloigne les enfants","Seulement les conducteurs qui approchent de l'autobus par derrière","Seulement les conducteurs de la voie de gauche"],
       e:"Lorsqu'un terre-plein divise physiquement la route en deux chaussées, seuls les conducteurs qui arrivent derrière l'autobus doivent s'arrêter. Sur une rue ou une route non divisée, les deux sens s'arrêtent." },
  c:2 },
{ id:"ytr20", sec:"rules", topic:"sharing",
  en:{ q:"You have stopped for a school bus with its red lights flashing. When may you move off again?",
       a:["As soon as the last child steps down","After waiting a slow count of ten","As soon as the bus door closes","When the red lights have stopped flashing and the bus starts to move"],
       e:"Two things have to happen: the red lights stop flashing and the bus begins to move. A closed door on its own is not the signal, because a child may still be crossing in front." },
  fr:{ q:"Vous vous êtes arrêté pour un autobus scolaire aux feux rouges clignotants. Quand pouvez-vous repartir ?",
       a:["Dès que le dernier enfant est descendu","Après avoir compté lentement jusqu'à dix","Dès que la porte de l'autobus se referme","Quand les feux rouges ont cessé de clignoter et que l'autobus se remet en mouvement"],
       e:"Deux conditions doivent être remplies : les feux rouges cessent de clignoter et l'autobus se remet en mouvement. Une porte fermée ne suffit pas, car un enfant peut encore traverser devant." },
  c:3 },
{ id:"ytr21", sec:"rules", topic:"sharing",
  en:{ q:"Your vehicle has no automatic daytime running lights. What does Yukon law require of you in daylight?",
       a:["Nothing, headlights are only for darkness","You must drive with your low beam headlights on","You must use your high beams","You must switch on your hazard lights"],
       e:"On Yukon roadways a vehicle without automatic daytime running lights must be driven with the low beams on during the day. It is a legal requirement, and it makes you far easier to see against snow, dust and a low northern sun." },
  fr:{ q:"Votre véhicule n'a pas de feux de jour automatiques. Qu'exige de vous la loi du Yukon en plein jour ?",
       a:["Rien, les phares servent seulement dans l'obscurité","Vous devez rouler avec les feux de croisement allumés","Vous devez utiliser les feux de route","Vous devez allumer vos feux de détresse"],
       e:"Sur les routes du Yukon, un véhicule sans feux de jour automatiques doit rouler de jour avec les feux de croisement allumés. C'est une obligation légale, et cela vous rend bien plus visible sur fond de neige, de poussière ou de soleil bas du Nord." },
  c:1 },
{ id:"ytr22", sec:"rules", topic:"permafrost",
  en:{ q:"Which Yukon roads does the territory name as affected by permafrost heaving?",
       a:["The Alaska Highway between Haines Junction and Beaver Creek, the Haines Road, the Dempster, the North and South Klondike and the Robert Campbell","The Dempster Highway only","The streets inside Whitehorse only","Every road that is unpaved"],
       e:"Ground ice beneath the road thaws and refreezes, leaving waves and dips the territory compares to a roller coaster. The Shakwak section also has cracks, potholes and frequent gravel stretches." },
  fr:{ q:"Quelles routes du Yukon le territoire désigne-t-il comme touchées par les soulèvements du pergélisol ?",
       a:["La route de l'Alaska entre Haines Junction et Beaver Creek, la route Haines, la Dempster, les Klondike Nord et Sud et la Robert Campbell","La route Dempster seulement","Les rues de Whitehorse seulement","Toutes les routes non revêtues"],
       e:"La glace souterraine sous la chaussée dégèle et regèle, laissant des vagues et des creux que le territoire compare à des montagnes russes. Le tronçon Shakwak présente aussi des fissures, des nids-de-poule et de fréquentes sections de gravier." },
  c:0 },
{ id:"ytr23", sec:"rules", topic:"permafrost",
  en:{ q:"You reach a stretch of highway that rolls and dips from frost heaving. What does Yukon advise?",
       a:["Keep your speed up so the vehicle floats over the dips","Drive on the shoulder where the surface is flatter","Pass slower vehicles quickly to get clear of the section","Slow down, scan well ahead and avoid passing"],
       e:"Yukon asks drivers to slow down, be cautious, scan the road ahead and avoid passing on heaved sections. A dip you cannot see into can hide oncoming traffic or a vehicle already stopped." },
  fr:{ q:"Vous arrivez sur un tronçon de route qui ondule et plonge à cause du gel. Que conseille le Yukon ?",
       a:["Maintenir votre vitesse pour que le véhicule survole les creux","Rouler sur l'accotement, où la surface est plus plane","Dépasser vite les véhicules lents pour sortir de la section","Ralentir, balayer loin devant du regard et éviter de dépasser"],
       e:"Le Yukon demande aux conducteurs de ralentir, d'être prudents, de scruter la route devant eux et d'éviter les dépassements sur les sections soulevées. Un creux dans lequel vous ne voyez pas peut cacher un véhicule qui vient en sens inverse ou déjà immobilisé." },
  c:3 },
{ id:"ytr24", sec:"rules", topic:"permafrost",
  en:{ q:"Why does Yukon tell drivers not to pull over on permafrost-damaged highways except in an emergency?",
       a:["Because stopping there is a ticketed offence","Because there is nothing worth seeing","Because the shoulders are unstable","Because the road belongs to a private owner"],
       e:"The shoulders on these roads can give way under a vehicle. Gravel sections also lengthen your stopping distance, so increase your following distance, and remember that posted speed limits are set for optimal road conditions." },
  fr:{ q:"Pourquoi le Yukon dit-il aux conducteurs de ne pas s'immobiliser sur les routes abîmées par le pergélisol, sauf en cas d'urgence ?",
       a:["Parce que s'y arrêter constitue une infraction avec amende","Parce qu'il n'y a rien d'intéressant à voir","Parce que les accotements sont instables","Parce que la route appartient à un propriétaire privé"],
       e:"Les accotements de ces routes peuvent céder sous un véhicule. Les sections de gravier allongent aussi la distance de freinage : augmentez votre distance de suivi et rappelez-vous que les limites affichées sont fixées pour des conditions routières optimales." },
  c:2 },
{ id:"ytr25", sec:"rules", topic:"winter",
  en:{ q:"A regulatory sign showing winter tires or chains is posted at the start of a section of road. What does it mean?",
       a:["Winter tires or chains must be used from that point on","They are recommended there but remain optional","It applies only to commercial trucks","It applies only after a snowfall warning is issued"],
       e:"Where that sign is displayed, winter tires or chains are required, not suggested. Turning back or waiting is the only legal choice if your vehicle is not equipped." },
  fr:{ q:"Un panneau de prescription montrant des pneus d'hiver ou des chaînes est installé au début d'un tronçon de route. Que signifie-t-il ?",
       a:["Les pneus d'hiver ou les chaînes sont obligatoires à partir de ce point","Ils y sont recommandés, mais demeurent facultatifs","Cela ne vise que les camions commerciaux","Cela ne s'applique qu'après un avertissement de neige"],
       e:"Là où ce panneau est affiché, les pneus d'hiver ou les chaînes sont exigés, et non suggérés. Faire demi-tour ou attendre est le seul choix légal si votre véhicule n'est pas équipé." },
  c:0 },
{ id:"ytr26", sec:"rules", topic:"winter",
  en:{ q:"Yukon says every vehicle should carry a winter driving emergency kit. Which of these belongs in it?",
       a:["A spare set of licence plates","One litre of windshield washer fluid and nothing more","A shovel, a flashlight, warm clothing, food and booster cables","A camera and a notebook for insurance"],
       e:"The territory's list also includes an ice scraper, a spare tire, a fire extinguisher, a first-aid kit and a source of heat. Where help can be hours away, the kit is what keeps you warm and visible until it arrives." },
  fr:{ q:"Le Yukon dit que chaque véhicule devrait transporter une trousse d'urgence pour la conduite hivernale. Lequel de ces éléments en fait partie ?",
       a:["Une plaque d'immatriculation de rechange","Un litre de lave-glace et rien de plus","Une pelle, une lampe de poche, des vêtements chauds, de la nourriture et des câbles de démarrage","Un appareil photo et un carnet pour l'assurance"],
       e:"La liste du territoire comprend aussi un grattoir, un pneu de secours, un extincteur, une trousse de premiers soins et une source de chaleur. Là où les secours peuvent mettre des heures, c'est la trousse qui vous garde au chaud et visible en attendant." },
  c:2 },
{ id:"ytr27", sec:"rules", topic:"winter",
  en:{ q:"What does Yukon recommend doing to your vehicle before the winter driving season?",
       a:["Fit the widest tires you can find","Install winter tires and carry an emergency winter driving kit","Let air out of the tires for extra grip","Take the spare tire out to save weight"],
       e:"Winter tires stay soft and keep gripping at temperatures where all-season rubber goes hard. Yukon pairs that advice with carrying the emergency kit, because the two problems arrive together." },
  fr:{ q:"Que recommande le Yukon de faire à votre véhicule avant la saison de conduite hivernale ?",
       a:["Monter les pneus les plus larges possible","Installer des pneus d'hiver et transporter une trousse d'urgence pour la conduite hivernale","Dégonfler un peu les pneus pour améliorer l'adhérence","Retirer le pneu de secours pour alléger le véhicule"],
       e:"Les pneus d'hiver restent souples et continuent d'adhérer à des températures où la gomme quatre saisons durcit. Le Yukon joint à ce conseil celui d'emporter la trousse d'urgence, car les deux problèmes arrivent ensemble." },
  c:1 },
{ id:"ytr28", sec:"rules", topic:"remote",
  en:{ q:"You are about to drive a long, empty stretch of Yukon highway. What does the territory ask you to do first?",
       a:["Nothing in particular, if the weather looks clear","Post your plans on social media","Drive only during daylight hours","Tell someone your route, your destination and when you expect to be back"],
       e:"Yukon asks drivers to tell someone their travel plans and their estimated time of travel before leaving. If you do not arrive, that is the information that tells searchers where to look." },
  fr:{ q:"Vous vous apprêtez à parcourir un long tronçon désert d'une route du Yukon. Que vous demande le territoire de faire d'abord ?",
       a:["Rien de particulier, si le temps est clair","Publier votre projet sur les réseaux sociaux","Rouler seulement pendant les heures de clarté","Dire à quelqu'un votre itinéraire, votre destination et l'heure de votre retour prévu"],
       e:"Le Yukon demande aux conducteurs d'informer quelqu'un de leur trajet et de la durée prévue avant de partir. Si vous n'arrivez pas, c'est cette information qui indiquera aux secours où chercher." },
  c:3 },
{ id:"ytr29", sec:"rules", topic:"remote",
  en:{ q:"Where can a Yukon driver check road conditions before setting out?",
       a:["At the vehicle registration counter","On a local radio phone-in show only","Through 511Yukon, the territory's road report service","Nowhere official, so you have to judge for yourself"],
       e:"Yukon publishes road and weather conditions through 511Yukon and asks drivers to check them before travelling. Conditions in the north can change completely between one valley and the next." },
  fr:{ q:"Où un conducteur du Yukon peut-il vérifier l'état des routes avant de partir ?",
       a:["Au comptoir d'immatriculation des véhicules","Seulement à une tribune téléphonique radiophonique locale","Auprès de 511Yukon, le service d'information routière du territoire","Nulle part officiellement : il faut juger par soi-même"],
       e:"Le Yukon diffuse l'état des routes et la météo par 511Yukon et demande aux conducteurs de les consulter avant de voyager. Dans le Nord, les conditions peuvent changer complètement d'une vallée à l'autre." },
  c:2 },
{ id:"ytr30", sec:"rules", topic:"remote",
  en:{ q:"What does Yukon suggest taking with you when you travel far from communities?",
       a:["Extra fuel and a satellite phone or CB radio","A second driver at all times","A trailer loaded with supplies","A mobile phone and nothing else"],
       e:"Distances between services are long and mobile coverage cannot be relied on, so Yukon suggests extra fuel and a satellite phone or CB radio. Both are for the trip that does not go to plan." },
  fr:{ q:"Que suggère le Yukon d'emporter lorsque vous voyagez loin des communautés ?",
       a:["Du carburant supplémentaire et un téléphone satellite ou une radio BP","Un deuxième conducteur en tout temps","Une remorque chargée de provisions","Un téléphone cellulaire et rien d'autre"],
       e:"Les distances entre les services sont longues et la couverture cellulaire n'est pas fiable : le Yukon suggère du carburant supplémentaire et un téléphone satellite ou une radio BP. Les deux servent au trajet qui ne se déroule pas comme prévu." },
  c:0 }
);


/* ---------------------------------------------------------------------------
   WHOSE NUMBERS ARE THESE? Half Yukon's, half ours — read carefully.

   YUKON'S OWN, published: the 80% pass mark. The Motor Vehicles Regulations
   (s.3(1)(a)) prescribe "a passing score of 80% for all classes of licences",
   so 80% applies to every class, not just the learner licence. The same
   provision describes ONE combined "basic written and sign recognition test",
   not two separate exams.

   OURS, because Yukon publishes neither: the number of questions and the
   timer. The regulation leaves the content of the basic test to the registrar
   and sets no question count for it, and no Government of Yukon page states a
   time limit. The 20 + 20 below and the 30 minutes are our practice standard.

   ALSO OURS: the split into two sections. Because the real Yukon exam is a
   single combined written and sign-recognition test, splitting signs from
   rules here is a study device of ours — it lets the study pages work — and
   we apply Yukon's 80% to each half (ask 20, pass 16) so the standard you
   practise against is the real one.

   FOR THE RECORD: at least one commercial practice site states that the Yukon
   exam has "two parts of 20 questions each". The regulation does not support
   that, since it describes a single combined test, and no official source
   publishes any question count at all.
   --------------------------------------------------------------------------- */
window.CQ_PROVINCE = {
  code: "YT",
  name: { en: "Yukon", fr: "Yukon" },
  licence: "Class 7 Learner",
  minutes: 30,
  sections: [
    { id: "signs", ask: 20, pass: 16,
      name: { en: "Road Sign Recognition",
              fr: "Reconnaissance des panneaux" } },
    { id: "rules", ask: 20, pass: 16,
      name: { en: "Rules of the Road",
              fr: "Code de la route" } }
  ],
  handbook: { en: "Yukon Driver's Basic Handbook",
              fr: "Guide de la route du Yukon" },
  handbookUrl: "https://yukon.ca/en/yukon-drivers-basic-handbook",
  bookingUrl: "https://yukon.ca/en/driving-and-transportation/driver-licensing/get-drivers-licence",
  topics: [
    { id:"gdl",        en:"Graduated Licensing",              fr:"Permis par étapes" },
    { id:"restrict",   en:"Learner and Novice Restrictions",  fr:"Restrictions des apprentis et des conducteurs intermédiaires" },
    { id:"test",       en:"Your Licence and the Test",        fr:"Votre permis et l'examen" },
    { id:"penalties",  en:"Demerit Points and Penalties",     fr:"Points d'inaptitude et sanctions" },
    { id:"sharing",    en:"Sharing the Road and Being Seen",  fr:"Partager la route et être visible" },
    { id:"permafrost", en:"Northern Highways and Permafrost", fr:"Routes nordiques et pergélisol" },
    { id:"winter",     en:"Winter Driving and Emergency Kit", fr:"Conduite hivernale et trousse d'urgence" },
    { id:"remote",     en:"Remote Travel and Road Reports",   fr:"Voyages en région éloignée et état des routes" }
  ],
  questions: window.CQ_DRIVE_Q
};


/* Ten more rules questions, added 3 September 2026.
   Written from this jurisdiction's own official handbook, and
   chosen for what makes its rules different from its neighbours'.
   The French is written beside the English on purpose: see the
   note at the top of tools/newq/fr_qbank.py. */
(window.CQ_DRIVE_Q = window.CQ_DRIVE_Q || []).push(

{ id:"ytx1", sec:"rules",
  en:{ q:"How many stages does the Yukon graduated licensing programme have?",
       a:["Two — learner and novice","Three","Four","None at all"],
       e:"Yukon has two stages: a learner licence from age 15 for at least six months, then a novice licence from 16 for at least eighteen months. The Northwest Territories next door uses three stages." },
  fr:{ q:"Combien d'étapes compte le programme d'accès graduel du Yukon ?",
       a:["Deux : apprenti et novice","Trois","Quatre","Aucune"],
       e:"Le Yukon compte deux étapes : un permis d'apprenti dès 15 ans pendant au moins six mois, puis un permis de novice dès 16 ans pendant au moins dix-huit mois. Les Territoires du Nord-Ouest voisins en comptent trois." },
  c:0 },

{ id:"ytx2", sec:"rules",
  en:{ q:"How many passengers may a Yukon learner carry?",
       a:["None","Two including the co-driver, or more if they are immediate family","Three","As many as there are seat belts"],
       e:"The limit is two people including the co-driver, unless the extra passengers are immediate family members." },
  fr:{ q:"Combien de passagers un apprenti du Yukon peut-il transporter ?",
       a:["Aucun","Deux, y compris le co-conducteur, ou plus s'il s'agit de la famille immédiate","Trois","Autant qu'il y a de ceintures"],
       e:"La limite est de deux personnes, y compris le co-conducteur, sauf si les passagers supplémentaires sont des membres de la famille immédiate." },
  c:1 },

{ id:"ytx3", sec:"rules",
  en:{ q:"Between which hours may a Yukon learner drive?",
       a:["Any time","Daylight only","5 a.m. to midnight","6 a.m. to 11 p.m."],
       e:"A learner drives between 5 a.m. and midnight. A novice may drive at any hour, but needs a co-driver in the vehicle between midnight and 5 a.m." },
  fr:{ q:"Entre quelles heures un apprenti du Yukon peut-il conduire ?",
       a:["En tout temps","Seulement le jour","De 5 h à minuit","De 6 h à 23 h"],
       e:"Un apprenti conduit entre 5 h et minuit. Un novice peut conduire à toute heure, mais doit avoir un co-conducteur dans le véhicule entre minuit et 5 h." },
  c:2 },

{ id:"ytx4", sec:"rules",
  en:{ q:"Who must be free of alcohol and drugs when a Yukon learner drives?",
       a:["Only the learner","The learner and the co-driver","Only the co-driver","Neither, below 0.05"],
       e:"Zero tolerance applies to both the new driver and the co-driver. A co-driver who has been drinking is not a co-driver." },
  fr:{ q:"Qui doit être exempt d'alcool et de drogue lorsqu'un apprenti conduit au Yukon ?",
       a:["Seulement l'apprenti","L'apprenti et le co-conducteur","Seulement le co-conducteur","Ni l'un ni l'autre, sous 0,05"],
       e:"La tolérance zéro s'applique tant au nouveau conducteur qu'au co-conducteur. Un co-conducteur qui a bu n'est pas un co-conducteur." },
  c:1 },

{ id:"ytx5", sec:"rules",
  en:{ q:"How many demerit points suspend a Yukon driver in the graduated programme?",
       a:["4","7","12","15"],
       e:"A graduated driver is suspended at 7 points. Every other Yukon licence holder has 15." },
  fr:{ q:"Combien de points d'inaptitude entraînent la suspension d'un conducteur du Yukon au programme gradué ?",
       a:["4","7","12","15"],
       e:"Un conducteur au programme gradué est suspendu à 7 points. Tout autre titulaire de permis du Yukon en a 15." },
  c:1 },

{ id:"ytx6", sec:"rules",
  en:{ q:"What extra penalty does a Yukon graduated driver face for distracted driving?",
       a:["Nothing extra","A doubled fine","A vehicle seizure","They must restart the programme and lose their earned days"],
       e:"On top of the fine and 3 demerit points, a graduated driver restarts the programme and loses all the driving experience days already earned." },
  fr:{ q:"Quelle sanction supplémentaire un conducteur gradué du Yukon subit-il pour conduite distraite ?",
       a:["Rien de plus","Une amende doublée","Une saisie du véhicule","Il doit recommencer le programme et perdre les jours accumulés"],
       e:"En plus de l'amende et des 3 points d'inaptitude, un conducteur gradué recommence le programme et perd tous les jours d'expérience déjà accumulés." },
  c:3 },

{ id:"ytx7", sec:"rules",
  en:{ q:"What is the speed limit in a Yukon playground zone?",
       a:["50 km/h during school hours","40 km/h","30 km/h, 24 hours a day","There is no special limit"],
       e:"Playground zones are 30 km/h around the clock. Yukon school zones are 50 km/h between 8 a.m. and 4:30 p.m. on school days." },
  fr:{ q:"Quelle est la limite de vitesse dans une zone de terrain de jeu au Yukon ?",
       a:["50 km/h pendant les heures de classe","40 km/h","30 km/h, 24 heures sur 24","Il n'y a pas de limite spéciale"],
       e:"Les zones de terrain de jeu sont à 30 km/h en tout temps. Les zones scolaires du Yukon sont à 50 km/h de 8 h à 16 h 30 les jours d'école." },
  c:2 },

{ id:"ytx8", sec:"rules",
  en:{ q:"Why should you slow down and avoid passing on a permafrost-affected Yukon highway?",
       a:["The road is closed to passing by law","Thawing ground leaves dips and waves in the road surface","Snow drifts hide the centre line","The road is always gravel"],
       e:"Thawing permafrost makes the surface roll like a wave. Slow down, scan far ahead, and do not stop or pull over except in an emergency." },
  fr:{ q:"Pourquoi ralentir et éviter de dépasser sur une route du Yukon touchée par le pergélisol ?",
       a:["La loi y interdit le dépassement","Le dégel du sol crée des creux et des vagues dans la chaussée","La poudrerie cache la ligne centrale","La route est toujours en gravier"],
       e:"Le dégel du pergélisol fait onduler la chaussée comme une vague. Ralentissez, regardez loin devant, et ne vous arrêtez pas sur l'accotement sauf en cas d'urgence." },
  c:1 },

{ id:"ytx9", sec:"rules",
  en:{ q:"What should you carry when driving the Dempster Highway?",
       a:["Spare tires — almost the whole road is gravel and flats are common","Nothing special","A boat","Extra windshield wipers only"],
       e:"Except for the first five kilometres the Dempster is all gravel, and flat tires are common. Stop only where others can pass safely, never on a hill, bridge or curve." },
  fr:{ q:"Que devriez-vous emporter en empruntant la route Dempster ?",
       a:["Des pneus de rechange : presque toute la route est en gravier et les crevaisons sont fréquentes","Rien de particulier","Une embarcation","Seulement des essuie-glaces supplémentaires"],
       e:"Sauf pour les cinq premiers kilomètres, la Dempster est entièrement en gravier et les crevaisons sont fréquentes. Arrêtez-vous seulement là où les autres peuvent passer en sécurité, jamais dans une côte, sur un pont ou dans une courbe." },
  c:0 },

{ id:"ytx10", sec:"rules",
  en:{ q:"When do the Peel and Mackenzie river crossings on the Dempster Highway not operate at all?",
       a:["Only in midwinter","Only in midsummer","During freeze-up and break-up","They always operate"],
       e:"Ferries run from early June to mid-October and ice bridges from late November to late April. In between, during freeze-up and break-up, neither runs and the road is cut." },
  fr:{ q:"Quand les traversées des rivières Peel et Mackenzie sur la route Dempster ne fonctionnent-elles pas du tout ?",
       a:["Seulement au cœur de l'hiver","Seulement au cœur de l'été","Pendant le gel et la débâcle","Elles fonctionnent toujours"],
       e:"Les traversiers circulent du début juin à la mi-octobre et les ponts de glace de la fin novembre à la fin avril. Entre les deux, pendant le gel et la débâcle, ni l'un ni l'autre ne fonctionne et la route est coupée." },
  c:2 }
);
