#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""analytics_kinds.py — tells js/analytics.js what kind of page each page is.

WHY THIS EXISTS
---------------
js/analytics.js used to work out whether a page was a game, a quiz, an article
or a driving page by matching the file name against a long regular expression.
On 24 August 2026 that guess was measured against the real site and it was wrong
on 13 games and on several articles:

    block-builder  brain-trainer  carrom  hide-and-find  maple-says  lights-out
    tag  tile-tap  math-race  times-tables  reversi  connect4  cube-twist

all reported as "other", along with two of the three new trade articles and most
of the kids' stories. Per-page numbers in Google Analytics were fine; every
grouped total was not.

WHAT IT DOES INSTEAD
--------------------
It reads the pages that already list the site's own content — the card grids on
games.html, quizzes.html, blog.html and for-kids.html, and the Driving Test
Practice group in tools/site_map.json — and writes an explicit slug -> kind map
into js/analytics.js between two markers. Nothing is guessed. A page that is not
on any of those lists still falls back to the old regular expression, so a brand
new page is never left unclassified.

Run it whenever a page is added, before rewrite_pages.py (which stamps the file
hash of js/analytics.js into every page).

    python3 tools/newq/analytics_kinds.py            # write
    python3 tools/newq/analytics_kinds.py --check    # report, change nothing
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TARGET = os.path.join(ROOT, "js", "analytics.js")
OPEN = "/* ---- KIND MAP: generated by tools/newq/analytics_kinds.py ---- */"
CLOSE = "/* ---- end KIND MAP ---- */"

# Pages that are signposts, not content. They would otherwise sit in "other"
# and make it look like a category.
HUBS = [
    "index", "games", "quizzes", "blog", "for-kids", "citizenship",
    "driving-test", "canada-driving-test-by-province", "all-pages", "about",
    "contact", "sources", "privacy", "terms", "offline", "daily", "tag",
]

# games.html carries a card for "tag" the game. The hub list above also has a
# "tag" page. The game wins: it is real content and it is on the games grid.
HUB_EXCEPTIONS = {"tag"}


def cards(filename):
    """Every page linked from a card on a landing page.

    Two shapes are in use and both have to work:
      blog.html   <a class="card c-red" href="x.html">
      games.html  <div class="card c-red"> ... <a href="x.html" class="btn">
    So: split on the card class, then take the first page link in each chunk.
    """
    path = os.path.join(ROOT, filename)
    if not os.path.isfile(path):
        return []
    html = open(path, encoding="utf-8").read()
    out, seen = [], set()
    for chunk in html.split('class="card')[1:]:
        m = re.search(r'href="([a-z0-9][a-z0-9-]*)\.html"', chunk)
        if m and m.group(1) not in seen:
            seen.add(m.group(1))
            out.append(m.group(1))
    return out


def driving():
    d = json.load(open(os.path.join(ROOT, "tools", "site_map.json"), encoding="utf-8"))
    for g in d["groups"]:
        if g["title"] == "Driving Test Practice":
            return [l[0].replace(".html", "") for l in g["links"]]
    return []


def build():
    """Most specific wins. A page on two grids is classified once, here."""
    kinds = {}
    for slug in cards("blog.html") + cards("for-kids.html"):
        kinds[slug] = "article"
    for slug in cards("games.html"):
        kinds[slug] = "game"
    for slug in cards("quizzes.html"):
        kinds[slug] = "quiz"
    for slug in driving():
        kinds[slug] = "driving"
    for slug in HUBS:
        if slug not in HUB_EXCEPTIONS:
            kinds[slug] = "hub"
    return kinds


def render(kinds):
    """One slug per line, sorted, so a diff shows exactly what changed."""
    lines = ['%s"%s"' % (" " * 2, k) + ':"%s",' % kinds[k] for k in sorted(kinds)]
    body = "\n".join(lines).rstrip(",")
    return "%s\nvar CQ_KIND = {\n%s\n};\n%s" % (OPEN, body, CLOSE)


def main():
    check = "--check" in sys.argv
    kinds = build()
    src = open(TARGET, encoding="utf-8").read()
    block = render(kinds)

    if OPEN in src:
        start = src.index(OPEN)
        end = src.index(CLOSE) + len(CLOSE)
        new = src[:start] + block + src[end:]
    else:
        anchor = "(function () {"
        if anchor not in src:
            raise SystemExit("analytics.js: could not find the place to insert the map")
        i = src.index(anchor)
        new = src[:i] + block + "\n\n" + src[i:]

    counts = {}
    for v in kinds.values():
        counts[v] = counts.get(v, 0) + 1
    print("kind map: %d pages — %s" % (len(kinds), ", ".join(
        "%s %d" % (k, counts[k]) for k in sorted(counts))))

    # Every root page must land somewhere. Anything left over is reported by
    # name, because silence is how the old regex hid thirteen games for months.
    pages = sorted(f[:-5] for f in os.listdir(ROOT) if f.endswith(".html"))
    loose = [p for p in pages if p not in kinds]
    if loose:
        print("not on any list, will fall back to the regex (%d):" % len(loose))
        for p in loose:
            print("   ", p)
    else:
        print("every page on the site is classified explicitly")

    if check:
        print("--check: analytics.js not written")
        return
    if new == src:
        print("analytics.js unchanged")
        return
    open(TARGET, "w", encoding="utf-8").write(new)
    print("wrote js/analytics.js")


if __name__ == "__main__":
    main()
