"""canada-quiz.com — write the printed question bank into citizenship.html.

The citizenship page carries its whole bank as static HTML between
``<!--QBANK-->`` and ``<!--/QBANK-->``, grouped by the chapters of the official
Discover Canada guide. That block is what a search engine reads, and it is most
of the page's word count.

Like the driving banks, it was generated by something that never lived in the
repository. So the moment a question was added, edited or de-duplicated in
js/citizenship-questions.js, the printed list quietly disagreed with the quiz
above it — the page went on advertising "All 259 questions" and listing the old
ones. This file closes that gap.

The French twin needs no separate step: citizenship questions are English-only
in the JS and their French lives in the dictionary, so tools/build_fr.py
translates this block like any other prose. Every string must therefore have a
pair in tools/extra_fr.json, which is true of every question in the bank.

Run it after any change to js/citizenship-questions.js, BEFORE build_fr.py:

    python3 tools/newq/cit_qbank.py
    python3 tools/newq/cit_qbank.py --check    # report only, exit 1 if stale
"""

import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))

PAGE = os.path.join(ROOT, "citizenship.html")
BANK = os.path.join(ROOT, "js", "citizenship-questions.js")
BLOCK = re.compile(r"<!--QBANK-->(.*?)<!--/QBANK-->", re.S)

INTRO = ("Every question in the practice exam above, written out with the right answer "
         "marked and a short explanation, grouped the same way the official Discover "
         "Canada guide is. This is a study list, not the real test.")


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def load():
    """The bank, as JSON, without trusting a regex to parse JavaScript."""
    js = ("var CITIZENSHIP_QUESTIONS;"
          + open(BANK, encoding="utf-8").read().replace("const CITIZENSHIP_QUESTIONS",
                                                        "CITIZENSHIP_QUESTIONS")
          + ";process.stdout.write(JSON.stringify(CITIZENSHIP_QUESTIONS))")
    out = subprocess.run(["node", "-e", js], capture_output=True, text=True, check=True)
    return json.loads(out.stdout)


def item(q):
    """One question. The correct option keeps its own place in the list — this page
    does not move it to the front the way the driving banks do."""
    opts = "".join(
        ('<li class="qb-ok">%s<span class="qb-lab">Correct answer</span></li>' % esc(o))
        if i == q["answer"] else ("<li>%s</li>" % esc(o))
        for i, o in enumerate(q["options"]))
    return ('<li class="qb-item">\n<p class="qb-q">%s</p>\n<ul class="qb-o">%s</ul>\n'
            '<p class="qb-e">%s</p>\n</li>' % (esc(q["q"]), opts, esc(q["explain"])))


def build():
    qs = load()
    order, groups = [], {}
    for q in qs:                       # chapters keep their first-appearance order
        ch = q["chapter"]
        if ch not in groups:
            order.append(ch)
            groups[ch] = []
        groups[ch].append(q)

    parts = []
    for ch in order:
        parts.append(
            '<details class="qb-acc">\n'
            '<summary><h3 class="qb-acc-t">%s</h3><span class="qb-acc-n">%d questions</span></summary>\n'
            '<ol class="qb">\n%s\n</ol>\n</details>'
            % (esc(ch), len(groups[ch]), "\n".join(item(q) for q in groups[ch])))

    return ('\n<section class="panel qbank">\n'
            '<h2>All %d citizenship practice questions, with every answer explained</h2>\n'
            '<p>%s</p>\n'
            '<div class="qb-tools"><button type="button" class="qb-openall" '
            'data-open="Open all" data-close="Close all">Open all</button></div>\n'
            '%s\n</section>\n' % (len(qs), INTRO, "\n".join(parts)))


def run(check_only=False):
    html = open(PAGE, encoding="utf-8").read()
    m = BLOCK.search(html)
    if not m:
        print("!! citizenship.html has no <!--QBANK--> block")
        return 1
    want = build()
    if m.group(1) == want:
        print("cit_qbank: printed bank is up to date")
        return 0
    if check_only:
        n_now = re.search(r"All (\d+) citizenship", m.group(1))
        print("cit_qbank --check: STALE (page says %s, bank has %d)"
              % (n_now.group(1) if n_now else "?", len(load())))
        return 1
    open(PAGE, "w", encoding="utf-8").write(
        html[:m.start(1)] + want + html[m.end(1):])
    print("cit_qbank: rewrote the printed bank — %d questions" % len(load()))
    return 0


if __name__ == "__main__":
    sys.exit(run("--check" in sys.argv))
