#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Tell Bing about pages the moment they go live.

IndexNow is a ping: the site says "this address is new or changed, come and
look", instead of waiting for a crawler to come round on its own. Microsoft
Bing, Yandex, Seznam, Naver and Yep act on it. DuckDuckGo and Ecosia get their
results from Bing, so they benefit too.

GOOGLE DOES NOT USE INDEXNOW. Checked again in August 2026. Nothing here will
move the "Discovered — currently not indexed" number in Google Search Console.
That one improves with time, internal links and links from other sites.

HOW OWNERSHIP IS PROVED
  A file named <key>.txt sits at the root of the site and contains the key,
  and nothing else. That is the whole check. The key does not have to be
  generated by Bing; any hex string of 8 to 128 characters works.
  Ours lives in tools/indexnow_key.txt and the file is in the repo root.
  If the key file is ever deleted, every submission silently starts failing.

WHAT THIS SCRIPT DOES
  It never sends anything itself. It reads sitemap.xml and writes two things:

    tools/indexnow_payload.json   the exact body for a bulk submission
    tools/indexnow_links.txt      one clickable link per URL, for small batches

  Sending is left to a person on purpose. Submitting a site to a search engine
  is an action taken in the owner's name, and a build script should not be doing
  that on its own.

WHICH TO USE
  After a nightly build that adds four pages, open the four links. That is the
  normal case and it takes ten seconds.
  After a big build, use the sitemap in Bing Webmaster Tools instead — it does
  the same job for every page at once and takes one click.

Usage:  python3 tools/indexnow.py            everything in the sitemap
        python3 tools/indexnow.py --new 20   the 20 most recently changed
"""
import io, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HOST = "canada-quiz.com"
API = "https://api.indexnow.org/indexnow"


def key():
    p = os.path.join(ROOT, "tools", "indexnow_key.txt")
    if not os.path.exists(p):
        raise SystemExit("tools/indexnow_key.txt is missing — the key is gone")
    k = io.open(p, encoding="utf-8").read().strip()
    if not os.path.exists(os.path.join(ROOT, k + ".txt")):
        raise SystemExit("%s.txt is not in the site root. Bing cannot verify us "
                         "without it and every submission will fail." % k)
    return k


def sitemap_urls():
    p = os.path.join(ROOT, "sitemap.xml")
    s = io.open(p, encoding="utf-8").read()
    out = []
    for m in re.finditer(r"<url>(.*?)</url>", s, re.S):
        loc = re.search(r"<loc>(.*?)</loc>", m.group(1))
        mod = re.search(r"<lastmod>(.*?)</lastmod>", m.group(1))
        if loc:
            out.append((mod.group(1) if mod else "", loc.group(1)))
    return out


def main():
    k = key()
    urls = sitemap_urls()

    if "--new" in sys.argv:
        n = int(sys.argv[sys.argv.index("--new") + 1])
        urls = sorted(urls, reverse=True)[:n]

    just = [u for _, u in urls]

    payload = {
        "host": HOST,
        "key": k,
        "keyLocation": "https://%s/%s.txt" % (HOST, k),
        "urlList": just,
    }
    pp = os.path.join(ROOT, "tools", "indexnow_payload.json")
    json.dump(payload, io.open(pp, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    io.open(pp, "a", encoding="utf-8").write("\n")

    lp = os.path.join(ROOT, "tools", "indexnow_links.txt")
    with io.open(lp, "w", encoding="utf-8") as f:
        for u in just:
            f.write("%s?url=%s&key=%s\n" % (API, u, k))

    print("key            %s" % k)
    print("key file       https://%s/%s.txt" % (HOST, k))
    print("urls           %d" % len(just))
    print("bulk body      tools/indexnow_payload.json  (POST to %s)" % API)
    print("one-click      tools/indexnow_links.txt     (open in a browser)")
    if just:
        print("\nfirst link, to test that the key works:")
        print("%s?url=%s&key=%s" % (API, just[0], k))


main()
