#!/usr/bin/env python3
"""
Canada Quiz — make_dict.py

Rebuilds js/i18n-fr.js (the English -> French word list the whole site uses).

It joins two things:
  1. the big translated word list  (tools/fr_base.json)
  2. small hand-written extras     (tools/extra_fr.json)   <-- edit this one

If a word comes out wrong in French, fix it in tools/extra_fr.json and run:

    python3 tools/make_dict.py
    python3 tools/build_fr.py
"""
import html, json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = os.path.join(ROOT, "tools", "fr_base.json")
EXTRA = os.path.join(ROOT, "tools", "extra_fr.json")
OUT = os.path.join(ROOT, "js", "i18n-fr.js")


# Names that must stay exactly the same in French — the brand, the domain,
# and anything official.  Add a line here if a name gets translated by mistake.
KEEP_AS_IS = [
    "Canada Quiz & Family Fun Games",
    "Canada Quiz &amp; Family Fun Games",
    "Canada Quiz",
    "Canada-Quiz.com",
    "canada-quiz.com",
    "Family Play Zone",
    "Discover Canada",
    "AdSense",
    # Province and territory names spelled the same in French. Without these the
    # word list turns a standalone "Manitoba" into "Le Manitoba", which looks
    # wrong as a card heading beside "Ontario" and "Nunavut".
    "Ontario",
    "Alberta",
    "Manitoba",
    "Saskatchewan",
    "Yukon",
    "Nunavut",
]


def norm(s):
    return re.sub(r"\s+", " ", s).strip()


def main():
    base = json.load(open(BASE, encoding="utf-8"))
    extra = json.load(open(EXTRA, encoding="utf-8"))

    out = {}

    # In extra_fr.json, writing a phrase as its OWN translation
    #     "The Beatles": "The Beatles"
    # means "leave this in English".  Band names, acronym answers and anything
    # that must not be translated go there.  Those keys are locked so the
    # machine word list cannot put French back in.
    locked = set()
    for k, v in extra.items():
        if norm(k) == norm(v):
            locked.add(norm(k))
            locked.add(norm(html.unescape(k)))

    def add(k, v, force=False):
        k, v = norm(k), norm(v)
        if not k or not v or v == k:
            return
        if k in locked:
            return
        if k in out and not force:
            return
        out[k] = v

    # extras win over the machine list
    for k, v in extra.items():
        add(k, v, force=True)
        add(html.unescape(k), html.unescape(v), force=True)
    for k, v in base.items():
        if not isinstance(v, str):
            continue
        add(k, v)
        add(html.unescape(k), html.unescape(v))

    for k in KEEP_AS_IS:
        out.pop(norm(k), None)
        out.pop(norm(html.unescape(k)), None)

    js = ("/* Canada Quiz — French word list. Built by tools/make_dict.py.\n"
          "   Do NOT edit this file by hand — edit tools/extra_fr.json instead. */\n"
          "window.CQ_FR = " + json.dumps(out, ensure_ascii=False, separators=(",", ":")) + ";\n")
    open(OUT, "w", encoding="utf-8").write(js)
    print("wrote %s — %d phrases (%d KB)" % (OUT, len(out), os.path.getsize(OUT) // 1024))


if __name__ == "__main__":
    main()
